### ISSUE TITLE
Switch operation instead of multiple `if`s

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#10]
Also a long requested feature, it is proposed to have some sort of alternative of doing repetitive `if`s like that:

```yaml
      - id: el_type
        type: u1
        enum: bson_type
      - id: el_string
        type: bson_string
        if: el_type == bson_type::string
      - id: el_document
        type: bson_document
        if: el_type == bson_type::document
      - id: el_boolean
        type: u1
        if: el_type == bson_type::boolean
...
```

I propose to discuss, choose the best possible plan and implement it :)

**Comment by GreyCat** [comment]
Ok, I want to suggest a few different syntaxes, usable for different purposes:

## Generic: type ID → different inner types

```yaml
- id: el_type
  type: u1
- id: el_body
  switch:
    on: el_type
    cases:
      1:
        type: u2
        repeat: expr
        repeat-expr: 5
      0x42:
        type: str
        size: 10
        encoding: UTF-8
      0x43:
        type: subtype_43
      _:
        size: 10
```

This is most verbose (and most flexible) syntax. Generated `el_body` getter would be on type `Object` (or, in best case, it would be `KaitaiStruct`, if all switch types are non-primitive types). Case `_` is a special case that catches "everything else", akin to `default` or `else` in many other languages. If there is no else case and nothing matches, then, I guess, `el_body` would be considered `null`, no errors or anything would be generated.

## Inheritance of some properties

In some cases, it would be useful to "inherit" some properties of an attribute from parent switch attribute to all case branches, i.e. `size`:

```yaml
- id: el_type
  type: u1
- id: el_size
  type: u4
- id: el_body
  size: el_size
  switch:
    on: el_type
    cases:
      1:
        type: subtype_1
      0x42:
        type: subtype_0x42
      0x43:
        type: str
        encoding: ASCII
      _: {}
```

This yields all subtypes hard-limited with `size: el_size` ­— that is, by far, would be the most common case. I don't know about inheritance of other properties: probably `repeat*` stuff might be useful (if we'll agree on its semantics).

## "Full auto" mode

It is kind of meaningless to do verbose stuff like:

```yaml
seq:
  - id: el_type
    type: u1
    enum: cmd
  - id: el_size
    type: u4
  - id: el_body
    size: el_size
    switch:
      on: el_type
      cases:
        cmd::foo:
          type: el_body_foo
        cmd::bar:
          type: el_body_bar
        cmd::baz:
          type: el_body_baz
types:
  el_body_foo:
    ...
  el_body_bar:
    ...
  el_body_baz:
    ...
```

Basically, it means that every switch case is a distinct custom subtype, named after a enum value. The suggested "full auto" syntax is:

```yaml
seq:
  - id: el_type
    type: u1
    enum: cmd
  - id: el_size
    type: u4
  - id: el_body
    size: el_size
    switch:
      on: el_type
types:
  el_body_foo:
    ...
  el_body_bar:
    ...
  el_body_baz:
    ...
```

I.e. abscence of `cases` clause means that we switch on values of `enum`-based type, selecting subtypes by name. It can be even more straightforward with abscence of enum:

```yaml
seq:
  - id: el_type
    type: u1
  - id: el_body
    switch:
      on: el_type
types:
  el_body_1:
    ...
  el_body_2:
    ...
  el_body_3:
    ...
```

Given that probably version 3 is most useful (and uniform), I suggest that we'd implement it first.

Comments, thoughts, feedback?

**Comment by LogicAndTrick** [comment]
I'm not too fond of the "magic" that's happening in the "full auto" mode - I prefer the explicit approach of specifying the exact type name, even if you have to type more.

I think the `switch` tag name might be a bit general - could it be renamed to specify that it's actually setting the type (e,g, `type-switch`)? Or perhaps a better option, overloading the `type` tag itself to accept the switch construct?

```yaml
seq:
  - id: el_type
    type: u1
  - id: el_body
    type:
      switch:
        on: el_type
        ...
```

I also wonder if it might be possible to make the system more flexible by allowing arbitrary expressions:

```yaml
seq:
  - id: el_type
    type: u1
  - id: el_body
    type:
      - if: el_type == 1
        then: el_body_1
      - if: el_type == 2
        then: el_body_2
      - if: el_type > 2 and el_type < 10
        then: el_body_3
      - else: el_body_4
```

At the very least I would like to make sure it's possible to switch on any data type (e.g. strings) - I've worked with several formats that print the type name as a string rather than using an enum/integer value.

**Comment by GreyCat** [comment]
The "more verbose" approach is actually already there. It is a bunch of `if`s, as illustrated in opening post. That's roughly 3x duplication:

```yaml
      - id: el_string                    # 1st "string"
        type: bson_string                # 2nd "string"
        if: el_type == bson_type::string # 3rd "string"
```

Duplication is generally a bad thing: it leads to non-uniformity, copy-paste errors, harder-to-maintain spec, etc.

I'm kind of hesitating about "switch can switch everything" vs "switch that switches only type" approaches — both have their own pros and cons.

**Comment by GreyCat** [comment]
Here we go, I've made a PoC: https://github.com/kaitai-io/kaitai_struct_compiler/pull/16

I ended up adopting your approach (i.e. switching for types only), but taking "type" as a pretty broad characteristic (i.e. inheriting `size`, `size-eos`, that kind of stuff).

**Comment by LogicAndTrick** [comment]
That looks good. What do you think about also adding an option like this (the syntax is a little crazy, but I think YAML supports it):

```yaml
  - id: code
    type: u1
  - id: body
    type:
      # switch-on is not specified - triggers "expression" mode
      cases:
        "code == 73": intval   # cases are full expressions
        "code >= 83 and code <= 93": strval
```

I think the implementation of this would be fairly straight forward to support both (the `switch-on` mode would just be transformed into `==` expressions when the YAML is parsed, and most compilers would have to use `if (...) else if (...)` chains instead of `switch`).

**Comment by GreyCat** [comment]
Else support is probably in, as `_` special. I'm still not really sure about allowing arbitrary expressions — although it won't hurt either too.

**Comment by GreyCat** [comment]
The majority of use cases are tested, most languages' support is done (only Perl is relatively lagging behind undertested, but that's because of the test conversion script, see #21). I consider this task to be  done.

**Comment by tschoening** [comment]
> I'm still not really sure about allowing arbitrary expressions — although it won't hurt either too.

I have a comparable case currently and IMHO at least the second `case` of the example `switch` seems a bit difficult to maintain to me. In my case, one of that cases would even be more complex. So my suggestion is to not use/allow expressions for this one, but instead use `instances` to check each case and later switch on all of those instances. I think my example is more readable in the end, especially can be documented per instance on an API level and such.

The only problem currently is that one is not able to switch on all interesting instances easily. The workaround I found was to create another instance providing some `integer` describing the current case. But in the end this is exactly what the `switch-on` should do itself... :-)

What do you think? Is there any way to get rid of the id-helper and switch on all interesting instances automatically somehow?

    meta:
      id:      fmts_oms_apl_hdr
      endian:  le
    
    seq:
      - id:   control_info
        type: u1
      - id:   header
        type:
          switch-on: available_header_id
          cases:
            0: fmts_oms_apl_hdr_none
            1: fmts_oms_apl_hdr_short
            2: fmts_oms_apl_hdr_long
    
    instances:
      is_header_none:
        value:  control_info == 0x50 or
                control_info == 0x51 or
                control_info == 0x52 or
                control_info == 0x69 or
                control_info == 0x70 or
                control_info == 0x71 or
                control_info == 0x78 or
                control_info == 0x79
      is_header_short:
        value:  control_info == 0x5A or
                control_info == 0x61 or
                control_info == 0x65 or
                control_info == 0x6A or
                control_info == 0x6E or
                control_info == 0x74 or
                control_info == 0x7A or
                control_info == 0x7B or
                control_info == 0x7D or
                control_info == 0x7F or
                control_info == 0x8A
      is_header_long:
        value:  control_info == 0x53 or
                control_info == 0x5B or
                control_info == 0x60 or
                control_info == 0x64 or
                control_info == 0x6B or
                control_info == 0x6C or
                control_info == 0x6D or
                control_info == 0x6F or
                control_info == 0x72 or
                control_info == 0x73 or
                control_info == 0x75 or
                control_info == 0x7C or
                control_info == 0x7E or
                control_info == 0x80 or
                control_info == 0x84 or
                control_info == 0x85 or
                control_info == 0x8B
      available_header_id:
        value:  "is_header_none ? 0 : (is_header_short ? 1 : 2)"

Don't know if it's more readable, but one can use `enums` as well:

    meta:
      id:      fmts_oms_apl_hdr
      endian:  le
    
    seq:
      - id:   control_info
        type: u1
      - id:   header
        type:
          switch-on: available_header_type
          cases:
            header_type::none:  fmts_oms_apl_hdr_none
            header_type::short: fmts_oms_apl_hdr_short
            header_type::long:  fmts_oms_apl_hdr_long
    
    instances:
      is_header_none:
      [...]
      is_header_short:
      [...]
      is_header_long:
      [...]
      available_header_type:
        value:  "is_header_none ? header_type::none :
                                  (is_header_short ?  header_type::short :
                                                      header_type::long)"
    
    enums:
      header_type:
        0: none
        1: short
        2: long

**Comment by GreyCat** [comment]
Good point, a real-life use-case, thanks. Probably we can implement multiple choice cases here relatively easy, YAML-style:

```yaml
  - id:   header
    type:
      switch-on: available_header_id
      cases:
        [0x50, 0x51, 0x52, 0x69, 0x70, 0x71, 0x78, 0x79]: fmts_oms_apl_hdr_none
        [0x5A, 0x61, 0x65, 0x6A, 0x6E, 0x74, 0x7A, 0x7B, 0x7D, 0x7F, 0x8A]: fmts_oms_apl_hdr_short
        # ...
```

Actually, you can do multiple cases in switch statement in most languages.

**Comment by tschoening** [comment]
I like it, if syntax would allow spanning the keys over multiple lines with proper indentation somehow. The syntax for line 2 and 3 in my following example is default syntax and should be possible, right? That's what I would prefer anyway, I guess.

    - id:   header
      type:
        switch-on: available_header_id
          cases:
            [0x50, 0x51, 0x52, 0x69, 0x70,
             0x71, 0x78, 0x79]:                              fmts_oms_apl_hdr_none
            [0x5A, 0x61, 0x65, 0x6A, 0x6E, 0x74]: fmts_oms_apl_hdr_short
            [0x7A, 0x7B, 0x7D, 0x7F, 0x8A]:          fmts_oms_apl_hdr_short

But IMHO my approach still has some pros: In your ruby visualizer the instances can be easily inspected and help during debugging, it might even be some useful public API for a caller.

OTOH, I think it might be too special to implement... Some syntax like the following would be great:

    switch-on: is_header_none | is_header_short | is_header_long | ...
    switch-on: [is_header_none, is_header_short, is_header_long, ...]

But don't know how this could map easily and for all languages to something useful.

**Comment by GreyCat** [comment]
Unfortunately, YAML "flow" style array doesn't seem to allow arbitrary line breaks. However, you can use "block" style arrays:

```yaml
- id:   header
  type:
    switch-on: available_header_id
    cases:
      ? - 0x50
        - 0x51
        - 0x52
        - 0x69
        - 0x70
        - 0x71
        - 0x78
        - 0x79
      : fmts_oms_apl_hdr_none
      ? - 0x5A
        - 0x61
        - 0x65
        - 0x6A
        - 0x6E
        - 0x74
      : fmts_oms_apl_hdr_short
```

> But IMHO my approach still has some pros: In your ruby visualizer the instances can be easily inspected and help during debugging, it might even be some useful public API for a caller.

Definitely. I'm just thinking about a more concise and terser syntax, when such verbosity is not requires.

> OTOH, I think it might be too special to implement... Some syntax like the following would be great:
> ```
> switch-on: is_header_none | is_header_short | is_header_long | ...
> switch-on: [is_header_none, is_header_short, is_header_long, ...]
> ```

Um, to be honest, I don't understand what that's supposed to mean. `switch-on` takes valid expression. That is, `is_header_none | is_header_short | is_header_long` is an expression with 3 values connected with `|` operator, which is bitwise AND. If `is_*` are numbers, then it will calculate proper bitwise AND result. If `is_*` are something else (for example, booleans), that would be compile time type check error. What are the supposed semantics?

**Comment by tschoening** [comment]
> What are the supposed semantics?

I want to tell the `switch-on` that it "somehow" should take the results of all the mentioned instances and map those to some values I can know beforehand and are compatible with some arbitrary `switch`. That's what I do in the following lines, making the `boolean` results `switch` compatible manually:

    available_header_id:
      value:  "is_header_none ? 0 : (is_header_short ? 1 : 2)"

**Comment by GreyCat** [comment]
Um, that's probably better to be solved directly with creation of some arrays / maps and accessing them?

Technically, you can do stuff like:

```yaml
instances:
  some_arr:
    value: '["foo", "bar", "baz", "qux", "foo", "foo", "bar again", "something"]' # or use enums, or anything you like
  mapped_val:
    value: some_arr[control_info]
```
