### ISSUE TITLE
How to deal with absolute positions?

### ISSUE THREAD

**Issue by HenryOfCarim** [kaitai-io/kaitai_struct#1004]
I have a file where at the beginning of it there are just absolute offsets for data blocks. In C I can just represent them as an array and then write a for loop, get a position and map my `mfx_entry` structure, but I can't figure out how to do it in kaitai

```
seq:
- {id: header, type: mfx_header}
- {id: mfx_emtry_offset, type: u4, repeat: expr, repeat-expr: header.entry_count-1}

types:
  mfx_header:
    seq:
      - {id: magic, contents: [0x4d, 0x46, 0x58, 0x00]}
      - {id: reserved_4, type: u2}
      - {id: reserved_6, type: u2}
      - {id: field_8, type: u4}
      - {id: entry_count, type: u4}
      - {id: string_table_offset, type: u4}
      - {id: unk_01,  type u4}
      
  mfx_entry:
    seq:
      - {id: string_1, type: u4}
      - {id: string_2, type: u4} 
```

I thought about mapping some types with just a position u4 , and using it as a type here

`- {id: mfx_emtry_offset, type: mfx_entry_position, repeat: expr, repeat-expr: header.entry_count-1}`

But IDK how to map a structure in this case
