### ISSUE TITLE
Trying to understand how nested types are resolved

### ISSUE THREAD

**Issue by wader** [kaitai-io/kaitai_struct#1019]
Hello

I'm trying to understand how nested types and `::` it used to resolves types. Here is an example that confuses me:

```yaml
meta:
  id: nested_types
  endian: le
seq:
  - id: s0
    type: t0
instances:
  e0_hello_0:
    value: t0::e0::hello
  e0_hello_1:
    value: ::t0::e0::hello
  e0_hello_2:
    value: t0::t0::e0::hello
  e0_hello_3:
    value: t0::t0::t0::e0::hello
types:
  t0:
    seq:
      - id: t0s0
        type: u1
    enums:
      e0:
        1: hello
    types:
      t0:
        seq:
          - id: t0t0s0
            type: u2
        enums:
          e0:
            2: hello
```
Using https://ide.kaitai.io/ results in: (using the default zip input)
```json
{
  "s0": {
    "t0t0s0": 19280
  },
  "e0Hello0": { "name": "HELLO", "value": 2 },
  "e0Hello1": { "name": "HELLO", "value": 2 },
  "e0Hello2": { "name": "HELLO", "value": 2 },
  "e0Hello3": { "name": "HELLO", "value": 2 }
}
```
`type: t0` seems to resolve to the nested "`t0::t0`", if i rename it to "`t0::t1`" the result is:
```json
{
  "s0": {
    "t0s0": 80
  },
  "e0Hello0": { "name": "HELLO", "value": 1 },
  "e0Hello1": { "name": "HELLO", "value": 1 },
  "e0Hello2": { "name": "HELLO", "value": 1 },
  "e0Hello3": { "name": "HELLO", "value": 1 }
}
```
now `type: t0` resolves to the "top" `t0`.

I get a feeling type name are global somehow even when using `::`?

**Comment by wader** [comment]
Should mention that i'm experiment with adding basic runtime support for kaitai to https://github.com/wader/fq so i'm trying to get a deeper understanding how types, enums etc are namespaces and resolved.

**Comment by Mingun** [comment]
There is a bug in WebIDE about equally named types: https://github.com/kaitai-io/kaitai_struct_webide/issues/105

**Comment by wader** [comment]
@generalmimon Thanks! that was exactly what i was looking for, and will keep in mind to not trust it too much :) to be clear, by "probably follow intuitively" you mean it should be quite straight forward to extend the described algorithm to support paths?

In the 3rd step when it says
> 3. If that fails too, it goes one level up in the hierarchy of nested types and tries to resolve it there.

Should one only look one level up or continue for each parent down to the root? when i tested both type and enums seems to go all the way to the root:

```yaml
meta:
  id: enum_to_i
  endian: le
seq:
  - id: s
    type: a
enums:
  e:
    0x50: name
types:
  b:
    seq:
      - id: s
        type: u1
  a:
    types:
      a:
        types:
          a:
            seq:
              - id: s0
                type: b
              - id: s1
                type: u1
                enum: e

```
webide result:
```json
{
  "s": {
    "s0": {
      "s": 80
    },
    "s1": { "name": "NAME", "value": 75 }
  }
}
```

**Comment by generalmimon** [comment]
@wader:

> In the 3rd step when it says
> 
> > 3. If that fails too, it goes one level up in the hierarchy of nested types and tries to resolve it there.
> 
> Should one only look one level up or continue for each parent down to the root? when i tested both type and enums seems to go all the way to the root:

Yes, step 3 is definitely meant to be recursive (i.e. the step 3 is actually "go back to step 1 and follow the process again, but now the _current type_ is the type one level up in the hierarchy).

**Comment by generalmimon** [comment]
@wader:

> to be clear, by "probably follow intuitively" you mean it should be quite straight forward to extend the described algorithm to support paths?

Yes, only the first component of the type path has the special handling with fallbacks (it's the same handling as described [in the KSY reference](https://github.com/kaitai-io/kaitai_struct_doc/blob/88c32183b26e4d2265bfecdce0a3dfeaea6975ff/ksy_reference.adoc#type), i.e. the actual type resolved as `foo` in `type: foo` and `type: foo::{...}` is always the same). All subsequent components of the path should have no fallbacks.

I'm not sure whether examples in this case are not more confusing than helpful, but I'll try anyway.

```ksy
meta:
  id: nested_types_paths
seq:
  - id: abc
    type: a::b
types:
  a:
    seq: []
    types:
      b:
        seq:
          - id: obj_cd
            type: c::d
        types: {}

  c:
    seq: []
    types:
      d:
        seq:
          - id: d_attr
            type: s1
```

Notice the `obj_de` attribute in the `/types/a/types/b` type. It references a type `c::d`. Finding what specific type `c` refers to is non-trivial (and it's using the same algorithm as for plain `type: c`). First, you need to

1. check <code>/types/a/types/b/<ins><strong>types</strong></ins></code>, only to find that the `c` isn't defined there (in this case);
2. check if the current type (still `/types/a/types/b`) has the name `c`. It doesn't, so we're now moving to the type one level up in the nested types hierarchy (`/types/a`).

No luck finding the `c` type under `/types/a/types/b/` => the new "current type" is `/types/a`.

1. check <code>/types/a/<ins><strong>types</strong></ins></code> - nope, no `c` there;
2. check if the current type (`/types/a`) is `c`: it's not. We're moving to the top-level type, i.e. the YAML path `/` (in KS language, it can be referred to using the name in `/meta/id`, i.e. `nested_types_paths`).

Now searching in `/`:

1. check <code>/<ins><strong>types</strong></ins></code> - yes, we've finally found the definition of `c` in `/types/c`.

---

Now when you know what `type: c` corresponds to, <code>type: c::<ins><strong>d</strong></ins></code> is easy. Given that `type: c` has been resolved as `/types/c`, the only valid location for `type: c::d` is <code>/types/c/types/<ins><strong>d</strong></ins></code>. If `d` is not there, game over - the spec is invalid.

**Comment by wader** [comment]
@generalmimon Thanks! much appreciated with nice example. Don't think i would gotten all those details right by testing things.

Another thing: Is the types and enums namespace shared for a type? I tried having a type and enum with the same name and the type seems to shadow/override the enum in webide. When i tried with ksdump the generated ruby fails with:

```
meta:
  id: type_enum_collision
seq:
  - id: s0
    type: e

types:
  e:
    seq:
      - id: a
        type: u1
        enum: e

enums:
  e:
    0: name
```
```
type_enum_collision.rb:29:in `<class:TypeEnumCollision>': E is not a class (TypeError)
ype_enum_collision.rb:12: previous definition of E was here
```

Hope it's ok with all questions. Maybe some of it could be used to clarify documentation?

If you want to follow the progress in fq the issue is https://github.com/wader/fq/issues/627

No code has been pushed yet but current progress is that i have a quite complete expression language parser/evaluator that passes most of the tests i've found, somewhat working ksy schema parser, kaitai style "bit-endian" integer kind-of works. The biggest mess currently it the code to glue it all together with the fq decode "DSL", and that also depend quite a lot on how types are resolved etc.  But it's looking promising i think, some days ago mp4.ksy and png.ksy produced a somewhat good looking decode tree :)
