### ISSUE TITLE
Expression language string method substring behavior 

### ISSUE THREAD

**Issue by wader** [kaitai-io/kaitai_struct#1021]
Hi, i noticed this difference while testing things:

```
meta:
  id: substring_diff
instances:
  a:
    value: '"hello".substring(4,1)'
```

ksdump (ruby):
```
$ docker run -v "$PWD:/share" -it --entrypoint=ksdump kaitai/ksv -f json /dev/zero substring_diff.ksy | tail +5
{
  "a": ""
}
```

webide (javascript):
```
{
  "a": "ell"
}
```

Haven't looked deeper but i guess the behavior comes from how the JavaScript string `substring` method works.

Is there a preferred kaitai behavior?
