### ISSUE TITLE
Trying to understand enum resolution

### ISSUE THREAD

**Issue by wader** [kaitai-io/kaitai_struct#1028]
Hello, i'm trying to understand how enum:s are resolved. I assumed first that enum were resolve something like this:

- If no namespace, just a name, look in current types enums
- If namespace, has `::`,  look up type first then look in enums.

But when i trying some thing in webide and with ksdump things got confusing, for example:

```ksy
meta:
  id: enum_resolve

seq:
  - id: s0
    type: u1
    enum: e
  - id: s1
    type: u1
    enum: a::e
  - id: s2
    type: u1
    enum: a::a::e
  - id: s3
    type: u1
    enum: b::e
  - id: s4
    type: u1
    enum: b::b::e
  - id: s5
    type: u1
    enum: a::b::e
  - id: s6
    type: u1
    enum: b::a::e

types:
  a:
    enums:
      e:
        0: zero2
  b: {}

enums:
  e:
    0: zero
```
Both ksdump and webide result in:
```sh
$ docker run -v "$PWD:/share" -i --entrypoint=ksdump kaitai/ksv -f json /dev/zero enum_resolve.ksy
{
  "s0": "e_zero",
  "s1": "e_zero2",
  "s2": "e_zero2",
  "s3": "e_zero",
  "s4": "e_zero",
  "s5": "e_zero",
  "s6": "e_zero2"
}
```

So seems to behave something like this: If last part(s?) of type namespace resolve to a type that has the enum then use it, otherwise ignore type namespace and just look in current types enums.

**Comment by generalmimon** [comment]
@wader Thanks for sharing this. I agree that the behavior you demonstrate is very weird, but I'd say that the expected behavior is simple - only the `s0` and `s1` fields are valid. If you compile your spec to a statically-typed language like Java, you'll find that only `s0` and `s1` work (unsurprisingly):

![image](https://user-images.githubusercontent.com/47499687/232246150-afa8216c-5545-4276-9082-e5908ca67c5c.png)

It's a very good observation that the compiler doesn't flag any of the incorrect `enum` references as invalid and reject the .ksy spec - this is clearly a bug. Unfortunately, the compiler is generally notorious for handling error cases poorly.

**Comment by wader** [comment]
Ok thanks! and good tip to try compile to some typed language as a test. So as i understand it now the enum resolution is something like this:
- If just a name with no namespace:
  - Look for enum in current type, if not found look in parent and so on to the root
- If there is a type namespace:
  - Use type resolution (as described here https://github.com/kaitai-io/kaitai_struct/issues/1019#issuecomment-1503769699) and then look for enum

**Comment by generalmimon** [comment]
@wader:

> So as i understand it now the enum resolution is something like this: (...)

Yes, looks good. Just noting that "look for enum" here:

> If there is a type namespace:
> * Use type resolution (...) and then **look for enum**

should be trivial (no fallbacks, only the direct `enums` section should be accessed) - same as when resolving `type` paths (https://github.com/kaitai-io/kaitai_struct/issues/1019#issuecomment-1503769699):

> Now when you know what `type: c` corresponds to, <code>type: c::<ins><strong>d</strong></ins></code> is easy. Given that `type: c` has been resolved as `/types/c`, <ins>the only valid location</ins> for `type: c::d` is <code>/types/c/types/<ins><strong>d</strong></ins></code>. If `d` is not there, game over - the spec is invalid.

(here, if the `c` type in `enum: c::e` is `/types/c`, the `e` enum has to be in <code>/types/c/enums/<ins><strong>e</strong></ins></code>). But I think you get it by now.

**Comment by wader** [comment]
Close this one and possibly split out the weirdness/bug into new issue?

**Comment by generalmimon** [comment]
@wader:

> possibly split out the weirdness/bug into new issue?

Yeah, makes sense.

After seeing this - https://github.com/kaitai-io/kaitai_struct/issues/1019#issuecomment-1519016475, I realized that the KSC's component for resolving nested type references apparently misbehaves similarly as the component for resolving nested enums, and the faulty behavior we see here for `enum` references (https://github.com/kaitai-io/kaitai_struct/issues/1028#issue-1669512660) most likely applies for nested `type` refs too.

**Comment by Mingun** [comment]
This is the same error as #786, but for enums, and when enum is specified with path it is full duplicate of #786. The recursive search of enum in parent types here:
https://github.com/kaitai-io/kaitai_struct_compiler/blob/c23ec2ca88d84042edba76f70c1f003d062b7585/shared/src/main/scala/io/kaitai/struct/ClassTypeProvider.scala#L96-L108
should be performed only when path to the type is not specified, otherwise enum should be taken only from specified type.

In the original example currently enums resolved as following:
```yaml
meta:
  id: enum_resolve

seq:
  - id: s0
    type: u1
    enum: e # ::e
  - id: s1
    type: u1
    enum: a::e # ::a::e
  - id: s2
    type: u1
    enum: a::a::e # ::a::e
  - id: s3
    type: u1
    enum: b::e # ::e
  - id: s4
    type: u1
    enum: b::b::e # ::e
  - id: s5
    type: u1
    enum: a::b::e # ::e
  - id: s6
    type: u1
    enum: b::a::e # ::a::e

types:
  a:
    enums:
      e:
        0: zero2
        0x89: v2_x89
        0x50: v2_x50
        0x4e: v2_x4e
        0x47: v2_x47
        0x0d: v2_x0d
        0x0a: v2_x0a
        0x1a: v2_x1a
  b: {}

enums:
  e:
    0: zero
    0x89: v_x89
    0x50: v_x50
    0x4e: v_x4e
    0x47: v_x47
    0x0d: v_x0d
    0x0a: v_x0a
    0x1a: v_x1a
```
