### ISSUE TITLE
Question: how to deal with relative offsets?

### ISSUE THREAD

**Issue by HenryOfCarim** [kaitai-io/kaitai_struct#1029]
A format that I investigate consists of three parts: a header, data blocks with offsets, and data, the problem is those offsets are relative to the beginning of the block( as I understood)
so the body of the first block = `pos: offset+ header_size`
the body of the second block  = `pos:  offset+ header_size + data_block_size`
the body of the third  block  = `pos:  offset+ header_size + data_block_size  +  data_block_size`
and so on

Somebody knows how to do it right because I didn't get how to adapt the example from the documentation for my case

the ridiculous current implementation for 3 blocks
![image](https://user-images.githubusercontent.com/18252816/232939068-360be6ca-9adc-4017-9830-3b540503dc6b.png)

**Comment by HenryOfCarim** [comment]
It's slightly beyond my level, I managed to create a kinda working code with currently hardcoded header and block sizes. Did I understand you right?

```
seq:
  - {id: id_magic, contents: [0x43, 0x48, 0x4e, 0x00]}
  - {id: unk_id, type: u4}
  - {id: size, type: u4}
  - {id: unk_num, type: u1}
  - {id: unk_01, type: u1}
  - {id: unk_02, type: u1}
  - {id: unk_03, type: u1}
  - {id: head_data, type: head_block, repeat: expr, repeat-expr: unk_num}
  - {id: body, type: child_type(_index), repeat: expr, repeat-expr: unk_num}
    
types:
  child_type:
    params:
      - {id: idx, type: u4}
    instances:
      offset:
      - {value: _parent.head_data[idx].unk_data_pos + 16 + (32 * idx)}
      body:
      - {pos: offset, type: block_body, repeat: expr, repeat-expr: _parent.head_data[idx].block_num}
```
