### ISSUE TITLE
switch-on for enum

### ISSUE THREAD

**Issue by tannewt** [kaitai-io/kaitai_struct#1043]
USB device and interface descriptors have [`class`, `subclass` and `protocol` fields](https://www.usb.org/defined-class-codes) where the meaning of `subclass` depends on the value of `class` and the meaning of `protocol` depends on `subclass`. It'd be great if you could:

```yaml
- id: class
  type: u1
  enum: interface_class
- id: subclass
  type: u1
  enum:
    switch-on: class
    cases:
      'interface_class::human_interface_device': hid_subclass
```

It'd work just like `switch-on` under type but for enums instead.

Thanks!
