### ISSUE TITLE
[Question] Type Parameter

### ISSUE THREAD

**Issue by Dakota628** [kaitai-io/kaitai_struct#1045]
Hi,

Is it possible for a user type to take other types as a parameter? This functionality would be similar to generics in some languages. For example, consider the below "optional" type:

```yaml
dt_null:
  doc: Intentionally left empty
dt_optional:
  params:
    - id: t
      type: type # This doesn't currently exist, for example purposes only
  seq:
    - id: exists
      type: s4le
    - id: value
      type:
        cases:
          0: dt_null
          _: t
        switch-on: exists
example_type_using_optional:
  - id: foo
    type: dt_optional(dt_vector4d)
  - id: bar
    type: dt_optional(dt_arbitrary_large_type)
```
