### ISSUE TITLE
How to get the size of the read record and its source buffer for crc validation?

### ISSUE THREAD

**Issue by tonal** [kaitai-io/kaitai_struct#1046]
How to get the size of the read record and its source buffer for crc validation?

For Example:

```yaml
types:
    rec_type_pack:
    seq:
    - id: mark
      contents: [0xc0]
    - id: type_id
      type: u1
      enum: ids_rec_type
    - id: body
      type:
        switch-on: type_id
        cases:
          'ids_rec_type::id_state_power': # 0x07:
            rec_state_power
          'ids_rec_type::id_all_settings': # 0x12:
            rec_all_settings

    - id: crc16
      type: u2
      doc: GetCRC16(this.currentData, sizeRecord - 2)
```

```python
with KaitaiStream(open(filename, 'rb')) as _io:
  rec = RecTypePack(_io)
  rec._read()
  if rec.crc16 != crc16(rec._raw_buffer[:-2]): # How to get _raw_buffer?
    print("invalid record:", rec)
```
