### ISSUE TITLE
Concat bits

### ISSUE THREAD

**Issue by davetapley** [kaitai-io/kaitai_struct#1052]
I've got an esoteric format which some bit wrangling.

With help from #435 and https://github.com/kaitai-io/kaitai_struct/issues/302#issuecomment-357073786 I've got it working [here](https://gist.github.com/davetapley/8e71acb0e2fd3e715fb906cd3f8e3ef9), but I find this ⬇️  a bit 🤢 
```yml
instances:
  id:
    value: id_0 + (id_1 << 6) + (id_2.to_i << 12)
  value:
    value: val_0 + (val_1 << 5)
```

---

I suppose what I'm really doing is _bit level concatenation_.
Is there a better way without requiring a new method?
