### ISSUE TITLE
[Question] Question about wrapping pure memory and peeking

### ISSUE THREAD

**Issue by AudriusButkevicius** [kaitai-io/kaitai_struct#1065]
I've looked into gitter but it seems quite dead so decided to raise an issue (sorry about that. Perhaps enabling github discussions would make this better?).

I have a few questions:

1. I have a project that uses multiple languages that interact with each over using shared memory. Not all data is linear (i.e, you have pointers to things that are somewhere further away in memory). Currently I have to reimplement the same structs, accessors, etc in all languages. I was hoping that I could perhaps use kaitai for that, so that I don't have to reimplement the structs in every language. However, I don't see a way to wrap memory address in a struct, and it also seems that it insists on copying everything, so I can't just use kaitai as a read and write accessor just on pure memory? (I.e, setters mutating the memory they are wrapping). Is that correct?
2. i have a sequence of structs that have a type byte at the front that I'd like to switch on when reading these structs. However I'd like to preserve the type byte in the struct instances themselves, as there are cases where the struct value it dependant on the total structs size, and if the type byte is consumed by the switch, there would have to be some manual calculations involved to work that out. Can i type switch by peeking and not consuming the type byte, so that its still available as the first byte in the struct?

Thanks.

**Comment by GreyCat** [comment]
NB: coming forward, please use two different issues to track two unrelated problems. It will be much easier to track.

> 1. I have a project that uses multiple languages that interact with each over using shared memory. Not all data is linear (i.e, you have pointers to things that are somewhere further away in memory). Currently I have to reimplement the same structs, accessors, etc in all languages. I was hoping that I could perhaps use kaitai for that, so that I don't have to reimplement the structs in every language. However, I don't see a way to wrap memory address in a struct, and it also seems that it insists on copying everything, so I can't just use kaitai as a read and write accessor just on pure memory? (I.e, setters mutating the memory they are wrapping). Is that correct?

In general, that's not what KS was designed for. Direct memory access, and any forms of addressing, are very platform and implementation-specific, and for KS, that's kind of anti-goal: we strive hard to avoid using such features and rather than supporting *implementation*, we strive to support *intent*, which might have many alternative implementations.

Speaking of structures in memory, quite often these are very different beasts than structures in a stream that KS is designed to handle. E.g. 80-90% of what KS is doing might be not applicable to structures in memory, but, vice versa, some unique features like pointers and emulation of virtual memory might be required. 

That being said, your mileage may vary, and, to certain extent, it might be possible to reuse KS to achieve some of your goals too. Also you might be interested to take a look at https://github.com/kaitai-io/kaitai_struct/issues/492, but that's approaching this problem from a slightly different angle.

> 2. i have a sequence of structs that have a type byte at the front that I'd like to switch on when reading these structs. However I'd like to preserve the type byte in the struct instances themselves, as there are cases where the struct value it dependant on the total structs size, and if the type byte is consumed by the switch, there would have to be some manual calculations involved to work that out. Can i type switch by peeking and not consuming the type byte, so that its still available as the first byte in the struct?

You can peek anywhere in an instance with `pos`, but in your case, I rather advise to pass that byte as parameter in case you'll need it:

```yaml
seq:
  - id: type
    type: u1
  - id: body
    type:
      switch-on: type
      cases:
        1: foo(type)
        2: foo(type)
        # ...
types:
  foo:
    params:
      - id: type
        type: u1
    seq:
      - id: cond_attr
        size: 'type == 1 ? 3 : 5'
        # can use `type` here
```

Or, you can use `_parent` to access it too:

```yaml
seq:
  - id: type
    type: u1
  - id: body
    type:
      switch-on: type
      cases:
        1: foo
        2: foo
        # ...
types:
  foo:
    seq:
      - id: cond_attr
        size: '_parent.type == 1 ? 3 : 5'
```
