### ISSUE TITLE
convenient way to handle "break on wrong value" sequences

### ISSUE THREAD

**Issue by enwony** [kaitai-io/kaitai_struct#1072]
There are some formats that rely on non-magic field to detect if sequence if exausted.

For example, this ksy:
```
meta:
  id: test
  file-extension: test
  endian: le

seq:
  - id: sequence
    repeat: until
    repeat-until: _.type != 0xBABECAFE
    type: myrecord
    
  - id: data
    size-eos: true

types:
  myrecord:
    seq:
    - id: type
      type: u4
    
    - id: value
      type: u4
```
for this file:
```
0xBABECAFE 
0x0000000001
0xBABECAFE
0x0000000001
...rest of data...
```

one additional myrecord consumed from rest of data
workaround is to parse such cases manually
how can I handle it in more convenient way?
could I use new valid expression?
