### ISSUE TITLE
How to use instances: in a loop, where each iteration has a dynamic size?

### ISSUE THREAD

**Issue by jeansanch** [kaitai-io/kaitai_struct#1079]
How can I get the ```pos``` of an item inside a loop of blocks that have different sizes?

I've tried doing

```
seq:
  - id: skip_init
    size: 280060
  - id: run_data
    type: data
    repeat: expr 
    repeat-expr: 2 # just to test
instances:
  names:
    io: run_data[_index]._io
    pos: 0
    size: run_data[_index].name_size
```

I have tried to add instances with a similar logic inside of the run_data block, but it would always point to the same block of data.

I'm doing this because I've a structure that looks something like this.

name[name_size]
zeroes[2] (that will only appear if (name_size / 2) % 2 == 1) + data[8]
name2[name_size]
zeroes[Value also based on the string size]
data[400]
name_size[2]
data[16]

so I have to pass through the string first, then I'm able to get the name_size value.

Still I've managed to parse each block using another logic, that doesn't allow me to filter the "name" , that's why I was using instances for "post-processing"

What I would like to do is something like this.

```
seq:
  - id: skip_init
    size: 280060
  - id: run_data
    type: data
    repeat: expr 
    repeat-expr: 2 # just to test
instances:
  names:
    pos: Start of the block at each index
    size: name_size variable of each index
```

Am I taking the best approach for this? I've read the documentation, but I was not able to get an answer for this specific case.
