### ISSUE TITLE
Regarding Parsing of Global Data in Kaitai Struct Definition

### ISSUE THREAD

**Issue by laosiji66666** [kaitai-io/kaitai_struct#1081]
I have a protocol definition where each frame consists of 64 bytes, with the first byte fixed at 0xAA and the last byte fixed at 0x55. The initial byte represents the frame ID, and depending on the frame ID, different data is included. Specifically, when the frame ID is 0x01, the data included is considered global, meaning that subsequent frames should also include the data associated with frame ID 0x01 during parsing. However, I am uncertain about how to include the data associated with frame ID 0x01 when parsing other data frames. The appearance of 0x01 is not fixed; it may occur at the beginning or in the middle of the file. I have been trying to address this for a while without success.

Below is my KSY file. Could you please advise on how to handle this situation or if it's possible to implement this functionality?
``` yaml
meta:
  id: test
  file-extension: test
  endian: le
  bit-endian: le

seq:
  - id: frames
    type: frame
    repeat: eos

types:
  frame:
    seq:
      - id: head
        type: u1
        valid: 0xaa
      - id: data_id
        type: u1
      - id: data
        size: 61
        type:
          switch-on: data_id
          cases:
            0x01: static_data
            0x42: dynamic_data
            0x43: dynamic_data
            0x44: dynamic_data
      - id: tail
        type: u1
        valid: 0x55
  static_data:
    seq:
      - id: data
        type: u4
  dynamic_data:
    seq:
      - id: data
        type: u4
      #...
```
I appreciate your assistance in advance.

Best regards,
