### ISSUE TITLE
if-expression with self-link for optional field

### ISSUE THREAD

**Issue by fersatgit** [kaitai-io/kaitai_struct#1084]
Seems self-linked conditions not working.  Here example
```
- id: signature
    size: 4
    type: str
    encoding: "windows-1251"
    if: signature.as<u4>==0x20424453
```
Another example (also not working)
```
  - id: signature
    size: "signature.as<u4>==0x20444253?4:0"
    type: str
    encoding: "windows-1251"
```

**Comment by fersatgit** [comment]
finaly I was found the solution with instances, but here is some litle bug in vizualizer (array dispalyed not yet correctly)
![1](https://github.com/kaitai-io/kaitai_struct/assets/122711455/ef95b7c1-92df-4958-ab9a-77a3083318df)

full code
```
meta:
  id: goldenland2_sdb
  title: "Златогоье 2 SDB"
  file-extension: sdb
  endian: le
  bit-endian: le
seq:
  - id: signature
    type: str
    size: 4
    encoding: "windows-1251"
  - data:
      type: string_entry
      repeat: eos
      if: signature=="SDB "
instances:
  encrypted_data:
    pos: 0
    type: encrypted_string_entry
    repeat: eos
    if: signature!="SDB "
types:
  string_entry:
    seq:
      - id: id
        type: u4
      - id: len
        type: u4
      - id: string
        size: len
        type: str
        encoding: "windows-1251"
  encrypted_string_entry:
    seq:
      - id: id
        type: u4
      - id: len
        type: u4
      - id: string
        size: len
        process: xor(0xAA)
        type: str_wrapper
  str_wrapper:
    seq:
      - id: value
        size-eos: true
        type: str
        encoding: "windows-1251"
```
