### ISSUE TITLE
Using enum members as int is broken in ruby

### ISSUE THREAD

**Issue by smx-smx** [kaitai-io/kaitai_struct#1091]
The following ksy:
```yaml
meta:
  id: kaitai_bug
  file-extension: kaitai_bug
  endian: le
enums:
  bug:
    0: item0
    1: item1
    2: item2
seq:
  - id: array
    type: u4
    repeat: expr
    repeat-expr: 3
instances:
  item1:
    value: array[bug::item1.as<u4>]
```

generates the following incorrect ruby code:

```ruby
  BUG = {
    0 => :bug_item0,
    1 => :bug_item1,
    2 => :bug_item2,
  }
  I__BUG = BUG.invert
  ...
  def item1
    return @item1 unless @item1.nil?
    @item1 = array[:bug_item1]
    @item1
  end
  ```
  
  which triggers the following error when accessing `item1`:
```
no implicit conversion of Symbol into Integer (TypeError)
```

because the array key is not a number.

I guess the expected output should be `array[I__BUG[:bug_item1]]` ?
