### ISSUE TITLE
How to access data in an item array dependent on the position from the current item

### ISSUE THREAD

**Issue by SLAZ666** [kaitai-io/kaitai_struct#111]
Hi,

I have a problem parsing a special data format. I have made a simple example and hope it makes my problem clear. I have attached it to this post [test.zip](https://github.com/kaitai-io/kaitai_struct/files/766865/test.zip)

This structure in general has two pointers from the beginning of the structure into the data field and references a string.

```yaml
meta:
  id: test
  endian: le
seq:
  - id: item
    type: itemheader
    repeat: eos
types:
  itemheader:
    seq:
      - id: flags
        type: u2
      - id: size
        type: u2
      - id: data1pos
        type: u2
      - id: data2pos
        type: u2
      - id: data
        size: size - 8
    instances:
      data1:
        if: (data1pos > 0) and (data1pos < size)
        pos: data1pos
        type: strz
        encoding: ASCII
      data2:
        if: (data2pos > 0) and (data2pos < size)
        pos: data2pos
        type: strz
        encoding: ASCII
```

Behavior:
item[0].data1 = test1
item[0].data2 = null
item[1].data1 = test1
item[1].data2 = \x23\x17
item[2].data1 = \x17
item[2].data2 = test1

Expected behavior:
item[0].data1 = test1
item[0].data2 = null
item[1].data1 = test12
item[1].data2 = test123
item[2].data1 = test1234
item[2].data2 = test12345

The problem is that the position reference in the instances is in reference to the used stream, which always starts at the beginning of the file and not for every item itself.

Is there anything I am doing wrong, or can I circumvent this behavior?
Any help would be appreciated.

Regards

Anton

**Comment by GreyCat** [comment]
I reckon that you have `itemheader` basically consisting of 2 parts:

* fixed 8 bytes of "header" which contains sizes and positions of data1 and data2 inside `data`
* arbitrary sized `data` buffer

Positions are relative to the start of that fixed bytes header, but actual data in always in `data` buffer, so we can assume that positions relative to start of `data` are always `dataXpos - 8`.

So, my idea of parsing would be to subtract 8 from data1 and data2 positions and use resulting values to address stuff inside `data` buffer, i.e. something like that:

```yaml
meta:
  id: test
  endian: le
  encoding: ASCII
seq:
  - id: item
    type: itemheader
    repeat: eos
types:
  itemheader:
    seq:
      - id: flags
        type: u2
      - id: size
        type: u2
      - id: data1pos
        type: u2
      - id: data2pos
        type: u2
      - id: data
        size: size - 8 # note that we specify a size here, so it creates a separate substream
        type: itemdata
  itemdata:
    instances:
      data1:
        if: (_parent.data1pos >= 8) and (_parent.data1pos < _parent.size)
        pos: _parent.data1pos - 8 # these positions are relative to new data substream
        type: strz
      data2:
        if: (_parent.data2pos >= 8) and (_parent.data2pos < _parent.size)
        pos: _parent.data2pos - 8
        type: strz
```

Also note that you can specify `encoding` once in `meta` section if it's mostly the same for whole file.

Alternatively, if you don't want extra level of abstraction, one might use a hack with dummy user type and specifying `io` to select proper IO stream:

```yaml
meta:
  id: test
  endian: le
  encoding: ASCII
seq:
  - id: item
    type: itemheader
    repeat: eos
types:
  itemheader:
    seq:
      - id: flags
        type: u2
      - id: size
        type: u2
      - id: data1pos
        type: u2
      - id: data2pos
        type: u2
      - id: data
        size: size - 8 # also creates new substream
        type: dummy
    instances:
      data1:
        if: (data1pos >= 8) and (data1pos < size)
        io: data._io # force usage of stream from `data` object
        pos: data1pos - 8
        type: strz
      data2:
        if: (data2pos >= 8) and (data2pos < size)
        io: data._io
        pos: data2pos - 8
        type: strz
  dummy: {}
```

And I believe that your last test is slightly erroneous: `item[2].data1 == "5"` and `item[2].data2 == "test12345"`?
