### ISSUE TITLE
Sometimes errors does not have path

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#1131]
This KSY
```yaml
meta:
  id: test_type
instances:
  me:
    value: _on
```
reports the error (note, that this is full text):
```
java.util.NoSuchElementException: None.get
```

Compare with that KSY:
```yaml
meta:
  id: test_type
instances:
  me:
    type:
      switch-on: 1
      cases:
        _on: u1
```
Error is:
```
test_type: /instances/me/type/cases/Name(identifier(_on)):
	error: None.get
```
Note, that error with missing path generated in many other cases (can't remember all the places, I started tracking them after I ran into the latest example).
