### ISSUE TITLE
Unconsistent requirements for enum keys when they represented as numbers and as strings

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#1132]
Kaitais struct allows to define enum key either as number, or as string which value is number.
https://github.com/kaitai-io/kaitai_struct_compiler/blob/c23ec2ca88d84042edba76f70c1f003d062b7585/shared/src/main/scala/io/kaitai/struct/format/EnumSpec.scala#L33-L35
Numbers are extracted using `ParseUtils.asLong` method...
https://github.com/kaitai-io/kaitai_struct_compiler/blob/c23ec2ca88d84042edba76f70c1f003d062b7585/shared/src/main/scala/io/kaitai/struct/format/ParseUtils.scala#L186-L194
...which uses `Utils.strToLong` which uses simple regular expressions to detect decimal and hexadecimal numbers:
https://github.com/kaitai-io/kaitai_struct_compiler/blob/c23ec2ca88d84042edba76f70c1f003d062b7585/shared/src/main/scala/io/kaitai/struct/Utils.scala#L29-L34
```
^(-?[0-9]+)$
^0x([0-9a-fA-F]+)$
```
That means that you cannot:
- use octal numbers (not bad, its anyway bad practice because of their low prevalence)
- use uppercase `X` in hexadecimal numbers (which is allowed in expression language)
- use underscores for better readability 

All of that creates inconsistence between literal numbers and literal strings in YAML markup:
```yaml
meta:
  id: enums
enums:
  enum:
    1_1: dec_int
    # '1_1': dec_string # error: unable to parse `1_1` as int
    0x1_1: hex_int
    # '0x1_1': hex_string # error: unable to parse `0x1_1` as int
    # 0X1: hex_uppercase # error: unable to parse `0X1` as int
```
For consistency it would be better reuse either YAML int parser, or int parser from expression language.

Also note, that both YAML parser and regular expression allows leading zeroes for decimal numbers, but expression language not:
https://github.com/kaitai-io/kaitai_struct_compiler/blob/c23ec2ca88d84042edba76f70c1f003d062b7585/shared/src/main/scala/io/kaitai/struct/exprlang/Lexical.scala#L86
This inconsistency probably also should be fixed.

#448 may be related (it is possible to solve both problems at once).
