### ISSUE TITLE
CSharpCompiler.scala | attrFixedContentsParse may generate invalid code

### ISSUE THREAD

**Issue by titobrasolin** [kaitai-io/kaitai_struct#1146]
In C# the byte number type is unsigned, that's why the generated code for this simpe ksy is invalid:

```
meta:
  id: test
seq:
  - id: something
    contents: [0xFF]
```

Generated code:

```
private void _parse()
{
    _something = m_io.EnsureFixedContents(1, new byte[] { -1 });
}
```

Of course -1 cannot be converted to byte.
