### ISSUE TITLE
Parent keyword for switch construction

### ISSUE THREAD

**Issue by zeddvandaar** [kaitai-io/kaitai_struct#1160]
Parent::child construction does not working for "switch-on" expression.

Real example of blizzard resources file format.

```
meta:
  id: m3
  application: Blizzard Game
  endian: le
seq:
  - id: header
    contents: ["43DM"]
  - id: ofs_tags
    type: u4
  - id: n_tags
    type: u4
types:
  tag:
    seq:
      - id: name
        type: str
        size: 4
        encoding: ASCII
      - id: offset
        type: u4
      - id: nbr_items
        type: u4
      - id: flag
        type: u4
    types:
      # tag_sd:
        # types:
          # tag_sd_item:
            # seq:
              # - id: entries
                # type: u4
              # - id: indx
                # type: u4
              # - id: flag
                # type: u4
              # - id: flags
                # type: u4
              # - id: end_frame
                # type: u4
              # - id: entries2
                # type: u4
              # - id: indx2
                # type: u4
              # - id: flag2
                # type: u4
        # instances:
          # tag_sd_content:
            # type: tag_sd_item
            # repeat: expr
            # repeat-expr: nbr_items
      tag_char:
        seq:
          - id: content
            # type: u1
            type: str
            size: _parent.nbr_items
            encoding: ASCII
    instances:
      tag_content:
        pos: offset
        type: 
          switch-on: name
          cases:
            # '"VEDS"': tag_sd
            # '"V2DS"': tag_sd
            # '"SD3V"': tag_sd
            # '"3RDS"': tag_sd
            # '"CCDS"': tag_sd
            # '"6SDS"': tag_sd
            # '"6UDS"': tag_sd
            # '"3UDS"': tag_sd
            # '"Q4DS"': tag_sd
            # '"GFDS"': tag_sd
            # '"BMDS"': tag_sd
            '"RAHC"': tag_char
        # repeat: expr
        # repeat-expr: nbr_items
        io: _root._io
instances:
  index:
    pos: ofs_tags
    type: tag
    repeat: expr
    repeat-expr: n_tags
    io: _root._io
```

nbr_items field is avaidle at tag_content instance, but _parent.nbr_items does not working at included over switch-on element.
I propose to change behavior of _parent expression, or add _owner keyword for runtime linking.
