### ISSUE TITLE
How to compare Bit1Type in conditional statement?

### ISSUE THREAD

**Issue by nsforth** [kaitai-io/kaitai_struct#118]
I've recently tried to compare boolean flag in conditional statement but got compilation error:
KS compilation error:  io.kaitai.struct.translators.TypeMismatchError: can't compare BitsType1 and BooleanType
Example code:
```
meta:
  id: check_b1
seq:
  - id: bit1
    type: b1
  - id: next
    type: u1
    if: bit1 == true
```
What a proper way to compare bit flag?
