### ISSUE TITLE
Negative enums generate invalid Javascript

### ISSUE THREAD

**Issue by natronium** [kaitai-io/kaitai_struct#1187]
Defining an enum with a negative value, generates some invalid Javascript that looks like
```javascript
  BrokenJsEnums.Constants = Object.freeze({
    NEGATIVE_ONE: -1,
    POSITIVE_ONE: 1,

    -1: "NEGATIVE_ONE",
    1: "POSITIVE_ONE",
  });
```
And throws `SyntaxError: Unexpected token -`

Javascript  is expecting [an identifier, a string, or a number](http://www.ecma-international.org/ecma-262/7.0/index.html#prod-LiteralPropertyName) and `-` [is an operator](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-unary-minus-operator), and not part of [the numeric literal syntax](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-literals-numeric-literals).

I think the right solution is to quote the numeric value when it's used as a key, since an Object's keys get up being converted to strings anyhow.

Here's a ksy for testing. The Web IDE breaks silently when it tries to use it, since the generate javascript is invalid.
```yaml
meta:
  id: broken_js_enums
enums:
  constants:
    -1: negative_one
    1: positive_one
seq:
  - id: f1
    type: s1
    enum: constants
  - id: f2
    type: s1
    enum: constants
```
Github doesn't like my testcase file, but you can generate a file to test this parser against with `echo -en '\xff\x00' > testcase.dat`
