### ISSUE TITLE
New repeat form "size"

### ISSUE THREAD

**Issue by nsforth** [kaitai-io/kaitai_struct#119]
Is is possible to implement new repeat directive "size"? For example:
```
     - id: record_length
        type: u2
      - id: subrecords
        type: subrecord
        repeat: size
        repeat-size: record_length
```
It's real example, i know i can do that with:
```
     - id: record_length
        type: u2
      - id: subrecords_array
        type: subrecord_array
        size: record_length
  subrecord_array:
    seq:
      - id: subrecords
        type: subrecord
        repeat: eos
```
But in such example i've got useless subrecord_array that holds array of subrecords, instead of simple array of subrecords.

**Comment by GreyCat** [comment]
Thanks for your suggestion!

I understand the issue, but I think we need to find a better way to deal with it. The actual problem is with ambiguility of `size` here, i.e.:

```yaml
  - id: record_length
    type: u2
  - id: subrecords_array
    type: subrecord
    size: record_length # <= this one
    repeat: eos
````

By our convention, `size` here means size of each individual element, but in reality there are 2 different "sizes" which it can refer to:

* size of each individual element
* size of whole collection

I have two ideas:

1. Separating them (for example, as `size-element` and `size-collection`) and implementing each one separately. `size` would map to `size-element` if `repeat` is present for compatibility for some time, then we'll make it an error.

This shouldn't need to be limited with particular `repeat: ...` type. If might be just as useful for `repeat: expr`, `repeat: until`, etc.

2. Go a bit further and introduce something like "passthrough types", i.e. for doing stuff like `subrecord_array` transparent. Something like that:

```yaml
  subrecord_array:
    seq:
      - id: subrecords
        type: subrecord
        repeat: eos
    passthrough-value: subrecords
```

That would mean that any reference to `subrecord_array` would actually access `subrecord_array.subrecords`, i.e. instead of this getter:

```java
    public SubrecordArray subrecordsArray() { return subrecordsArray; }
```

compiler would generate this automatically:

```java
    public ArrayList<Subrecord> subrecordsArray() { return subrecordsArray.subrecords(); }
```

etc.

**Comment by LogicAndTrick** [comment]
Hm, I fear you may be overcomplicating things a bit. Could this be solved by #84 with the `sizeof` function?

Like this:
```yaml
    - id: record_length
      type: u2
    - id: subrecords
      type: subrecord
      repeat: expr
      repeat-expr: record_length / sizeof(subrecord)
```

**Comment by KOLANICH** [comment]
>Go a bit further and introduce something like "passthrough types"

related to #88

**Comment by GreyCat** [comment]
@LogicAndTrick Not really. First of all, `sizeof` would probably work only on fixed-size types, and `subrecord` might have conditionals, strings, etc. Even if there is a fixed size type inside, generally that's not exact equivalent: for example, declaring size of entire collection would make a guarantee that that collection will take exactly as many bytes as it was declared to have. If something inside would read less than that amount, that's ok — we'll just ignore the unused bytes. If something inside would try to use more than allocated substream — we'll get clean exception, which would alarm for a problem early, instead of figuring out much later why we've got corrupt data.

@KOLANICH Yeah, thanks — I was just remembering that the original idea yours and it was something in the tracker...

**Comment by JaapAap** [comment]
I am having a need for a similar (possibly identical) functionality. Would the `size-element` and  `size-collection` allow for an a priori unknown number of elements in the collection? In my case, the number of elements is unknown, as each element contains some fixed integers plus N sub-elements (with N varying for each element) and I am sure whether that would automatically be supported with this proposed solution?

**Comment by GreyCat** [comment]
@JaapAap To make it clear, we're talking about cosmetic stuff here, i.e. better-looking, more concise syntax, not some new functionality. 100% of stuff described here can be implemented right now, with existing syntax, as @nsforth pointed out in the opening message — it just needs extra intermediate type declaration.

If your situation is "total collection size is known, but number of elements is unknown and each element's size is varying", then it's exactly how @nsforth described it. If it's something else, please clarify what's known, what's not and how it's supposed to be parsed by manually coded parser?

**Comment by JaapAap** [comment]
You might well be right (I am a starting user and might just misunderstand this). Indeed, my situation is very much like the one described in the first post:
```
     - id: record_length
        type: u2
      - id: subrecords_array
        type: subrecord_array
        size: record_length
  subrecord_array:
    seq:
      - id: subrecords
        type: subrecord
        repeat: ??? until the end of subrecords_array ???
```
The number of subrecords is unknown a priori. My assumption is that using 'eos' is actually ensuring repetition until the end of the stream, while in my case I would need it to repeat until the end of the `subrecords_array` instead. Am I mistaken?
