### ISSUE TITLE
Opaque parametric types

### ISSUE THREAD

**Issue by SpenserStyles** [kaitai-io/kaitai_struct#1192]
Is there a way to do opaque parametric types without Kaitai references in the constructor?  I have a large code base and would like to start integrating the use of Kaitai but currently it would require some additional code to connect to the two.
 
Example:

```
meta:
  id: main
  file-extension: main
  endian: be
  ks-opaque-types: true

seq:
  - id: buff
    size: 31
  - id: result
    type: custom(buff)
```

This would generate:
Custom result = new Custom(buff);

This seems to be similar to custom processes minus the decode step.
