### ISSUE TITLE
Ability to sum array elements in Kaitai Struct

### ISSUE THREAD

**Issue by tetelevm** [kaitai-io/kaitai_struct#1230]
I have two similar problems. The first one: I need `int` of sizes other than `u1`, `u2`, `u4`, and `u8`. I created a custom `u3` type that fits my needs:

```yaml
types:
  u3:
    seq:
      - id: b0
        type: u1
      - id: b1
        type: u1
      - id: b2
        type: u1
    instances:
      le:
        value: (b0 << 16) + (b1 << 8) + b2
      be:
        value: b0 + (b1 << 8) + (b2 << 16)

seq:
  - id: my_val
    type: u3
instances:
  le:
    value: my_val.le
  be:
    value: my_val.be

# in: hex("01 02 03")
# out: le == 66051
# out: be == 197121
```

The problem is that using other sizes requires duplicating code. Is there any way to generalize the creation of such types? Something like this:

```yaml
type:
  byte_type:
    params:
      - id: size
        type: u1
      - id: index
        type: u1
    seq:
      - id: byte
        type: u1
    instances:
      le:
        value: byte << ((size-index) * 8)
      be:
        value: byte << (index * 8)
  u:
    params:
      - id: size
        type: u1
    seq:
      - id: bytes
        type: byte_type(len, _index)
        repeat: expr
        repeat-expr: size
    instances: 
      le:
        value: sum(bytes.le) # ???
      be:
        value: sum(bytes.be) # ???
```

So that later I could define it simply like this:

```yaml
seq:
  - id: data0
    type: u(3)
  - id: data1
    type: u(5)
instances:
  data0_le:
    value: data0.le
  data1_le:
    value: data1.be

# in: hex("010203 0405060708")
# out: data0_le == 66051
# out: data1_le == 17264150280
```

Is it possible to reproduce the effect of `sum(bytes.be)` in Kaitai?

The second problem is quite similar, but this time I need to concatenate an array of strings (concatenate(["01", "02", "03"]) # => "010203").

**Comment by EmperorArthur** [comment]
Hacky solution.  May break in the future.


Example:
```yaml
seq:
  - id: to_sum
    type: u1
    repeat: until
    repeat-until: _ == 0xff
instances:
  accumulator:
    type: accumulator(_index, to_sum[_index])
    repeat: expr
    repeat-expr: to_sum.size - 1
  sum:
    value: accumulator[accumulator.size - 1]
types:
  accumulator:
    params:
      - id: i
        type: u4
      - id: to_add
        type: u4
    instances:
      running_total:
        doc: 'The as<u4>' allows this to work without an error.'
        value: |
          i <=0 ? to_add : to_add + _parent.accumulator[i-1].running_total.as<u4>
```
