### ISSUE TITLE
Coalescing string with length prefix

### ISSUE THREAD

**Issue by Shinmera** [kaitai-io/kaitai_struct#1232]
My apologies if this has been discussed before, I tried to look for it and couldn't find it.

In a format I'm developing strings usually are a combination of a leading length integer, followed by a zero terminated string. So for instance:

```yaml
string4:
  seq:
    - id: length
      type: u4
    - id: string
      type: strz
      size: length  
```

What bothers me about this is that in the generated parser this creates a wrapping structure, even though *all* of the information is already contained in the string itself, and I can't see a way to elide this extra wrapping.

This is a separate issue, but: additionally it would be nice if I could specify the size of the length encoding as a parameter, so `string(4)` would use `u4` for the length, rather than having to copy-paste define a `string1`, `string2`, etc. It's not clear to me that this kind of parametric typing is possible however, and it's not that big a deal.
