### ISSUE TITLE
Accessing of sibling properties

### ISSUE THREAD

**Issue by Shinmera** [kaitai-io/kaitai_struct#1233]
In the "table data" format I'm parsing there is a sort of sibling array structure, where the first array describes the data types of elements in the second array.  For example a table with two columns, the first being a 16-bit integer and the second two single floats would have two column descriptors, followed by a number of rows, where each row is made up of that integer and those two floats.

However, in order to parse the row cell contents, I somehow have to access which column the cell belongs to, to get the corresponding column descriptor entry. I can't see any way to do this. My current Kaitai spec looks something like this (abbreviated):

```yaml
  table:
    seq:
      - id: column_count
        type: u2
      - id: row_count
        type: u8
      - id: column_specs
        type: column_spec
        repeat: expr
        repeat-expr: column_count
      - id: rows
        type: row
        repeat: expr
        repeat-expr: row_count
  column_spec:
    seq:
      - id: column_type
        type: u1
        enum: column_types
      - id: column_length
        type: u4
    instances:
      element_size:
        value: 0x0F & column_length
      element_count:
        value: column_length / element_size
  row:
    seq:
      - id: cells
        type: cell
        repeat: expr
        repeat-expr: _parent.column_count
  cell:
    seq:
      - id: elements
        repeat-expr: _root.table.column_specs[???].element_count
        type:
          switch-on: _root.table.column_specs[???].column_type
          cases:
            'column_types::uint8': u1
            'column_types::uint16': u2
            'column_types::uint32': u4
            'column_types::uint64': u8
            'column_types::int8': s1
            'column_types::int16': s2
            'column_types::int32': s4
            'column_types::int64': s8
            'column_types::float32': f4
            'column_types::float64': f8
```

I tried to think of a way to do the parsing logic via instances, but I'm honestly quite confused about how one would get this to work using those, too, as I would still need to somehow access the sibling position or io or something.

**Comment by Mingun** [comment]
If I understand your correctly, you need to pass index as a parameter to `cell`:
```yaml
...
  row:
    seq:
      - id: cells
        type: cell(_index)
        repeat: expr
        repeat-expr: _parent.column_count
  cell:
    params:
      - id: column:
        type: u4
    seq:
      - id: elements
        repeat-expr: _root.table.column_specs[column].element_count
...
```
