### ISSUE TITLE
Erroneous C++ forward declarations for types

### ISSUE THREAD

**Issue by lafrecciablu** [kaitai-io/kaitai_struct#1234]
I am trying to use an enumeration for determining the message type to decode.
It works fine with ksdump, but the generated C++ code fails to compile due to wrongly generated forward declaration.
This may be related to bug #651, but I am not completely sure.
As a general behavior, `ksc` is producing an `include` and a **useless forward declaration** for each `import` instruction.
This may be fine in most cases, but is problematic when it does it also inside class declaration, adding a hierarchy which does not exist.

Here is a simplified example of the behavior.

```yaml
meta:
  id: message
  endian: be
  imports:
    - msg_kind

seq:
  - id: header
    type: header
  - id: content
    type: content( header.kind )

types:
  header:
    seq:
      - id: kind
        type: msg_kind

  content:
    params:
      - id: kind
        type: msg_kind

    seq:
      - id: content_variant
        type:
          switch-on: kind.kind
          cases:
            'msg_kind::msg_kind_enum::type_1': type_1
            'msg_kind::msg_kind_enum::type_2': type_2
            _: unsupported_message

  type_1: {}
  type_2: {}
  unsupported_message: {}

```

```yaml
meta:
  id: msg_kind
  endian: be

seq:
  - id: kind
    type: u2
    enum: msg_kind_enum

enums:

  msg_kind_enum:
    0: type_1
    1: type_2

```

Using
`ksc --target cpp_stl --outdir cpp --cpp-standard 11 content.ksy
`
produces:

_message.h:_

```cpp
[...]
#include "msg_kind.h"
class msg_kind_t; // why is this forward declaration produced?

class message_t : public kaitai::kstruct {

public:
    // why are these forward declarations produced?
    class unsupported_message_t;
    class type_1_t;
    class content_t;
    class header_t;
    class type_2_t;

    message_t(kaitai::kstream* p__io, kaitai::kstruct* p__parent = nullptr, message_t* p__root = nullptr);

public:
    class content_t : public kaitai::kstruct {

    public:
        // ==> this nested forward declaration is inexistent and leads to a compiler error <==
        class msg_kind_t;

        content_t(msg_kind_t* p_kind, kaitai::kstream* p__io, message_t* p__parent = nullptr, message_t* p__root = nullptr);

    class header_t : public kaitai::kstruct [...]
    class type_2_t : public kaitai::kstruct [...]
    class type_1_t : public kaitai::kstruct [...]
    class unsupported_message_t : public kaitai::kstruct [...]

```

_message.cpp:_

```cpp
#include "message.h"
#include "msg_kind.h" // why is msg_kind included again?

message_t::message_t(kaitai::kstream* p__io, kaitai::kstruct* p__parent, message_t* p__root) : kaitai::kstruct(p__io) [...]

message_t::content_t::content_t(msg_kind_t* p_kind, kaitai::kstream* p__io, message_t* p__parent, message_t* p__root) : kaitai::kstruct(p__io) {
    m__parent = p__parent;
    m__root = p__root;
    m_kind = p_kind;
    _read();
}

void message_t::content_t::_read() {
    switch (kind()->kind()) { // does not compile <==
    case msg_kind_t::MSG_KIND_ENUM_TYPE_1: {
        m_content_variant = std::unique_ptr<type_1_t>(new type_1_t(m__io, this, m__root));
        break;
    }

```
The kind()->kind() cannot be resolved due to the nested forward declaration:

```console
message.cpp:67:10: error: incomplete type 'message_t::content_t::msg_kind_t' named in nested name specifier
message.h:80:15: note: forward declaration of 'message_t::content_t::msg_kind_t'
```

```bash
ksc --version
kaitai-struct-compiler 0.10

```

Until a bug fix is released, what would be the recommended workaround?

Thank you for any feedback.
