### ISSUE TITLE
Strings in UTF-16 encodings does not decoded correctly

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#1243]
I develop a KSY for new [Windows event log file format](https://github.com/libyal/libevtx/blob/main/documentation/Windows%20XML%20Event%20Log%20(EVTX).asciidoc#value_types) (*.evtx). The part of that KSY is `utf16_str` type to use in `switch-on` type:
```yaml
types:
  utf16_str:
    -webide-representation: '{value}'
    seq:
      - id: value
        type: str
        encoding: UTF-16LE
        size-eos: true
```
That KSY generates the following code:
```js
  var Utf16Str = WindowsEvtxLog.Utf16Str = (function() {
    function Utf16Str(_io, _parent, _root) {
      this._io = _io;
      this._parent = _parent;
      this._root = _root || this;

      this._read();
    }
    Utf16Str.prototype._read = function() {
      this.value = KaitaiStream.bytesToStr(this._io.readBytesFull(), "UTF-16LE");
    }

    return Utf16Str;
  })();
```
But in WebIDE (both old and new) the results are one `U+FFFD` character:
![firefox_mQZ2CXgGjF](https://user-images.githubusercontent.com/450131/196003284-d6bd3cf9-ebb6-4001-8970-0c4e919790e3.png)
