### ISSUE TITLE
Parsing from multiple files

### ISSUE THREAD

**Issue by mnakamura1337** [kaitai-io/kaitai_struct#125]
I'm working on reverse engineering of a container that essentially consists of 2 files:

* first file is a "directory", which contains a list of file names and offsets / sizes in a second file
* second file is "data file", which contains no directory / indexes/ whatever, but just raw files

The only way to access data in second file is to use the first file. However, if I'm not mistaken, Kaitai Struct does not allow to access extra files while parsing. So, I want to propose something like:

```yaml
seq:
  - {id: filename, size: 16, type: str}
  - {id: offset, type: u4}
  - {id: len, type: u4}
instances:
  file_body:
    filename: '"body.dat"' # expression language for flexibility
    pos: offset
    size: len
```

In fact, I've encountered quite a few of such multi-file formats in last few months or so. I believe it would be a very useful addition to Kaitai Struct.
