### ISSUE TITLE
Should we eliminate repeat-* ?

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#128]
Why do we need the whole family of ```repeat-*``` ?
The suggestion is to eliminate them and use the expression type of usual ```repeat``` to decide which type of repeat is used.
1 If it is integer, behave like ```repeat-expr```
2 if it is boolean, behave like ```repeat-until```
3 if it is string, for example "eos", behave depending on the string
4 if it is something else, throw error

**Comment by GreyCat** [comment]
No, we shouldn't. This is against the idea of having a YAML-based language, where one doesn't to solve too many ambiguities and introduce complex logic to parse the .ksy.

Besides, what are you gonna do with stuff like that:

```yaml
seq:
  - id: foo
    type:
      size: 1
      switch-on: something
      cases:
        1: u1 # => integer
        2: b1 # => boolean
        3: str # => string
  - id: bar
    repeat: foo
```

This way `bar` can be either integer or boolean. Shall it generate all possible loop implementations and switch in runtime?
