### ISSUE TITLE
Fixed-length string with terminating character

### ISSUE THREAD

**Issue by LogicAndTrick** [kaitai-io/kaitai_struct#13]
I can't work out if this is possible currently, but it doesn't seem obvious: Many formats reserve a fixed space for a file name but also have a terminating character (usually `\0`) to support variable length names.

For example:

``` c
typedef struct {
    char name[256];
} example;

example e;
e.name = "test";
writeToFile(e); // Writes { 'T', 'E', 'S', 'T', '\0', ... [+ 251 more bytes] }
```

Right now there's two options currently available that I can think of:

Option 1. Use `str` with a fixed length and the consumer has to deal with the terminator manually:

```
KSY:
      - id: name
        type: str
        size: 256
        encoding: ASCII

Code:
    var e = Example.FromFile("...");
    e.Name = FixTerminatedString(e.Name);
```

Option 2. Use `strz` with a terminator and then a second value for the rest of the array:

```
      - id: name
        type: strz
        encoding: ASCII
        terminator: 0x00
        consume: false
      - id: junk
        size: 256 - name.length
```

It'd be nice to support an optional terminator in the `str` type to automatically truncate the string in the runtime:

```
KSY:
      - id: name
        type: str
        size: 256
        encoding: ASCII
        terminator: 0x00

Runtime:
    public string ReadStrByteLimit(long length, bool terminated, byte terminator, string encoding)
    {
        var bytes = ReadBytes(length);
        if (terminated) bytes = bytes.TakeWhile(b => b != terminator).ToArray();
        return System.Text.Encoding.GetEncoding(encoding).GetString(bytes);
    }
```

Alternatively, a `size` option in the `strz` type would work as well, but I think it'd be more suited for the `str` type because the data is still fixed-width in the end.

You can see a real-world example in the `doom_wad.ksy` format (boxes = null characters):

![image](https://i.imgur.com/pfm2DTB.png)

**Comment by GreyCat** [comment]
Yeah, that might be a good idea - I like the approach that you've suggested. It also has a very important feature - thus data types can be both read (what we're doing now) and written (what we'll hopefully be doing in the future - i.e. serialization of objects into binary streams) without any ambiguility.

**Comment by GreyCat** [comment]
Returning to this proposal: I'd like to suggest slight modification: do not reuse `terminator` per se, but add another option like `pad-right`, which can be used to specify right padding bytes. I've seen two real-life use-cases:

* many formats use 0 designate end of string + pad the rest of the field with 0s as well
* some formats (ISO9660, majority of bank/card billing formats) use `0x20` (ASCII space) for right-padding of the field

The parsing idea is to read full field at once and then strip as many right-padding bytes (from the right side of the string) as we can. The generation (serialization) idea is to add right padding bytes to the given string's byte representation to make it up for full desired length of the field.

The semantics are slightly different than `terminator`, so I think that reusing `terminator` is a bad idea, it's better to add distinct new parameter. What do you think of it?

**Comment by LogicAndTrick** [comment]
I'd still prefer the terminator, myself. There's cases where the rest of the data in the buffer after the terminator is simply gibberish, consider that the string buffer would often be allocated using `malloc` and `strcpy`:

```c
char* str = (char*) malloc(16);
strcpy(str, "ABC");
```
Possible result:
```
41 42 43 00 C5 92 A3 A6 10 0F 57 C4 25 68 D2 6F 
A  B  C  .  |----- uninitialised memory ------|
```

**Comment by GreyCat** [comment]
Ok, then we actually need both - they're different, albeit linked concepts. I don't really like the idea of mixing different string reading algorithms (i.e. `str` and `strz`, though). May be we could just add `size: X` limiter argument for `strz`? That fits current "workaround with true object" well too, i.e.:

```yaml
- id: my_str
  type: strz
  # terminator: 0 is by default
  encoding: UTF-8
  size: 16
```

instead of:

```yaml
seq:
  - id: my_str
    type: terminated_str
    size: 16
types:
  seq:
    - id: value
      type: strz
      # terminator: 0 is by default
      encoding: UTF-8
```

**Comment by LogicAndTrick** [comment]
Yeah, works for me. But I'm starting to see the two different string readers merge into one. If `terminator` isn't specified (and had no default) and `size` is specified, you could replicate the `str` method using `strz`. Only having one string reading method would simplify the interface and also reduce duplicated work when adding new features such as the `pad-right` option.

```yaml
seq:
  - id: my_str
    type: str      # performs the role of both str and strz
    # at least one of size and terminator must be specified
    size: 16       # optional if terminator is specified (strz behaviour)
    terminator: 0  # doesn't default to 0 if not specified
    # other str/strz options
    encoding: ASCII
    pad-right: 0x20
    ...
```

While we're talking about strings, what do you think about adding a default encoding to the `meta` section, like the endianness? Often when a file uses a particular encoding, the encoding will be the same for the entire file.

```yaml
meta:
  endian: le
  encoding: UTF-8
seq:
  - id: str1
    type: str
    size: 32
    # use the default encoding
  - id: str2
    type: str
    size: 64
    encoding: ASCII   # encoding can still be overridden
```
