### ISSUE TITLE
Parsing numbers from string representations

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#132]
Some formats have numbers encoded as strings, though it is weird. For example they can have a text header consisting of numbers separated by spaces, and after \n follows binary data. Should we have a syntax to transform string representations back to binary one? If we should, I propose the following syntax:
```yaml
alphabets:
  number_conv_alph: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" # the proposed default one
seq:
  - id: snum
    type: str
instances:
  num:
    value: parse_num(snum, u1, 16, false, number_conv_alph) #16 is the base, false means that the characters not from the alphabet of digits are ignored, number_conv_alph means alphabet, everything except the first argument is optional
```
