### ISSUE TITLE
Lazy parsing of sequence attributes

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#133]
Sometimes we have some fairly large / complex subtypes in a `seq` with a known size, which are not really used on every file read, so it's beneficial to read the lazily, i.e. on demand. A simple case:

```yaml
seq:
  - id: foo
    type: u4
  - id: bar
    size: 100500
    type: something_else
    lazy: true # <= new proposed key
  - id: baz
    type: u4
```

See https://github.com/kaitai-io/kaitai_struct/issues/65#issuecomment-287337155 for proposed generation results.

Another, more complex option, is to have lazy `seq` arrays with fixed size elements *and* (`repeat-expr` or `repeat-eos`) — thus number of elements being known a priori. Probably it's worth discussing after we've handled this simple case.
