### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#135]
I think we need templates/generics, don't we?
the proposed syntax:

```yaml
types:
  a:
    template:
      - first
      - second
      - third
    seq:
      - id: b
        type: first
        enum: second
    instances:
      c:
        value: third*b
```

All the template arguments should be known at compile time.

**Comment by GreyCat** [comment]
I've proposed approximately the same syntax some time ago: https://github.com/kaitai-io/kaitai_struct/issues/78#issuecomment-272581874

Could you show what you propose for usage of your example template?

**Comment by KOLANICH** [comment]
> Could you show what you propose for usage of your example template?

This was just an example. The use cases are strings and other arrays prepended by count of elements, wrappers for data structures, where first structure must have certain type (see [flac.ksy](https://github.com/KOLANICH/kaitai_struct_formats/blob/flac/media/flac.ksy), the first frame is always metadata one),  etc.

**Comment by SerhiiPok** [comment]
In my point of view also the generics is much needed: some use-cases in [this ](https://github.com/kaitai-io/kaitai_struct/issues/996#issue-1422624020 )duplicate thread of mine. 

Also, [here](https://stackoverflow.com/a/74208223/9904592), I have posted a workaround implementation of generics that I am using as long as no generics is avialable in kaitai so far.

**Comment by anonhostpi** [comment]
I definitely think the largest use case for this would be arrays and lists.

Repeating this scheme over and over again gets _tedious_ very quickly:

```yaml
seq:
  ...
  - id: array_count
    type: u4
  - id: array
    type: element
    repeat: expr
    repeat-expr: array_count
  ...
```
