### ISSUE TITLE
Set the stream position inside a repeat loop

### ISSUE THREAD

**Issue by LogicAndTrick** [kaitai-io/kaitai_struct#14]
This one's a bit wild, but I don't think it's currently possible so I wanted to log it.

[Quake's BSP format](http://www.gamers.org/dEngine/quake/spec/quake-spec34/qkspec_4.htm#BL2) defines some structures like this:

```cpp
// pseudocode
typedef struct {
    int miptexnum;
    int offsets[miptexnum]; // offsets to each miptex's header
} miptex_lump_t;

typedef struct
{
    char name[16];
    uint32_t width;
    uint32_t height;
    ... etc ...
} miptex_t;

// pseudocode to read the data
var stream = open(filename);
miptex_lump_t lump = stream->read_miptex_lump();
foreach (int o in lump->offsets) {
    stream->seek(o);
    miptex_t tex = stream->read_miptex();
}
```

Basically to read this data you need to first read an array of offsets, and then loop through that array and read the data at each offset. Is something like this currently possible?

If not, could support for this kind of structure be added? I was thinking something like this would probably be the least amount of change (important part is at the end):

```yaml
types:
  miptex:
    seq:
      - id: name
        type: str
        size: 16
        encoding: ASCII
      - id: width
        type: u4
      - id: height
        type: u4
        # ... etc ...
  miptex_lump:
    seq:
      - id: num_textures
        type: s4
      - id: offsets
        type: s4
        repeat: expr
        repeat-expr: num_textures
    instances:
      miptex_list:
        type: miptex
        repeat: expr
        repeat-expr: num_textures
        repeat-pos: offsets[_index]    # `_index` is the index of the for loop:
                                       # for (int _index = 0; ...) { }
```

The idea being that `pos` runs once for the whole instance, and `repeat-pos` runs once for each item in the list.

The generated code would look something like this:

```cs
// generated C# code
public List<Miptex> MiptexList
{
    get
    {
        if (_miptexList != default(List<Miptex>))
            return _textures;
        long _pos = m_io.Pos();
        _miptexList = new List<Miptex>();
        for (var _index = 0; _index < NumTextures; _index++) {
            m_io.Seek(Offsets[_index]);    // <--- New code here
            _miptexList.Add(new Miptex(m_io, this, m_root));
        }
        m_io.Seek(_pos);
        return _miptexList;
    }
}
```

I've managed to get a (kinda hacky) version of this working, so I don't think massive changes are required - I'm able work on the proper implementation if we can work out the best way to do it. I've come across this kind of 'list of offsets' structure in other formats as well (e.g. Half-Life 1 models), so I think it would be a useful addition to have.

**Comment by GreyCat** [comment]
It's possible right now, and I believe it's actually a little bit shorter, more straightforward and even allows lazy loading (i.e. actual `miptex` won't get loaded and parsed until that instance will be asked for).

```yaml
types:
  miptex:
    seq:
      # ...
  miptex_lump:
    seq:
      - id: num_textures
        type: s4
      - id: textures
        type: miptex_index
        repeat: expr
        repeat-expr: num_textures
  miptex_index:
    seq:
      - id: offset
        type: s4
    instances:
      body:
        pos: offset
        type: miptex
```

The basic idea is that you add just another layer of indirection (intermediate type like `miptex_index`). If you want an offset, you just do

```ruby
lump.textures[42].offset
```

If you want the `miptex` object itself, you do

```ruby
lump.textures[42].body
```

If you want to do something with all of the textures, you do something like

```ruby
lump.textures.each { |t|
  # do something with t
}
```

(the code examples are for Ruby, but it's basically the same for every other language)

**Comment by LogicAndTrick** [comment]
I hadn't thought of that approach, that's a pretty neat way to work around the problem. Thanks!

On a bit of a tangent: if a long-term goal is adding support for writing to files, do you think that the heavy use of instances for offset-based data will become an issue? I can't pinpoint exactly why, but the current approach makes me a little nervous when I think about writing the data back to a file.

**Comment by GreyCat** [comment]
Writing files like that is tricky anyway, no matter the way you slice it.

If you basically have a fixed "file catalog", which has offsets to various other parts of the file to actual file bodies, there are more than one way to "pack" the archive with the files. You can glue them end-to-end, in an arbitrary sequence, or you can stick some padding between them, or you can actually have a very weird algorithm that optimizes something like disk seeks for placing these files in archive, etc, etc.

If you'll take a look at BMS, for example, try kind of work around this problem by introducing a dozen of strategies for such "allocations". It's crude, but it kind of works for 90% of stuff.

**Comment by LogicAndTrick** [comment]
True, and calculating the actual offset values when writing would probably be quite tricky as well.

I guess that if the consumers of the data follow the offsets correctly, there probably wouldn't be a problem with just appending everything on the end of the file without doing anything clever, but I bet there's a lot of code out there that just ignores the offsets and makes assumptions about where the data is based on the existing tools that generate those files.

**Comment by GreyCat** [comment]
Ok, I believe we've discussed this one, and everyone's happy with proposed solution, so I'm closing it.

**Comment by codecat** [comment]
I'm looking for something similar, as I have a list of sizes, followed by the actual data of each size:
```yaml
          - id: num_header_chunks
            type: u4
          - id: header_chunks_info
            type: header_entry
            repeat: expr
            repeat-expr: num_header_chunks
          - id: header_chunks
            size: header_chunks_info[_index].chunk_size
            repeat: expr
            repeat-expr: num_header_chunks
```
Having some kind of `_index` would be perfect for this. I'm not sure I can use the `pos` attribute for this, either.
