### ISSUE TITLE
Add new meta field: Wikidata ID

### ISSUE THREAD

**Issue by davidhicks** [kaitai-io/kaitai_struct#144]
I propose an additional meta field `wikidata` which corresponds to the matching entry in Wikidata describing the file format which the .ksy file defines.

For example:

```
meta:
  id: png_1_2
  title: Portable Network Graphics, version 1.2
  wikidata: Q27229642
  ...
```

In this example, the matching Wikidata item is https://www.wikidata.org/wiki/Q27229642

Wikidata lists 1000's of file formats defined with links to corresponding Wikipedia articles in multiple languages, data on the documentation/specifications defining each file format, and plenty of other useful metadata.

Some further information on usage of Wikidata to collect information on file formats:
[1] https://www.wikidata.org/wiki/Wikidata:WikiProject_Informatics/File_formats
[2] https://www.wikidata.org/wiki/Wikidata:WikiProject_Informatics/File_formats/Lists/File_formats
