### ISSUE TITLE
Repeat until size of array reaches predefined size

### ISSUE THREAD

**Issue by davidhicks** [kaitai-io/kaitai_struct#145]
Is there currently a mechanism to have something like:
```
seq:
  - id: length
    type: u4
  - id: variable_sized_blocks
    type: block
    repeat: until
    repeat-until: sizeof(variable_sized_blocks) == length
```

An exception would be raised if there isn't enough or there is too much data available to fill the variable_sized_blocks array to the specified length.

**Comment by GreyCat** [comment]
Yeah, you can do something like:

```yaml
seq:
  - id: length
    type: u4
  - id: variable_sized_blocks
    type: variable_sized_blocks
    size: length
    # this `size` defines a substream, which will be used for parsing of a given type
types:
  variable_sized_blocks:
    seq:
      - id: blocks
        type: block
        repeat: eos # repeats until end of substream, hard limited by `length`
  block:
    # ...
```

Probably it's worth moving to user guide as example, or something like that... It's like 5 or 6th time this is asked, if I'm not mistaken...
