### ISSUE TITLE
Handling of detached indexes defining the size of variable sized blocks

### ISSUE THREAD

**Issue by davidhicks** [kaitai-io/kaitai_struct#147]
Here is the situation I am trying to handle with KS, including some proposed syntax/approach that doesn't yet exist for array keys:

```
seq:
  - id: header
    type: detached_header
  - id: blocks
    type: block
    repeat: eos
types:
  detached_header:
    seq:
      - id: number_of_blocks
        type: u4
      - id: block_definitions
        type: block_definition
        repeat: expr
        repeat-expr: number_of_blocks
        repeat-key: block_definition.unique_id
  block_definition:
    seq:
      - id: unique_id
        type: str
        size: 5
      - id: size
        type: u4
  block:
    seq:
      - id: unique_id
        type: str
        size: 5
      - id: data
        size: _parent.header.block_definitions[unique_id].size
```

Is there a way to lookup the size of a `block` from the `detached_header` whilst inside a `block` structure? Ideally the approach should be able to support a `detached_header` block index that doesn't specify each `block` in the same order as they appear in the file structure.

In the example above, I have proposed a syntax of `repeat-key` to specify the field to use to generate a key in a `map` data structure. I have also proposed using `map[key]` as a syntax to obtain a value from a `map` by specifying a `key`.

Perhaps there is a better way to do this that doesn't require new features within KS?

**Comment by koczkatamas** [comment]
((Off-topic note: sqlite has the same detached size structure, we should try out the proposed solution on that too. The difference is that there are no keys there, it's only based on indices.))

**Comment by davidhicks** [comment]
ICC profiles (.icc) also uses this detached size structure. Must be a somewhat common pattern.

**Comment by koczkatamas** [comment]
TrueType font (TTF) also uses this pattern in the glyf header.

**Comment by koczkatamas** [comment]
Microsoft PDB files are also use detached indices. This is a multi-stream file format, where every stream can contain multiple pages of data.

The file format is using the following structure (in the root stream):
 - stream count (u4)
 - page count number for every stream (array, type: u4, repeat: stream_count)
 - a continuous list of page indices, length is basically the sum of the previous array

So it could be parsed with some structure like this:

```yaml
seq:
  - id: stream_count
    type: u4
  - id: stream_page_counts
    type: u4
    repeat: expr
    repeat-expr: stream_count
  - id: stream_pages
    type: page_list(stream_page_counts[i])
    repeat: expr
    repeat-expr: stream_count
types:
  page_list:
    arguments:
      - name: page_count
    seq:
      - id: page_indices
        type: u4
        repeat: expr
        repeat-expr: page_count
```

Also we would need some primitive (process?) which could convert a list of (offset, size) pairs into a continuous stream and makes it possible to continue parsing from there.

**Comment by fubar-coder** [comment]
The ProTracker MOD file format has a similar problem. The data of all samples comes after all patterns (variable count). The formula to get to the stream offset of sample `index` would be: `pos_after_patterns + sample_infos[..index-1].map(i: i.length).sum()`.

# Proposal

For me, it would be totally fine to be able to access the array index in the function where the value gets calculated.

# Example (simplified)

```yml
seq:
  - id: sample_infos
    type: sample_info
    repeat: expr
    repeat-expr: 31
  - id: song_info
    type: song_info
    size: 130
  - id: patterns
    type: pattern
    repeat: expr
    repeat-expr: song_info.positions.max + 1
    
types:
  sample_info:
    seq:
      - id: length
        type: i4
    instances:
      offset_next:
        value: offset + length
      offset:
        value: _.index == 0 ? _parent._iopos + _parent.patterns.size * 1024 + 1084 : _array[_._index-1].offset_next
      body:
        pos: offset
        size: length
  song_info:
    seq:
      - id: song_length
        type: u1
      - id: positions
        type: u1
        repeat: expr
        repeat-expr: song_length
  pattern:
    seq:
      - id: lines
        type: u1
        repeat: expr
        repeat-expr: 1024
```

The new feature would be:

```yml
      offset:
        value: _.index == 0 ? _parent._iopos + _parent.patterns.size * 1024 + 1084 : _array[_._index-1].offset_next
```

# Mandatory features

* Automatic `_index` attribute for elements in arrays

# Optional features (from important to unimportant)

* `_iopos` for all objects containing the stream position where this object was read from
  This could be optional as long as the size can be calculated (e.g. my unpacked ProTracker mod file format).
* `_array` points to the array contained by this element
  This could be optional als long as the type is only used in one element of one parent.
* `_iosize` for all objects containing the number of bytes read from the stream position for this object
  This is useful when the array elements are of different size. This might come in handy when the library/compiler allows custom processing of data.

# Requirements

Every struct that's used as array element automatically contains the index attribute and must not be used outside an array.

**Comment by GoodBoyCC** [comment]
i have encountered the same problem, Is there a solution yet?

**Comment by koczkatamas** [comment]
My issues could be resolved with a really easy(?) modification I think.

What do you think @GreyCat could you create a prototype for this, so we could see how many real world problems does this solve?

This is the .ksy proposal, the only new thing is `_index` (so if we replace _index with ex. 3, this code currently compiles):

```yaml
meta:
  id: index_test
seq:
  - id: count
    type: u1
  - id: sizes
    type: u1
    repeat: expr
    repeat-expr: count
  - id: values
    size: sizes[_index]
    repeat: expr
    repeat-expr: count
```

This would generate the following (JS) code:
```javascript
function IndexTest(_io, _parent, _root) {
    this._io = _io;
    this._parent = _parent;
    this._root = _root || this;

    this.count = this._io.readU1();
    this.sizes = new Array(this.count);
    for (var i = 0; i < this.count; i++) {
      this.sizes[i] = this._io.readU1();
    }
    this.values = new Array(this.count);
    for (var i = 0; i < this.count; i++) {
      this.values[i] = this._io.readBytes(this.sizes[i]);
    }
  }
```

The only modification is replacing `_index` with the already known index variable (`i` in this case). Or in the generated code ex. `this.sizes[3]` would change to `this.sizes[i]`.

Of course maybe `i` is not always available, but we could throw a compile time error for now I think.

Also for the serialization issue: I think for a basic serialization scenario the application developer should maintain the correct sizes / indices, so this .ksy descriptor would work in that case too. Later we can introduce a more advanced serialization method which can fill these values automatically.

@davidhicks @fubar-coder @GoodBoyCC would this modification help in your use-case?

**Comment by davidhicks** [comment]
@koczkatamas: your proposed `_index` syntax would help in most circumstances I can think of. The only exception is where the index and records are not necessarily in the same order. I haven't come across a use case for that situation though.

**Comment by GreyCat** [comment]
@koczkatamas This doesn't solve all the problems mentioned in this issue (for example, it's impossible to access `_index` from inside a user type that's being parsed, and it might be necessary), but I guess it's a good starting point anyway.

More thoughts:

* All loop implementation should always have an index variable. Not that hard, but we need to not forget about that. `_index` is always of integer type.
* What shall we do if we encounter usage of `_index` in `if`? Right now, `if` is a top-level thing that embraces everything outside of a loop. So, probably `_index` in `if` should be illegal.
* Usage of `_index` in a type `switch-on`, i.e. something like:

```yaml
- id: foo
  type:
    switch-on: _index
    cases:
      0: bar
      1: baz
      # ...
  repeat: eos
```

This seems to be legit (though stupid), no need to outlaw that.

* Usage of `_index` in process arguments, i.e. something like:

```yaml
- id: foo
  repeat: eos
  size: 24
  process: xor([0xca, _index])
```

Seems legit and may be even somewhat useful.

* Usage of `_index` in `pos`:

```yaml
- id: foo
  pos: positions[_index]
  size: 42
```

Might be super useful, if we're dealing with, for example, array of offsets without sizes, and one should derive size of entry from a difference between offsets. For example:

```yaml
- id: offsets
  type: u4
  repeat: expr
  repeat-expr: num_offsets
instances:
  entries:
    pos: offsets[_index]
    size: offsets[_index + 1] - offsets[_index]
    repeat: expr
    repeat-expr: num_offsets - 1
```

* Usage of `_index` in `repeat-expr` → illegal.
* Usage of `_index` in `repeat-until` → legal, but I dislike it for the same reason as `_io.eof` and `_io.pos`, but probably it can be useful in some circumstances ;)
* Usage of `_index` in a non-repeat attribute. Are we ok with that generating a non-compilable code, or we'd want a ksc compile-time error?

Probably the most complex thing here would be all these checks and legal/illegal combinations. Right now, all our expressions are more or less context-less (um, except for the stateful variables that control type of `_` variable and thus affect code generation), and this one makes kind of a first precedent (um, not really) ;)
