### ISSUE TITLE
type switching default

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#149]
I have a switch of the following nature:

  switch-on: msg_type
      cases:
        0: msg_type_0
        1: msg_type_1
        2: msg_type_2

There are many (around 50) messages that are not yet defined in the protocol - these are reserved for future use in the protocol and at all mapped to say, some reserved_msg_type that takes care of these undefined messages.  It would be great if there would be a 'default' case that would take care of this instead of listing all these explicitly.

This would also be very useful for messages that don't need handling to allow these to be effectively skipped  - and possibly for error cases in which an unexpected message type would arrive. Is this possible at all or would it be possible to add this?

**Comment by koczkatamas** [comment]
The default case is called "_" (yet to be documented):
```yaml
switch-on: msg_type
cases:
  0: msg_type_0
  1: msg_type_1
  2: msg_type_2
  _: msg_type_unknown
```
