### ISSUE TITLE
Disallow name clashes between attributes

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#161]
As of now, ksc does no checks for attribute IDs to be unique. In most cases (especially in statically typed languages) it will result in name clash and invalid code that won't compile.

So, I'd like to propose to add checks and disallow situations like:

```yaml
seq:
  - id: foo
    type: u4
  - id: foo
    type: u4
```

and 

```yaml
seq:
  - id: foo
    type: u4
instances:
  foo:
    value: 42
```

i.e. seq-seq and seq-instance clash; instance-instance clash can't be checked without having our own YAML parser :(
