### ISSUE TITLE
Named references / dictionary support

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#172]
For example the [TTF format](https://github.com/kaitai-io/kaitai_struct_formats/blob/ttf/font/ttf.ksy) contains multiple records, each one has a "tag" name which is unique across the file.

Some record references other named record's fields. As the order of records is variable, we cannot find the referenced record by index, we can only find it by name.

So we'd probably need either some kind of dictionary or named reference support. A bonus feature would be if these records could be referenced in statically-typed languages like C# as typed fields.

Here is a simplified example (sadly it's still a large one):
```yaml
seq:
  - id: entries
    type: entry
    size-eos: true
types:
  entry:
    seq:
      - id: tag
        type: str
        size: 4
        encoding: ascii
      - id: length
        type: u4
      - id: value
        size: length
        type:
          switch-on: tag
          cases:
            "'thdr'": thdr
            "'tval'": tval
  thdr:
    seq:
      - id: item_count
        type: u4
  tval:
    seq:
      - id: items
        type: u4
        repeat: expr
        repeat-expr: _parent.thdr.item_count # or _parent.refs["thdr"].item_count
```

One of the options is to implement as an instance I presume, but implementing lambdas may not be trivial:

```yaml
seq:
  ...
types:
  ...
instances:
  thdr:
    value: entries.filter(x => x.tag == "thdr")[0].value
    type: thdr # ???
```

Other option is thinking about some records as singletons, so we could put them a global(?) or ksy-local(?) storage, like:
```yaml
  thdr:
    seq:
      - id: item_count
        type: u4
    ref: thdr
```
Which would automatically put a `thdr` field to the root (TTF) record.

**Comment by fubar-coder** [comment]
Similar to #147

**Comment by koczkatamas** [comment]
Similar functionality required for parsing the `.dynsym` table in the ELF, which requires accessing the `.dynstr` table.

**Comment by ZetaTwo** [comment]
I'm parsing a format which is essentially a flattened two-level tree structure where there is a list of objects: "master objects" and "child objects". Master objects have an "ObjectId" attribute and child objects have a "MasterID" attribute which refers to the "ObjectId" of a "master object". I need to be able to refer to attributes within the corresponding "master object" within the "child object", for example to determine the size of the "child object". 

I think a feature like this is what I'm looking for is there a different way to solve this?

**Comment by GreyCat** [comment]
@ZetaTwo Yep, looks pretty much like a dictionary for me too. For now, the only way it can be solved is by introducing language-specific code with a opaque type or custom processing routine.

**Comment by ZetaTwo** [comment]
I have a suggestion on how this could be handled without making Kaitai a general programming language. You could implement support for an already existing language specifically designed for traversing tree structures such as Xpath or CSS queries. This way you don't have to invent anything new, it's well tested and clearly defined and limited in scope.

**Comment by KOLANICH** [comment]
Could you create a sample `ksy` source and post it here?

**Comment by ZetaTwo** [comment]
To clarify, you mean an example of what it could look like in a ksy file if such a feature existed?

**Comment by KOLANICH** [comment]
Exactly this.

**Comment by ZetaTwo** [comment]
Some variants on what it could look like. I think I actually prefer the last one, i.e. creating a small custom query language:

XPath:
```
- id: data
  type: map_tile_data_record
  repeat: expr
  repeat-expr: /gbr1_object[@object_id="$object_id"]/body/@width * /gbr1_object[@object_id="object_id"]/body/@height
```

jq:
```
- id: data
  type: map_tile_data_record
  repeat: expr
  repeat-expr: .[]|select(.object_id == object_id)|.body.width * .[]|select(.object_id == object_id)|.body.height
```

query selector
```
- id: data
  type: map_tile_data_record
  repeat: expr
  repeat-expr: "_root gbr1_object[object_id=.object_id] body width" * "_root gbr1_object[object_id=.object_id] body height"
```

Custom:
```
- id: data
  type: map_tile_data_record
  repeat: expr
  repeat-expr: _root[.object_id == object_id].body.width * _root[.object_id == object_id].body.height
```

**Comment by KOLANICH** [comment]
The last one looks best of all, but it has too much ambiguity.

1. the impl of look-up. Should it be a hashtable, or a trie, or some other assoc container, or a O(N) lookup on every access, or maybe the collection must be (at least partially) ordered and a bin search can be used? It'd be nice to tweak it with hints.
2. it'd be nice to cache that in an instance.
3. it'd be nice to make queries by multiple attrs. It feels more like a database!
4. >`_root[.object_id`
Do you mean `_root.objects[.object_id` ?
5. I am not very sure how it gonna interplay with serialization.
6. Noone wants a custom syntax within a string. KS is defined in terms of JSON-serializeable stuff, it would be nice to minimize the amount of additional formats to parse. Maybe something like

```yaml
seq:
  - id: a
    type: b
    repeat:
      expr: 10
index:
  a_i:
    indexee: a
    key:
      - c 
      - d
instances:
  lookup:
    value: a_i[1, 2]

types:
  b:
    seq:
      - id: c
        type: u1
      - id: d
        type: u1
```

BTW, it may be possible to implement a kind of linear lookup in KS already. You may want to look at my CBOR spec PR for an impl of a loop and maybe an already merged spec for `mo` files.
