### ISSUE TITLE
import instances problem

### ISSUE THREAD

**Issue by GoodBoyCC** [kaitai-io/kaitai_struct#184]
i write a dex.ksy with some instances, like 
```yaml
instances:
          interfaces:
            pos: interfaces_off
            type: type_list
            if: interfaces_off != 0
```
when i parse the android dex file, it's ok.
but when i parse oatfile, which contain some dex files. i use dex.ksy with import

```yaml
    instances:
      dex_file:
        pos: dex_file_offset + _root.elf_file.header.section_headers[_root.rodata_section_index].offset
        type: dex
```

the result is not right, i guess the pos of interfaces is treated as off to the start of oatfile, rather than off  to the start of dexfile.

How can i solved this problem ?
