### ISSUE TITLE
java contains error if using type-switching with condition

### ISSUE THREAD

**Issue by i-n-g-o** [kaitai-io/kaitai_struct#185]
when using type-switching for a value with a condition the generated java code contains errors

e.g.:
```
seq:
  - id: the_type
    type: u1
  - id: value
    type:
      switch-on: the_type
      cases:
        0: u1
        1: f8
    if: the_type >= 0
```

kaitia generates this for the value.
```
...
    private void _read() {
        this.theType = this._io.readU1();
        if (theType() >= 0) {
            switch (theType()) {
            case 0: {
                this.value = this._io.readU1();
                break;
            }
            case 1: {
                this.value = this._io.readF8be();
                break;
            }
            }
        }
    }
    private int theType;
    private Double value;
...
```

the returned `int` from `this._io.readU1();` can not be cast to a `Double`

**Comment by i-n-g-o** [comment]
a workaround is to force the value to type Object using a custom dummy-type which is never read:

```
seq:
  - id: the_type
    type: s1
  - id: value
    type:
      switch-on: the_type
      cases:
        -1: dummy
        0: u1
        1: f8
    if: the_type >= 0
types:
  dummy:
    seq:
      - id: never
        size: 0
```
