### ISSUE TITLE
can't parse file from END to beginning known it's size

### ISSUE THREAD

**Issue by leanid** [kaitai-io/kaitai_struct#189]
```
meta:
  id: dvpl
  file-extension: dvpl
  endian: le
seq:
  - id: compressed_data
    size: stream_size - sizeof(dvpl_footer_t) # HOW TO do it?
  - id: dvpl_footer
    type: dvpl_footer_t
types:
  dvpl_footer_t:
    seq:
      - id: size_uncompressed
        type: u4
      - id: size_compressed
        type: u4
      - id: crc32_compressed
        type: u4
      - id: compressor_type
        type: u4
      - id: pack_marker_lite
        contents: "DVPL"
```

I have struct with data in beginning of file and known footer at the end of file, so first I parse end footer struct and than goto begin and load data, I read all documentation but can't find how to do it?

**Comment by GreyCat** [comment]
Generally, you can use an instance for that, i.e. something like

```yaml
instances:
  dvpl_footer:
    # for example, this one goes to 20 bytes prior to EOF
    pos: _io.size - 20
    type: dvbpl_footer_t
```

You can access parsed fields from `dvlp_footer` in `seq`, it will automatically jump to footer, parse it, and come back when it's needed.

However, if you literally need just what you've shown in your example, you don't even need that. Just reading sequentially would be enough:

```yaml
meta:
  id: dvpl
  file-extension: dvpl
  endian: le
seq:
  - id: compressed_data
    size: _io.size - 20
  - id: dvpl_footer
    type: dvpl_footer_t
types:
  dvpl_footer_t:
    seq:
      - id: size_uncompressed
        type: u4
      - id: size_compressed
        type: u4
      - id: crc32_compressed
        type: u4
      - id: compressor_type
        type: u4
      - id: pack_marker_lite
        contents: "DVPL"
```

Unfortunately, there is no automatic way to calculate `sizeof` yet (there is [a proposal](https://github.com/kaitai-io/kaitai_struct/issues/84), but it's not yet implemented), so you'll have to calculate it manually. In your case, `dvpl_footer_t` seems to be exactly 20 bytes.
