### ISSUE TITLE
Parent class type detector doesn't check instances (C#/Java)

### ISSUE THREAD

**Issue by LogicAndTrick** [kaitai-io/kaitai_struct#19]
This one's pretty obscure, but there's definitely a bug here.

The compiler seems to have some logic to check if a type is used in multiple locations to determine whether the parent is a known type or whether it should just a a generic `KaitaiStruct` type. (`ClassCompiler.scala@markupParentTypes`)

This check doesn't check the usages of the type inside instances. If only one type uses it in the `seq` section, but other types use it in the `instances` section, the resulting output won't compile.

I tried to fix this one by adding to `markupParentTypes`, but I couldn't work it out (I'm not familiar enough with the type system yet).

---

KSY to replicate the bug:
```yaml
meta:
  id: multiple_use
  endian: le
seq:
  - id: t1
    type: type_1
  - id: t2
    type: type_2
types:
  multi:
    seq:
      - id: value
        type: s4
  type_1:
    seq:
      - id: first_use
        type: multi  # parent type = type_1
  type_2:
    seq: []
    instances:
      second_use:
        pos: 0
        type: multi  # parent type = type_2
````

Compiled result (similar problems in both C# and Java):
```cs
// Error CS1503 - Argument 2: cannot convert from 'MultipleUse.Type2' to 'MultipleUse.Type1'
class MultipleUse : KaitaiStruct
{
    ...
    
    // Note here that `parent` is `Type1`. It should be `KaitaiStruct`.
    class Multi : KaitaiStruct
    {
        public Multi(KaitaiStream io, Type1 parent = null, MultipleUse root = null) : base(io) { ... }
    }
    
    class Type1 : KaitaiStruct
    {
        ...
        
        private void _parse()
        {
            _firstUse = new Multi(m_io, this, m_root);
        }
    }
    
    class Type2 : KaitaiStruct
    {
        public Multi SecondUse
        {
            get
            {
                ...
                _secondUse = new Multi(m_io, this, m_root); // <--- compile error here
                ...
            }
        }
    }
}
```
Temporary work around: 
```yaml
# Add this to `seq`:
  - id: unused
    type: multi
    if: false
```
