### ISSUE TITLE
Can't combine zlib processed field with unprocessed field in instance

### ISSUE THREAD

**Issue by mickdekkers** [kaitai-io/kaitai_struct#193]
@GreyCat as requested, here's an issue for this bug

```yaml
seq:
  - id: buf_uncomp
    size: meh
    if: is_uncompressed
  - id: buf_comp
    size: meh
    process: zlib
    if: not is_uncompressed
instances:
  buf:
    value: is_uncompressed ? buf_comp : buf_uncomp
```

Results in this error:
```
can't combine output types:
BytesLimitType(Name(identifier(length)),None,false,None,Some(ProcessZlib))
vs
BytesLimitType(Name(identifier(length)),None,false,None,None)

**Comment by GreyCat** [comment]
Seems to be [fixed](https://github.com/kaitai-io/kaitai_struct_compiler/commit/92ebca907aa7c51239e267c9f425301b37d9c422). Added [3 tests to test it](https://github.com/kaitai-io/kaitai_struct_tests/commit/24b83d1bdda8ef7c6588c3e8076dd269767512f5). Should be [at CI](http://kaitai.io/ci/) in a couple of minutes. Please take a look.

**Comment by mickdekkers** [comment]
Can confirm, I am no longer getting an error

**Comment by GreyCat** [comment]
Thanks!

**Comment by mickdekkers** [comment]
@GreyCat here's a ksy for the switch issue:
```yaml
meta:
  id: processed_unprocessed_switch_issue
  license: MIT
  endian: le
seq:
  - id: thing
    type: switcharoo
types:
  switcharoo:
    seq:
      - id: switcharoo_type
        type: u1
      - id: length
        doc: Length of following data
        type: u1
      - id: uncompressed_length
        doc: >
          If this value is non-zero, data is compressed.
          This value then represents the uncompressed length.
        type: u1
      - id: data_uncomp
        size: length
        if: uncompressed_length == 0
        type:
          switch-on: switcharoo_type
          cases:
            0: switcharoo_foo
      - id: data_comp
        size: length
        process: xor(0xff)
        if: uncompressed_length > 0
        type:
          switch-on: switcharoo_type
          cases:
            0: switcharoo_foo
    instances:
      data:
        value: >
          (uncompressed_length > 0) ? data_comp : data_uncomp
  switcharoo_foo:
    seq:
      - id: bar
        type: u4
```

It can be tested with this binary data:
```
00 04 04 FF FF FF FF
```
