### ISSUE TITLE
Following a chain of sectors to merge them in a new stream

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#196]
At least both FAT filesystem and Microsoft's CFB files follow the same pattern: to specify file contents, one provides an index of starting sector *s0*. A parser must follow the chain of sectors, as specified in a FAT-like table, i.e.:

* 1st sector = *a0*
* 2nd sector = *fat[a0]*
* 3rd sector = *fat[fat[a0]]*
* etc

until it meets certain terminator (like -1 or -2) in the FAT table. After that, if we would want to do further parsing on the file contents, we should reassemble all these individual sectors into one new stream (and probably trim it to the size specified in a separate field somewhere in the directory entry).

The following structure can model most of this behavior, but not all:

```yaml
seq:
  # Offset to the FAT table, which is, for simplicity sake, consists of 4-byte entries
  - id: ofs_fat
    type: u4
  # A pointer to the first sector
  - id: file_first_sector
    type: sector_ptr
  # Full size that we need to trim file size to
  - id: file_full_size
    type: u4
types:
  fat:
    seq:
      - id: entries
        type: u4
        repeat: eos
  sector_ptr:
    seq:
      - id: current_ptr
        type: u4
    instances:
      body:
        pos: current_ptr * 512
        size: 512
        if: current_ptr != -1
      next:
        pos: _root.ofs_fat + 4 * current_ptr
        type: sector_ptr
        if: current_ptr != -1
```

This effectively allows to access file sectors one by one by using:

```ruby
parsed.file_first_sector.body # 1st sector contents
parsed.file_first_sector.next.body # 2nd sector contents
parsed.file_first_sector.next.next.body # 3nd sector contents, etc
```

However, there is no simple way to unite all these sectors and trim it to `file_full_size`, except in the app code, to continue parsing, i.e:

```ruby
data = ''
s = parsed.file_first_sector
while not s.body.nil? do
  data << s.body
  s = s.next
end
```

Any ideas on what would be the best syntax to do it?

**Comment by koczkatamas** [comment]
Should we unify this issue with other substream related issue, eg. the PNG one (data of multiple IDAT entries should be concatenated before zlib decompression).

I presume it would be better if we could come up with a more universal solution which may be good enough to support file format we haven't met yet.

Also it may worth thinking a little about serialization (but really just a little as it is _really_ out-of-scope right now): so if we came up with multiple ideas, we can compare them from this point too.

@GreyCat could we collect all the sub-stream related file formats to somewhere (this issue's description, separate wiki page, etc)?

Current this is the list (I'll try to collect them and modify this comment):
 - Microsoft CFB
 - FAT filesystem
 - PNG
 - (registry file?)
 - (TCP?)

**Comment by GreyCat** [comment]
Substreams, as in #44, is somewhat different issue, although may be it's worth to discuss this one after completing #44.

**Comment by GreyCat** [comment]
Another complex example from Ogg specification. Each Ogg page has a list of physical "segments" defined like that:

```yaml
      - id: len_segments
        type: u1
        repeat: expr
        repeat-expr: num_segments
      - id: segments
        repeat: expr
        repeat-expr: num_segments
        size: len_segments[_index]
```

Nowadays, with advent of `_index` we can even read them. But the actual software works not on physical "segments", but logical "packets", which are constructed by joining "segments" which its length is 255. That is, a typical Ogg page might contain segment lengths like that:

```
        [.] 12 = 1       } length 1
        [.] 13 = 1       } length 1
        [.] 14 = 1       } length 1
        [.] 15 = 252     } length 252
        [.] 16 = 255     ⎫
        [.] 17 = 36      ⎭ length 291
        [.] 18 = 255     ⎫
        [.] 19 = 34      ⎭ length 289
        [.] 20 = 255     ⎫
        [.] 21 = 255     ⎪
        [.] 22 = 255     ⎪
        [.] 23 = 61      ⎭ length 826
```

Packet of 255 bytes is encoded as 2 segments, 255-byte segment + 0-byte segment.

To add the insult to injury, technically packets can be even split between different Ogg pages (i.e. higher level structures). This way one page might end up with a segment of 255 bytes and another one might start with a segment that continues it (and a "continuation" flag).

**Comment by KOLANICH** [comment]
```yaml
seq:
.......
chains:
  chain_typed:
    doc: lol
    type: frame # for better clarity the type is mandatory for typed entries, even though it can be derived
  chain_stream:
    doc: united strem of bytes ready to be parsed
   
types:
   aaaa:
     seq:
        - id: frame
          type: frame
          chain: _root.chain_typed
        - id: size
          type: u8
        - id: byte_chunk
          size: size
          chain: chain_stream

```

**Comment by GreyCat** [comment]
Would you care to elaborate a little on how's that supposed to work, so I won't be reinventing the whole thing from the very beginning, trying to guess what you've meant here?

**Comment by KOLANICH** [comment]
```chains``` is the dictionary of chains identifiers. It is by definition a collection. Implementation is to be decided, I guess different languages will have differrent ones. For C++ I guess we need chain to be a vector and adding to the chain are move semantics operations like ```emplace_next```. For reference types in GC languages I guess it's just a collection.
Chain is typed. If ```type``` is ommited it is by definition a collection of raw bytes (with array-like and stream interfaces). A chain has address as any property has. In fact it is a property, as any field in ```seq``` and any instance are. So it has an address.

```chain``` bounds any property to its chain by its path. The types of a property and the chain it is bound to must be compatible. Binding property to chain means that KSC adds some code inserting pointer/reference to the recently parsed property to the chain.

**Comment by koczkatamas** [comment]
Before we implementing anything concrete I'd like to see how the suggested solution solves the issues mentioned above (Microsoft CFB, FAT filesystem, PNG, registry file?, TCP?, Ogg, referenced issue).

Finding a fits-them-all solution is probably not easy.

**Comment by KOLANICH** [comment]
For ogg do you mean something like this:
```yaml
chains:
 - data : {}
types:
  page:
    seq:
      - id: segments
        repeat: expr
        repeat-expr: num_segments
        size: len_segments[_index]
        doc: Segment content bytes make up the rest of the Ogg page.
        chain: _root.data
```

**Comment by pavja2** [comment]
I'm not sure if this is directly related to this enhancement proposal but I've encountered a related issue when attempting to build a struct to describe MPEG-TS protocol captures. MPEG-TS consists of lots of small packets (188 bytes each) which have program identifiers and counters in their headers.

Ideally, it would be possible to use Kaitai to not only split a capture in the 188 byte packets but also merge the payloads of packets belonging to a given program identifier according to their specified order (e.g. demultiplex) and then parse that re-assembled payload with its own Kaitai structure.  

Right now, I have to pop out of Kaitai into python to do this merging process, generate an intermediary binary containing the demultiplexed payloads, and then pop back into Kaitai with a different .ksy to parse this intermediary format. It'd be great to do this all inside Kaitai for cross-language portability and clarity.

**Comment by GreyCat** [comment]
@pavja2 Could you demonstrate merging algorithm for our reference here? In indeed looks like it's another valid use case for this feature.

**Comment by kalidasya** [comment]
@pavja2 I was also about to implement an mpeg-ts parser do u have your structure file shared somewhere?

**Comment by GreyCat** [comment]
@kalidasya [This person here](https://www.linkedin.com/in/emily-roberts-b6948b130/) actually claims that she has developed that, although I'm not sure if they'll be able to open source it.

**Comment by pavja2** [comment]
@kalidasya I do have a basic struct file. It's rough around the edges but works well enough for my needs. It'd be awesome if someone made it better! I'm traveling ATM but will post it soon as I can and let you know when I do.

**Comment by GreyCat** [comment]
@kalidasya @pavja2 Guys, just a heads up: please consider [creating a new issue in formats repo](https://github.com/kaitai-io/kaitai_struct_formats/issues/new) for that format and move the discussion there? Otherwise, it will be virtually impossible for others who might be interested to find these and join your cause :)

**Comment by kalidasya** [comment]
@GreyCat thanks for the tip, issue created! @pavja2 when you have time can you link it to the referred ticket?

**Comment by kalidasya** [comment]
To give some context for this ticket from mpeg-ts point of view:

**Comment by jaroslaw-wieczorek** [comment]
Moved from #555

> In the ksy, is it possible to combine all ```value``` fields from ```data_chunk``` into a new ```_io``` stream? I need to combine(concatenate) the data into one stream for further processing without checksums. 
> 
> ```yaml 
> types:
>   data_chunk:
>     seq:
>       - id: value
>         size: '(_io.size - _io.pos > 17) ? 16 : ((_io.size - _io.pos) - 2)'
>       - id: checksum
>         size: 2
> ```
> 

Example
![obraz](https://user-images.githubusercontent.com/19189927/59180225-a7388380-8b64-11e9-8afc-665335284294.png)

Result:
New ```_io``` stream or  ```instance``` with value, that could be used to futher processing:
![obraz](https://user-images.githubusercontent.com/19189927/59181359-6f7f0b00-8b67-11e9-843f-e358d59636f7.png)

**Comment by tannewt** [comment]
Hi hi! This would be handy for USB as well. For example with usb mass storage, with full speed usb packets are 64 bytes at a time but reads and writes of data are done in 512 byte chunks over multiple low level (IN) packets. This is also done for things like long descriptor strings.

**Comment by tisoft** [comment]
Squashfs (https://github.com/kaitai-io/kaitai_struct_formats/pull/596) would also benefit from this. Metadata is stored in blocks, that need to be processed individually and then concatenated, before being able to parse it.

I have it working using custom functions, but native support would be great.

**Comment by Mingun** [comment]
I suggest to introduce new `streams` key which describes stream types like in `types` key. This is usual kaitai types, but they implements additional interface.

Look at FAT example from @GreyCat using the new key and example of the generated Java code
```yaml
seq:
  # Offset to the FAT table, which is, for simplicity sake, consists of 4-byte entries
  - id: ofs_fat
    type: u4
  # A pointer to the first sector, which starts stream
  - id: file_first_sector
    type: sector_stream
  # Full size that we need to trim file size to
  - id: file_full_size
    type: u4
instances:
  file:
    # read from the stream which type is defined in `streams` collection
    io: file_first_sector
    size: file_full_size

# The collection of named streams which implements KaitaiStream interface
streams:
  # Stream is just a regular type, which have 2 special attributes:
  # - `data` of `bytes` type which contains data of the next data chunk
  # - `next` of the nullable self type, null = no more data
  # Streams and types share the same namespace
  sector_stream:
    seq:
      - id: current_ptr
        type: u4
    instances:
      data:
        pos: current_ptr * 512
        size: 512
        if: current_ptr != -1
      next:
        pos: _root.ofs_fat + 4 * current_ptr
        type: sector_stream
        if: current_ptr != -1
```
Example of how this may work in Java ([runnable](https://onlinegdb.com/ItV3BIa8Z)!):
```java
// Runtime
abstract class KaitaiStream {
    abstract public int readU1();
}
class KaitaiStruct {}
interface Chunk {
  /** Reads current chunk of data. */
  byte[] data();
  /** Reads next chunk or null if there is not more chunks. */
  Chunk next();
}
class ChunkedKaitaiStream extends KaitaiStream {
    /// Internal buffer of not yet consumed data.
    /// Fill it using cursor.data() when its exhausted.
    private byte[] buffer = new byte[0];
    private int pos = 0;
    private Chunk cursor;
    
    public ChunkedKaitaiStream(Chunk cursor) { this.cursor = cursor; }
    
    private byte[] fillBuf() {
        if (this.pos == this.buffer.length && this.cursor != null) {
            this.pos = 0;
            this.buffer = this.cursor.data();
            this.cursor = this.cursor.next();
        }
        return this.buffer;
    }

    @Override
    public int readU1() {
        this.fillBuf();
        return this.buffer[this.pos++];
    }
}

// Generated
class SectorStream extends KaitaiStruct implements Chunk {
  private SectorStream cursor = this;
  private int counter = 5;

  // usual implementation of KaitaiStruct
  //@Instance("chunk")
  @Override
  public byte[] data() { return Integer.toString(counter).getBytes(); }
  //@Instance("next")
  @Override
  public SectorStream next() { return counter-- > 0 ? this : null; }
}

// Usage in other Kaitai types
public class Main
{
	public static void main(String[] args) {
	    final KaitaiStream io = new ChunkedKaitaiStream(new SectorStream());
	    System.out.println(io.readU1());// '5' = 53
	    System.out.println(io.readU1());// '4' = 52
	    System.out.println(io.readU1());// '3' = 51
	    System.out.println(io.readU1());// '2' = 50
	    System.out.println(io.readU1());// '1' = 49
	    System.out.println(io.readU1());// '0' = 48
	    System.out.println(io.readU1());// exception
	}
}
```
*Edit*: `ChunkedKaitaiStream` no need to be generic, each chunk may be represented by different types
