### ISSUE TITLE
switch-on string?

### ISSUE THREAD

**Issue by joeyo** [kaitai-io/kaitai_struct#198]
Is it possible to switch-on non-integer values? I'd like to do something like this and the compiler complains that mapping values are not allowed:

```
packet:
  seq:
    - id: packet_id
      type: str
      size: 8
      - id: body
        type: 
          switch-on: packet_id
          cases:
            "STRING_A": body_a
            "STRING_B": body_b
            "STRING_C": body_c
  types:
    body_a: # ...
    body_b: # ...
    body_c: # ...
```

**Comment by GreyCat** [comment]
It actually works. You just need to use quotes twice (as YAML normally interpretes normal quotes as a string), i.e. `"STRING"` and `STRING` is essentially the same thing):

```yaml
      - id: body
        type: 
          switch-on: packet_id
          cases:
            '"STRING_A"': body_a
            '"STRING_B"': body_b
            '"STRING_C"': body_c
```

**Comment by joeyo** [comment]
Hmm, that doesn't work for me either. Do I need to use version more recent than 0.7?

```
joey@idoru:~$ ksc --version
kaitai-struct-compiler 0.7

joey@idoru:~$ ksc test.ksy -t graphviz
mapping values are not allowed here
 in 'reader', line 18, column 18:
                cases:
                     ^
```

Here's my full test:

```yaml
meta:
  id: test
  endian: le
seq:
  - id: packet
    type: packet

types:

  packet:
    seq:
      - id: packet_id
        type: str
        size: 8
      - id: body
        type:
          switch-on: packet_id
            cases:
              '"STRING_A"': body_a
              '"STRING_B"': body_b
              '"STRING_C"': body_c

    types:
      body_a:
        seq:
        - id: reserved
          size: 24
      body_b:
        seq:
          - id: reserved
            size: 24
      body_c:
        seq:
          - id: reserved
            size: 24
```

**Comment by koczkatamas** [comment]
It's an indentation issue. The `switch-on` and `cases` properties should be on the same level.

Please try this .ksy (I also added ASCII `encoding` to `packet_id`):
```yaml
meta:
  id: test
  endian: le
seq:
  - id: packet
    type: packet

types:

  packet:
    seq:
      - id: packet_id
        type: str
        size: 8
        encoding: ascii
      - id: body
        type:
          switch-on: packet_id
          cases:
            '"STRING_A"': body_a
            '"STRING_B"': body_b
            '"STRING_C"': body_c

    types:
      body_a:
        seq:
        - id: reserved
          size: 24
      body_b:
        seq:
          - id: reserved
            size: 24
      body_c:
        seq:
          - id: reserved
            size: 24
```
