### ISSUE TITLE
how to validate filed with custom function?

### ISSUE THREAD

**Issue by leanid** [kaitai-io/kaitai_struct#199]
```
meta:
  id: dvpl
  file-extension: dvpl
  endian: le
seq:
  - id: compressed_data
    size: _io.size - 20
  - id: dvpl_footer
    type: dvpl_footer_t
types:
  dvpl_footer_t:
    seq:
      - id: size_uncompressed
        type: u4
      - id: size_compressed
        type: u4
      - id: crc32_compressed
        type: u4
      - id: compressor_type
        type: u4
        enum: compression
      - id: pack_marker_lite
        contents: "DVPL"
enums:
  compression:
    0: none
    1: lz4
    2: lz4hc
    3: deflate
```
I want to validate: crc32_check(_root.compressed_data) == _root.dvpl_footer.crc32_compressed. Is it possible?  And if it is possible how to add custom decompress function to check:
```
var bytes = decompress(_root.dvpl_footer.compressor_type, _root.compressor_data)
len(bytes) == _root.dvpl_footer.size_uncompressed;
crc32_check(bytes) == _root.dvpl_footer.crc32_uncompressed;

```
Thanks in advance!
