### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#20]
Just another simple idea that was floating around for ages and I keep forgetting it.

The proposal is to add docstrings into .ksy format, something like:

```yaml
seq:
  - id: num_files
    type: s4
    doc: Number of files in the archive
```

This should result in rendition of proper docstring for every language, for example, for Java:

```java
/**
 * @return Number of files in the archive
 */
public int numFiles() { return this.numFiles; }
```

Should be easy enough to do (although almost impossible to check with tests), but a huge help for proper format documentation.
