### ISSUE TITLE
Signaling errors in switch constructs

### ISSUE THREAD

**Issue by cyco** [kaitai-io/kaitai_struct#208]
The switch type operation provides a default case that falls back to *raw bytes* if none of the cases match. While this is quite useful in combination with a `size` attribute to skip over unknown message types during development, a complete definition of a binary structure might want to signal an error for unknown types instead.

## Workaround
Currently, an error can be enforced by adding an *error type* whose contents are unlikely to be encountered in real world situations.
```
  message:
    seq:
      - id: rec_type
        type: u4
      - id: rec_len
        type: u4
      - id: content
        type:
          switch-on: rec_type
          cases:
             1: handshake
             ...
             _: unknown_type_error
  unknown_type_error:
    seq:
      - id: message
        contents: "Unknown record type"
```

## Possible solutions:
  * provided a designated error type `_error`
```
    type:
      switch-on: rec_type
      cases:
        1: rec_type_1
        2: rec_type_2
        _: _error
```
 Combined with #192, one could specify an error message as well
```
    type:
      switch-on: rec_type
      cases:
        1: rec_type_1
        2: rec_type_2
        _: _error("Unknown record type")
```
 * allow for an `error` attribute (could also be called `final` or maybe `restricted`) that can be `true` or might specify an error message
```
    type:
      switch-on: rec_type
      error: "Unknown record type"
      cases:
        1: rec_type_1
        2: rec_type_2
```

**Comment by GreyCat** [comment]
Searching Gitter archives, I've found that @DarkDimius was definitely interested in this issue previously, and probably @mickdekkers as well.

**Comment by KOLANICH** [comment]
in #81 I have proposed the syntax
```yaml
throw:
  if: checksum_checksum_type(....) != expected_value
  result: 
    type: u1
    enum: error
    value: it_happened_again
```

it is easily generalized to ``cases```
```yaml
cases:
  _ :
    throw:
      result:
        value: "oh no!"
```
