### ISSUE TITLE
Using a struct parameter as a parameter itself gives an error

### ISSUE THREAD

**Issue by jcreigh** [kaitai-io/kaitai_struct#218]
Error:
```/seq/1/type: can't pass argument #0 of type KaitaiStructType into parameter `foo` of type KaitaiStructType```

Code:
```yaml
meta:
  id: struct_type

params:
  - id: foo
    type: struct

seq:
  - id: bar
    type: baz(foo)

types:
  baz:
    params:
      - id: foo
        type: struct
    seq:
      - id: qux
        type: u1
```
