### ISSUE TITLE
Type casting can't find imported type

### ISSUE THREAD

**Issue by jcreigh** [kaitai-io/kaitai_struct#219]
Error:
`(main): /instances/test/value: unable to find type 'other', searching from type_cast_test`

Code:
```yaml
meta:
  id: type_cast_test
  imports:
    - other
   
params:
  - id: foo
    type: struct
    
seq:    
  - id: bar
    type: u1

instances:
  test:
    value: 'foo.as<other>.first'
```

```yaml
meta:
  id: other

seq:
  - id: first
    type: u1
```
