### ISSUE TITLE
Properties and types hints/attributes

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#225]
The idea is to provide compiler and runtime with some info about the purpose of the member. This info can be used either to generate more usable and/or more performant code, or it can be passed to runtime and used by runtime somehow.

```yaml
seq:
  - id: signature
    hint:
      - signature # informs the implementation that it can scan the blob for the bytes in contents. Informs the compiler to generate offset for this field and to emit a warning if there is no 'contents' attribute
    contents: "signature"
  - id: reserved
    hint:
      - reserved # informs that this field should not be accessed. Compiler can create the metainformation for languages that support it (for C# [Obsolete], for C++ [[deprecated]] )
      - 
```
