### ISSUE TITLE
Referencing

### ISSUE THREAD

**Issue by SpenserStyles** [kaitai-io/kaitai_struct#228]
Quick question.  Say I have a something like this:

[FIELD_TYPE][....FIELD...][CHECKSUM][FIELD_DETAILS]

A particular FIELD contains a parameter NUM_ENTRIES that describes the number of entries in the corresponding FIELD_DETAILS.  I would like to reference the NUM_ENTRIES from the FIELD within the FIELD_DETAILS.  How would I do this?

Example:
01 00 00 00 05 00 00 00 00 00 00 00 00 06 01 02 03 04 05
FIELD_TYPE:  01
FIELD: 00 00 00 05 00 00 00 00 00 00 00 00 (parsing this gives 5 entries are contained in details)
CHECKSUM: 06
FIELD_DETAILS: 01 02 03 04 05  (the 5 entries)

```
seq:
  - id: field_type
    type: u1
    enum: field_types
  - id: field
    size: 12
    type:
      switch-on:  field_type
      cases:
        field_types::type_1: type_1
  - id: checksum
    type: u1
  - id: field_details
    parent: field
    switch-on: field_type
    cases:
      field_types::type_1: type_1_details

types:
  type_1:
    - id: num_entries
      type: u4

  type_1_details:
    - id: entry
      type: u1
      repeat: expr
      repeat: _parent.num_entries # How can I reference this from field which type is type_1??

```
