### ISSUE TITLE
Cannot replace _parent in repeats

### ISSUE THREAD

**Issue by ertaquo** [kaitai-io/kaitai_struct#230]
Hello.
I have such struct:
```yaml
  layers_info:
    seq:
      - id: count
        type: u2
      - id: layers
        type: layer
        repeat: expr
        repeat-expr: count
      - id: layer_channels
        type: layer_channels
        parent: layers[_index] # <-- here i try to replace parent
        repeat: expr
        repeat-expr: count
  layer:
    seq:
      # skipped...
      - id: channels_count
        type: u2
      # skipped...
  layer_channels:
    seq:
      - id: channels
        type: channel_image_data
        repeat: expr
        repeat-expr: _parent.channels_count # <-- here should be each layer's channels_count value
```
Otherwords, file looks like:
```
[Layer 1 description, channels_count = 2]
[Layer 2 description, channels_count = 4]
[Layer 1 channel 0 data]
[Layer 1 channel 1 data]
[Layer 2 channel 0 data]
[Layer 2 channel 1 data]
[Layer 2 channel 2 data]
[Layer 2 channel 3 data]
```
I tried to replace `_parent` because Kaitai doesn't support nested loops. But compiled JavaScript code is wrong:
```javascript
  var LayersInfo = Psd.LayersInfo = (function() {
    function LayersInfo(_io, _parent, _root) {
      this._io = _io;
      this._parent = _parent;
      this._root = _root || this;

      this._read();
    }
    LayersInfo.prototype._read = function() {
      this.count = this._io.readU2be();
      this.layers = new Array(this.count);
      for (var i = 0; i < this.count; i++) {
        this.layers[i] = new Layer(this._io, this, this._root);
      }
      this.layerChannels = new Array(this.count);
      for (var i = 0; i < this.count; i++) {
        this.layerChannels[i] = new LayerChannels(this._io, this, this._root); // <--- look here
      }
    }

    return LayersInfo;
  })();
```
This line should be:
```javascript
        this.layerChannels[i] = new LayerChannels(this._io, this.layers[i], this._root);
```
I think problem is in hardcoded string `", this, this._root"` in compiler's code:
https://github.com/kaitai-io/kaitai_struct_compiler/blob/9d7f979c10a97dc1984acb52d81dd70122b2e091/shared/src/main/scala/io/kaitai/struct/languages/JavaScriptCompiler.scala#L371

**Comment by GreyCat** [comment]
Heh, you've invented a clever hack that probably nobody ever thought of ;)

You're right, as you [can see in the CI](http://kaitai.io/ci/), NavParentOverride is not properly implemented for JavaScript.

Technically, in production you'd probably want to use proper parametric types (see #192) instead of using this "sacrifice parent to pass one thing as parameter" trick, i.e. something like:

```yaml
      - id: layer_channels
        type: layer_channels(_index)
        repeat: expr
        repeat-expr: count
# ...
  layer_channels:
    params:
      - id: num_channels
        type: u4
    seq:
      - id: channels
        type: channel_image_data
        repeat: expr
        repeat-expr: num_channels
```
