### ISSUE TITLE
create if/elif/else syntax for attributes

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#237]
The proposed syntax
```yaml
seq:
  - id: a
    type: u1
  - id: b
     type: u8
instances:
   c:
     value:
       if:
         'b>0': b
         'b<=0 and a>10': a
          _: 10
```

Yes, I know that a quite non-standard parser preserving the order of items is required. But I don't consider it as a problem.

**Comment by GreyCat** [comment]
I believe it's the same as:

```yaml
instances:
  c:
    value: >
      b > 0 ? b :
      (b <= 0 and a > 10) ? a :
      10
```

And, yeah, "non-standard parser preserving the order of items" is indeed a problem, given that we don't even have any single parser that solves all our problems yet — #229.
