### ISSUE TITLE
Bug in process with repeat

### ISSUE THREAD

**Issue by SpenserStyles** [kaitai-io/kaitai_struct#238]
I encountered a bug in javascript compilation of a field using process and repeat.
```
meta:
  id: bug_process_repeat_js
  file-extension: bug_process_repeat_js 

seq:
  - id: second
    size: 5
    repeat: expr
    repeat-expr: 2
    process: xor(0x11)
```
This results in this source code.  I commented the two lines that are incorrect.
```
// This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

var BugProcessRepeatJs = (function() {
  function BugProcessRepeatJs(_io, _parent, _root) {
    this._io = _io;
    this._parent = _parent;
    this._root = _root || this;

    this._read();
  }
  BugProcessRepeatJs.prototype._read = function() {
    this.second = new Array(2);
    for (var i = 0; i < 2; i++) {
      this._raw_second[i] = this._io.readBytes(5);  // _raw_second needs created as new Array(2)
      this.second = KaitaiStream.processXorOne(this._raw_second, 17); // this should be this.second[i]
    }
  }

  return BugProcessRepeatJs;
})();

// Export for amd environments
if (typeof define === 'function' && define.amd) {
  define('BugProcessRepeatJs', [], function() {
    return BugProcessRepeatJs;
  });
}

// Export for CommonJS
if (typeof module === 'object' && module && module.exports) {
  module.exports = BugProcessRepeatJs;
}
```

C# suffers a similar problem too.
