### ISSUE TITLE
KSC should return not only path to errored properties, but also their location in input stream (line, column) and ids

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#240]
The first can require modificationnof yaml parsing library in order to make it to give full AST with metadata (line, column).

The second can be implemented right now.

**Comment by GreyCat** [comment]
I'm tempted to close this as duplicate of https://github.com/kaitai-io/kaitai_struct_compiler/issues/22 and https://github.com/kaitai-io/kaitai_struct/issues/229.

What do you mean by "ids"?

**Comment by KOLANICH** [comment]
```yaml
seq:
 - id: this_is_id
   ...
instances:
  this_is_also_id:
     ...
```
