### ISSUE TITLE
Is it for instances possible to retrieve the instance index?

### ISSUE THREAD

**Issue by seirdb** [kaitai-io/kaitai_struct#248]
I'm trying to write a .ksy for MRP message types (IEEE 802-1Q, section 10.8)

Without going into to much detail, it tries to save data by packing multiple values (2 bit values f.e.) into a single byte. The  number of values are specified in a separate field.

Say for example that all values are '1'. The data would look like:

```
number of values = 1
values = 0x40       // [ '1' ]

number of values = 5
values = 0x01 0x55  // [ '1 ', '1' , '1', '1', '1']
```

Currently, my .ksy contains:

```
- id: number_of_values
  type: u1
- id: values
  size: (number_of_values + 3) / 4
```

This will correctly get the values as a byte stream, but I want to be able to parse them to a list of values.
Is there a way to do this? One way would be to use 'instances', but then I would need access to the index of the instance. Looking at the code, this doesn't seem possible (yet).

**Comment by GreyCat** [comment]
Why don't you just use `type: b2` to parse that as 2-bit integers?

**Comment by seirdb** [comment]
Agreed, in the example above that would be an easy solution.

However, the protocol specifies 2 types of packing; 4-packed (as above) and 3-packed.
For 3-packed, 3 values are encoded in 1 byte by doing:

`
value_0 * 36 + value_1 * 6 + value_2
`

As a result, there is no straight-forward bit-selecting or bit shifting possible.
To give the same example, with 3-packing:

```
number of values = 1
values = 0x24       // [ '1' ]

number of values = 5
values = 0x2B 0x2A  // [ '1 ', '1' , '1', '1', '1']
```

**Comment by seirdb** [comment]
Thinking about it, what needs to happen here is similar to what is done in the process directives.

There currently is however no way to specify a custom processor. What we could do with instances if we have access to the instance-index would closely resemble what would be needed for a custom process directive.

**Comment by GreyCat** [comment]
Well, you always can use value instances to extract these particular values, for example:

```yaml
seq:
  - id: number_of_values
    type: u1
  - id: values
    size: # something here
instances:
  value_2:
    value: values % 6
  value_1:
    value: (values / 6) % 6
  value_0:
    value: (values / 36) % 6
```

and, ultimately, if you want them as array, you can do:

```yaml
instances:
  values_as_array:
    value: '[value_0, value_1, value_2]'
```

> There currently is however no way to specify a custom processor.

Actually, there is: #51.

**Comment by seirdb** [comment]
My first implementation was like that, but then the generated code is not "nice" to work with, if you need to access the 4th element, you'd have to access values_as_array[1].value_0. 
I'd end up with some extra wrapper code, which could then just as easily parse the opaque byte stream...

**Comment by GreyCat** [comment]
What's the range for `num_values`, and how many bytes would it take? If there are like hundreds of bytes, then it's obviously impractical to do all that manual `value_0..1..2` stuff — and, you're right, opaque external type would be probably the way to go here.

**Comment by seirdb** [comment]
One of the MRP flavours, MVRP, can go up to the full allowed VLAN id range (0-4096). It thus seems that handling it externally would be the only option.

Would you be opposed to exposing the index in a repeat-expr? If not, I'd be willing to work towards a pull-request for this feature.

**Comment by GreyCat** [comment]
It is already exposed as `_index` — see #147.

**Comment by seirdb** [comment]
Aha. Using the _index, I can almost implement it. The only thing now missing is the power function mentioned in #216 . 

An implementation could then be:
```
- id: value                                                                                                    
        type: value_type(_index)                                             
        repeat: expr                                                               
        repeat-expr: number_of_values
```

```
types:                                                                          
  value_type:                                                             
    params:                                                                     
      - id: idx                                                                 
        type: u1                                                                
    instances:                                                                  
      the_value:                                                              
         value: (_parent.events[idx/3]/(6**(2-(idx%3))))
```
  
For now I'll resort to handling it externally. I'll keep an eye #216 though.

This current issue can thus be closed.
