### ISSUE TITLE
Generating tests with KS expressions (KST)

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#253]
Right now, all our test specs are written manually or semi-manually in relevant target languages. We use a family of hackish conversion scripts that mostly take Ruby specs and try to convert them into all the relevant languages. However, this still involves still lots of manual correction work, and adding a new language is pretty complex given a huge amount of tests that need to be converted.

I thought of why don't we just use the same KS expression language (and its translators in ksc) to produce the test specs from some ksy-like file?

This could look something like that:

```yaml
id: nested_types # test format name
data: fixed_struct.bin # binary input data file in tests/src dir
asserts:
  - actual: one.typed_at_root.value_b
    expected: 80
  - actual: one.typed_here.value_c
    expected: 65
  - actual: two.value_b
    expected: 67
```

This should be easy to translate into all the specs — this time, within a compiler itself, without any hacks and with full knowledge of what's going on.

**Comment by GreyCat** [comment]
Proof of concept branch: https://github.com/kaitai-io/kaitai_struct_tests/tree/kst
Mostly works.

Ported tests: https://github.com/kaitai-io/kaitai_struct_tests/tree/kst/spec/ks
Translator project: https://github.com/kaitai-io/kaitai_struct_tests/tree/kst/translator — it's (obviously) in Scala, and it depends on KSC jars

**Comment by KOLANICH** [comment]
IMHO it'd be a bit better not to provide the full path as string, but as tree:
not
```yaml
asserts:
  # LE
  - actual: docs[0].indicator
    expected: '[0x49, 0x49]'
  - actual: docs[0].main.some_int
    expected: 0x42
```
but
```yaml
asserts:
  docs:
    0:
       indicator: [0x49, 0x49]
       main:
          some_int: 0x42
```
