### ISSUE TITLE
Question: accessing attributes on a higher level

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#259]
I am dealing with a data format that has n datablocks of m data points, where the data is in a user-defined type:

```
meta:
  id: message
seq:
  - id: nr_of_data_blocks  
    type: u1 
  - id: nr_of_data_points_per_block  
    type: u1
  - id: data_block
    type: data_block_t
    repeat: expr
    repeat-expr: nr_of_data_blocks  
types:
  data_block:
    seq:
      - id: data
        type: i2
        repeat: expr
        repeat-expr: nr_of_data_points_per_block
```
How can the 'data_block type' get access to the `nr_of_data_points_per_block` ?
