### ISSUE TITLE
Default values for fields in seq

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#271]
Look at the code
```yaml
seq:
  - id: version
    type: u4
  - id: size_
    type: u4
    if: version>=1
  - id: contents
    size: size
instances:
  size:
    value: (version>=1?size_:10)
```

There are at least 2 issues there
1 two probably mistakenly different conditions in 2 diferrent places
2 overcomplicated nasty-looking code

There are 2 possible solutions:
1 introduce default values for fields
2 (I think I prefer this more) introduce a template incapsulating the construction we see
