### ISSUE TITLE
large 32-bit unsigned integers in instances cause KSC to throw an exception

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#272]
```yaml
instances:
  block_is_unallocated:
    value: 0xffffffffe
```
causes
>```4294967294 (of class java.lang.Long)```
