### ISSUE TITLE
Optional fields

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#273]
Here is pseudocode taking in account templares, inlining and sizeof proposals
```yaml
type:
  optional:
    templates:
      - type # the type to be wrapped
    seq:
      - id: value
        type: type
        if: _parent._io._pos + sizeof() < sizeof(_parent)
```
where _pos is the position in stream and _size is size of parent

This code should parse a field if there is enough space for them in a stream. This kind fields must be in the end of structs. Putting them in the middle is UB.

Usage:
```yaml
seq:
  - id: a
    type: b
  - id: c
    type: optional(d)
```
