### ISSUE TITLE
JS codegen: Troubles with strings containing character codes

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#279]
```yaml
meta:
  id: aaaa
  encoding: utf-8
  endian: le
seq:
  - id: a
    type: str
    size: 4
  - id: b
    type:
      switch-on: a
      cases:
       '"a\0a"': u4
```

causes
```
Parse error: undefined
Call stack: undefined SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead
```

because ```\000``` is not a valid literal for JS.

**Comment by GreyCat** [comment]
Current web IDE it gives me:

```
Parse error: undefined
Call stack: undefined SyntaxError: Octal escape sequences are not allowed in strict mode.
```

@koczkatamas, still probably that's some setting in our YAML parsing library in web IDE?

If we'll get down to [YAML spec, section 5.7](http://www.yaml.org/spec/1.2/spec.html#id2776092), it explicitly says that `\0` is allowed as special case, but regular octal literals (i.e. `\12`) are not allowed. For them, error should be something like:

```
- 1 is an invalid escaped character.
```

**Comment by GreyCat** [comment]
Yeah, a somewhat simpler test file:

```yaml
meta:
  id: aaaa
instances:
  foo:
    value: '"a\0a"'
```
