### ISSUE TITLE
Arrays and strings slices

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#282]
It is proposed to implement arrays and strings slices with the same syntax as in Python.

**Comment by GreyCat** [comment]
String slicing is already available as `substring(from, to)`. I don't really like Python syntax — it introduces extra (and, IMHO, meaningless) syntactic constructions in the language grammar, but generally it's a good idea to introduces slices for array.

The devil is, again, in the details. For example, we'll probably decide whether theses "slices" would be deep or shallow copies of the array, and how to implement them in every particular target language. If they're to be deep copies, then in some cases we're going to face a challenge of memory management. If they're going to be shallow, we're facing a challenge of reference counters, etc.

**Comment by KOLANICH** [comment]
>String slicing is already available as substring(from, to).

That's nice, thank you.

>For example, we'll probably decide whether theses "slices" would be deep or shallow copies of the array, and how to implement them in every particular target language. If they're to be deep copies, then in some cases we're going to face a challenge of memory management. If they're going to be shallow, we're facing a challenge of reference counters, etc.

I guess ... both. By default the shallow ones, but use COW on modification and then reassembly on serialization ans transfrm back to the shallow ones. More precisely:
```yaml
seq:
  - id: as_count
    type: u4
  - id: bs_count
    type: u4
  - id: as_offsets
    type: u4
    repeat: expr
    repeat-expr: bs_count
  - id: as
    type: a
    repeat: expr
    repeat-expr: as_count*4
instances:
  bs:
    repeat: expr
    repeat-expr: bs_count
    value:
      switch-on: as.substring(as_offsets[_index], as_offsets[_index]+2)
      cases:
         "'aa'": 1
         "'bb'": 2
```

So we change values of 2 differrent elements of ```bs```. As you see, ```as_indexes``` are offsets, so parts of strings for differrent elements of ```bs``` can overlap. So we use COW. We promote the slices to strings and modify them according to the result of a solver. Then on finalization step we apply them back and look for a conflict. If they don't overlap surely there will be no conflicts. If they overlap, we need to check if the overlapping region the same in both patches. If it is we apply and make it slices back. If it is not we have a conflict.
