### ISSUE TITLE
"Unable to access hdr" when trying to compile pcap.ksy

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#284]
If I remove switching on ```_root.hdr.network``` in ```packet.body``` it compiles fine. I use the latest build from appveyor (```akiljj9jxex52nv1```) and the latest master of kaitai_struct_formats

**Comment by GH0st3rs** [comment]
I have that problem too
If I try compile the next ksy file:
```
meta:
  id: test
  endian: be
  imports:
    - /executable/elf
seq:
   - id: magic
     type: u4
```

I receive error:

> Compilation OK
... processing /tmp/test.ksy 0
Error: [{"file"=>"/tmp/test.ksy", "path"=>[], "message"=>"unable to access 'bits' in test context"}]

Because in elf.ksy uses `_root.bits` as item type
