### ISSUE TITLE
Question on cast_to_top 

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#288]
Question: what is the use case for `cast_to_top `? The unit test is based on a toy example and doesn't really help me to understand its use.

**Comment by GreyCat** [comment]
Real-life use case for casting to top-level type is recursive formats. For example, most tree node-based formats are like that, i.e. whole file is just one tree node, and each node can hold some information + sometimes a list of subnodes, which are actually follow the same "main" node format. Something like that should illustrate it:

```yaml
meta:
  id: tree_node
  endian: le
seq:
  - id: type_children
    type: u1
  - id: num_children
    type: u4
  - id: children
    type:
      switch-on: type_children
      cases:
        1: tree_node
        2: header
        3: vertex
        4: face
        # ...
    repeat: expr
    repeat-expr: num_children
```

This allows for arbitrarily complex list-like structure. Each element, including root, might have an array of some typed meaningful elements (i.e. `some_header`, `some_block`, etc), or a list of more `tree_node` objects for organizational purposes. For example, a typical 3D model format might have the following format:

* tree_node(type_children = 1)
  * tree_node(type_children = 2)
    * header
  * tree_node(type_children = 3)
    * vertex
    * vertex
    * ...
  * tree_node(type_children = 4)
    * face
    * face
    * ...

The comes the following trick. If you ever need to access `header` in this structure from some other element (for example, from `face`), you know that it is always first element of format, i.e. you could technically access it as:

```
_root.children[0].children[0]
```

However, it won't compile as `_root.children[0]` is an arbitrary KaitaiStruct-compatible object. There is no way to guarantee that it would be `tree_node`. So, you'll have to typecast that in runtime:

```
_root.children[0].as<tree_node>.children[0].as<header>
```

This one compiles and works for all languages — both statically typed and dynamically typed. That's a real-life example of where casting to top-level type is useful.
