### ISSUE TITLE
Summing the values in a sequence doesn't work

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#291]
There is no built-in way to sum values, so I tried a nasty hack
```yaml
  field:
    seq:
      - id: distance
        type: u2
      - id: elevation_count
        -orig-id: evCount
        type: u1
      - id: azimuth_counts
        -orig-id: azCount
        type: azimuth(_index)
        repeat: expr
        repeat-expr: elevation_count
    types:
      azimuth:
        params:
          - id: index
            type: u1
        seq:
          - id: value
            type: u1
        instances:
          sum:
            value: (index>0?_parent.azimuth_counts[index-1].sum:0)+value
```

It doesn't work.

**Comment by GreyCat** [comment]
I believe it's the same issue as reported in https://github.com/kaitai-io/kaitai_struct_compiler/issues/70

Generally, it's a bad idea to do recursive calls like that — even if it will work, it would be inefficient and crash-prone due to stack overflow in majority of languages that don't support tailrec.

It's better to add some sort of sum or, even better yet, a fold-like function.

**Comment by KOLANICH** [comment]
>Generally, it's a bad idea to do recursive calls like that — even if it will work, it would be inefficient and crash-prone due to stack overflow in majority of languages that don't support tailrec.
>It's better to add some sort of sum or, even better yet, a fold-like function.

I understand. But for now we don't have it, right? And I even don't know how to implement that better. I see at least these ways
* optimize the method of nasty hacks by allowing to marking the item varibles as disposable and making the compiler smart enough to infer that that variable should exist in a single instance and (in my case) behave like a cumulative sum;
* introduce a new syntax for reduction, but it is obvious that the it is not possible to express everything as reduction;
* introduce loops, variables and all the things Turing-complete languages have;
* state that opaque function must be used and implement this things in runtime or in additional packages;
* or just say that this is out of scope of KS language.

**Comment by GreyCat** [comment]
> optimize the method of nasty hacks by allowing to marking the item varibles as disposable

I don't really like introducing that approach, as it directly contradicts the original goal of the KS language: to be declarative. It basically means that we're not *how* to parse structure, but *what* is the structure. It's up to the user (or used generation algorithms) to decide on how and what to do with it.

> introduce a new syntax for reduction,

That's possible, at least I don't see much contradiction to our existing practices. Moreover, translating functional → imperative is always easy, and it's hard the other way around.

Technically, I don't even see doing stuff like `azimuth_counts.sum` for an easy start, defined for all integer arrays.

> but it is obvious that the it is not possible to express everything as reduction;

We never had a goal to "express everything".

> introduce loops, variables and all the things Turing-complete languages have;

Unlikely, see above. Besides, I really don't want to reinvent Haxe. 

> state that opaque function must be used and implement this things in runtime or in additional packages

Totally possible.

> or just say that this is out of scope of KS language.

If it is not needed for *parsing* — it definitely is out of scope. If it's needed — then we're interested in doing it one way or another.

**Comment by KOLANICH** [comment]
>I don't really like introducing that approach

Neither do I, but because of another reason: one can never be sure that hacky approaches won't break.

>I don't really like introducing that approach, as it directly contradicts the original goal of the KS language: to be declarative.

In fact it doesn't: we still declare the things. But it is still too verbose and a bit ugly.

>Technically, I don't even see doing stuff like azimuth_counts.sum for an easy start, defined for all integer arrays.

We need it to work with fields of arrays of structs too.

>Totally possible.

Not quite - for statically-typed compiled languages like C++  this IMHO won't work.

>If it's needed — then we're interested in doing it one way or another.
a bit contradicts to
>We never had a goal to "express everything".
since for parsing it may be needed to "do everything" : who knows what perversions file formats designers will use.

**Comment by cher-nov** [comment]
Okay, I've came up with a `reduce`-like sum pattern that doesn't use recursion.
Ready to use proof-of-concept is next (tested and worked):

```yaml
meta:
  id: sum_reduce_pattern

instances:
  example_array:
    value: '[1, 2, 3, 4, 5]'

  adder:
    type: sum_reduce( example_array[_index], (_index == 0) ? 0 : sum[_index-1].result )
    repeat: expr
    repeat-expr: test_array.size

  # the sum (1+2+3+4+5 = 15 in that example) will be stored in adder.last.result

types:
  sum_reduce:
    params:
      - id: step_item
        type: s8
      - id: accumulator
        type: s8

    instances:
      result:
        value: step_item + accumulator
```
