### ISSUE TITLE
Cannot import enums:

### ISSUE THREAD

**Issue by qux42** [kaitai-io/kaitai_struct#293]
Hello,
I have several Enums, that I wanna use in different .ksy files.
I tried to import it the following way:
`type_enum.ksy`
```yaml
meta:
  id: type_enum
enums:
  type_enum:
    1: test
    2: hey
```
and `file.ksy`
```yaml
meta:
  id: file
  imports:
    - type_enum
types:
  entry:
    seq:
      - id: filetype
        type: u1      
        enum: type_enum
```

Is there a way to import Enum? If not is it possible to support it?
Big Thanks  :)
Samuel
