### ISSUE TITLE
 ks-opaque-types not working with imports

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#295]
Moved from https://github.com/kaitai-io/kaitai_struct_compiler/issues/120, originally submitted by @ii8:

`ks-opaque-types: true` seems to have no effect whenever there is an `imports` directive, even if they are completely unrelated.

#### Example:
filea.ksy:
```yaml
meta:
  id: filea
  ks-opaque-types: true
  imports:
    - fileb

seq:
  - id: a
    type: i_am_opaque
```
fileb.ksy:
```yaml
meta:
  id: fileb
```
command:
```
λ /usr/local/Cellar/kaitai-struct-compiler/0.7/bin/kaitai-struct-compiler --target graphviz filea.ksy

/seq/0: unable to find type 'i_am_opaque', searching from filea
```
