### ISSUE TITLE
Unknown values for enums that are used in switch-on cases leads to NPE in Java

### ISSUE THREAD

**Issue by SeriyBg** [kaitai-io/kaitai_struct#300]
I have a field that is defined as an enum and the second field that in uses this enum in switch-on case:

```
- id: type
  type: u1
  enum: type_code

- id: body:
  type:
    swith-on: type
    case: 
      'type_code::type1': type1
      'type_code::type2': type2
      _: generic_type

enums:
  type_code:
    1: type1
    2: type2
```

For these case, I have to define all the possible values for enum, even if I care only about two values, otherwise I will get NPE in Java as the field `type` is `null` and this field is used in Java `switch` statement.
The expected behavior for me is to get `generic_type` if the `type` field will be of `type3`.
