### ISSUE TITLE
Can't apply bitwise operations to b1 type

### ISSUE THREAD

**Issue by ikv** [kaitai-io/kaitai_struct#302]
With this grammar:
```
meta:
  id: foobar
seq:
  - id: foo
    type: b2
  - id: bar
    type: b1

instances:
  foobar:
    value: foo << 2 | bar
```

both katai-struct-compiler version 0.7 and webide gives me error:
 `/instances/foobar/value: can't apply operator BitOr to CalcIntType and BitsType1`

Real world example would be something like: a nibble in a 16bit word placed on bits 10:07.
