### ISSUE TITLE
Web IDE converts calculated instances to signed

### ISSUE THREAD

**Issue by ikv** [kaitai-io/kaitai_struct#303]
Consider the simple grammar:
```
meta:
  id: unsigned_to_signed

instances:
  foo:
    value: 0xffffffff
  bar:
    value: foo & foo
```

Web IDE gives the following values for foo and bar:
foo: 0xffffffff
bar: -0x1

Which is correct, but confusing
