### ISSUE TITLE
Web IDE fails on conditional attributes

### ISSUE THREAD

**Issue by ikv** [kaitai-io/kaitai_struct#304]
On this grammar:
```
meta:
  id: conditional

instances:
  foo:
    value: 123
    if: 0
```

Web IDE fails on foo expansion with error:
```
Parse error (Error): primitiveToText: object is not primitive!
Call stack: primitiveToText@https://ide.kaitai.io/js/parsedToTree.js:75:23
childItemToNode@https://ide.kaitai.io/js/parsedToTree.js:140:101
getNode/<@https://ide.kaitai.io/js/parsedToTree.js:257:44
Error: primitiveToText: object is not primitive!
```
