### ISSUE TITLE
support for UNIONS (?)

### ISSUE THREAD

**Issue by kyarkov** [kaitai-io/kaitai_struct#306]
Many thanks for your project to start with. 

I am trying to write .ksy file for pe-coff object file format and finding one thing hard to implement. Maybe due to lack of knowledge but nevertheless.

So, in COFF symbol table Name attribute is actually a UNION of ascii string[8] and u4[2]. If u4[0] == 0 then long name should be read by some base_offset +u4[1] otherwise those bytes represent an ascii sting.

I have not found solution/workaround rather then fixing name in target language yet.

1. If I read seq attribute as u4[2] I can easily read long name by offset but cant convert u4[2] to str(ascii).
2. If I read as size:8 in bytes or string I can not address individual bytes in expression or make any kind of "reinterpret casts".
3. I can`t reread same bytes as cant memorize stream offset using value: _io.pos() in sequence declaration. 

I think adding some UNION construction like swith-on:cases may be beneficial in some cases like this or/and reinterpret_cast like operation.

Would be great if you can advise how to implement this using current syntax of ksy.

**Comment by kyarkov** [comment]
I am also trying to use TypeCasting but with little successes
```
  coff_symbol:
    seq:
      - id: name
        size: 8
      - id:  ...
    instances:
      has_long:
        value: 'name.as<long_name>.is_short == 0'
    types:
      long_name:
        seq:
         - id: is_short
           type: u4
         - id: table_offset
           type: u4
```
Compiles ok.

But it runtime:

```
Traceback (most recent call last):
  File "test_obj.py", line 29, in <module>
    print 'symbol.name=', s.name , s.has_long
  File "....", line 58, in has_long
    self._m_has_long = self.name.is_short == 0
AttributeError: 'str' object has no attribute 'is_short'
```

It appears that you have to read LongName object from io anyway.

**Comment by KOLANICH** [comment]
I guess you can use ```io``` api
```yaml
seq:
  - id: str_u4_union
    size: 8
instances:
  name:
    pos: 0
    io: str_u4_union._io
    type: str
    if: str_u4_union[0]==0
```

**Comment by kyarkov** [comment]
Unfortunately  it wont compile in many variants.

str_u4_union[0] when str_u4_union is size:8 byte array 
  => unable to apply operation [] to BytesLimitType(IntNum(8),None,false,None,None)

so, using u4[2] to access short/long name and table_offset

But,

```
  coff_symbol:
    seq:
      - id: name_union
        type: u4
        repeat: expr
        repeat-expr: 2
      - id: value
        type: u4
      - id: section_nubmer
        type: u2
      - id: type
        type: u2
      - id: storage_class
        type: u1
      - id: number_of_aux_symbols
        type: u1                  
      - id: aux
        size: number_of_aux_symbols * 18
    instances:
      name:
        pos: 0
        io: name_union._io
        size: 8
```

Comilation error :
```
kaitai-struct-compiler.bat --target python --outdir . pe_coff.ksy
_io (of class java.lang.String)
```

**Comment by kyarkov** [comment]
So looks like I have just two options here read as size:8 (bytes) or read as u4[2] (two uints)

But:

1.  Adding size:8 in will create substream that I can reuse to re-read correct type ... but I can not address individual byte to compare it with 0 neither I can read a string as data itself has non ascii characters.

2. When I read u4[2] by using repeat-expr:2 looks like specifying size:8 is illegal so I cant later select substream to read 8 bytes  from.

**Comment by KOLANICH** [comment]
1 Which version ov the compiler do you use?
2 Where have you get it?

**Comment by kyarkov** [comment]
C:\DevEnv\kaitai-struct-compiler\bin>kaitai-struct-compiler.bat --version
kaitai-struct-compiler 0.7

Installed from msi (Windows) package.

**Comment by KOLANICH** [comment]
I have tried, there is really an error even in the latest build. But I remember that when I was playing around vdi.ksy `_io` has been working fine.

**Comment by webbnh** [comment]
Would something like the following work?  (I'm sorry, but I'm not at liberty to try it, now....)

```
  coff_symbol:
    seq:
      - id: mbz
        type: u4
        if: union_is_offset
      - id: name_offset
        type: u4
        if: union_is_offset
      - id: name
        size: 8
        if: not union_is_offset
    instances:
      union_is_offset:
        pos: 0
        type: u4
```

**Comment by GreyCat** [comment]
@kyarkov Generally, that type of problem is covered by substreams and parse instances where you can specify offset in that substream. I'm not sure if solution @KOLANICH would work (AFAIR, we won't allow `._io` on an array), something like that would be probably more illustrative:

```yaml
seq:
  - id: some_coff_symbol
    type: coff_symbol
    size: 8 # <= this is important to create a substream
types:
  coff_symbol:
    seq:
      - id: is_offset
        type: u4
      - id: ofs_name
        type: u4
    instances:
      name_inplace:
        pos: 0 # <= offset in a substream, i.e. refers to the same bytes where `is_offset` is
        type: str
        size: 8
      name_via_offset:
        io: _root._io # <= required to show that we reference bytes in main IO stream, not a substream
        pos: your_basic_offset + ofs_name
        type: strz
```

**Comment by KOLANICH** [comment]
@GrayCat, that solution indeed doesn't work, I have also tried ```_io``` on 8 byte buffer, surprisingly it failed (as I remenber, `_io` on buffers were working when I have been designing ```vdi.ksy``` (but then I have rewritten that into a solution not using ```_io```) , there are still some traces of that in that file). Could you clarify which fields' ```_io```s are allowed to be used and why don't we support them everywhere?

**Comment by kyarkov** [comment]
@GreyCat ok thats make sense. if its technically possible union declaration is just a syntactic sugar.

Can I ask couple of related questions? (Fell free to ignore)

1. I am trying to select name using ternary operator.
```
    name:
        value: 'name_.is_short==0 ? name_.long_name : name_.short_name'
```
But it wont compile with error:
```
(main): /types/coff_symbol/instances/name/value: can't combine output types: StrFromBytesType(BytesTerminatedType(0,false,true,true,None),as
cii) vs StrFromBytesType(BytesLimitType(IntNum(8),None,false,None,None),ascii)
```

It looks like I cant combine null terminated string and size-limited in the statement.
Could you advise if it`s possible to use ternary operator (or emulate it somehow)? 

2.COFF symbol table.

Relocations uses table index to address symbol being relocated. But some symbols have aux entries of different type that occupy a slot in the table.  So, ...

```
instances:
  symbols:
      pos: coff_hdr.pointer_to_symbol_table
      type: coff_symbol <= actual type is determined on contents of previously read entry
      repeat: expr
      repeat-expr: coff_hdr.number_of_symbols
```

transform to something like:

```
instances:
  symbols:
      pos: coff_hdr.pointer_to_symbol_table
      repeat: expr
      repeat-expr: coff_hdr.number_of_symbols
      type:
        switch-on: {last_read_item}.aux_type 
        cases: 
          1: coff_symbol::aux_1
          2: coff_symbol::aux_2
          ...
          _ : coff_symbol

```

I need to add switch-on type selection but bases on previously read item. Is it possible to access last read element in type:swtich-on statement as in repeat-until?
