### ISSUE TITLE
PDB format problem (pointers required?)

### ISSUE THREAD

**Issue by tim-lebedkov** [kaitai-io/kaitai_struct#307]
Hello,

I wrote a simple ksy file for Microsoft PDB format (debug information):

```
meta:
  id: pdb
  endian: le
  file-extension: pdb
seq:
  - id: file_hdr
    type: file_header
instances:
  block_map:
    io: _root._io
    pos: file_hdr.block_map_addr * file_hdr.block_size
    type: block_map
  stream_directory:
    io: _root._io
    pos: _root.block_map.pages[0] * file_hdr.block_size
    type: stream_directory
types:
  file_header:
    # https://llvm.org/docs/PDB/MsfFile.html
    # https://github.com/andremussche/map2dbg/blob/master/tds2pdb/tds2pdb/PdbCompile.cs
    seq:
      - id: file_type
        contents: "Microsoft C/C++ MSF 7.00\r\n\x1a\x44\x53\x00\x00\x00"
      - id: block_size
        type: u4
      - id: free_block_map_block
        type: u4
      - id: num_blocks
        type: u4
      - id: num_directory_bytes
        type: u4
      - id: unknown
        type: u4
      - id: block_map_addr
        type: u4
  block_map:
    seq:
      - id: pages
        type: u4
        repeat: expr
        repeat-expr: _root.file_hdr.num_directory_bytes / _root.file_hdr.block_size
  stream_directory:
    seq:
      - id: num_streams
        type: u4
      - id: stream_sizes
        type: u4
        repeat: expr
        repeat-expr: num_streams
      - id: stream_blocks
        type: u4
        repeat: expr
        repeat-expr: num_streams

```

The problem that I have now is with "streamBlocks". It is actually an array of pointers to other structures in the file. Additionally, these pointers must be multiplied by file_hdr.block_size to get absolute offsets in the file. How can this be implemented in .ksy? Is maybe some new type "*typename" necessary that represents a pointer to another type?

![image](https://user-images.githubusercontent.com/831371/34986399-bc1a4534-fab7-11e7-989c-76a727a990f5.png)
