### ISSUE TITLE
accessing instance fields in arrays with objects of different types in it

### ISSUE THREAD

**Issue by kyarkov** [kaitai-io/kaitai_struct#314]
Hello,

I came across one case which I believe can be improved in ksy compiler.

So, consider this bit of code. It compiles ok when type is the same in both cases, but if they are not regardless to the fact that .get_x return values of the same type it wont compile with error.

called attribute 'get_x' on generic struct expression 'Subscript(Name(identifier(items)),BinOp(Attribute(Name(identifier(items)),identifier(
size)),Sub,IntNum(1)))'

Can it be improved? It should be possible to check that all types in cases clause have .get_x in there definitions. Would be great if you could share your opinion.

```
meta:
  id: test
  endian: le
  ks-version: 0.7

seq:
  - id: items
    repeat: eos
    type: 
      switch-on: 'items[items.size-1].get_x == 1'
      cases:
        false: complex_type1        
        true:  complex_type2
types:
   complex_type1:
     seq:
       - id: x
         type: u4
     instances:
       get_x:
         value: x * 2
   complex_type2:
     seq:
       - id: x
         type: u4
     instances:
       get_x:
         value: x * 2

```
