### ISSUE TITLE
Types: adding PascalString

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#316]
I would like to propose adding a new type, PascalString. If selective-impl would be added, then some targets could use below schema-impl. C target would probably use very efficient native-impl. 

Schema assumes another feature, that special instance `_value` replaces the struct as result.

```yaml
seq:
  - id: prefix
    type: u1
  - id: data
    size: prefix
    type: str
instances:
  _value:
    value: data
```
If templates were added, then prefix field could be arbitrary `u*` integer, not just a byte.
