### ISSUE TITLE
combining size and repeat eos 

### ISSUE THREAD

**Issue by kyarkov** [kaitai-io/kaitai_struct#317]
In my model coff_symbol type object is not fixed size as it may include optional 'aux' record. So my intention was to create a substream of known size and read from it as many entries as fits this block. But 'size' in this context defines sizeof(coff_symbol) not io stream size. 

I believe repeat should use sizeof(type) and size referrer to stream buffer length as it fits general use of size keyword.

```
instances:
  symbols:
    pos: coff_hdr.pointer_to_symbol_table
    size: coff_hdr.number_of_symbols * 18
    type: coff_symbol
    repeat: eos
```

generated code:
```
  _pos = self._io.pos()
  self._io.seek(self.coff_hdr.pointer_to_symbol_table)
  while not self._io.is_eof():
       self._raw__m_symbols_.append(self._io.read_bytes((self.coff_hdr.number_of_symbols * 18)))
       io = KaitaiStream(BytesIO(self._raw__m_symbols_[-1]))
       self._m_symbols_.append(self._root.CoffSymbol(io, self, self._root))
       ...
```

**Comment by GreyCat** [comment]
http://doc.kaitai.io/user_guide.html#_repeating_until_total_size_reaches_limit probably has the answer?

**Comment by kyarkov** [comment]
That`s how  I am reading the list.
And actually its easy to hide artefacts of this indirection by 
```
  symbols_:
    ...
  symbols:
      value: symbols_.items
```

I am just curious why this semantics was chosen. But I may not know details of implementation. It just looks like to me containtuitive and it leads to context sensitivity. If you have size in the scope it refers to size of the scope stream if you add repetition size of stream implicitly updated to size of parent stream and meaning of size changes.  And from top of head I cant find a good example why would you want to create substream for every entry rather than limiting current scope stream size.

```
When we’re dealing with an array of elements, size will refer to the size of one particular element of the array
Any repetition (and this includes repeat: eos) uses current object’s IO stream. Substreams are created individually for every object inside the loop.
```

**Comment by GreyCat** [comment]
Actually, both semantics (i.e. limiting whole list vs limiting individual elements) are valid and legal, and could be useful. For example, if you process a list of directory entries, each of while is exactly 128 bytes long, something like that would be useful:

```yaml
  - id: entries
    type: dir_entry
    size: 128
    repeat: eos
```

There were some proposals to ban `size` for repetitions and add more explicit names like `size-element` and `size-list` to support both semantics and make the distinction clear — but I'm still not sure if it's worth doing and dealing with backward compatibility.

**Comment by GreyCat** [comment]
@arekbulski It's not that simple:

* Sometimes you have a list of variable-length elements, and you want to limit total size of the list.
* Sometimes you have a fixed-size elements, and, while you can say that `size_list = size_element * num_elements`, we still need to be able to limit every individual element to a certain size, or we won't catch an error when a single element would exceed `size_element` limit.

So, we need both, sometimes even simultaneously. Right now it can be solved by using intermediate type, i.e.:

```yaml
seq:
  - id: entries
    size: size_list # <=======
    type: entries
type:
  entries:
    seq:
      - id: entries
        repeat: expr
        repeat-expr: num_elements
        type: entry
        size: size_element # <=======
  entry:
    # ...
```
