### ISSUE TITLE
using different string types in IfExpr

### ISSUE THREAD

**Issue by kyarkov** [kaitai-io/kaitai_struct#318]
Is it possible to update compiler to accept code like this?

```yaml
meta:
  id: test
  encoding: ASCII
seq:
  - id: condition
    type: b1
  - id: value1
    type: strz
  - id: value2
    type: str
    size: 8
instances:
  something:
    value: 'condition ? value1 : value2'
```
