### ISSUE TITLE
Default encoding for strings

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#34]
As per https://github.com/kaitai-io/kaitai_struct/issues/13#issuecomment-254383836, @LogicAndTrick proposed to add default encoding to strings in `meta`, in the same fashion as default endianness works:

``` yaml
meta:
  endian: le
  encoding: UTF-8
seq:
  - id: str1
    type: str
    size: 32
    # use the default encoding
  - id: str2
    type: str
    size: 64
    encoding: ASCII   # encoding can still be overridden
```

**Comment by GreyCat** [comment]
This is mostly implemented now. Actually, I had to rewrite whole `meta` stuff, so it works as properly hierarchical tree of defaults now, i.e.:

```yaml
meta:
  encoding: UTF-8 # top-level default
seq:
  - id: str1
    type: strz # uses UTF-8, from top-level default
types:
  example1:
    seq:
      - id: str2
        type: strz # uses UTF-8, inheriting it from top-level default as well
  example2:
    meta:
      encoding: cp437
    seq:
      - id: str2
        type: strz # uses cp437, from current class meta
```

cc @LogicAndTrick @koczkatamas 

Results should be [on CI](http://kaitai.io/ci) pretty soon - that's `str_encodings_default` test.
