### ISSUE TITLE
Nested Subtypes

### ISSUE THREAD

**Issue by hilts-vaughan** [kaitai-io/kaitai_struct#35]
Consider the following YAML type:

```
    seq:
      - id: frame_entry
        repeat: eos

        # The pages are always 512 byte blocks / pages
        # for some reason... not sure why considering a lot of
        # the data is wasted...
        size: 512

        types:
          junk:
            size: 174
          other:
            size: 338
```

It'd be nice if we could support the "subtypes", that is `types` within `types`. How is this done in Kaistruct today? Is everything top level?

**Comment by hilts-vaughan** [comment]
Forget me... I had it intended one level too shallow. :)

**Comment by LmpOSX** [comment]
Hi, I wonder if this is already implemented, or I'm using it the wrong way.
I'm trying to consolidate various individual ksy files into one file, and then calling those as subtypes, but I'm not getting the expected results at least under python. However using opaques, It works.
How should I use it, if it is implemented?

Follow is the example

File **test1.ksy**
```YAML
meta:
  id: test1
  imports:
    - test2

seq:
  - id: test3
    type: test2::test3
```
 I got the following python, no import test2, and no test2.Test3 neither

```python
class Test1(KaitaiStruct):
    def __init__(self, _io, _parent=None, _root=None):
        self._io = _io
        self._parent = _parent
        self._root = _root if _root else self
        self._read()

    def _read(self):
        self.test3 = self._root.Test3(self._io, self, self._root)
```

However, if I use opaque-types as follows:

File **test1.ksy**
```YAML
meta:
  id: test1
  ks-opaque-types: true

seq:
  - id: test3
    type: test2::test3
```

Then python code is:

```python
import test2
class Test1(KaitaiStruct):
    def __init__(self, _io, _parent=None, _root=None):
        self._io = _io
        self._parent = _parent
        self._root = _root if _root else self
        self._read()

    def _read(self):
        self.test3 = test2.self._root.Test3(self._io)
```
