### ISSUE TITLE
Broken in 0.8, nullable instance produces missing declaration bug

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#355]
Original was filed by @webbnh at https://github.com/kaitai-io/kaitai_struct_compiler/issues/127:

> I'm working on a reproducer; meanwhile, see the lobby chat from [here](https://gitter.im/kaitai_struct/Lobby?at=5a80faf118f388e6268f8c59) to [here](https://gitter.im/kaitai_struct/Lobby?at=5a81946cf283b8e5464f7b80).

**Comment by webbnh** [comment]
Here's a cut-down reproducer:
```
enums:
  rec_types:
    1: rec1
meta:
  endian: le
  id: kscbug
  title: A reproducer for a bug in non-nullable instances
seq:
- id: fileheader
  type: fileheader
- doc: Having this reference satisfies type deduction requirements; the conditional
    allows us to defer reading it.
  id: records
  if: false
  type: record
types:
  rec1:
    seq:
    - id: fld0
      type: s2
  fileheader:
    seq:
    - id: device_type
      type: u4
  payload:
    instances:
      data:
        pos: 0
        size-eos: true
        type:
          cases:
            rec_types::rec1: rec1
          switch-on: _parent.type
  record:
    seq:
    - id: length
      type: u1
    - enum: rec_types
      id: type
      type: u2
    - id: payload
      if: length > 12
      size: length - 10 - 2
      type: payload
    - id: trailer
      type: u2
```

(My apologies for using the wrong tracker; thanks for moving the issue for me!)
