### ISSUE TITLE
using the type from imported .ksy file

### ISSUE THREAD

**Issue by UnseeingEye** [kaitai-io/kaitai_struct#364]
I am trying to use the type "header1" defined in "types:" section of the imported a_1.ksy file from a_0.ksy (the simplified example below).
I get the following error:
```
Compilation OK
... processing a_0.ksy 0
Error: [{"file"=>"(main)", "path"=>["seq", "0"], "message"=>"unable to find type 'header1', searching from a_0"}]
Fatal errors encountered, cannot continue
```
I tried all the options I had in my mind, including:
```
type: a_1::header1
type: header1
type: a_1.header1
type: _root.header1
```
etc
But without any success. I also haven't found the example for such usage in the formats library and documentation. Is it possible at all and if so, what's the right syntax?

a_0.ksy:
```
meta:
  id: a_0
  imports:
    - a_1
  endian: le
seq:
  - id: t1
    type: header1
  - id: t2
    type: header2
```
a_1.ksy:
```
meta:
  id: a_1
  endian: le
types:
  header1:
    seq:
      - id: field1
        type: u8
  header2:
    seq:
      - id: field2
        type: u4
```
