### ISSUE TITLE
official benchmark comparison with Construct

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#367]
As part of Construct compiler documentation, I am making an (official) benchmark comparison with Kaitai. @GreyCat Would you translate this schema to KSY for me? I am asking you specifically, because this is for official publishing. If you can squeeze performance out of it, the better. I added BitStruct because I think Kaitai has actually faster implementation of that one. If you would like to add some fields, even if only because Kaitai has better or faster implementation of those, please just say so.

```py
Struct(
    "count" / Int32ul,
    "items" / Array(this.count, Struct(
        "num1" / Int8ul,
        "num2" / Int24ul,
        "flags" / BitStruct(
            "bool1" / Flag,
            "num4" / BitsInteger(3),
            Padding(4),
        ),
        "fixedarray1" / Array(3, Int8ul),
        "name1" / CString("utf8"),
        "name2" / PascalString(Int8ul, "utf8"),
    )),
)
```

**Comment by GreyCat** [comment]
Probably that would be:

```yaml
meta:
  id: foo
  encoding: utf-8
  endian: le
seq:
  - id: count
    type: u4
  - id: items
    repeat: expr
    repeat-expr: count
    type: item
types:
  item:
    seq:
      - id: num1
        type: u1
      - id: num2_lo
        type: u2
      - id: num2_hi
        type: u1
      - id: flags
        type: flags
      - id: fixedarray1
        size: 3
      - id: name1
        type: strz
      - id: len_name2
        type: u1
      - id: name2
        type: str
        size: len_name2
    instances:
      num2:
        value: 'num2_hi << 16 | num2_lo'
    types:
      flags:
        seq:
          - id: bool1
            type: b1
          - id: num4
            type: b3
```

Note that there's no direct equivalent of `Int24ul` in KS (so I'm doing an value instance for it), and there are multiple ways to implement `BitStruct` and `PascalString`.

However, I don't think that it's a good idea to use an arbitrary synthetic structure for benchmarking purposes, not specifying what you're going to do with it after parsing. Various compilers would perform different optimizations on this one, and it would heavily depend on a task that you'll be performing with the fields of this structure. You're asking to "squeeze performance out of it", but, for example, you can have some fields parsed lazily, and if you won't be using them, that would bring some performance boost.

I'd rather use some real-world structure and something that resembles a real-world task (like getting to 1-2 individual fields and doing something simple with them, i.e. counting, summing, min/max, etc). Good candidates are probably something like:

* networking packets
* some serialization protocol like Protobuf, Thrift, ASN1 CER/DER, BSON, MessagePack, etc.
* some simple container format (simplest one would be probably from the games — i.e. doom wad, quake pak, etc).
