### ISSUE TITLE
bitstruct with 4 bits causes following string to fail

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#368]
This the YAML from #367 but slightly updated (array of 3 integers, not 3 bytes). Note that it fails when parsing a string, but its probably the bitstruct that is faulty. Also I modified the array that is in between those two so please check that one too.
```yaml
meta:
  id: comparison_1_kaitai
  encoding: utf-8
  endian: le
seq:
  - id: count
    type: u4
  - id: items
    repeat: expr
    repeat-expr: count
    type: item
types:
  item:
    seq:
      - id: num1
        type: u1
      - id: num2_lo
        type: u2
      - id: num2_hi
        type: u1
      - id: flags
        type: flags
      - id: fixedarray1
        repeat: expr
        repeat-expr: 3
        type: u1
      - id: name1
        type: strz
      - id: len_name2
        type: u1
      - id: name2
        type: str
        size: len_name2
    instances:
      num2:
        value: 'num2_hi << 16 | num2_lo'
    types:
      flags:
        seq:
          - id: bool1
            type: b1
          - id: num4
            type: b3
```
Fails:
```bash
$ python3 comparison_1_kaitai.py 
Traceback (most recent call last):
  File "comparison_1_kaitai.py", line 64, in <module>
    print(ConstructComparison1.from_bytes(data))
  File "/home/arkadiusz/.local/lib/python3.6/site-packages/kaitaistruct.py", line 43, in from_bytes
    return cls(KaitaiStream(BytesIO(buf)))
  File "comparison_1_kaitai.py", line 14, in __init__
    self._read()
  File "comparison_1_kaitai.py", line 20, in _read
    self.items[i] = self._root.Item(self._io, self, self._root)
  File "comparison_1_kaitai.py", line 27, in __init__
    self._read()
  File "comparison_1_kaitai.py", line 42, in _read
    self.name2 = (self._io.read_bytes(self.len_name2)).decode(u"utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 11: invalid start byte
```
Compiled into:
```py3
# This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

from pkg_resources import parse_version
from kaitaistruct import __version__ as ks_version, KaitaiStruct, KaitaiStream, BytesIO

if parse_version(ks_version) < parse_version('0.7'):
    raise Exception("Incompatible Kaitai Struct Python API: 0.7 or later is required, but you have %s" % (ks_version))

class ConstructComparison1(KaitaiStruct):
    def __init__(self, _io, _parent=None, _root=None):
        self._io = _io
        self._parent = _parent
        self._root = _root if _root else self
        self._read()

    def _read(self):
        self.count = self._io.read_u4le()
        self.items = [None] * (self.count)
        for i in range(self.count):
            self.items[i] = self._root.Item(self._io, self, self._root)

    class Item(KaitaiStruct):
        def __init__(self, _io, _parent=None, _root=None):
            self._io = _io
            self._parent = _parent
            self._root = _root if _root else self
            self._read()

        def _read(self):
            self.num1 = self._io.read_u1()
            self.num2_lo = self._io.read_u2le()
            self.num2_hi = self._io.read_u1()
            self.flags = self._root.Item.Flags(self._io, self, self._root)
            # replace flags with 1 byte and its peachy, no errors
            # self._io.read_u1()
            self.fixedarray1 = [None] * (3)
            for i in range(3):
                self.fixedarray1[i] = self._io.read_u1()

            self.name1 = (self._io.read_bytes_term(0, False, True, True)).decode(u"utf-8")
            self.len_name2 = self._io.read_u1()
            self.name2 = (self._io.read_bytes(self.len_name2)).decode(u"utf-8")

        class Flags(KaitaiStruct):
            def __init__(self, _io, _parent=None, _root=None):
                self._io = _io
                self._parent = _parent
                self._root = _root if _root else self
                self._read()

            def _read(self):
                self.bool1 = self._io.read_bits_int(1) != 0
                self.num4 = self._io.read_bits_int(3)
                # insert a dummy 4 bits and its peachy too
                # self._io.read_bits_int(4)

        @property
        def num2(self):
            if hasattr(self, '_m_num2'):
                return self._m_num2 if hasattr(self, '_m_num2') else None

            self._m_num2 = ((self.num2_hi << 16) | self.num2_lo)
            return self._m_num2 if hasattr(self, '_m_num2') else None

data = open("blob","rb").read()
print(ConstructComparison1.from_bytes(data))

```
Blob was generated by corresponding Construct:
```py3
from construct import *

d = Struct(
    "count" / Int32ul,
    "items" / Array(this.count, Struct(
        "num1" / Int8ul,
        "num2" / Int24ul,
        "flags" / BitStruct(
            "bool1" / Flag,
            "num4" / BitsInteger(3),
            Padding(4),
        ),
        "fixedarray1" / Array(3, Int8ul),
        "name1" / CString("utf8"),
        "name2" / PascalString(Int8ul, "utf8"),
    )),
)

data = d.build(dict(count=1000, items=[dict(num1=0, num2=0, flags=dict(bool1=True, num4=0), fixedarray1=[0,0,0], name1=u"...", name2=u"...") for i in range(1000)]))
with open("blob","wb") as f:
    f.write(data)
```

**Comment by GreyCat** [comment]
Yeah, actually it's a bug in the compiler. It should detect bit-aligned -> byte-aligned fields transition properly and insert `self._io.align_to_byte()` after flags reading. It actually does that if you'll embed `flags` contents into the `seq`, i.e.:

```yaml
# ...
types:
  item:
    seq:
      - id: num1
        type: u1
      - id: num2_lo
        type: u2
      - id: num2_hi
        type: u1
      - id: bool1 # <= flags contents right here
        type: b1
      - id: num4
        type: b3
      # no padding declaration needed here
      - id: fixedarray1
        repeat: expr
        repeat-expr: 3
        type: u1
      - id: name1
        type: strz
      - id: len_name2
        type: u1
      - id: name2
        type: str
        size: len_name2
# ...
```

results in:

```python
# ...
            self.num1 = self._io.read_u1()
            self.num2_lo = self._io.read_u2le()
            self.num2_hi = self._io.read_u1()
            self.bool1 = self._io.read_bits_int(1) != 0
            self.num4 = self._io.read_bits_int(3)
            self._io.align_to_byte()
            self.fixedarray1 = [None] * (3)
            for i in range(3):
                self.fixedarray1[i] = self._io.read_u1()
# ...
```
