### ISSUE TITLE
Is there a way to define the empty sequence?

### ISSUE THREAD

**Issue by UnseeingEye** [kaitai-io/kaitai_struct#369]
Consider the example below.
Based on the value from the header one of the bodies is used. However, one header value expects no body at all, and the current implementation does not allow empty "seq:" sequence:
```
"seq: expected array, found null"
```
Is there a way to achieve this?
Or what is fundamentally preventing from allowing the empty sequence?
```
seq:
  - id: header
    type: u8
  - id: body
    type:
      switch-on: header
      cases:
        ' foo_enum::a' : body_a
        ' foo_enum::b' : body_b
        ' foo_enum::c' : body_c
types:
  body_a:
    seq:
      - id: d
        type: u4
  body_b:
    seq:
      - id: e
        type: u8
  body_c:
    seq:
      #should be the empty body
enums:
  foo_enum:
    1: a
    2: b
    3: c
```

**Comment by UnseeingEye** [comment]
UPD: I know the code can be rewritten in a way below.
But this breaks the choice into multiple pieces and makes it complicated in nontrivial cases.
```
  - id: body
    if: header !=  foo_enum::c
    type:
      switch-on: header
      cases:
        ' foo_enum::a' : body_a
        ' foo_enum::b' : body_b
```

**Comment by KOLANICH** [comment]
Yaml is a superset of json, so 
```yaml
seq: []
```

**Comment by GreyCat** [comment]
@UnseeingEye You can also omit `seq` at all:

```yaml
types:
  body_c: {}
```

Or adding some `doc` or something:

```yaml
types:
  body_c:
    doc: Intentionally left blank
```
