### ISSUE TITLE
Is it possible to reduce repetition at all in this example?

### ISSUE THREAD

**Issue by trejkaz** [kaitai-io/kaitai_struct#373]
I'm trying to golf a structure definition down to a reasonable size, but I'm not quite sure how at the moment.

The structure comes from FBX, which defines 5 identical formats for storing arrays, all with optional zlib compression indicated by a flag.

```
  f4_array:
    seq:
      - id: element_count
        type: u4
      - id: encoding
        type: u1
      - id: compressed_size
        type: u4
      - id: elements
        type:
          switch-on: encoding
          cases:
            0: f4_array_data(element_count)
            1: f4_array_data_compressed(element_count)
        size: compressed_size

  f4_array_data_compressed:
    params:
      - id: element_count
        type: u4
    seq:
      - id: data
        type: f4_array_data(element_count)
        process: zlib
        size-eos: true
    instances:
      elements:
        value: data.elements

  f4_array_data:
    params:
      - id: element_count
        type: u4
    seq:
      - id: elements
        type: f4
        repeat: expr
        repeat-expr: element_count

  f8_array:
    seq:
      - id: element_count
        type: u4
      - id: encoding
        type: u1
      - id: compressed_size
        type: u4
      - id: elements
        type:
          switch-on: encoding
          cases:
            0: f8_array_data(element_count)
            1: f8_array_data_compressed(element_count)
        size: compressed_size

  f8_array_data_compressed:
    params:
      - id: element_count
        type: u4
    seq:
      - id: data
        type: f8_array_data(element_count)
        process: zlib
        size-eos: true
    instances:
      elements:
        value: data.elements

  f8_array_data:
    params:
      - id: element_count
        type: u4
    seq:
      - id: elements
        type: f8
        repeat: expr
        repeat-expr: element_count

  # And then again for u4_..., u8_..., u1_...

```

As far as I can tell, I can't use `switch-on:` with `process:`, and I wasn't allowed to have a param of type `type`. If both these existed, I figured I could write it like this:

```
  array:
    params:
      - id: element_type
        type: type # nonexistent feature?
    seq:
      - id: element_count
        type: u4
      - id: encoding
        type: u1
      - id: compressed_size
        type: u4
      - id: elements
        type: array_data(element_count, element_type)
        process:
          switch-on: encoding # nonexistent feature?
          cases:
            0: xor(0x00) # no-op
            1: zlib
        size: compressed_size

  array_data:
    params:
      - id: element_count
        type: u4
      - id: element_type
        type: type # nonexistent feature?
    seq:
      - id: elements
        type: element_type
        repeat: expr
        repeat-expr: element_count
```

And then of course if it would let me use `process` on built-in types instead of just my own, I could do this:

```
  array:
    params:
      - id: element_type
        type: type # nonexistent feature?
    seq:
      - id: element_count
        type: u4
      - id: encoding
        type: u1
      - id: compressed_size
        type: u4
      - id: elements
        type: element_type # not permitted with `process`
        repeat: expr
        repeat-expr: element_count
        process:
          switch-on: encoding # nonexistent feature?
          cases:
            0: xor(0x00) # no-op
            1: zlib
        size: compressed_size
```

There are definitely gaps in my understanding of the permitted syntax though, so maybe there is a way to cut it down that I simply am not aware of yet.

**Comment by GreyCat** [comment]
You're mostly correct. KS is generally designed to be efficient, and optimizing code for size is not always efficient.

Passing type as parameter is widely requested feature (see #135), but it's not clear so far how to implement it. Namely, some languages lack these features at all (Go), and some don't really have true generics, but get away generating all possible permutations (C++). That said, you can always emulate this one with artificial type ID passed through parameters + switching over it, i.e.:

```yaml
  data_array:
    params:
      - id: data_type
        type: u1
    seq:
      - id: element_count
        type: u4
      - id: encoding
        type: u1
      - id: compressed_size
        type: u4
      - id: elements
        type:
          switch-on: encoding
          cases:
            0: data_array_data(data_type, element_count)
            1: data_array_data_compressed(data_type, element_count)
        size: compressed_size

  data_array_data:
    params:
      - id: data_type
        type: u1
      - id: element_count
        type: u4
    seq:
      - id: elements
        type:
          switch-on: data_type
          cases:
            0: f4
            1: f8
            2: u4
            3: u8
            # ...
        repeat: expr
        repeat-expr: element_count
```

This is, of course, not very efficient, as the decision has to be taken in runtime, not compile-time.

Switchable `process` is not even something on the roadmap. Feel free to add a request issue about that.

Using `process` on all types and not only user types & byte arrays is actually something that's connected with ability to create a specific substream for every element (for example, by specifying `size` or by some other means). This was discussed to some extent in https://github.com/kaitai-io/kaitai_struct_compiler/issues/77, and would be probably eventually implemented, but the priority is not very high.
