### ISSUE TITLE
Difficulty computing the size when only the end offset has been given

### ISSUE THREAD

**Issue by trejkaz** [kaitai-io/kaitai_struct#376]
I'm dealing with a bit of an odd structure (FBX format again) where the structure has only stored the end offset instead of the size:

```
seq:
  - id: header
    type: header
  - id: records
    type: node_record
    repeat: until
    repeat-until: _.end_offset == 0

types:

  node_record:
    seq:
      - id: end_offset
        type: u4
      - id: property_count
        type: u4
      - id: property_list_length
        type: u4
      - id: name_length
        type: u1
      - id: name
        type: str
        size: name_length
      - id: properties
        type: property
        repeat: expr
        repeat-expr: property_count
        size: property_list_length
      - id: children
        size: end_offset - _root._io.pos
        type: node_record
        repeat: until
        repeat-until: _.end_offset == 0
        if: not _io.eof
```

The code above represents what I've tried to do. It seems like `end_offset - _root._io.pos` should be the correct size for the total list of child nodes plus the 13-byte zero terminator that follows them. The 13-byte terminator is essentially a node with no name, properties or children, so I'm terminating that on `_.end_offset == 0` as a weak check.

But I get an error:

```
Call stack: undefined RangeError: Invalid typed array length: -1795
```

without any context as to where it's having the problem. I do know that it isn't in the property parsing area, because I can comment out the type/repeat for the properties and get the same error. So it's something about parsing nodes, but I'm unfortunately not being given enough context in the error to figure out why it doesn't work.

I dumped the full code [here](https://gist.github.com/trejkaz/5d5c3ffacd870589f9f22404f24c80d6) in case it's more useful than my fairly small extract here.

**Comment by GreyCat** [comment]
I still haven't fully realized what's the problem exactly, but several ideas I had so far:

```yaml
      - id: properties
        type: property
        repeat: expr
        repeat-expr: property_count
        size: property_list_length
```

That might not do what you imply here. `size:` in this case sets the size of each individual property in this list, not whole list.

```
Call stack: undefined RangeError: Invalid typed array length: -1795
```

Given that the only `repeat: expr` in your code is the fragment above, it probably comes from `property_count` being negative. You can try doing something akin to:

```yaml
        repeat: expr
        repeat-expr: 'property_count >= 0 ? property_count : 0'
```

to mitigate the issue, let it be parsed and see what's happening there. Judging from the error message, you're using Web IDE, so may be that's Web IDE issue as well? Cc @koczkatamas?
