### ISSUE TITLE
Can compiler support `_` instead of `-`?

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#382]
Construct export tool produces a bit different tags, namely it uses underscore instead of hyphen. Could KSY compiler support this syntax, or do I need to adjust it on CS side?
```yaml
seq:
- id: data2
  size_eos: true
```

**Comment by KOLANICH** [comment]
I often writed small convertor scripts from other formats and didn't have this problem. Could you show your code?

**Comment by arekbulski** [comment]
Its not that difficult to implement it on my side, but not entire convenient either. I am asking just in case if it would be trivial to implement it on your side.
```py
def _emitfulltype(self, ksy):
    return dict(size_eos=True)
    return {"size-eos":True}
```

**Comment by KOLANICH** [comment]
to conform the style guide you need ordered dicts anyway

**Comment by arekbulski** [comment]
Ah sorry, I manage to fix it on my side, just took me some time to figure it out. 
```py
def hyphenatedict(d):
    return {k.replace("_","-"):v for k,v in d.items()}
```
Before I close the ticket... do you mean `id` should be before type?

**Comment by arekbulski** [comment]
I cannot find the style guide in documentation, where is it?

**Comment by KOLANICH** [comment]
the whole sequence: `id`, `orig-id`, `type`, ...., `doc`

BTW, if I remember rigth, I have used https://pypi.python.org/pypi/ruamel.yaml for serialization, with other libs I had problems with them generating dicts in json style.

**Comment by arekbulski** [comment]
I used pyYAML but thanks for the tip, I will look into this module as alternative.

**Comment by arekbulski** [comment]
As for key order, PYPY solves that. I recently learned that all dicts on PYPY are ordered-dicts.

**Comment by KOLANICH** [comment]
on python 3.5+ all the dicts are also ordered, but you should use OrderedDict anyway

**Comment by KOLANICH** [comment]
>I cannot find the style guide in documentation, where is it?

https://github.com/kaitai-io/kaitai_struct_doc/blob/master/ksy_style_guide.adoc#seq-attr

**Comment by GreyCat** [comment]
http://doc.kaitai.io/ksy_style_guide.html#seq-attr is probably slightly prettier rendition.

**Comment by arekbulski** [comment]
If I use OrderedDict then pyYAML inserts junk into the output:
```yaml
!!python/object/apply:collections.OrderedDict
- - - meta
    - !!python/object/apply:collections.OrderedDict
      - - - id
          - unnamed_schema
  - - seq
    - - !!python/object/apply:collections.OrderedDict
        - - - id
            - num1
          - - type
            - u4be
      - !!python/object/apply:collections.OrderedDict
        - - - id
            - num2
          - - type
            - u4be
      - !!python/object/apply:collections.OrderedDict
        - - - id
            - num2
          - - type
            - f4be
      - !!python/object/apply:collections.OrderedDict
        - - - id
            - data1
          - - size
            - 4
      - !!python/object/apply:collections.OrderedDict
        - - - id
            - data2
          - - size-eos
            - true
      - !!python/object/apply:collections.OrderedDict
        - - - id
            - array2d
          - - type
            - type_0
          - - repeat
            - expr
          - - repeat-expr
            - 5
  - - types
    - type_0:
        seq:
        - !!python/object/apply:collections.OrderedDict
          - - - id
              - x
            - - type
              - u1be
            - - repeat
              - expr
            - - repeat-expr
              - 5

```
