### ISSUE TITLE
Enum is not allowed if type uses switch-on

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#389]
The `.ksy` below throws the following error:

`/seq/0/enum: unknown key found, expected: consume, contents, doc, doc-ref, eos-error, id, if, include, pad-right, parent, process, repeat, size, size-eos, terminator, type`

```yaml
meta:
  id: enum_type_switch
seq:
  - id: field1
    type:
      switch-on: 1
      cases:
        1: u4le
        2: u8le
    enum: test_enum
enums:
  test_enum:
    1: a
    2: b
```

**Comment by GreyCat** [comment]
Well, they are disabled for a reason — how do you expect to handle situations like having strings / raw bytes / user types in `cases` with mandatory enum on top of all that?

Technically, currently existing workaround would be something like:

```yaml
seq:
  - id: field1
    type:
      switch-on: 1
      cases:
        1: u4le
        2: u8le
instances:
  field1_as_enum:
    value: field1
    enum: test_enum
```
