### ISSUE TITLE
user guide docs, repeat until with size

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#392]
http://doc.kaitai.io/user_guide.html#_repetitions
4.9.3. Repeat until condition is met

There is no explanation for:
```yaml
- size: 10
  repeat: until
```

It could be interpreted as 10 bytes total or 10 bytes per item.

**Comment by arekbulski** [comment]
I also dont understand what means:
```yaml
- id: entries
  type: str
  size: 4
  repeat: eos
  encoding: UTF-8
```
