### ISSUE TITLE
add u1bool and b1bool types

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#395]
I am proposing adding a type that parses one byte or bit and converts it into a True or False boolean.

**Comment by KOLANICH** [comment]
>one byte

`u1`


>or bit

`b1`

**Comment by KOLANICH** [comment]
if you need a boolean variable storing the value as a boolean create an instance

```yaml
instances:
  a:
    value: a_==0
```
