### ISSUE TITLE
enum directive ignored in params list

### ISSUE THREAD

**Issue by webbnh** [kaitai-io/kaitai_struct#413]
```
type:
  # ...
  payload:
    params:
    - id: rec_type
      enum: rec_types
      type: u1
    seq:
    - id: data
      #process: xor(0)
      type:
        cases:
          rec_types::type_1: type_1
          rec_types::type_2: type_2
        switch-on: rec_type
```
Produces errors, such as:
```
/types/payload/seq/0/type/cases/EnumByLabel(identifier(rec_types),identifier(type_2)): can't compare Int1Type(false) and EnumType(List(rec_types),CalcIntType)
```
(See [Lobby discussion](https://gitter.im/kaitai_struct/Lobby?at=5acbb331080a38505313c74b).)

**Comment by GreyCat** [comment]
Ok, just for clarity, this seems to be caused not by type switching, so basically anything like that should reproduce the bug:

```yaml
meta:
  id: params_enum
enums:
  animals:
    1: cat
    2: dog
seq:
  - id: one
    type: u1
    enum: animal
  - id: invoke_with_param
    type: with_param(one)
types:
  with_param:
    params:
      - id: enumerated_one
        type: u1
        enum: animal
    instances:
      is_cat:
        value: enumerated_one == animals::cat # would break if there's a bug
```
