### ISSUE TITLE
Spurious failure and cryptic reponse to default-only cases map:  "empty.reduceLeft"

### ISSUE THREAD

**Issue by webbnh** [kaitai-io/kaitai_struct#415]
This KSY:
```
meta:
  endian: le
  id: kscbug
  title: Demonstrate cryptic response to a dearth of cases
seq:
  - id: type
    type: u1
  - id: payload
    type:
      cases:
#       1: data
        _: data
      switch-on: type
types:
  data:
    seq:
    - size: 1
```
produces the following cryptic (to me...) message:
```
empty.reduceLeft
```
I don't think there is actually an error in the KSY.  In any case (pun intended), if you add another entry in the "switch" (e.g., uncomment the line above), then the error goes away.
