### ISSUE TITLE
Call stack: undefined java.util.NoSuchElementException: None.get when using recursion

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#418]
```yaml
meta:
  id: test
  file-extension: test
seq:
  - id: bytes
    type: u1
    repeat: expr
    repeat-expr: 10
instances:
  sum:
    pos: 0
    size: 0
    type: 'sum(0, 3)'
types:
  sum:
    params:
      - id: i 
        type: u1
      - id: total
        type: u1
    instances:
      value:
        value: '(i<total?next.value + _root.bytes[i]:1)'
      next:
        pos: 0
        size: 0
        type: 'sum(i+1, total)'
        if: i<total
```
