### ISSUE TITLE
java.util.NoSuchElementException: None.get when using a loop to sum up elements

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#419]
```yaml
meta:
  id: test
  file-extension: test
seq:
  - id: bytes
    type: u1
    repeat: expr
    repeat-expr: 10
types:
  sum:
    params:
      - id: i
        type: u4
    instances:
      sum:
        value: 'i == 0 ? _parent.bytes[0] : _parent.sums[i-1].sum + _parent.bytes[i]'

instances:
  sums:
    pos: 0
    size: 0
    type: sum(_index)
    repeat: expr
    repeat-expr: 4
```

this may be caused by
```
    pos: 0
    size: 0
```
