### ISSUE TITLE
undefined ReferenceError: term is not defined

### ISSUE THREAD

**Issue by smx-smx** [kaitai-io/kaitai_struct#423]
Binary test case (decode base64)
```
SURCX1ZFUlNJT049MS4xCklEQl9OVU1fSU1HPTY3OTEKICAgICAgICAgICAgICAKSURCX0hEUl9F
TkRNQVJLCg==
```

KSY
```yaml
seq:
    - id: header
      type: header_field
      repeat: until
      repeat-until: _.u.value == "IDB_HDR_ENDMARK"
types:
  header_field:
    seq:
      - id: u
        type: header_field_union
        size-eos: true #length not known in advance
  header_field_union:
    seq:
      - id: value
        type: str
        terminator: 0xa
    instances:
      assignment:
        pos: 0
        type: header_field_assignment
  header_field_assignment:
    seq:
      - id: field
        type: str
        terminator: 0x3d
      - id: value
        type: str
        terminator: 0xa
```

Setting `size-eos` to false makes it build, but we lose the substream.
As such header_field_assignment instances will always point to absolute offset 0
