### ISSUE TITLE
how to read bits in little endian manner?

### ISSUE THREAD

**Issue by bibekdw** [kaitai-io/kaitai_struct#426]
I have this simple hex 7B EA 28 68 48 99 70 13 FF,
I tried to create ksy file for this as:
meta:
id: test
endian: le
seq:

id: version
type: b8
id: data
type: b9
I need to read bits in little endian manner

version - read 8 bit
data - b9 is not helping because actaul value would be 0EA, where 0 comes from LSB of 28

Expected value is version: 123, data: 234

**Comment by GreyCat** [comment]
The short answer is that in current version you can't do that: the only way to do it is manual extraction from integers, i.e. something like that:

```yaml
seq:
  - id: data_and_something
    type: u2le
instances:
  data:
    value: data_and_something & 0b1_1111_1111
```

The longer answer is in #155. There is a proof-of-concept runtime code there that will be most likely merged in the next version of KS.
