### ISSUE TITLE
is there a way to define 24 bit int?

### ISSUE THREAD

**Issue by jerzyk** [kaitai-io/kaitai_struct#428]
Just happens that in this specific protocol, addresses are encoded on 3 bytes, is there a way to handle those 3 bytes as one integer (other than writing own processor)?

**Comment by GreyCat** [comment]
If it's a big-endian integer, you can do `type: b24`. If it's a little-endian integer, you can assemble it from 2+1 byte integers manually, i.e. something like that:

```yaml
types:
  u3le:
    seq:
      - id: b12
        type: u2
      - id: b3
        type: u1
    instances:
      value:
        value: 'b12 | (b3 << 16)'
```

**Comment by KOLANICH** [comment]
The signed example: https://github.com/KOLANICH/kaitai_struct_formats/blob/GPS/hardware/GPS/gps_almanac.ksy#L76L84

**Comment by jerzyk** [comment]
@GreyCat Thanks Mikhail, that was what I needed :) only one small change and is working for me :)

```
types:
  u3le:
    seq:
      - id: b12
        type: u2le
      - id: b3
        type: u1
    instances:
      value:
        value: 'b12 | (b3 << 16)'
```

@GreyCat , @KOLANICH this is a great example - maybe it will be worth to add it to docs?
