### ISSUE TITLE
Validation of parsed data with assertions

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#435]
Extracting easier part of #81, with a concrete proposal on implementation.

Context: we want to have some sort of way to state that certain attributes have some sort of "valid" values. Stating that has two implications:

1. All values which are "not valid" must trigger an error of parsing
2. In some cases, we can calculate values automatically during generation of stream

The simplest existing implementation is `contents`: it is essentially a byte array, which validates that its contents are exactly as specified in ksy file. On parsing, we'll throw an error if byte array contents won't match the expected value. On generation, we can just write the expected value, and not bother the end-user with setting the attribute manually.

## Syntax proposal

Add `valid` key to the attribute spec. Inside it, there could be:

* A string, integer or boolean => it will be treated as expression that's supposed to be the only valid value of this attribute. For example:

```yaml
- id: foo
  type: u4le
  valid: 0x42 # expected in stream: 42 00 00 00
- id: bar
  type: strz
  valid: '"abcd"' # expected in stream: 61 62 63 64 00
- id: baz
  type: u2le
  valid: '2 * foo' # expected in stream: 84 00
```

* A map, which can feature keys:
  * `eq: expected` states that attribute value must be equal to given value (i.e. the same as above)
  * `min: expected` states minimum valid value for this attribute (compared with `a >= expected`)
  * `max: expected` states maximum valid value for this attribute (compared with `a <= expected`)
  * `any-of: list-of-expected` states that valid value must be equal to one in the given list of expressions
  * `expr: expression` states that given expression need to be evaluated (substituting `_` with an actual attribute value) to be true to treat attribute value as valid.

All `expected` and `expression` values are KS expression strings, which can be constants or can depend on other attributes. `list-of-expected` must be a YAML array of KS expression strings. `expected` inferred type must be comparable with type of the attribute. `expression` inferred type must be boolean.

**Comment by KOLANICH** [comment]
You have suggested to check such relations using syntax in YAML. Having this syntax in YAML has both drawbacks and profits. The drawback is that we have to support it alongside with usual expressions. The profit is that it is yaml, any tools working with yaml would be able to parse it.

So shouod we drop our current expr syntax and start using entirely yaml-based?

**Comment by GreyCat** [comment]
> So shouod we drop our current expr syntax

What exactly is "our current expr syntax", and what do you mean by "dropping" it? We had no syntax proposal for validation until now, and I suspect what you imply is covered in `valid/expr`, for example, checking that value is even:

```yaml
- id: foo
  type: u4
  valid:
    expr: _ % 2 == 0
```

**Comment by webbnh** [comment]
> A map, which can feature keys
If the field is supposed to contain an enum value, can I check that by specifying a key of `enum`, or can `any-of` take the enum type-name instead of a list?

**Comment by GreyCat** [comment]
@webbnh Probably for enums we can just do the following:

1. Ensure that in all languages "invalid" enum values does not trigger a error by default
2. Add extra key here, something like that:

```yaml
- id: foo
  type: u4
  enum: bar
  valid:
    enum-key: true
```

**Comment by kalidasya** [comment]
Please take into account bit sized values like:
```
- id: fixed_10
  type: b2
  contents: [2]

- id: fixed_10
  contents: [true, false]
```

**Comment by GreyCat** [comment]
I went forward and do some proof-of-concept implementation in current compiler. Namely:

* `valid` is now recognized and parsed in its short form => only equals is supported now, but it's really easy to extend it to support ranges, lists, arbitrary expressions, etc.
* There is a system of relevant ValidationSpec objects created during KSY loading
* For Java, Ruby, Python, JS: codegen actually generates validation code
* Added 3 tests `valid_*.ksy`:
  * [valid_short](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/valid_short.ksy)
  * [valid_fail_eq_int](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/valid_fail_eq_int.ksy)
  * [valid_fail_eq_bytes](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/valid_fail_eq_bytes.ksy)
* Added a more or less formal system of exceptions specific to KS
  * Implemented it in Ruby, Python, Java; JS is on the way
  * Added relevant knowledge of this system of exceptions into ksc

**Comment by generalmimon** [comment]
The current KSC (0.9-SNAPSHOT) generates incorrect code when `valid` is used on an optional field (with `if`). The validation check is executed outside the `if` clause instead of inside it.

Test code:

```yaml
meta:
  id: valid_if_test
seq:
  - id: optional
    if: false
    type: u1
    valid: 42
```
produces (in JavaScript, but it happens in all languages):
```javascript
ValidIfTest.prototype._read = function() {
  if (false) {
    this.optional = this._io.readU1();
  }
  if (!(this.optional == 42)) {
    throw new KaitaiStream.ValidationNotEqualError(42, this.optional, this._io, "/seq/0");
  }
}
```

**Comment by GreyCat** [comment]
@generalmimon 
> The current KSC (0.9-SNAPSHOT) generates incorrect code when `valid` is used on an optional field (with `if`). The validation check is executed outside the if clause instead of inside it.

Probably moving it inside `if` would make sense, good catch! Can I ask you to contribute relevant test to [tests repo](https://github.com/kaitai-io/kaitai_struct_tests)?

**Comment by generalmimon** [comment]
Sure.

**Comment by GreyCat** [comment]
Recent compiler updates fixed `ValidFailInst` and `ValidNotParsedIf` tests by @generalmimon. Thanks for enhancing our test base!

**Comment by suhr** [comment]
Not closely related, but you may find it interesting how CUE unifies types and constrains: https://cuelang.org/docs/concepts/logic/

**Comment by GreyCat** [comment]
Implemented `min`, `max` and `any-of` clauses. Works for C++, JS, Python, Ruby. Pending runtime fixes for Java.

**Comment by Mingun** [comment]
May be name key `expect`? I think, is sounds better:
```yaml
id: answer
expect: 0x42
expect:
  min: 42
  max: 42
  any-of: [answer]
  expr: _ == 42

**Comment by generalmimon** [comment]
AFAIK, this feature is basically implemented (all `valid` sub-keys described in https://github.com/kaitai-io/kaitai_struct/issues/435#issue-323332353) work), but no proper type checks if the `type` of the attribute can be compared with the type of the expressions in `valid` sub-keys (like `eq`, `min`, `any-of`, ...) are done yet. For example, this spec should raise the same "can't compare ... and ..." error as the `==` operator currently does:

```yaml
meta:
  id: attr_valid_eq_bad
seq:
  - id: foo
    type: u1
    valid:
      eq: '"bar"'
```

So that means implementing the checks in compiler + adding relevant `ErrorMessagesSpec`s testing if the error message is correct. I think it makes sense to make the message could look like that one in the existing test for `==` type mismatch: [`tests/formats_err/expr_compare_enum2.ksy:1`](https://github.com/kaitai-io/kaitai_struct_tests/blob/9fc2a0eef1b9e88e60f562cb5ff7d2962419af6f/formats_err/expr_compare_enum2.ksy#L1)

However, I think that this little thing can wait until we release the 0.9 version, so I'm moving this issue from the 0.9 milestone to 0.10.

**Comment by sykhro** [comment]
Given that the keyword is mostly implemented, is it time to add it to the .ksy schema?
This would be beneficial for users (like me) that use a YAML language server for validation

**Comment by krisutofu** [comment]
I found out that it will only pay attention to the first `valid` key of the field but ignore the others.

```yaml
seq:
  - id: first_byte
    type: u1
    valid:
      eq: 0x00
    # ignores this:
    valid: 0x01
```

```yaml
    # ...
    valid:
      expr: _ >= clip_bottom
      # ignores these:
      expr: _ <= clip_top
      expr: _ == 0x7 or _ == 0x17 or _ == 0x23 or _ == 0x68 or _ == 0xB5
```

A reasonable behaviour would be a logical AND of all `valid` expressions.

It strictly separates `min`/`max`, `eq`, `any-of` and `expr` so that combinations of these are not accepted. The error message might be confusing, stating that the key is unknown.
Writing it like this is not possible:

```yaml
seq:
  - id: clip_bottom
    type: u1
  - id: clip_top
    type: u1
  - id: byte
    type: u1
    valid:
      min: clip_bottom
      max: clip_top
      any-of: [0x7, 0x17, 0x23, 0x68, 0xB5]
```

If this would work it would be a fair solution:

```yaml
    # ...
    valid:
      min: clip_bottom
      max: clip_top
    valid:
      any-of: [0x7, 0x17, 0x23, 0x68, 0xB5]
```

The only combination, which works at the moment, is one-time `min` + `max`. Multiple `min` or `max` are ignored. A useful behaviour would be an n-ary `min` and `max`, i.e. a logical AND.

This is not a functional limitation however because one could write the set of validation formulas as a single formula.

**Comment by KOLANICH** [comment]
>I found out that it will only pay attention to the first valid key of the field but ignore the others.

`.ksy` is the file extension, where the letter `y` stands for YAML. What is placed into `ksy` files is a subset of YAML. YAML is the language to serialize and deserialize possinly nested data like in JSON.

in JavaScript it'd look like

```js

let field = {};
....
field.valid = {eq: 0x00};
field.valid = 0x01;
```

As you see, the latter assignments overide the former.
When you store data it is clear that this must not be happen. Different YAML parsers react differently on that. Some raise an error. Other ones just take one of values and silently ignore the rest.

So your mental model is wrong, repeated keys don't mean what you assume them to mean.

**Comment by krisutofu** [comment]
> ...
> in JavaScript it'd look like
> 
> ```js
> let field = {};
> ....
> field.valid = {eq: 0x00};
> field.valid = 0x01;
> ```
> 
> As you see, the latter assignments overide the former. When you store data it is clear that this must never happen. Different YAML parsers react differently on that. Some raise an error. Other ones just take one of values and silently ignore the rest.
> 
> So your mental model is wrong, repeated keys don't mean what you assume them to mean.

Sorry, thank you for clarifying.

**Comment by Omar-Abdul-Azeez** [comment]
Considering that we can assign `contents: ["some string", 0x30, 30]` shouldn't we also be able to assign
```
seq:
  - id: sig
    size: : 6
    valid:
      any-of: [ ["AA", 0, 0, 1, 0] , ["BB", 0, 0, 1, 0] ]
```
currently the compiler throws an error as it expects "string"? I assume that means KSY expressions so I tried `[ '["AA", 0, 0, 1, 0]' , '["BB", 0, 0, 1, 0]' ]` to no avail... `can't combine output types: CalcStrType vs Int1Type(true)`

Heck even the painful approach doesn't work:
```
seq:
  - id: sig1
    size: : 2
    valid:
      any-of: ["AA", "BB"]
  - id: sig2
    contents: [0, 0, 1, 0]
```
KSC seems to evaluate `AA` and `BB` as KSY expressions which makes it search for `id`s matching those values but an `id` can only have small letters hence an error is thrown...

I understand that this can be used by using the hex representation of the characters and numbers but that loses clarity.
