### ISSUE TITLE
How to make hash map instance in kaitai struct?

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [kaitai-io/kaitai_struct#443]
I want to make a byte code parser in kaitai struct. In [the .pyc file format](http://formats.kaitai.io/python_pyc_27/index.html), bytecodes are defined in enum, but to determine number of arguments for each byte code,  the .pyc file format still uses conditional expression.

So I think, is there anyway to make a hash map that can define both bytecode name and number of bytecode arguments, something like this (I take the below from .pyc file format, but I want to use it for another format):
```yaml
type:
  instruction:
      seq:
        - id: op_code # assume this is always correct
          type: u1
        - id: args
          type: argType(op_code)
          repeat: expr
          repeat-expr: op_codes[op_code][1] # the important line is here
instances:
  op_codes:
    value: # how to realize this?
      0 : ['stop_code', 1]  #[<op_code name>, <op_code_argc>]
      1 : ['pop_top', 2]
      2 : ['rot_two', 3]
      3 : ['rot_three', 4]
```

**Comment by GreyCat** [comment]
Let's start from a given problem. Given that we have byte-encoded opcodes, which have a different number of generic arguments (i.e. all the opcodes would have the same "type" that deals with arguments), the canonical way to solve it today would be:

```yaml
types:
  instruction:
    seq:
      - id: op_code # assume this is always correct
        type: u1
        enum: op_codes
      - id: args
        type:
          'op_codes::stop_code': generic_args(1)
          'op_codes::pop_top': generic_args(2)
          'op_codes::rot_two': generic_args(3)
  generic_args:
    params:
      - id: num_args
        type: u4
    seq:
      - id: args
        type: generic_arg
        repeat: expr
        repeat-expr: num_args
enums:
  op_codes:
    0: stop_code
    1: pop_top
    2: rot_two
```

If there are no "generic args", and actually every opcode has its own set of rules for args encoding, then most likely it would be better to just stick with a single conditional type and tons of per-opcode types:

```yaml
types:
  instruction:
    seq:
      - id: op_code # assume this is always correct
        type: u1
        enum: op_codes
      - id: args
        type:
          'op_codes::stop_code': args_stop_code
          'op_codes::pop_top': args_pop_top
          'op_codes::rot_two': args_rot_two
```

That said, implementing hashmaps is totally possible as well, but it is much more work to do that for all the language we support, and I'm not sure how to implement them for this particular case to not impede declarativity of the language (at least to keep it compatible with serialization process and generation of documentation).
