### ISSUE TITLE
How to depict mixed strings and binary data?

### ISSUE THREAD

**Issue by exaos** [kaitai-io/kaitai_struct#444]
[tek0008CH2.isf.gz](https://github.com/kaitai-io/kaitai_struct/files/2043265/tek0008CH2.isf.gz)
I encounter a binary file format which is like:
```
seq:
  - id: header
    type: strz
    length: variable-lenght
  - id: data
    type: u2
    repeat: eos
```

How to identify the variable-length string correctly? (Please see the attachment.)
