### ISSUE TITLE
How to stop a sequence when certain contion is matched?

### ISSUE THREAD

**Issue by exaos** [kaitai-io/kaitai_struct#445]
![kmax-event-file-structure](https://user-images.githubusercontent.com/93395/40593421-0fb8d9ac-625b-11e8-9ee9-07520bda9c56.png)
As the attached picture, a sequence might stop at certain condition, e.g., when encountering some magic or next block is not the same data type. How to depict this kind of conditional reading? How about this:
```
seq:
  - id: data_block
    type: data_type
    repeat-if: next_is_the_same_type
```

**Comment by GreyCat** [comment]
Just use `repeat-until` with a `block` type that will consume both real "event blocks" and "event file footer" as a special terminator block. I have no idea what `Ev-1 :: [Parmeter-1]` etc stand for, but if that's just several 32-bit integers, then you can always do something like that:

```yaml
seq:
  # ...
  - id: more_blocks
    type: event_block
    repeat: until
    repeat-until: _.is_footer
type:
  event_block:
    seq:
      - id: param1
        type: u4
      - id: param2
        type: u4
      - id: params_rest
        type: u4
        repeat: expr
        repeat-expr: _root.ev_size - 2
        if: not is_terminator
    instances:
      is_terminator:
        value: param1 == 0xffffffff and param2 == 0xffffffff
```
