### ISSUE TITLE
Allow writing the char representation when creating enums

### ISSUE THREAD

**Issue by lithp** [kaitai-io/kaitai_struct#448]
[The postgres protocol](https://www.postgresql.org/docs/10/static/protocol-message-formats.html) (usually) begins every message with a byte which determines what the rest of the message will be. This is a great use-case for a enum. What I'd like to be able to do is this:

```
enums:
  messages:
    '"R"': AuthenticationRequest
    '"K"': BackendKeyData
    '"S"': ParameterStatus
    '"B"': Bind
    '"2"': BindComplete
    '"3"': CloseComplete
    '"C"': CommandComplete' 
    '"d"': CopyData
    '"c"': CopyDone
    '"f"': CopyFail
    '"G"': CopyInResponse
    '"H"': CopyOutResponse
    '"W"': CopyBothResponse  # used for streaming replication
    '"D"': DataRow  # from backend
```

However, this fails:

```
/enums/messages: unable to parse `"W"` as int
```

As a workaround I'm just using a type: 

```
  message:
    seq:
      - id: msg_type
        type: str
        encoding: ASCII
        size: 1
      - id: len
        type: u4
      - id: body
        size: len - 4  # the length includes itself
        type:
          switch-on: msg_type
          cases:
            '"R"': authentication_request
            '"K"': backend_key_data
```

But it'd be nice to not need to.

**Comment by KOLANICH** [comment]
See #434

**Comment by GreyCat** [comment]
#434 proposes much more radical changes. This one is doable staying in current paradigm: enums stay as lists of integer-based constants, the only thing changes is that we could introduce an extra way to represent integers by doing string-to-integer conversion (akin to `0o` which does octal-to-integer conversion or `0x` which does hex-to-integer). This, in turn, if it stays constant, can be used for static stuff like enums keys as well.

I want to emphasize that these are *not* the strings. No integer-to-string conversion (with encoding and stuff) and a string comparison should take place here.

Typically, languages like C/C++ and even Java allow syntax like `'x'` to represent single bytes. Also we should probably have a way to specify multi-byte integers this way. If we'll stick to existing practice, this usually means that we're bound to:

1. Define the string
2. Convert it to byte array
3. Convert it to integer (for example, unsigned 4-byte long little-endian)

I.e. although even this does not work right now, it should be something like `"RIFF".to_bytes.to_u4le`. Probably we could benefit from some more syntactic sugar here. Any ideas?

**Comment by lithp** [comment]
> Also we should probably have a way to specify multi-byte integers this way.

I just look a quick look at the YAML spec, it already allows putting escape sequences into double-quoted strings, you can write literals such as: `"\x0d\x0ahello\x0"`, I'm not very good with Unicode but I think for any of these literals there's only one obvious byte array it could become.

So, I think my proposal is to allow someone to write this:
 
```yaml
enums:
  messages:
    "R": AuthenticationRequest
    10: BackendKeyData
    0x05: ParameterStatus
    "\x06": Bind
```

Where Kaitai attempts to convert each key into a byte array and throws an error if all keys do not result in byte arrays with the same width.

**Comment by lithp** [comment]
> Where Kaitai attempts to convert each key into a byte array and throws an error if all keys do not result in byte arrays with the same width.

This rule gets a bit tricky if you allow literals such as `10`, so maybe it only throws an error if there's no size of byte array which all of the keys can fit into? So, this would be invalid:

````yaml
enums:
  messages:
    "R": AuthenticationRequest
    300: BackendKeyData
````

Because the first key says "this enum is for a byte array with width 1", while the second key requires at least a 2-byte enum.
