### ISSUE TITLE
Question: How do I reference a _parent from a file which imports the current file?

### ISSUE THREAD

**Issue by lithp** [kaitai-io/kaitai_struct#451]
Here's my list of asks:
- Probably I'm making this more complicated than I should, and there's a better way to do what I'm trying to do, I'd appreciate any pointers :)
- When targeting a language with dynamic typing, such as Python, the type checking should be relaxed. There, `_parent.body.size` should be allowed even if we can't figure out what type `_parent` is.
- I should be able to cast to AnyType
- I should be able to call `.size` on AnyType

---

And here's a detailed description of my problem:

I have some files which import `shared.ksy`, both of them look like this:

```
types:
  message:
    seq:
      - id: msg_type
        type: str
        encoding: ASCII
        size: 1
      - id: len
        type: u4
      - id: body
        size: len - 4  # the length includes itself
        type:
          switch-on: msg_type
          cases:
            '"d"': copy_data
            # lots of other cases
```

In `shared.ksy` I'm trying to write `copy_data`

```
  copy_data:
    seq:
      - id: copy_data_stream
        size: XXX something goes here XXX
```

This is for [the postgres protocol](https://www.postgresql.org/docs/10/static/protocol-message-formats.html). CopyData can be anything, it's the raw data which clients are trying to throw into their postgres database. The important part is that it doesn't include any length data, because that was included in the `message` wrapper.

I'd like to be able to say:

    `size: _parent.body.size`

This should work, because the _parent of copy_data only ever has type `message` with a field called body. I understand that it'd be hard to get Kaitai to figure that out though.

---

Instead, I thought maybe I could just treat the parent as an arbitrary message and use it's size: 

    `size: _parent.as<kaitai_message>.size - 5`

This fails:

    `shared: /types/copy_data/seq/0/size: unable to find type 'kaitai_message', searching from shared::copy_data`

---

Well, maybe I can use the AnyType it's previously complained to be about?

    `size: _parent.as<AnyType>.size - 5`

Nope:

    `shared: /types/copy_data/seq/0/size: unable to find type 'AnyType', searching from shared::copy_data`

---

Okay, what if I cheat by embedding a copy of the "message" definition into my `shared.ksy`?

````
types:
  message:
    seq:
      - id: msg_type
        type: str
        encoding: ASCII
        size: 1
      - id: len
        type: u4
      - id: body
        size: len - 4  # the length includes itself
        type:
          switch-on: msg_type
          cases:
            '"d"': copy_data
  copy_data:
    seq:
      - id: copy_data_stream
        size: _parent.as<message>.body.size
````

At least this will work, right? Nope:

    `shared: /types/copy_data/seq/0/size: don't know how to call anything on AnyType`

---

I understand not being able to call something like "body" on AnyType, but you can't even call `size` on it? Doesn't everything have a size?

Okay, fine, I'll do it manually:

    `size: _parent.as<message>.size - 5`

I have no idea why, but this results in 

   `shared: /types/copy_data/seq/0/size: unable to access 'size' in shared::message context`

---

I finally got it to work by doing:

    `size: _parent.as<message>.len - 4`

But I feel like any of the other ways (except the first, which I realize is unreasonable) should have worked.

**Comment by GreyCat** [comment]
> When targeting a language with dynamic typing, such as Python, the type checking should be relaxed. There, `_parent.body.size` should be allowed even if we can't figure out what type _parent is.

It's not possible. KS expression by itself is strongly typed language. We need to infer type for `_parent.body.size`, for example, to check that it is indeed an integer. And, what's more important, we totally don't want to have .ksy files that would only work for *some* targets.

> I should be able to cast to AnyType

Why would you want that?

> I should be able to call `.size` on AnyType

How would you want to handle it if AnyType value is, for example, an integer, which does not have a `.size`?

**Comment by GreyCat** [comment]
@lithp Given that you've already done substream size limitation on the upper level, why don't you just use?

```yaml
  copy_data:
    seq:
      - id: copy_data_stream
        size-eos: true
```
