### ISSUE TITLE
Recursive field definition bug

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#453]
The following definition
```yaml
meta:
  id: sum_test
types:
  item:
    params:
      - id: idx
        type: u4
    seq:
      - id: value
        type: u1
    instances:
      val_sum:
        value: '(idx == 0 ? 0 : _parent.items[idx - 1].val_sum) + value'
        -webide-parse-mode: eager
seq:
  - id: items
    type: item(_index)
    repeat: until
    repeat-until: '_index >= 1 + _.val_sum'
```

throws this error: `io.kaitai.struct.precompile.ErrorInInput: sum_test: /seq/0/repeat-until: val_sum`

If I change the `repeat-until` definition to `repeat-until: true` (or anything else which does not cause the previous error) then I get this exception: `java.util.NoSuchElementException: None.get`.

I presume it happens because the `val_sum` definition is recursive and its type cannot be inferred.
