### ISSUE TITLE
Inconsistent hex literals in pos:

### ISSUE THREAD

**Issue by JKAnderson** [kaitai-io/kaitai_struct#456]
Starting a pos: expression with a hex literal gives very undesirable results. For instance:
```yaml
instances:
  compressed:
    io: _root._io
    pos: 0x44 + _parent.compression_header_size + offset
    size: size
```
Generates code:
```cs
io.Seek(19332502143299584);
```

Placing the literal in the middle or at the end behaves as expected:
```yaml
instances:
  compressed:
    io: _root._io
    pos: _parent.compression_header_size + offset + 0x44
    size: size
```
Generated code:
```cs
io.Seek(((M_Parent.CompressionHeaderSize + Offset) + 68));
```
