### ISSUE TITLE
Non-hardcoded contents

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#458]
From https://github.com/KOLANICH/kaitai_struct_formats/blob/CNTK/scientific/data_science/cntk.ksy
```yaml
types:
  begin_marker_hardcode:
    params:
      - id: name
        type: str
    seq:
      - id: end
        contents: ["B", 0]
      - id: marker
        contents: [name]
```

contents matches variable name instead of parameter
