### ISSUE TITLE
Is it possible to access data beyond linked list?

### ISSUE THREAD

**Issue by m-ka** [kaitai-io/kaitai_struct#460]
I'm trying to parse files containing data organized into linked lists. Here is an example of  simplified version of the parser:
``` YAML
meta:
  id: structlist

instances:
  struct_pointer:
    type: u1
    pos: 0x10

  struct_list:
    type: struct
    pos: struct_pointer

types:
  struct:
    seq:
    - id: id
      type: u1
    - id: next_pointer
      type: u1
    - id: data
      type: ...
    instances:
      next:
        type: struct
        pos: next_pointer
        io: _root._io
        if: next_pointer != 0
```
The data structures do not occupy the whole file and there is some unused space left after the list which I expect to be filled with zeroes. I would like to get access to this unused space to make sure its content meets my expectations. The problem is that I can't make any assumptions about list ordering or data sizes, and the last structure in the list can be placed in the beginning of the file. It looks like there is no way to access unused space in such situation. Am I right here?
