### ISSUE TITLE
How to reference the total length of the frame ? 

### ISSUE THREAD

**Issue by scallacs** [kaitai-io/kaitai_struct#467]
I would like to read the whole buffer except the two last bytes, but i cannot find anything to help me in the doc...

For exemple i have this definition: 

```
meta:
  id: test
  endian: be
seq:
  - id: data
    size: <TOTAL_LENGTH> - 2
  - id: status
    size: 2
```

How to reference the total length of the frame ?
