### ISSUE TITLE
support for YAML aliases?

### ISSUE THREAD

**Issue by skwerlman** [kaitai-io/kaitai_struct#478]
Is there a way to use YAML aliases?

In a spec i'm writing, i have to switch the endianness of a lot of types, and it'd make my file a lot more readable if i could just define the switch once and reference it where needed.

basically, instead of this
```yaml
...
  some_type:
    meta:
      endian:
        switch-on: _root.header.archive_flags.endianness
        cases:
          true: be
          false: le
    seq:
...
  some_other_type:
    meta:
      endian:
        switch-on: _root.header.archive_flags.endianness
        cases:
          true: be
          false: le
    seq:
...
```
i'd like to write
```yaml
aliases:
  endian_switch: &endian_switch
    endian:
      switch-on: _root.header.archive_flags.endianness
      cases:
        true: be
        false: le
...
  some_type:
    meta:
      <<: *endian_switch
    seq:
...
  some_other_type:
    meta:
      <<: *endian_switch
    seq:
...
```
