### ISSUE TITLE
Uncertain where the compiler is choking...

### ISSUE THREAD

**Issue by elliottecton** [kaitai-io/kaitai_struct#479]
I have written several .ksy files for RPC. When I try to compile to python, I get the following error:

```
kaitai-struct-compiler --verbose import -t python rpc_rpc_msg.ksy 
home path: location = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/lib/io.kaitai.kaitai-struct-compiler-0.8.jar
... URL-decoded = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/lib/io.kaitai.kaitai-struct-compiler-0.8.jar
... home = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec
... formats = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/formats
.. LoadImports: processing class rpc_rpc_msg (workDir = RelativeImportPath(List()))
.. LoadImports: loadImport(rpc_call_body, workDir = RelativeImportPath(List()))
.. importing relative rpc_call_body
.. LoadImports: processing class rpc_call_body (workDir = RelativeImportPath(List()))
.. LoadImports: loadImport(rpc_call_body_nfs, workDir = RelativeImportPath(List()))
.. importing relative rpc_call_body_nfs
.. LoadImports: loadImport(rpc_call_body_mount, workDir = RelativeImportPath(List()))
.. importing relative rpc_call_body_mount
rpc_call_body: /meta/imports/0: /seq/1/cases: expected map, got null
```

Any direction would be appreciated...

**Comment by GreyCat** [comment]
@elliottecton 
Please use proper triple backticks (```) Markdown layout to post preformatted bodies of text in the future: in-lined formatting with single backtick ruins the newlines.

For the message, as far as I see, it says that in a file `rpc_call_body` (probably imported as the first one in `rpc_rpc_msg`), you have element `/seq/1`, which is 2-nd element in sequence in top-level `seq` element, where you have `cases` subelement, where a compiler expected a map and got null. This is probably due to having something like that:

```
seq:
  - id: foo
    type: u1
  - bar:
    type:
      cases: # <= here's the empty cases clause
```

If the error persists, please share your ksy collection so I could investigate.

**Comment by elliottecton** [comment]
Still getting the following error:

```
kaitai-struct-compiler --verbose import -t python rpc_rpc_msg.ksy 
home path: location = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/lib/io.kaitai.kaitai-struct-compiler-0.8.jar
... URL-decoded = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/lib/io.kaitai.kaitai-struct-compiler-0.8.jar
... home = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec
... formats = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/formats
.. LoadImports: processing class rpc_rpc_msg (workDir = RelativeImportPath(List()))
.. LoadImports: loadImport(rpc_call_body, workDir = RelativeImportPath(List()))
.. importing relative rpc_call_body
.. LoadImports: processing class rpc_call_body (workDir = RelativeImportPath(List()))
.. LoadImports: loadImport(rpc_call_body_nfs, workDir = RelativeImportPath(List()))
.. importing relative rpc_call_body_nfs
.. LoadImports: loadImport(rpc_call_body_mount, workDir = RelativeImportPath(List()))
.. importing relative rpc_call_body_mount
rpc_call_body: /meta/imports/0: /seq/1/cases: expected map, got null
```

Here is the file 'rpc_rpc_msg.ksy':

```
meta:
  id: rpc_rpc_msg
  imports:
    - rpc_call_body
seq:
  - id: rpc_last_frag
    type: b1
  - id: rpc_frag_length
    type: b31
  - id: rpc_xid
    type: u4be
  - id: rpc_message_type
    type: u4be
    enum: message_type_enum
  - id: rpc_body
    size-eos: true
    type:
      switch-on: rpc_message_type
      cases:
        'message_type_enum::rpc_call': rpc_call_body
        #'message_type_enum::rpc_reply': rpc_reply_body
enums:
  message_type_enum:
    0: rpc_call
    1: rpc_reply
```

Here is the file 'rpc_call_body.ksy':

```
meta:
  id: rpc_call_body
  imports:
    - rpc_call_body_nfs
    - rpc_call_body_mount
seq:
  - id: rpc_version
    type: u4be
  - id: rpc_program
    type: u4be
    enum: rpc_program_enum
  - id: rpc_program_vers
    size-eos: true
    type:
      switch-on: rpc_program
      cases:
        'rpc_program_enum::nfs': rpc_call_body_nfs
        'rpc_program_enum::mount': rpc_call_body_mount
enums:
  rpc_program_enum:
    100000: portmap
    100003: nfs
    100005: mount
    100011: rquota
    100021: nlm
    100024: nsm
```

Let me know if you need more of the import files. I truly appreciate you taking a look at this!

**Comment by GreyCat** [comment]
With just these 2 files, substituting `rpc_call_body_nfs` and `rpc_call_body_mount` with empty files, everything compiles perfectly for me. Please send these 2 in as well?

**Comment by elliottecton** [comment]
rpc_call_body_nfs:
```
meta:
  id: rpc_call_body_nfs
  imports:
    - rpc_call_body_nfsv3
    - rpc_call_body_nfsv4
seq:
  - id: rpc_nfs_version
    type: u4be
    enum: rpc_nfs_version_enum
  - id: rpc_nfs_procedure
    size-eos: true
    type:
      switch-on: rpc_nfs_version
      cases:
      'rpc_nfs_version_enum::v3': rpc_call_body_nfsv3
      'rpc_nfs_version_enum::v4': rpc_call_body_nfsv4
enums:
  rpc_nfs_version_enum:
    3: v3 
    4: v4
```

and rpc_call_body_mount:
```
meta:
  id: rpc_call_body_mount
seq:
  id: body 
  size-eos: true
```
