### ISSUE TITLE
How to Change the Order of read bits

### ISSUE THREAD

**Issue by belse-de** [kaitai-io/kaitai_struct#484]
The data I want to read are 144 flags concatenated to one byte buffer with the following structure:
```
x[0]     x[1]     x[2]     ...
01234567 01234567 01234567 ...
abcdefgh ijklmnop qrstuvwx ...
```
Naively I wrote the following ksy config:
```
found_entities:
        seq:
          - id: seen
            type: b1
            repeat: expr
            repeat-expr: 144
```
Which gives me the bits in the wrong order:
```
x[0]     x[1]     x[2]     ...
01234567 01234567 01234567 ...
hgfedcba ponmlkji xwvutsrq ...
```
Can some tell me how to reverse this behaviour in the ksy file without writing the bitmask for every flag
