### ISSUE TITLE
Importing custom types fails

### ISSUE THREAD

**Issue by elliottecton** [kaitai-io/kaitai_struct#486]
I am trying to keep common data structures in their own file, and then importing them into other .ksy files when they are needed. Currently looks like this:

**u_nfsv3_setattr_call.ksy**
```yaml
meta:
  id: u_nfsv3_setattr_call
  imports:
    - ../nfs_structs
seq:
  - id: fhandle
    type: nfs_structs.nfs_fh
```
**nfs_structs.ksy**
```yaml
meta:
  id: nfs_structs
types:
  nfs_fh:
  - id: fhandle_length
    type: u4be
  - id: fhandle
    size: fhandle_length
```
**Compiler Error**
```bash
kaitai-struct-compiler -t python --verbose import u_nfsv3_setattr_call.ksy 
home path: location = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/lib/io.kaitai.kaitai-struct-compiler-0.8.jar
... URL-decoded = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/lib/io.kaitai.kaitai-struct-compiler-0.8.jar
... home = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec
... formats = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/formats
.. LoadImports: processing class u_nfsv3_setattr_call (workDir = RelativeImportPath(List()))
.. LoadImports: loadImport(../nfs_structs, workDir = RelativeImportPath(List()))
.. importing relative ../nfs_structs
u_nfsv3_setattr_call: /meta/imports/0: /types/nfs_fh: expected map, got List(Map(id -> fhandle_length, type -> u4be), Map(id -> fhandle, size -> fhandle_length)) (class scala.collection.immutable.$colon$colon)
```

Is this not a supported feature yet? If it is supported, any clue what I am doing wrong?

**Comment by KOLANICH** [comment]
You don't have `seq`

**Comment by GreyCat** [comment]
@KOLANICH is right, it's all in the error message:

```
u_nfsv3_setattr_call: /meta/imports/0: /types/nfs_fh: expected map, got List(...)
```

That means that in `/types/nfs_fh` of first import from `u_nfsv3_setattr_call` we expect to find a map (with all these `seq`, `types`, `instances`, etc, but you've got an array (list) there.

**Comment by elliottecton** [comment]
Hopefully this isn't something painfully obvious again. I have corrected the file to have `seq` in it:

*updated nfs_structs.ksy file*
```yaml
meta:
  id: nfs_structs
types:
  nfs_fh:
    seq:
    - id: fhandle_length
      type: u4be
    - id: fhandle
      size: fhandle_length
```

Now I am getting the following error:

```bash
kaitai-struct-compiler -t python --verbose import u_nfsv3_setattr_call.ksy 
home path: location = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/lib/io.kaitai.kaitai-struct-compiler-0.8.jar
... URL-decoded = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/lib/io.kaitai.kaitai-struct-compiler-0.8.jar
... home = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec
... formats = /usr/local/Cellar/kaitai-struct-compiler/0.8_1/libexec/formats
.. LoadImports: processing class u_nfsv3_setattr_call (workDir = RelativeImportPath(List()))
.. LoadImports: loadImport(../nfs_structs, workDir = RelativeImportPath(List()))
.. importing relative ../nfs_structs
.. LoadImports: processing class nfs_structs (workDir = RelativeImportPath(List(..)))
.. LoadImports: processing class  (workDir = RelativeImportPath(List(..)))
imports done, got: Set(u_nfsv3_setattr_call, nfs_structs) (async=List())
/seq/0: unable to find type 'nfs_structs.nfs_fh', searching from u_nfsv3_setattr_call
```
