### ISSUE TITLE
Enhancement request: Something like Lisp cond for type selection

### ISSUE THREAD

**Issue by brunchboy** [kaitai-io/kaitai_struct#489]
We currently have `if`, which allows elements to appear or disappear based on a logical expression, and `case`, which allows a type to be selected based on matching a literal value with an optional default case. I sometimes need something which is halfway between these, like the `cond` expression in Lisp, where you can choose between a variety of alternatives based on a series of logical expressions, with an optional default case.

To make this concrete, here is a definition that is the best I can do in the current implementation (taken from [here](https://github.com/Deep-Symmetry/beat-link/blob/5da596c526768a3f6df40d044754845f6397dc67/kaitai/pdb.ksy#L803-L808)):
```yaml
        type:
          switch-on: length_and_kind
          cases:
            0x40: device_sql_long_ascii
            0x90: device_sql_long_utf16be
            _: device_sql_short_ascii(length_and_kind)
```
The problem is that this is not correct, what I have labeled as the default should only be chosen if `length_and_kind` is odd. So I would much prefer to be able to write something like this:
```yaml
        type:
          switch-on-cond:
            case:
              expr: length_and_kind == 0x40
              result: device_sql_long_ascii
            case:
              expr: length_and_kind == 0x90
              result: device_sql_long_utf16be
            case:
              expr: (length_and_kind % 1) > 0
              result: device_sql_short_ascii(length_and_kind)
```
Note that in this structure I actually don’t want a default, and it should act like `case` when nothing matches in this situation. To support defaulting, one could either use a `case` clause with an `expr` that was always true (evaluation should stop with the first `case` that succeeds), or a `default: some_type` in place of a final `case:` subtree.

**Comment by KOLANICH** [comment]
>what I have labeled as the default should only be chosen if length_and_kind is odd.

You can create an own wrapper type and either and pass there `length_and_kind` or use `_parent`

**Comment by brunchboy** [comment]
I’m not sure what you mean? I did that, I think, if you follow the link in my second paragraph you can see the entire `.ksy` file. `device_sql_short_ascii` is a parametric type. What I was trying to say in my comment is that I only want that case to match when `length_and_kind` is not a multiple of two.

…oh, I think I understand perhaps? I could use an `if:` inside the implementation of `device_sql_short_ascii` to avoid trying to create the string if the length is incorrect. Or create a string whose contents are something like “Unexpected length_and_kind value!” That is a good idea in the current file, thanks.

**Comment by dgelessus** [comment]
This would also be useful for complex switch blocks that depend on multiple variables. Currently I'm using a workaround like this (which does what I need, but is not very readable):

```yml
switch-on: 'first_char == 0x2f ? second_char >= 0x30 and second_char <= 0x39 ? 1 : 2 : 0'
cases:
  0: regular_member_name
  1: long_member_name
  2: special_member_name
```

**Comment by GreyCat** [comment]
My main concern here is that it's very different from current switch semantics, which is currently (1) totally order-independent, (2) maps neatly to existing switch-case semantics in majority of languages.

The proposed mechanism is possible to implement, but probably we should start with order-dependent semantics, i.e. something like:

```yaml
        type:
          switch-on-cond:
            - expr: length_and_kind == 0x40
              result: device_sql_long_ascii
            - expr: length_and_kind == 0x90
              result: device_sql_long_utf16be
            - expr: (length_and_kind % 1) > 0
              result: device_sql_short_ascii(length_and_kind)
```

**Comment by dgelessus** [comment]
Right, this construct would potentially be order-dependent if the conditions aren't all mutually exclusive. I don't think compiling it will be a problem, as far as I can tell this would be equivalent to a simple `if`-`else if`-...-`else` chain in most languages.

Also, I noticed now that the example I posted above is not a very good one, since it contains a nested condition. Just to be clear, I wasn't asking for special syntax for the nesting. I would be fine with writing this:

```yml
type:
  switch-on-cond:
    - expr: first_char == 0x2f
      result:
        switch-on-cond:
          - expr: second_char >= 0x30 and second_char <= 0x39
            result: long_member_name
          - expr: _
            result: special_member_name
    - expr: _
      result: short_member_name
```

This is longer than my current solution with the integer codes, but IMHO more readable, because it's obvious which condition belongs to which case.

**Comment by GreyCat** [comment]
@dgelessus

1. I'm not sure that nested switched types are supported right now, most likely they're not. Actually, that's a probably a good idea to make sure they work separately. Shouldn't be very hard, but requires some pretty good test coverage, as I suspect something fishy with C++ object ownership / memory management in this situation.

2. There's actually been somewhat related proposal on adding ranges to our syntax / types — #130. It would probably make stuff like that somewhat more elegant, like:

```yaml
switch-on: second_char
cases:
  0x30..0x39: long_member_name
  _: special_member_name
```
