### ISSUE TITLE
`substring` method is not available for graphviz and go

### ISSUE THREAD

**Issue by kolen** [kaitai-io/kaitai_struct#491]
```yaml
meta:
  id: substring_test
seq:
  - id: somestr
    type: str
    size: 2
    encoding: ascii
instances:
  foo:
    value: somestr.substring(0, 1)
```

This compiles successfully for all targets except `graphviz` and `go`.

```
% kaitai-struct-compiler -t graphviz test.ksy
Call(Attribute(Name(identifier(somestr)),identifier(substring)),ArrayBuffer(IntNum(0), IntNum(1))) (of class io.kaitai.struct.exprlang.Ast$expr$Call)
% echo $?
2
```

```
% kaitai-struct-compiler -t go test.ksy
an implementation is missing
% echo $?
2
```
