### ISSUE TITLE
Handling of virtual mapping and addressing

### ISSUE THREAD

**Issue by angea** [kaitai-io/kaitai_struct#492]
Executables often define how the file is loaded in memory, then some structures
(relocation tables, imports...) are referred by [relative] virtual address rather than file offset.

For these, we need a way to determine the initial offset of the structure to be able to parse it.

**Comment by GreyCat** [comment]
I agree that this is a long called-for functionality for throughout parsing of many executable formats.

From what I see so far, this boils down to solving 2 things:

* We need to get KS to know that certain attributes in the file we have actually define memory map — i.e. which RVAs correspond to which regions in the file. For example, in PE this is done in [section](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/executable/microsoft_pe.ksy#L321-L346) — `pointer_to_raw_data` and `size_of_raw_data` define a spot in disk file, and it should be loaded (mapped to) RVA `virtual_address`.

* We need to be able to point KS structures to RVA addresses.

Defining this map probably warrants some magic to create a new IO stream object that will engulf all these section declarations. It would get us a new shiny IO object (say, `io_memory`). Given that it's basically the same as value instance, I would tentatively propose something like:

```yaml
instances:
  io_memory:
    memory-map: pe.sections
```

and `pe.sections` in this case must define some well-known reserved attributes like `_rva` and `_data`, i.e. something like:

```yaml
  section:
    seq:
      - id: name
        type: str
        encoding: UTF-8
        size: 8
        pad-right: 0
      - id: virtual_size
        type: u4
      - id: virtual_address
        type: u4
      - id: size_of_raw_data
        type: u4
      - id: pointer_to_raw_data
        type: u4
      - id: pointer_to_relocations
        type: u4
      - id: pointer_to_linenumbers
        type: u4
      - id: number_of_relocations
        type: u2
      - id: number_of_linenumbers
        type: u2
      - id: characteristics
        type: u4
    instances:
      _rva:
        value: virtual_address
      _data:
        pos: pointer_to_raw_data
        size: size_of_raw_data
```

As long as it will be normal IO object, using it in parse instances would be piece of cake, i.e.:

```yaml
instances:
  foo:
    io: io_memory
    pos: 1234 # <= this is RVA, not just a position in a file
    type: bar
```
