### ISSUE TITLE
c++ memory leak if switch-on and repeat are combined

### ISSUE THREAD

**Issue by jeclarke** [kaitai-io/kaitai_struct#494]
If a switch on field is set to repeat then the generated c++ code leaks memory in the case where the found value is not covered by the switch cases.

A ksy file like this:
````yaml
meta:
  id: sample
  endian: be

seq:
  - id: sample_type
    type: u1
  - id: sample_field
    repeat: eos
    type:
      switch-on: sample_type
      cases:
        '1': subsample

types:
  subsample:
    seq:
      - id: subsample_field
        type: u1
````

Generates code like this:
````cpp
void sample_t::_read() {
    m_sample_type = m__io->read_u1();
    m_sample_field = new std::vector<subsample_t*>();
    {
        int i = 0;
        while (!m__io->is_eof()) {
            n_sample_field = true;
            switch (sample_type()) {
            case 1: {
                n_sample_field = false;
                m_sample_field->push_back(new subsample_t(m__io, this, m__root));
                break;
            }
            }
            i++;
        }
    }
}

sample_t::~sample_t() {
    if (!n_sample_field) {
        for (std::vector<subsample_t*>::iterator it = m_sample_field->begin(); it != m_sample_field->end(); ++it) {
            delete *it;
        }
        delete m_sample_field;
    }
}
````

Note that `m_sample_field` is always created with new but only deleted if n_sample_field is false. When a case statement matches all is OK but when it does not the vector is not deleted.

I worked around this by introducing a wrapper type for each case and putting the repeat clause in there. Like this:
````yaml
meta:
  id: sample
  endian: be

seq:
  - id: sample_type
    type: u1
  - id: sample_field
    type:
      switch-on: sample_type
      cases:
        '1': wrapper

types:
  wrapper:
    seq:
      - id: items
        repeat: eos
        type: subsample

  subsample:
    seq:
      - id: subsample_field
        type: u1
````
