### ISSUE TITLE
multiple terminators for strz

### ISSUE THREAD

**Issue by wyrex** [kaitai-io/kaitai_struct#5]
23 16 34 13 56 23 10 00 74 76 77 65 23 22 00 11 1A 47 2E 23 0A 00 7E 4A 23 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

I have file that has script commands (0x23) and no size markers. File ends with varying amount of 0x0 bytes. 

23 [command number u2 ] [parameters]
Unexpected fixed contents: got 00, was waiting for 23 (because trailing 0x00's). 

Is there 'correct' way to read this without getting error? Visualizer shows right values, just this popup happens when opening file.

```
meta:
    id: dat
    application: script
    endian: le
seq:
    - id: commands
      repeat: eos
      type: script_cmd
types:
    script_cmd:
        seq:
            - id: cmd_start
              contents: [0x23] 
            - id: num
              type: u2
            - id: params
              type: strz
              encoding: SJIS
              terminator: 0x23
              consume: false
              if: num != 0x12 # command num for end of file
```

**Comment by GreyCat** [comment]
Try something like that:

```yaml
meta:
    id: dat
    application: script
    endian: le
seq:
    - id: commands
      repeat: eos
      type: script_cmd
types:
    script_cmd:
        seq:
            - id: cmd_start
              contents: [0x23] 
            - id: num
              type: u2
            - id: params
              type: strz
              encoding: SJIS
              terminator: 0x23
              consume: false
              eos-error: false
```

That allows to parse the file you've provided without errors. However, it is still probably not a very good idea to parse the file using "parse anything up to 0x23" semantic - real parsing code rarely use something like that, and parsing `params` as a 0x23-terminated string is probably not what you want anyway.

In 99% of cases I've seen (with notable exception of terminator-based strings encoding), if we're dealing with something like a bytecode (i.e. `[opcode] [parameters]`), variable length parameters depend on the opcode itself, not the termination symbol. Notably, it's generally a very bad idea to add "termination bytes" like 0x23, given that some opcode might have genuine integer 0x23 as a parameter.

It is possible to implement something like "read bytes until some termination byte / sequence of bytes, and then reinterpret them as some complex subtype" in future, but so far I haven't seen a single example where such a semantic would be helpful. I'd be grateful if you'll prove me wrong :)
