### ISSUE TITLE
Specify opaque types in meta data

### ISSUE THREAD

**Issue by bsagal** [kaitai-io/kaitai_struct#500]
In the meta section i can state whether to allow opaque types with the `ks-opaque-types` key.

I think it would be a good idea to allow the specification of witch opaque types are allowed instead of just `true`.

This allow someone to easily see witch types are needed and to produce an error at generation time if an extra type is used (or if there is a typo in a type name)

**Comment by KOLANICH** [comment]
I suggest to make it a dict.

```yaml
meta:
 ks-opaque-types:
   some_type:
     params:
       - id: a
         type: u8
     doc: "this opaque type does ...."

**Comment by GreyCat** [comment]
A good idea, actually ;) The only thing I would probably consider is just moving it into TypeSpec space, and naming something like `opaque-types`:

```yaml
meta:
  id: foo
  # no ks-opaque-types required, as everything will be compile-time checked
types:
  regular_subtype:
    # normal type spec follows
opaque-types:
  opaque_subtype: {} # just a dumb type without parameters or documentation
  opaque_subtype_with_params_and_doc:
    params:
      - id: a
        type: u8
    doc: Some documentation...
seq:
  - id: use_regular
    type: regular_subtype
  - id: use_opaque_1
    type: opaque_subtype
  - id: use_opaque_2
    type: opaque_subtype(42)
```

No need to abuse `meta`, pushing such complex structures there.

**Comment by GreyCat** [comment]
Two extra thoughts:

1. Types declared this way would be inevitably considered nested. Not all languages are actually ok with that — i.e. it's not universal to be able to able to define inner nested class in external code.

2. If we're going to have `params`, it makes perfect sense to actually have something like "opaque instances", thus effectively concluding interface definition for both "ins" and "outs". Given that this is *not* opaque type, probably it's worth renaming this concept to "external type" or something like that:

```yaml
meta:
  id: foo
external-types:
  external_subtype:
    params:
      - id: input_a
        type: u8
    instances:
      output_b:
        type: str
    doc: Some documentation...
seq:
  - id: use_regular
    type: regular_subtype
  - id: use_external
    type: external_subtype(42)
instances:
  more_derivations:
    # able to use .output_b as it's declared
    value: use_external.output_b + "."
```
