### ISSUE TITLE
compiler not support "contents" key in Attribute spec

### ISSUE THREAD

**Issue by iabdurrahman** [kaitai-io/kaitai_struct#501]
based on document in [http://doc.kaitai.io/ksy_reference.html#attribute-contents](http://doc.kaitai.io/ksy_reference.html#attribute-contents) (2018-12-20), Attribute spec may contain "contents" key. but ksc throw error when compiling file containing "contents" key in seq

example ksy file:
```yaml
meta:
  id: socksv5_method
  title: SOCKSv5 Method packet (RFC 1928)
  endian: be
doc: |
  packet format for message identifier/method selection for SOCKSv5
seq:
  - id: ver
    doc: "SOCKS version, must 0x05"
    type: u1
    contents:
      - 0x05
  - id: nmethod
    doc: "length of supported SOCKSv5 method"
    type: u1 
  - id: method
    doc: "SOCKSv5 client supported method (authentication), length equal to nmethod"
    type: u1
    repeat: expr
    repeat-expr: nmethod
```

but compiler show error (compile to python class):
`/seq/0/contents: unknown key found, expected: consume, doc, doc-ref, eos-error, id, if, include, repeat, terminator, type`

compiler version:
`kaitai-struct-compiler 0.9-SNAPSHOT`

java version:
```
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

I want kaitai struct stop parsing data when some field value is invalid.
