### ISSUE TITLE
Get integer from inside an optional block

### ISSUE THREAD

**Issue by DarkShadow44** [kaitai-io/kaitai_struct#502]
Now, the problem is a bit hard to describe:
The file contains list of blocks, which are identified by an id in front of each block. One of the blocks contains a number I need later on in the parsing, but outside the block. Since I don't know which index the block has, or if it even exists, I can't get that integer.
See the code for a clearer view of my problem:
```yaml
meta:
  id: ribbon
  endian: le

seq:
  - id: count_blocks
    type: u1
  - id: blocks
    type: type_block_generic
    repeat: expr
    repeat-expr: count_blocks
  - id: main_blocks
    type: u2
    repeat: expr
    repeat-expr: count_optional_tabs # <--problem

enums:
  block_type:
    0: main_tabs
    1: optional_tabs

types:
  type_block_main_tabs:
    seq:
    - id: count_main_tabs
      type: u2
  
  type_block_optional_tabs:
    seq:
    - id: count_optional_tabs
      type: u2
      
  type_block_generic:
    seq:
    - id: type
      type: u2
      enum: block_type
    - id: block
      type:
        switch-on: type
        cases:
          block_type::main_tabs: type_block_main_tabs
          block_type::optional_tabs: type_block_optional_tabs
```
count_optional_tabs needs to be used later, and it can't be accessed outside. And if it doesn't exist, I need to skip the field (i.e. assume count_optional_tabs as 0).
Do we already have functionality for that kind of issue? Sorry if I missed something, but I didn't find anything.
