### ISSUE TITLE
Option to not byte-align when going into substream

### ISSUE THREAD

**Issue by ZetaTwo** [kaitai-io/kaitai_struct#504]
First of all, thanks for an amazing tool. I have two questions and ~~have created two separate issues for them~~ the other matches issue #484.

I'm parsing a format which uses a bit-stream to pack various values including repeated entries without byte alignment. Basically I need to write some KSY that looks like this:

```
seq:
  - id: flag1
    type: b1
  - id: entries
    type: entry
    repeat: eos

types:
  entry:
    seq:
      - id: flag2
        type: b1
      - id: length
        type: b13
      ...
```

If I compile and run this however the resulting Python code looks like this:
```
class Entries
 ...
 def _read(self):
        self.flag1 = self._io.read_bits_int(1) != 0
        self._io.align_to_byte()
 ...
```

This means that after reading the first bit of the stream it will skip the next 7 bits and data will be lost. If I manually comment out the "align_to_byte()" call, everything works fine.

So, is it possible to make it so that it doesn't align to byte before descending into a sub type? I.e. basically just leaving out that single align call?
