### ISSUE TITLE
Calculated instance type

### ISSUE THREAD

**Issue by ecoskian** [kaitai-io/kaitai_struct#505]
Hi,

I'm trying to use a calculated instance to get a view of value multiplied by a constant, somewhat like this:

```
seq:
  - id: my_field
    type: u4be
instance:
  transformed_field:
    value: my_field * 10000
```
I would like for transformed field to be an u8 (uint64_t), but I can't find a way to instruct kaitai to make it so, and when I compile to C++ it creates a method transformed_field with return type uint32_t, which I know that is doomed to overflow given my data. Ideally I would provide a clue in the literal (e.g. 10000UL) or a type for the field, but neither seems to be an option. 

I am quite new to kaitai, so any advice is welcome!
