### ISSUE TITLE
Missing raw values for non custom-types using size attribute.

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct#508]
I have some special type-length-value containing multiple values of the same length. So the type might be an integer with 8 bits or 16 or some binary-coded-decimal or such and that repeated e.g. 5 times or 10 or whatever. I want to be able to access the properly typed values AND additionally the raw binary data which build the values, simply because I need to process that value further and don't want to serialize again what in theory already was/is available.

So using `size` came into my mind, because that provides a substream which I already access in other cases. Luckily this seems to work with multiple values as well, great work! :-), but it seems that this doesn't work if the individual values are one of the built-in supported types. So if the type of the value is a user type, I get raw data from KS, while I don't if it's simply a 16 bit integer.

I would have expected that `size` always provides the raw data additionally. So is this restriction by design or by accident? Any reasons why one shouldn't always get binary data if requested using `size`?

Of course I could serialize the missing data on my own, but it's easier if KS could provide it like with user types, it's already available, I don't need to check for if KS already provided data or I need to do it on my own etc.

The following is the example YAML:

```Yaml
  fmt_oms_apl_vdb_data_compact_prof_with_regs:
    seq:
      - id:   spacing_control_byte
        type: fmt_oms_apl_vdb_header_dib_dif

      - id:   spacing_value
        type: u1

      - id:   registers
        size: spacing_control_byte.get_fixed_data_size
        type:
          switch-on: spacing_control_byte.data_coding
          cases:
            fmt_oms_apl_vdb_header_dib_data_coding::bcd_02_digits:    bcd_02_digits
            [...]
            fmt_oms_apl_vdb_header_dib_data_coding::bin_int_08_bits:  u1
            [...]
        repeat:       expr
        repeat-expr:  registers_cnt
```

Which leads to some Java which in some `case`s doesn't use `this._raw_registers`:

```Java
        private void _read() {
            this.spacingControlByte = new FmtOmsAplVdbHeaderDibDif(this._io, this, _root);
            this.spacingValue = this._io.readU1();
            registers = new ArrayList<Object>(Long.valueOf(registersCnt()).intValue());
            for (int i = 0; i < registersCnt(); i++) {
                switch (spacingControlByte().dataCoding()) {
                [...]
                case BIN_INT_08_BITS: {
                    this.registers.add(this._io.readU1());
                    break;
                }
                [...]
                case BCD_02_DIGITS: {
                    this._raw_registers.add(this._io.readBytes(spacingControlByte().getFixedDataSize()));
                    KaitaiStream _io__raw_registers = new KaitaiStream(_raw_registers.get(_raw_registers.size() - 1));
                    this.registers.add(new Bcd02Digits(_io__raw_registers, this, _root));
                    break;
                }
                [...]
                }
            }
        }
````
