### ISSUE TITLE
Error reporting into stderr stream

### ISSUE THREAD

**Issue by valery1707** [kaitai-io/kaitai_struct#509]
If I try to compile KSY with errors, than compiler set exit status to `2` and show in console messages about discovered problems.
But this messages will be printed into `stdout` process's stream, while I expect them in `stderr`.

Demo KSY:
```
meta:
  id: demo
  file-extension: demo
  endian: le
seq:
  - id: header
    type: header
types:
  header:
    seq:
      - id: Magic
        contents: 'DEMO'
```
Compiler message: `/types/header/seq/0/id: invalid attribute ID: 'Magic', expected /^[a-z][a-z0-9_]*$/`
