### ISSUE TITLE
Add "meta/ks-version" to designate minimal compiler version needed

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#53]
A proposal to add stuff like:

```yaml
meta:
  id: ...
  version: 0.6
```

to designate minimal version of compiler need to parse the file.
