### ISSUE TITLE
Add `.is<...>` syntax to check if a value has a certain type (isinstance/instanceof)

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct#533]
It would be useful to have a `.is<...>` method (as a counterpart to `.as<...>`) to check whether a value has a certain type. This would be useful for working with `switch-on` types: right now there is no way to check which switch case was taken and to safely access an attribute of a specific switch case.

As a workaround, I'm currently defining my own boolean value instances that indicate whether a specific case was taken:

```yaml
instances:
  is_foo:
    value: thing == 123
  parsed:
    pos: 0
    type:
      switch-on: thing
      cases:
        123: foo_case
        _: bar_case
```

This lets me write expressions like `is_foo ? parsed.as<foo_case>.foo_specific_attr : generic_default` (which I'd instead like to write as `parsed.is<foo_case> ? parsed.as<foo_case>.foo_specific_attr : generic_default`). For small `switch-on` blocks this workaround is fine, but with more cases I need to add an extra helper instance for every case that I want to check for.

---

#518 suggests the same syntax, but for a different use case (checking whether a raw value is valid for a certain enum).

In that issue, some concerns were raised about how `.is<...>` could be implemented for languages that don't have sufficient information about object types at runtime (or at least not unconditionally). I don't think this is a big issue. First of all, all currently supported languages have some kind of runtime type checking (though apparently for C++ the situation might be more difficult). And even in languages that don't have sufficient runtime support (i. e. C and maybe C++) the respective codegen could store the necessary dynamic type information manually and have `.is<...>` check against that.

Since the types of almost all values are statically known, trivial `.is<...>` checks could also be optimized away at compile time to avoid unnecessary generation/use of dynamic type information. As far as I can tell, the only places where exact types are not known at compile time are `switch-on` types and types with `struct`/`any` parameters.

**Comment by KOLANICH** [comment]
If one have selected the type, he has a criteria. If he has a criteria, he can store it in an instance. This instance would efficienly be a type of a variable stored in runtime.

But it also may be redundant. So I propose the following

1. implement a property `._type` of every property. 
2. allow only switching on it and comparing it to something
3. for the languages without RTTI (including C++, where RTTI is usually disabled) Go up by type hierarchy, concatinating values of every `switch-on` and `if` into a single value with bit operations
for example:
```yaml
seq:
    - id: a
      type: u8
    - id: b:
      type:
          switch-on: a
          cases:
            1: b
      
     - id: d_type_if
         type: u8
         if: b.d._type == ... # a<< 2 | b.e is used as a type id
types:
   b:
     seq:
       - id: e
         type: u2
       - id: d
         type:
           switch-on: e
           ....
       - id: d_type_if
         type: u8
         if: d._type == ... # e is used as a type id
```
