### ISSUE TITLE
[Question] Switch on Variable of itself

### ISSUE THREAD

**Issue by thetemplar** [kaitai-io/kaitai_struct#537]
I have a header, and within it, its version/specialized-type is defined, declaring the other fields.
A simplified example:
![image](https://user-images.githubusercontent.com/5371336/54288508-e24c0a80-45a7-11e9-87a3-fd4b04253df3.png)

Can I switch using itself? Or can i somehow used a fixed position to "reuse" the byte?

```

types:
  data_segment_row:
    seq:
      - id: flags
        type: u4
      - id: header
        type: 
          switch-on: header.packet_transport_type
          cases:
            1: data_header_hyper
            _: data_header_unknown
      - id: data
        size: 1000
        
  data_header_unknown:
    seq:
      - id: timestamp
        type: u8
      - id: packet_transport_type
        type: u4
        enum: enum_packet_transport_type
      - id: crc
        type: u4
      - id: ckp_len
        type: u4
  data_header_hyper:
    seq:
      - id: timestamp
        type: u4
      - id: size
        type: u4
      - id: packet_transport_type
        type: u4
        enum: enum_packet_transport_type
      - id: crc
        type: u8

```

**Comment by thetemplar** [comment]
I think I found the answer: Is this correct ?

```
types:
  data_segment_row:
    seq:
      - id: flags
        type: u4
      - id: header
        type: #data_header_hyper
          switch-on: header_type
          cases:
            'enum_packet_transport_type::hyper': data_header_hyper
            _: data_header_unknown
      - id: hyperperiod
        size: _parent.byte_array_length-8
        
    instances: 
      header_type:
        value: _parent.as<data_segment_row>.header.as<data_header_unknown>
        enum: enum_packet_transport_type
```
