### ISSUE TITLE
Value instances fail to support enums

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#54]
Value instances like that:

```yaml
instances:
  foo:
    value: # some integer
    enum: some_enum
```

return just the value, not wrapped in enum.
