### ISSUE TITLE
Bug when using Bit-sized integers and eof flag.

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [kaitai-io/kaitai_struct#548]
Suppose I have this file schema:
```yaml
meta:
  id: my_data
  endian: le
seq:
- id: pixels
  type: b4
  repeat: eos
```
And a **32 bytes** binary file.
My expectation is the pixels property would have **64 elements** (each byte has two "4 bits" group).
But when I tried, Kaitai only produced a **63 elements** pixels array, it missed the last "4 bits" element.
So there is some kind of bug in the parsing process.
