### ISSUE TITLE
Stl format seems to be broken

### ISSUE THREAD

**Issue by mykolapolonskyi** [kaitai-io/kaitai_struct#554]
regarding http://www.fabbers.com/tech/STL_Format 
seems that without this 2bytes unsigned int (short) format isn't full

compare java implementation http://formats.kaitai.io/stl/index.html
with https://numpy-stl.readthedocs.io/en/latest/usage.html#initial-usage

```
types:
  triangle:
    doc: |
      Each STL triangle is defined by its 3 points in 3D space and a
      normal vector, which is generally used to determine where is
      "inside" and "outside" of the model.
    seq:
      - id: normal
        type: vec3d
      - id: vertices
        type: vec3d
        repeat: expr
        repeat-expr: 3
      - id: atb
        type: u2
```
