### ISSUE TITLE
Data chunks with fixed length except for trailing chunk, matching overall stream length

### ISSUE THREAD

**Issue by jaroslaw-wieczorek** [kaitai-io/kaitai_struct#555]
I have problem with decoding data chunks by ksy file. My data chunks have fix size of 16 bytes, but last data chunk must have to len matched to the rest of stream. It's mean last data chunk must have size of (total_bytes_stream by mod 16) bytes. 
* Data_chunks (46b) :
** data_chunk1 - len 16 bytes  
** data_chunk2 - len 16 bytes 
** data_chunk3 - len 14 bytes

How to do it?

**Comment by GreyCat** [comment]
I can propose a few methods, for example:

```yaml
seq:
  - id: chunks
    type: data_chunk
    repeat: eos
types:
  data_chunk:
    seq:
      - id: sixteen_bytes_or_less
        size: '(_io.size - _io.pos > 16) ? 16 : (_io.size - _io.pos)'
```

**Comment by jaroslaw-wieczorek** [comment]
working, great thanks :D

**Comment by GreyCat** [comment]
@jaroslaw-wieczorek Any extra questions on this topic?

**Comment by jaroslaw-wieczorek** [comment]
In the kaitai struct, is it possible to combine all ```value``` fields from ```data_chunk``` into a new ```_io``` stream?  I need to combine the data into one stream for further processing without checksums.

```yaml
types:
  data_chunk:
    seq:
      - id: value
        size: '(_io.size - _io.pos > 17) ? 16 : ((_io.size - _io.pos) - 2)'
      - id: checksum
        size: 2
```

**Comment by GreyCat** [comment]
https://github.com/kaitai-io/kaitai_struct/issues/196 is probably what you're looking for, but it's currently in very early design stages. Please consider adding your issue there, specifying how exactly do you want to choose these chunks for collection?

**Comment by jaroslaw-wieczorek** [comment]
Okey.

**Comment by jaroslaw-wieczorek** [comment]
I'm sorry for a lot of questions, but I would like to know how to divide data_chunks as in the previous approach, but with the difference that the first element will contain a maximum of 15 bytes. The rest, as in the previous approach, are 16 bytes and the last one between 1-16 bytes.
Data_chunks (61b) :
** data_chunk1 - len 15 bytes
** data_chunk2 - len 16 bytes
** data_chunk2 - len 16 bytes
** data_chunk3 - len 14 bytes

**Comment by jaroslaw-wieczorek** [comment]
If someone is looking for a similar solution:
```yaml
  data_chunk:
    seq:
      - id: value
        size: '(_parent.data_chunks.size == 0 and (_io.size - _io.pos) > 17) ? 15 :  (_parent.data_chunks.size > 0 and (_io.size - _io.pos) > 17) ? 16 :  ((_io.size - _io.pos))'
      - id: checksum
        size: 2
```
