### ISSUE TITLE
Decoding the value relative to the starting position of another value.

### ISSUE THREAD

**Issue by jaroslaw-wieczorek** [kaitai-io/kaitai_struct#558]
Hi, 
I want start decoding instance  ```my_application_layer``` in second byte of  ```_io``` stream for  ```data_chunks```, but decoding instance  ```my_application_layer``` always start in 0 position of whole stream.. not in  ```data_chunks[0]._io``` or  ```data_chunks._io ```

code: 

```yaml
seq:
  - id: my_data_link_layer
    type: my_my_data_link_layer
    
  - id: transport_control
    type: my_transport_control
    if: my_data_link_layer.length > 5
    
  - id: data_chunks
    type: data_chunk 
    repeat: eos
    if: my_data_link_layer.header_control.fc.to_i == 4
  
instances:
  application_layer:
    io: data_chunks[0]._io
    type: my_application_layer
    pos: data_chunks[0]._pos
    if: my_data_link_layer.length > 5 and my_data_link_layer.header_control.fc.to_i == 4
 
types:
  data_chunk:
    seq:
      - id: data
        size: '(_io.size - _io.pos > 16) ? 16 : (_io.size - _io.pos)'
```
Whole io stream:
![image](https://user-images.githubusercontent.com/19189927/55856770-958a2e00-5b6b-11e9-8609-bd44f232c4f6.png)

Blue selection is data_chunks and in this position instance my_application_layer have to start decoded, but it start in red selection on stream beginning.

When I change ```data_chunks[0]._io``` to ```data_chunks._io``` i get this error: 
```bash
Parse error: undefined
Call stack: undefined scala.MatchError: _io (of class java.lang.String)
```

**Comment by GreyCat** [comment]
@jaroslaw-wieczorek Please use Markdown formatting (i.e. triple backticks) for source code.

Could you clarify, what is your question?

For general situation like "decoding the same buffer several times with different types", you can use substreams:

```yaml
seq:
  # some unknown number of bytes here
  - id: value_as_type1
    type: type1
    size: 16
instances:
  value_with_type2:
    io: value_with_type1._io
    pos: 0
    type: type2
```

`value_with_type1` and `value_with_type2` will parse the same 16-byte buffer.

**Comment by jaroslaw-wieczorek** [comment]
I want start decoding instance "application_layer" in second byte of _io stream for data_chunks, but decoding instance application_layer always start in 0 position of whole stream.. not in datachunks[0]._io or datachunks._io
 
```yaml
seq:
  - id: data_link_layer
    type: my_data_link_layer
    
  - id: transport_control
    type: my_transport_control
    if: data_link_layer.length > 5
    
  - id: data_chunks
    type: data_chunk 
    repeat: eos
    if: data_link_layer.header_control.fc.to_i == 4
  
instances:
  application_layer:
    io: data_chunks[0]._io
    type: my_application_layer
    pos: data_chunks[0]._pos
    if: data_link_layer.length > 5 and data_link_layer.header_control.fc.to_i == 4
 
```
