### ISSUE TITLE
Disallow referencing _io on fields that don't have their own substream

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct#563]
I've seen a few questions here (#562) and in Gitter recently where people had trouble with instance positioning, which in the end were because of an incorrect substream. (It's happened to myself as well.) Specifically, you might write a spec like this:

```yaml
seq:
  - id: foo
    type: u4
  - id: bar
    type: another_structure
instances:
  thing:
    io: bar._io
    seq: ...
```

with the expectation that `bar._io` is its own substream that starts at the same position as the `bar` field. However, in this case `bar._io` is in this case identical to `_parent._io`, since `bar` doesn't have an explicit `size`. This mistake only becomes obvious at runtime when parsing some data, at which point you get parse errors or unexpected results that are confusing when you don't know the cause of the problem yet.

I'd like to suggest that referring to `_io` on a field should only be allowed if that field has its own substream, and not one that is shared with a parent structure. I think it's very unlikely that you'd intentionally use `bar._io` to refer to a stream that doesn't belong to `bar` - why not refer to the stream via its actual "owner" instead? You have to know the stream's "owner" anyway in order to meaningfully use it.

**Comment by KOLANICH** [comment]
>I'd like to suggest that referring to _io on a field should only be allowed if that field has its own substream, and not one that is shared with a parent structure.

Only for the case `io` is absent in the property.

**Comment by dgelessus** [comment]
@KOLANICH Do you mean reusing another instance's explicitly set `io` should be allowed, like this?

```yaml
seq:
  - id: foo
    type: u4
  - id: bar
    size: 16
instances:
  thing1:
    io: bar._io
    type: ...
  thing2:
    io: thing1._io
    type: ...
```

I've never used this in practice, but if there's a use case for it then it should probably stay allowed.

**Comment by KOLANICH** [comment]
>Do you mean reusing another instance's explicitly set io should be allowed, like this?

Yes, but not exactly: `bar` has no `_io`, it is forbidden according to this proposal (and in fact it have never worked because primitive types are really primitive ones, `int` has no `_io` member).

**Comment by LikeLakers2** [comment]
Outsider here, I'm a little confused about what exactly is meant here. If you re-use an IO for multiple instances, (for example, both thing1 and thing2's IO are `bar._io`) wouldn't the instances have different values depending on what order the instances are read?

**Comment by KOLANICH** [comment]
>If you re-use an IO for multiple instances, (for example, both thing1 and thing2's IO are `bar._io`) wouldn't the instances have different values depending on what order the instances are read?

They would ... unless you specify `pos: 0` .

**Comment by LikeLakers2** [comment]
Then what would referencing an instance's IO in [the way dgelessus mentioned above](https://github.com/kaitai-io/kaitai_struct/issues/563#issuecomment-482798867) do that specifying the same IO twice couldn't?

Or am I just completely missing the point? It feels like I am with how confusing those responses are...

**Comment by KOLANICH** [comment]
>Then what would referencing an instance's IO in the way dgelessus mentioned above do that specifying the same IO twice couldn't?

Nothing, but it may be convenient to use polymorphism. I mean select one field `type` with `switch-on`-`cases` and then use it's property's `io`. Now it is likely won't work (as far as I remember), but in some future it may be fixed.

**Comment by LikeLakers2** [comment]
Ah, now I think I'm starting to understand. I don't think I agree with polymorphism being a good idea, since it sounds (at least to me) like it'd be ripe for even more confusion compared to just requiring the same IO be specified twice - even for a `switch-on` statement.

**Comment by GreyCat** [comment]
> I'd like to suggest that referring to `_io` on a field should only be allowed if that field has its own substream, and not one that is shared with a parent structure.

It's pretty hard to trace and catch in compile time, but probably we can do a warning or something like that in run time.

Example how things can get hard for static analysis:

```yaml
seq:
  - id: foo
    type: u4
  - id: bar
    type: another_structure
  - id: baz
    type: another_structure
    size: 100
instances:
  some_io:
    value: 'foo == 0 ? bar._io : baz._io'
  thing:
    io: some_io
    pos: 42
    type: ...
```

If  "foo == 0", then we'll be using `bar._io`, which is technically the same as main object's `_io`, and this violates proposed rule.
