### ISSUE TITLE
Setting pos:0 doesn't work when dealing with partially consumed byte

### ISSUE THREAD

**Issue by ronMilne** [kaitai-io/kaitai_struct#564]
Given the following, pos:0 fails as the id: type only consumes 5bits. Adding another id that consumes the final 3bits works,

seq:
  - id: thing
    type: seven_byte_thing
    size: 7
types:
  seven_byte_thing:
    seq:
      - id: type
        type: b5
    instances:
      payload:
        pos: 0
        type:
          switch-on: type
          cases:
            0: type0
            1: type1
            # ...
  type0:
    seq:
      - id: type
        type: b5
      - id: field1
        type: b5
      - id: field2
        type: b4
      # ...

**Comment by KOLANICH** [comment]
@ronMilne , https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by GreyCat** [comment]
Slightly simpler repro:

Input: `0b11111000`

KSY:

```yaml
seq:
  - id: first_5_bits
    type: b5
instances:
  repro:
    pos: 0
    type: b1
```

`first_5_bits` will be always `0b11111`. `repro` should be `1` (as it shall reset everything to bit \#0 + byte \#0), but in current broken state it will be `0` (as it will seek to byte \#0, but not to bit \#0).

**Comment by GreyCat** [comment]
Another related problem: instances should memorize & restore bit position. I.e.:

```yaml
seq:
  - id: a
    type: b4
  - id: b
    type: b4
    if: c >= 0 # always true, but invokes `c` before `b`
instances:
  c:
    pos: 1
    type: b2
```

Expected:

```
aaaa bbbb|cc.. ....
```

However, actual implementation will do:

```
aaaa ccbb|bb.. ....
```
