### ISSUE TITLE
Java: switching over nullable values may trigger NPE

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#568]
Follow up for https://github.com/kaitai-io/kaitai_struct/issues/300 — original issue mentioned case of enum being null and then being switched over. The problem is actually much deeper and, currently, it's pretty hard to solve without major reworking of expression type derivation to include nullability tracking.

Java allows switching over `String` or boxed integers (like `Integer`, `Long`), which can be null due to:

* `if` failing
* `type` switching match failed without default case
* something else?

A very simple repro:

```yaml
seq:
  - id: always_null
    type: u1
    if: false
  - id: trigger_npe
    type:
      switch-on: always_null
      cases:
        1: one
        _: two
```

This issue will acts as a reminder, may be we'll return to it one day.
