### ISSUE TITLE
`meta/tags`: add multiple tags

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#572]
Our formats repo grows (it's 134 formats already, as of now, and a huge backlog of PRs to be merged), and it gets hard to navigate it. Current model uses simple one-level tree-like structure, like this:

* archive
* cad
* common
* database
* executable
* ...

However, it gets progressively hard to decide which category to stick a particular format to. For example:

* "windows_evt_log" is *both* a "log" and Windows-specific format (so it should be also in "windows")
* "ds_store" should belong to both "macos" (as it is MacOS-specific) and probably "filesystem" (as it is part of filesystem harness)
* "efivar_signature_list" should be both in "security" (as these are security-related signatures) and in "firmware" (as this is part of UEFI firmware format)
* there's no way to find all files that hold 3D models: part of them are in "media" ("blender_blend", "stl"), part of them are in "game" ("quake_mdl"), etc.

So, the proposal is to add a field like `meta/tags` which will allow to put multiple arbitrary categories / keywords into a file. For example:

```yaml
meta:
  id: efivar_signature_list
  tags:
    - security
    - firmware
    - eufi
```

We'll parse these in formats HTML generators and make a better navigable website. The tags themselves could form a navigable tree or graph, i.e.

```
os:
  freebsd: {}
  linux: {}
  macos: {}
  windows: {}
media:
  image:
    bitmap: {}
    vector: {}
  video: {}
  3d_model: {}
firmware:
  uefi: {}
```
