### ISSUE TITLE
Custom integer formats: bit segments split across bytes, VLQ (variable-length quantities), etc

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#58]
An companion issue to #9: we'll discuss stuff related to very custom integers formats, reading and writing of which will feature some combining / splitting operations. I'll try to keep track of real-life use cases here.

## Basic [VLQ](https://en.wikipedia.org/wiki/Variable-length_quantity)

Every byte:

* bit 7 - continuation flag
* bit [0:6] - number body

### Reading

```java
int t, continuation, body, result;
do {
    t = _io.readU1();
    continuation = t & 0b10000000;
    body = t & 0b01111111;
    result = (result << 7) | body;
} while (continuation != 0);
```

### Writing

TODO

## EDID

* Byte 0: x[0:7]
* Byte 1: y[0:7]
* Byte 2: x[8:11] and y[8:11]

**Comment by rpavlik** [comment]
For a better reference on the stuff in EDID: see the Chromaticity coordinates in this format description: https://en.wikipedia.org/wiki/Extended_Display_Identification_Data#EDID_1.3_data_format  as well as the detailed timing descriptors (which is what I had in mind when I wrote the example)

**Comment by koczkatamas** [comment]
If we want to prepare the format for serialization then it would be preferable if the .ksy would contain the continuation bit(s) as a "terminator" (like we use them for strings).

So if the "101" bit string is the terminator then while parsing peek into the next 3 bits and stop if we found them. And while serialization just simply put 101 into the output stream. (101 could be even result of an expression.)

Although from the implementation point of view I don't know whether we can allow ourselves this luxurious functionality or not as this can be a niche use-case...

From optimization point of view maybe we can automatically detect and switch between the generic implementation (supports more use-cases) and the stricter, but faster one (like the reader code in @GreyCat original post).

**Comment by kenoph** [comment]
I was translating radare2's IDA Pro .sig file parsing code to a kaitai struct (I wanted to try out the project and I also need to actually do it for a project of mine).

The code has stuff like:
```C
static ut32 read_multiple_bytes(RBuffer *b) {
	ut32 r = read_byte (b);
	if ((r & 0x80) != 0x80) {
		return r;
	}
	if ((r & 0xc0) != 0xc0) {
		return ((r & 0x7f) << 8) + read_byte (b);
	}
	if ((r & 0xe0) != 0xe0) {
		r = ((r & 0x3f) << 24) + (read_byte (b) << 16);
		r += read_short (b);
		return r;
	}
	return read_word (b);
}
```

Which basically encodes the number of bytes to be read in the first consecutive bits of the first byte.

So, I'm basically switching back to writing a custom parser in python, but I guess it would be nice to eventually have enough expressiveness to define such things in kaitai.

**Comment by koczkatamas** [comment]
Kaitai is capable of parsing such a structure, just not as nice and performant as it could be.

If I am not wrong the following parsing definition is equivalent with the `read_multiple_bytes` method.

```yaml
meta:
  id: read_multiple_bytes
seq:
  - id: b1
    type: u1
  - id: b2
    type: u1
    if: len >= 1
  - id: b3
    type: u1
    if: len >= 2
  - id: b4
    type: u1
    if: len >= 3
  - id: b5
    type: u1
    if: len >= 4
instances:
  len:
    value: >
      (b1 & 0x80) != 0x80 ? 1 :
      (b1 & 0xc0) != 0xc0 ? 2 :
      (b1 & 0xe0) != 0xe0 ? 3 : 4
    -webide-parse-mode: eager
  value:
    value: >
      len == 1 ? b1 :
      len == 2 ? ((b1 & 0x7f) << 8) + b2 :
      len == 3 ? ((b1 & 0x3f) << 24) + (b2 << 16) + (b3 << 8) + b4 :
      (b2 << 24) + (b3 << 16) + (b4 << 8) + b5
    -webide-parse-mode: eager
```

**Comment by kenoph** [comment]
Wow, that actually seems to work. I was trying different combinations of things but the compiler kept complaining because I could not perform arithmetic on bits / switched types / etc.

The `len` trick is pretty clever, thanks mate. Performance should not be that big of an issue, I think. Looking forward to publishing my complete `.ksy` soon.

**Comment by GreyCat** [comment]
I believe that here:

```yaml
seq:
  - id: b1
    type: u1
  - id: b2
    type: u1
    if: len >= 1
```

You probably need to use `len > 1`, `len > 2`, etc, everywhere, as it turns out that this type eats up extra byte into `b2` and does not actually use it. Actually, there are 4 cases here, determined by first byte:

* `0b0xxx_xxxx` => total length is 1 (byte)
* `0b10xx_xxxx` => total length is 2 (byte + byte)
* `0b110x_xxxx` => total length is 4 (byte + byte + short)
* `0b1110_xxxx` => total length is 5 (byte + word)

One can replace all that `b2`, `b3` with `if: len ...` with just an array:

```yaml
seq:
  - id: b1
    type: u1
  - id: bytes
    repeat: expr
    repeat-expr: len - 1 # or just generate 0-based len
```

If we'd implement #112, then probably it would be even easier to parse, as one could just use something like:

```yaml
seq:
  - id: b1
    type: u1
  - id: extra
    bit-size: (len - 1) * 8
```

and use `extra.to_i` as ready-made integer.

**Comment by davidhicks** [comment]
I was working on a type for the variable length integer used in the 7zip (.7z) file format, but it's a little different to the scheme mentioned above. So far I have this implementation developed:

```
types:
  uint64:
    seq:
      - id: b1
        type: u1
      - id: b2
        type: u1
        if: len >= 2
      - id: b3
        type: u1
        if: len >= 3
      - id: b4
        type: u1
        if: len >= 4
      - id: b5
        type: u1
        if: len >= 5
      - id: b6
        type: u1
        if: len >= 6
      - id: b7
        type: u1
        if: len >= 7
      - id: b8
        type: u1
        if: len >= 8
    instances:
      len:
        value: >
          (b1 & 0x80) == 0x00 ? 1 :
          (b1 & 0xC0) == 0x80 ? 2 :
          (b1 & 0xE0) == 0xC0 ? 3 :
          (b1 & 0xF0) == 0xE0 ? 4 :
          (b1 & 0xF8) == 0xF0 ? 5 :
          (b1 & 0xFC) == 0xF8 ? 6 :
          (b1 & 0xFE) == 0xFC ? 7 : 8
      value:
        value: >
          len == 1 ? b1 :
          len == 2 ? ((b1 & 0x7F) << 8) + b2 :
          len == 3 ? ((b1 & 0x3F) << 16) + (b2 | (b3 << 8)):
          len == 4 ? ((b1 & 0x0F) << 24) + (b2 | (b3 << 8) | (b4 << 16)):
          len == 5 ? ((b1 & 0x07) << 36) + (b2 | (b3 << 8) | (b4 << 16) | (b5 << 24)):
          len == 6 ? ((b1 & 0x03) << 48) + (b2 | (b3 << 8) | (b4 << 16) | (b5 << 24) | (b6 << 36)):
          len == 7 ? (b2 | (b3 << 8) | (b4 << 16) | (b5 << 24) | (b6 << 36) | (b7 << 48)) :
                     (b2 | (b3 << 8) | (b4 << 16) | (b5 << 24) | (b6 << 36) | (b7 << 48) | (b8 << 56))
```

If byte arrays had a `to_i` method, a simpler format would be possible:
```
types:
  uint64_v2:
    seq:
      - id: first_byte
        type: u1
      - id: extra_bytes
        type: u1
        repeat: expr
        repeat-expr: len - 1
    instances:
      len:
        value: >
          (first_byte & 0x80) == 0x00 ? 1 :
          (first_byte & 0xC0) == 0x80 ? 2 :
          (first_byte & 0xE0) == 0xC0 ? 3 :
          (first_byte & 0xF0) == 0xE0 ? 4 :
          (first_byte & 0xF8) == 0xF0 ? 5 :
          (first_byte & 0xFC) == 0xF8 ? 6 :
          (first_byte & 0xFE) == 0xFC ? 7 : 8
      first_byte_value:
        value: >
          len == 1 ? 0 :
          len == 2 ? ((first_byte & 0x7F) << 8) :
          len == 3 ? ((first_byte & 0x3F) << 16) :
          len == 4 ? ((first_byte & 0x0F) << 24) :
          len == 5 ? ((first_byte & 0x07) << 36) :
          len == 6 ? ((first_byte & 0x03) << 48) : 0
      value:
        value: first_byte_value + extra_bytes.to_i
```

Specification:
```
UINT64 means real UINT64 encoded with the following scheme:

  Size of encoding sequence depends from first byte:
  First_Byte  Extra_Bytes        Value
  (binary)   
  0xxxxxxx               : ( xxxxxxx           )
  10xxxxxx    BYTE y[1]  : (  xxxxxx << (8 * 1)) + y
  110xxxxx    BYTE y[2]  : (   xxxxx << (8 * 2)) + y
  ...
  1111110x    BYTE y[6]  : (       x << (8 * 6)) + y
  11111110    BYTE y[7]  :                         y
  11111111    BYTE y[8]  :                         y
```

Reference implementation (C):
```
static SRes SkipBitUi32s(CSzData *sd, UInt32 numItems)
{
  Byte allAreDefined;
  UInt32 numDefined = numItems;
  SZ_READ_BYTE(allAreDefined);
  if (!allAreDefined)
  {
    size_t numBytes = (numItems + 7) >> 3;
    if (numBytes > sd->Size)
      return SZ_ERROR_ARCHIVE;
    numDefined = CountDefinedBits(sd->Data, numItems);
    SKIP_DATA(sd, numBytes);
  }
  if (numDefined > (sd->Size >> 2))
    return SZ_ERROR_ARCHIVE;
  SKIP_DATA(sd, (size_t)numDefined * 4);
  return SZ_OK;
}
```

Other implementation (hachoir/python3):
```
class SZUInt64(Field):
    """
    Variable length UInt64, where the first byte gives both the number of bytes
    needed and the upper byte value.
    """
    def __init__(self, parent, name, max_size=None, description=None):
        Field.__init__(self, parent, name, size=8, description=description)
        value = 0
        addr = self.absolute_address
        mask = 0x80
        firstByte = parent.stream.readBits(addr, 8, LITTLE_ENDIAN)
        for i in xrange(8):
            addr += 8
            if not (firstByte & mask):
                value += ((firstByte & (mask-1)) << (8*i))
                break
            value |= (parent.stream.readBits(addr, 8, LITTLE_ENDIAN) << (8*i))
            mask >>= 1
            self._size += 8
        self.createValue = lambda: value
```

**Comment by GreyCat** [comment]
This is not generally how you want to parse the byte array:

```yaml
      - id: extra_bytes
        type: u1
        repeat: expr
        repeat-expr: len - 1
```

You'll end up with "true" array of u1 (i.e. in Java that would be something like `ArrayList<Byte>`), not byte array (`byte[]`). This one is probably better:

```yaml
      - id: extra_bytes
        size: len - 1
```

True arrays will probably never get `to_i` method, as it's kind of pointless for an array of strings, for example, or array of some custom type objects. Implementing `to_i` for byte arrays is possible, but you'll need some way to specify endianness and signed/unsigned type. An alternative approach here might be actually introduction of some integer-of-given-size type. Something like:

```yaml
      - id: extra_bytes
        type: ube
        size: len - 1
```

It's effectively like `type: u(len - 1)be`. It will actually help with the previous case mentioned by @kenoph as well.
