### ISSUE TITLE
Need to specify size in bits

### ISSUE THREAD

**Issue by ncihnegn** [kaitai-io/kaitai_struct#582]
Like:
```yaml
  data:
    seq:
      - id: header
        type: b4
      - id: a
        size: b4
        type: bits4
  bits4:
    seq:
      - id: bits4
        type:
        switch-on: _parent.header
        ....
```
