### ISSUE TITLE
How to dynamically switch type based on a condition?

### ISSUE THREAD

**Issue by takase1121** [kaitai-io/kaitai_struct#584]
```ksy
  - id: ar
    type: '_parent.osu_ver < 20140609 ? u1 : f4'
  - id: cs
    type: '_parent.osu_ver < 20140609 ? u1 : f4'
  - id: hpd
    type: '_parent.osu_ver < 20140609 ? u1 : f4'
  - id: od
    type: '_parent.osu_ver < 20140609 ? u1 : f4'
```

This will not work as kaitai parses that as the `type` without checking it. Case does not work (at least in my case) when used to compare values. What else can I do to achieve the same effect?

**Comment by KOLANICH** [comment]
Please NEVER post source code as screenshots 👿👿👿👿.

>Case does not work (at least in my case) when used to compare values.

What is your code? Can `osu_ver` be uniquely addressed from `_root`?

Also, as you have the same selection of the type in each field, it is obvious you should encapsulate it into a type.

**Comment by takase1121** [comment]
> What is your code? Can osu_ver be uniquely addressed from _root?

```yaml
type:
  switch-on: _unplayed
  cases:
    _parent.osu_ver < 20140609: u1
    _: f4
```
I remembered its something like this. `_unplayed` is simply another random `b1` so I can somehow do the comparison

> Also, as you have the same selection of the type in each field, it is obvious you should encapsulate it into a type.

I don't really understand it. I just begin using kaitai last few hours ago

**Comment by takase1121** [comment]
oh and also I think i tried using `_root` but it doesn't work

**Comment by dgelessus** [comment]
@takase1121 I would suggest writing the condition like this:

```yaml
type:
  switch-on: _parent.osu_ver < 20140609
  cases:
    true: u1
    false: f4
```

That way you don't have to use another unrelated field in the condition.

I think @KOLANICH's suggestion is that you should define the `u1`/`f4` switch as a separate type, so that you don't have to copy the switch block every time. Something like this:

```yaml
seq:
  - id: cs
    type: version_dependent_number
  - id: hpd
    type: version_dependent_number
  - id: od
    type: version_dependent_number
types:
  version_dependent_number:
    seq:
      - id: value
        type:
          switch-on: _parent.osu_ver < 20140609
          cases:
            true: u1
            false: f4
```

**Comment by KOLANICH** [comment]
As I understand, younare implementing https://osu.ppy.sh/help/wiki/osu!_File_Formats/Db_(file_format)


So
```yaml
seq:
  - id: osu_ver
    type: u4
 ....
instances:
  float_or_int_selector:
    value: osu_ver < 20140609
types:
  float_or_int:
    seq:
      - id: value
        type:
          switch-on: _root.float_or_int_selector
          cases:
            true: u1
            false: f4
```

**Comment by takase1121** [comment]
Oh my. I must be a mega idiot to not realize I can do that

**Comment by takase1121** [comment]
> As I understand, younare implementing https://osu.ppy.sh/help/wiki/osu!_File_Formats/Db_(file_format)

Yes

**Comment by takase1121** [comment]
@dgelessus I tried your method and this happens when I run the script through `ksv`
```
Compilation OK
... processing main.ksy 0
Error: [{"file"=>"main.ksy", "path"=>[], "message"=>"called attribute 'osu_ver' on generic struct expression 'Name(identifier(_parent))'"}]
Fatal errors encountered, cannot continue```

**Comment by takase1121** [comment]
@KOLANICH I have the `Beatmap` object in a seperate file. Where should I put this?

**Comment by KOLANICH** [comment]
I don't understand the question. It is a module you can use in an own program.

**Comment by takase1121** [comment]
@KOLANICH sorry i wasnt clear
I mean I have a file called `Beatmap.ksy` where I handle the `Beatmap` object 
![image](https://user-images.githubusercontent.com/20792268/58372413-60853f80-7f4f-11e9-9adc-bbfc2bc8e112.png)

and another file called `main.ksy` that handles the whole target file as a whole.
Now which file should I put the code you gave into?

**Comment by KOLANICH** [comment]
1 clone https://github.com/kaitai-io/kaitai_struct_formats
2 create a branch `osu` and switch to it
3 go to `game` dir and create an `osu` dir
4. dump your files there and give them names matching their ids
5. send a PR to ksf.

**Comment by takase1121** [comment]
should i fork?

**Comment by KOLANICH** [comment]
yes

**Comment by takase1121** [comment]
If i understood what you said correctly, this should be it
https://github.com/kaitai-io/kaitai_struct_formats/pull/157

**Comment by KOLANICH** [comment]
Yeah, let[s have the further discussion in that PR.

**Comment by dgelessus** [comment]
> `osu_ver` is in `main.ksy` and the logic I posted is in `Beatmap.ksy`

I think this structure will not work here. `_parent` and `_root` will always stay inside the current ksy file, so you cannot use `_parent` in Beatmap.ksy to access fields from main.ksy. I think in this case you need to merge Beatmap.ksy into main.ksy (i. e. make `beatmap` a type inside main.ksy), then you can access fields "above" `beatmap` using `_parent` and `_root`.

**Comment by takase1121** [comment]
@dgelessus 
that is sure a pain. I will do that instead

**Comment by ams-tschoening** [comment]
> I think in this case you need to merge Beatmap.ksy into main.ksy (i. e. make beatmap a type inside main.ksy), then you can access fields "above" beatmap using _parent and _root.

[Parametric types](https://doc.kaitai.io/user_guide.html#param-types) might be a solution as well, those are designed to forward types to types and circumvent the concepts of implicit `_parent` and `_root` implemented currently.

https://github.com/kaitai-io/kaitai_struct/issues/275#issuecomment-368820503

**Comment by milahu** [comment]
> source code as screenshots

```yaml
- id: xx
  type: '_parent.osu_ver < 20140609 ? u1 : f4'

- id: cs
  type: '_parent.osu_ver < 20140609 ? u1 : f4'

- id: hpd
  type: '_parent.osu_ver < 20140609 ? u1 : f4'

- id: od
  type: '_parent.osu_ver < 20140609 ? u1 : f4'
```

also title is horrible, should be "how to use dynamic type based on other value"
