### ISSUE TITLE
Is exist way to repeat pair of fields without creating new type?

### ISSUE THREAD

**Issue by jaroslaw-wieczorek** [kaitai-io/kaitai_struct#586]
I mean repeating two fields in order: index, value without creating a new type as follows:
```yaml
seq:
    - id: qualifier_field
      type: qualifier_field_type

    - id: num_of_items
      type: u2le
    
    - id: points
      type: point_type
      
      repeat: expr
      repeat-expr: num_of_items
```
where point_type is:
```yaml 
  point_type:
    seq:
      - id: index
        type: u2
      - id: value
        type: u4
```
Maybe it would be a good idea to create a repeat loop start and end character?
For example:
```yaml
seq:
    - id: qualifier_field
      type: qualifier_field_type

    - id: num_of_items
      type: u2le
    loop_inside:
     - id: index
        type: u2
     - id: value
        type: u4
    end_of_loop_inside:   
      repeat: expr
      repeat-expr: num_of_items

```

**Comment by jaroslaw-wieczorek** [comment]
I ask because I have many different data types with several fields, and subsequences. Such an approach would allow to emilineate the creation of redundant data types.

**Comment by GreyCat** [comment]
There is no way to do that, and, by definition, new type *is* the way to do it. The syntax you're proposing is not a valid YAML.

What do you mean by "redundant data types" — how comes they're redundant, if they're being used and referenced?

**Comment by jaroslaw-wieczorek** [comment]
> There is no way to do that, and, by definition, new type _is_ the way to do it. The syntax you're proposing is not a valid YAML.
> 
> What do you mean by "redundant data types" — how comes they're redundant, if they're being used and referenced?

The use of the word redundant may have been wrong.
I have 80 data types that have a specific structure. Each of them can be repeated in the stream many times. The problem is that while repeating each of these objects can be preceded by an index or not. 
Going this way I have to create a type for the data and then an additional type that contains the index and this already created data type. To replicate it in stream with index. 

I try to avoid executive hundreds of ```if``` statements or creating many subtypes differenced, by one additional field.

```yaml
  point_type:
    seq:
      - id: index
        type: u2
        if: _parent.index_exist == true
      - id: value
        type: u4

```
Of course i can check if index shouldbe added or not in each repeat. In this way  ```if``` statement will be execute e.g. 60 times.
