### ISSUE TITLE
Is it possible to use repeat-expr with switch-on? 

### ISSUE THREAD

**Issue by jaroslaw-wieczorek** [kaitai-io/kaitai_struct#587]
I think with a good feature, it would be possible to use a switch-on construction with a repeat-expr loop.
```yaml
type_a:  
  seq:
    - id: qualifier_field
      type: qualifier_field_type
    
    - id: num_of_items
      type:
        switch-on: qualifier_field.range_code.to_i
        cases:
          0 : range_start_end_8bit_indexes # 2-two 8bit indexes
          1 : range_start_end_16bit_indexes #2-two 16bit indexes
          7 : u1 # 8bit value from stream
          8 : u2 # 16bit value from stream
          9 : u4  # 32bit value from stream
    - id: points
      type: point_binary_input
      repeat-expr: 
          switch-on: qualifier_field.range_code.to_i
          cases:
             0 : num_of_items.end_idx.to_i + 1 - num_of_items.start_idx.to_i 
             1 : num_of_items.end_idx.to_i + 1 - num_of_items.start_idx.to_i 
             7 : num_of_items.to_i
             8 : num_of_items.to_i
             9 : num_of_items.to_i
```

**Comment by dgelessus** [comment]
In this specific case, you can use a conditional expression:

```yaml
repeat-expr: |
  qualifier_field.range_code.to_i <= 1
  ? num_of_items.end_idx.to_i + 1 - num_of_items.start_idx.to_i
  : num_of_items.to_i
```

It could be useful to have something similar to `switch-on` in the KSY expression language, but it would have to use different syntax, because KSY expressions are written in plain text and not as YAML objects.

**Comment by dgelessus** [comment]
In this specific case, you can use a conditional expression:

```yaml
repeat-expr: |
  qualifier_field.range_code.to_i <= 1
  ? num_of_items.end_idx.to_i + 1 - num_of_items.start_idx.to_i
  : num_of_items.to_i
```

It could be useful to have something similar to `switch-on` in the KSY expression language, but it would have to use different syntax, because KSY expressions are written in plain text and not as YAML objects.

**Comment by jaroslaw-wieczorek** [comment]
Something is wrong... :/   
``` yaml data
type_a:
    seq:``` yaml data
    - id: qualifier_field
      type: qualifier_field_type

    - id: num_of_items
      type:
        switch-on: qualifier_field.range_code.to_i
        cases:
          0 : start_end_index_8bit
          1 : start_end_index_16bit
          7 : u1
          8 : u2le
          9 : u4le

    - id: points
      type: point_analog_change_event
      
      repeat: expr
      repeat-expr: | 
        qualifier_field.range_code.to_i == 0 or  
        qualifier_field.range_code.to_i == 1
        ? 1 : num_of_items
```
```bash
Parse error: undefined
Call stack: undefined io.kaitai.struct.format.YAMLParseException: /types/type_a/seq/2/repeat-expr: invalid type: expected integer, got AnyType
```

```yaml
type_a:
    seq:
    - id: qualifier_field
      type: qualifier_field_type

    - id: num_of_items
      type:
        switch-on: qualifier_field.range_code.to_i
        cases:
          0 : start_end_index_8bit
          1 : start_end_index_16bit
          7 : u1
          8 : u2le
          9 : u4le

    - id: points
      type: point_analog_change_event
      
      repeat: expr
      repeat-expr: | 
        qualifier_field.range_code.to_i == 0 or  
        qualifier_field.range_code.to_i == 1
        ? num_of_items.end_idx.to_i + 1 - num_of_items.start_idx.to_i
        : num_of_items
```


```bash
Parse error: undefined
Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: (main): /types/type_a/seq/2/repeat-expr: don't know how to call anything on AnyType
```

**Comment by GreyCat** [comment]
It's not exactly impossible, but I'd rather not do that for several reasons:

* This functionality is already supported using ternary operator in expressions (i.e. `a ? b : c`), as @dgelessus illustrated.
* This mixes YAML syntax into KS expression language. Existing `type` => `switch-on` => `cases` functionality has nothing to do with it, it works in KS types domain. Currently, KS expression language is more or less agnostic from the rest of KS framework related to binary structure parsing.
* Switching types by itself is already a pretty powerful solution. With type switching, you're introducing clear declarative notion of *what* is the underlying data structure. With expression switching, it's much more obscure (again, this is more about "how", not "what").
* Proposed syntax is not very flexible: it does not allow nesting or some kind of interoperability with string-based expression syntax, it suffers from all the existing limitations of case constructions (i.e. no range support, no simple multiple keys per value support, etc).

**Comment by GreyCat** [comment]
@jaroslaw-wieczorek 

> /types/type_a/seq/2/repeat-expr: don't know how to call anything on AnyType

Your `num_of_items` is AnyType. That implies that you can't call anything on this. You're asking for `num_of_items.end_idx`, but what if `num_of_items` is actually an integer — how do you want compiler to behave in that situation?

**Comment by jaroslaw-wieczorek** [comment]
Value of field 'num_of_items'  and his type depend on  qualifier_field.range_code field. 

If qualifier_field.range_code.to_i == 0 or 1, 
then the num_of_items field contains two indices, in the first case 8-bit indexes in the second 16-bit indexes (start_idx and end_idx). From these indexes I calculate how many objects I have to decode.
end_idx - start_idx + 1 

If qualifier_field.range_code.to_i == 7, 8 or 9 then there is simply counte (integer number): 
8-bit (value 7), 16-bit (value 8) or 32-bit (value 9)  (integer).

**Comment by GreyCat** [comment]
@jaroslaw-wieczorek, this coercion is how statically typed languages (i.e. C++, Java, C#, etc) work, we can't do anything about that. Do be able to run `.end_idx` on a certain value, that value needs to be of type that supports such a method.

If you're coercing several different types using switch type, from consumer's perspective, that will be a generic type (either AnyType of KaitaiStructType) — that means that statically typed language compiler (i.e. a C++ or Java compiler) will have no information on how to call any arbitrary method on that.

If you have some external information of what that switch type will be exactly (e.g. based on some conditions / checks you do, or just some extra information on formats), you can use type casting to enforce that type:

```yaml
      repeat-expr: | 
        (qualifier_field.range_code.to_i == 0) ?
        (num_of_items.as<start_end_index_8bit>.end_idx.to_i + 1 - num_of_items.as<start_end_index_8bit>.start_idx.to_i) :
        (qualifier_field.range_code.to_i == 1) ?
        (num_of_items.as<start_end_index_16bit>.end_idx.to_i + 1 - num_of_items.as<start_end_index_16bit>.start_idx.to_i) :
        num_of_items.as<u4>
```

However, if I were you I'd really try to rethink that whole structure or at least introduce some helper methods (i.e. wrapping that `end_idx + 1 - start_idx` semantics into some instance, etc).

**Comment by jaroslaw-wieczorek** [comment]
I thought it was working already, but I'm still getting errors..

type_a: 
```yaml
type_a:
    seq:
    - id: qualifier_field
      type: qualifier_field_type

    - id: num_of_items
      type:
        switch-on: qualifier_field.range_code.to_i
        cases:
          0 : start_end_index_8bit
          1 : start_end_index_16bit
          _ : u4le # u4 # 

    - id: points
      type: point_analog_change_event
      repeat: expr
      repeat-expr: | 
        (qualifier_field.range_code.to_i == 0) ?
        (num_of_items.as<start_end_index_8bit>.end_idx.to_i + 1 - num_of_items.as<start_end_index_8bit>.start_idx.to_i) :
        (qualifier_field.range_code.to_i == 1) ?
        (num_of_items.as<start_end_index_16bit>.end_idx.to_i + 1 - num_of_items.as<start_end_index_16bit>.start_idx.to_i) :
        num_of_items.as<u4>
```
If start_end_index_8bit - use type b8:
```yaml

  start_end_index_8bit:
    seq:
      - id: start_idx
        type: b8
      - id: end_idx
        type: b8

```
I get this error:
```bash
Parse error: undefined
Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: (main): /types/type_a/seq/2/repeat-expr: called invalid attribute 'to_i' on expression of type BitsType(8)
```

after remove ```to_i```:
```bash
Parse error: undefined
Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: (main): /types/type_a/seq/2/repeat-expr: unable to find type 'u4', searching from extract_data::type_a
```

If start_end_index_8bit  - use type u1 create the same errors like b8

```yaml

  start_end_index_8bit:
    seq:
      - id: start_idx
        type: u1
      - id: end_idx
        type: u1
```

```bash
Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: (main): /types/type_a/seq/2/repeat-expr: unable to find type 'u4', searching from extract_data::type_a
```


If start_end_index_8bit  - use ```size: 1```:

```yaml

  start_end_index_8bit:
    seq:
      - id: start_idx
        size: 1
      - id: end_idx
        size: 1
```


added ```to_i```
```bash
Parse error: undefined
Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: (main): /types/type_a/seq/2/repeat-expr: don't know how to call anything on BytesLimitType(IntNum(1),None,false,None,None)
```

after remove ```to_i```:
```bash
Parse error: undefined
Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: (main): /types/type_a/seq/2/repeat-expr: can't apply operator Add to BytesLimitType(IntNum(1),None,false,None,None) and Int1Type(true)
```

**Comment by GreyCat** [comment]
> called invalid attribute 'to_i' on expression of type BitsType(8)

This is an error, it shouldn't be that way. I've created #588 to fix it. However, of course, that `to_i` is not needed and effectively is a no-op.

> Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: (main): /types/type_a/seq/2/repeat-expr: unable to find type 'u4', searching from extract_data::type_a

I'm actually not sure if our current implementation allows typecasting to primitive types. If you get the same error with the latest unstable build, then likely we'll need to fix that too.

As a simple workaround, you can avoid using primitive types like `uX` in cases directly, but rather use a wrapper like that:

```yaml
types:
  my_u4:
    seq:
      - id: value
        type: u4
```

and, subsequently, last line would become `num_of_items.as<my_u4>.value`.

**Comment by jaroslaw-wieczorek** [comment]
I've tried different approaches, but I still get parsing errors.. :( 

My types: 
```yaml
types:
 tu1:
    seq:
      - id: value
        type: u1
 tu2:
    seq:
      - id: value
        type: u2
 tu4:
    seq:
      - id: value
        type: u4
 tu5:
    seq:
      - id: value
        type: u5

start_end_index_8bit:
    seq:
      - id: start_idx
        type: tu1  # tu1 
      - id: end_idx 
        type: tu1
```

My code:
```yaml
- id: points
  type: point_analog_change_event
  if: qualifier_field.range_code.to_i != 6
  repeat: expr
  repeat-expr: | 
     (qualifier_field.range_code.to_i == 0) ?
     (num_of_items.as<start_end_index_8bit>.end_idx.value + 1 - num_of_items.as<start_end_index_8bit>.start_idx.value):
     (num_of_items.as<tu4>.value) 
```




**Error 1:**
**When ```qualifier_field.range_code.to_i  == 0 ```**
```yaml
- id: points
  type: point_analog_change_event
  if: qualifier_field.range_code.to_i != 6
  repeat: expr
  repeat-expr: | 
     (qualifier_field.range_code.to_i == 0) ?
     (num_of_items.as<start_end_index_8bit>.end_idx.value + 1 - num_of_items.as<start_end_index_8bit>.start_idx.value):
     (num_of_items.as<tu4>.value) 
```

Result:
```bash
Parse error: undefined
Call stack: undefined TypeError: this.numOfItems.endIdx is undefined
```

The same error is received when I use  ```.as<tu1>``` on ```start_idx``` and ```end_idx```.
```yaml
- id: points
  type: point_analog_change_event
  if: qualifier_field.range_code.to_i != 6
  repeat: expr
  repeat-expr: | 
    (qualifier_field.range_code.to_i == 0) ?
    (num_of_items.as<start_end_index_8bit>.end_idx.as<tu1>.value + 1 - num_of_items.as<start_end_index_8bit>.start_idx.as<tu1>.value):
    (num_of_items.as<tu4>.value) 
```

Result:
```bash
Parse error: undefined
Call stack: undefined TypeError: this.numOfItems.endIdx is undefined
```



**Error 2 - without error:**
When ``` qualifier_field.range_code.to_i != 0 ```
```yaml
  repeat-expr: | 
    (qualifier_field.range_code.to_i == 0) ?
    (num_of_items.as<start_end_index_8bit>.end_idx.as<tu1>.value + 1 - num_of_items.as<start_end_index_8bit>.start_idx.as<tu1>.value):
    (num_of_items.as<tu4>.value) 
```
Result: 
Parsing without errors, but not repeating the structure. The number of elements should be 60 but gets 0:
![obraz](https://user-images.githubusercontent.com/19189927/58811176-9d23fb80-861f-11e9-8b4e-e645f67eddd2.png)


**Error 3:**
Try use ``` num_of_items.as<tu4>.value.to_i ```

```yaml
  repeat-expr: | 
    (qualifier_field.range_code.to_i == 0) ?
    (num_of_items.as<start_end_index_8bit>.end_idx.as<tu1>.value + 1 - num_of_items.as<start_end_index_8bit>.start_idx.as<tu1>.value):
    (num_of_items.as<tu4>.value.to_i) 
```
Result:
Casting this field with `to_i` returns an error:
```bash 
Parse error: undefined
Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: (main): /types/type_a/seq/2/repeat-expr: called invalid attribute 'to_i' on expression of type IntMultiType(false,Width4,Some(LittleEndian))
```
