### ISSUE TITLE
Why got error: EOFError: requested 1 bytes, but only 0 bytes available

### ISSUE THREAD

**Issue by jaroslaw-wieczorek** [kaitai-io/kaitai_struct#592]
I got that error:
```bash
Parse error: undefined
Call stack: undefined EOFError: requested 1 bytes, but only 0 bytes available
```

When I moved field ```value``` from ```object_quality_type``` to ```object_1```.
In each situation whole type ```object_1``` has size == ```b8```.

```yaml
seq:
   - id: new
     type: object_1
      repeat: eos

types:
   object_1:
      seq:
         - id: quality
           type: object_quality_type

    object_quality_type:
        seq:
          - id: value
            type: b1
          - id: reserved
            type: b1 
          - id: filter
            type: b1
          - id: force
            type: b1
          - id: remote
            type: b1
          - id: comm
            type: b1 
          - id: restart
            type: b1
          - id: online
            type: b1
```

With error:
```yaml
seq:
   - id: new
     type: object_1
      repeat: eos

types:
   object_1:
      seq:
         - id: value
           type: b1
         - id: quality
           type: object_quality_type

    object_quality_type:
        seq:
          - id: reserved
            type: b1 
          - id: filter
            type: b1
          - id: force
            type: b1
          - id: remote
            type: b1
          - id: comm
            type: b1 
          - id: restart
            type: b1
          - id: online
            type: b1
```
