### ISSUE TITLE
"Error - can't combine output types" when using ternary operation on two different types 

### ISSUE THREAD

**Issue by ProvidenceXz** [kaitai-io/kaitai_struct#593]
How to recreate:
```
instances:
  foo:
    value: true
  bar:
    if: foo == true
    value: output
    enum: bar_types
  baz:
    if: foo == false
    value: output
    enum: baz_types
  qux:
    value: 'foo ? bar : baz'
```
`bar` and `baz` have the same value, but I intend to apply different sets of enum based on `foo`. One of the two fields will always be empty this way. The purpose of `qux` is to combine them to one field so that it is always populated for easier access.

Since `bar` and `baz` are different in types(enums), an error will be thrown when trying to use this ternary operation to combine two fields to one:

`can't combine output types: EnumType(<bar_type>) vs EnumType(<baz_type>)`
