### ISSUE TITLE
Support bit field enums

### ISSUE THREAD

**Issue by ismell** [kaitai-io/kaitai_struct#597]
I would like the ability to annotate an enum as being a [bit field](https://en.wikipedia.org/wiki/Bit_field). This way I can have an enum that is a bit field and apply it to an integer type.

i.e.,
```yaml
flags:
  myflags:
    1: bit_1
    2: bit_2
    4: bit_3
    8: bit_4

seq:
  - id: some_field
    type: u4
    flag: myflags
```

So if I was parsing a value `0x5`, `some_field` would have the value `bit_1` and `bit_3`.

Java has this concept as [EnumSet](https://docs.oracle.com/javase/7/docs/api/java/util/EnumSet.html), C# has it as [FlagsAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=netframework-4.8), and C++ has enums.

**Comment by GreyCat** [comment]
Normal way we specify bit flag sets is using lots of `type: b1` in sequence:

```yaml
seq:
  - id: some_field
    size: 4
    type: myflags
types:
  myflags:
    seq:
      - id: reserved
        type: b28 # skip first 28 bits
      - id: bit_4
        type: b1
      - id: bit_3
        type: b1
      - id: bit_2
        type: b1
      - id: bit_1
        type: b1
```

This provides you an API like `someField().bit4()`, which returns true or false value.

That said, fixed bitset flags implemented as enums might be interesting idea to impement as alternative API — i.e. .ksy file stays the same, but compiler, given certain feature flags, starts generating different API, in which `Myflags` would be an enum like you want it.

**Comment by ismell** [comment]
One thing I forgot to add. A drawback of manually defining the bit sequence is that you now need to take into account the endianness of the field when defining the `seq` v.s. just defining the type as `u4le` or `u4be` and matching on the value.

**Comment by GreyCat** [comment]
It's not really a "drawback", it's just a certain way to define sequences of bits. You can start with endianness and work from certain endianness-based implementation, or you can start with raw bits (that's the model that KS is trying to push, actually, being declarative) and just describe what is in there.

**Comment by ismell** [comment]
Thinking about this a bit more, in my original example, I had the bit field values as 1, 2, 4, 8, etc. Increasing by powers of 2. It would honestly be easier to read if it just described the bit position. i.e., 0, 1, 2, 4, etc. The generated code could just do the shift `(1 << n)`. The reason I recommend starting at 0 is that most hardware documentation starts with bit 0.

Here is a concrete example that I have:

```yaml
types:
  generic_processor_validation_bits:
    # We need to encode the bits in little-endian 
    seq:
      - id: cpu_brand_info_valid # (1 << 7)
        type: b1
      - id: cpu_version_valid # (1 << 6)
        type: b1
      - id: level_valid # (1 << 5)
        type: b1
      - id: flags_valid # (1 << 4)
        type: b1
      - id: operation_valid # (1 << 3)
        type: b1
      - id: processor_error_type_valid # (1 << 2)
        type: b1
      - id: processor_isa_valid # (1 << 1)
        type: b1
      - id: processor_type_valid # (1 << 0)
        type: b1

      - id: reserved_1 # (7 << 13)
        type: b3
      - id: instruction_ip_valid # (1 << 12)
        type: b1
      - id: responder_identifier_valid # (1 << 11)
        type: b1
      - id: requester_identifier_valid # (1 << 10)
        type: b1
      - id: target_address_valid # (1 << 9)
        type: b1
      - id: cpu_id_valid # (1 << 8)
        type: b1

      - id: reserved_2
        type: u2
      - id: reserved_3
        type: u4
seq:
  - id: valid
    type: generic_processor_validation_bits
```

It requires reversing the bits and grouping them into 8. So it's a bit difficult to cross check with my documentation.

Here is what my ideal implementation would be:

```yaml
flags:
  generic_processor_validation_bits:
    0: processor_type_valid
    1: processor_isa_valid
    2: processor_error_type_valid
    3: operation_valid
    4: flags_valid
    5: level_valid
    6: cpu_version_valid
    7: cpu_brand_info_valid
    8: cpu_id_valid
    9: target_address_valid
    10: requester_identifier_valid
    11: responder_identifier_valid
    12: instruction_ip_valid
seq:
  - id: valid
    type: u8
    flags: generic_processor_validation_bits
```

Thanks

**Comment by dgelessus** [comment]
Regarding the endianness problem: #155 suggests making it possible to select the bit order used when reading bit fields. This would solve the problem with having to manually swap bytes when specifying the bit fields. For big-endian data you would use MSB-first bit order (the current behavior) and specify bit fields from most to least significant; for little-endian data you would use LSB-first bit order and specify bit fields from least to most significant. Either way, you read the bytes sequentially from the file, without having to deal with "jumps" on byte boundaries.

I recently dealt with [a similar case](https://github.com/kaitai-io/kaitai_struct_formats/pull/173#discussion_r294102515) where some bit fields were stored in a little-endian integer. My solution was to first read the entire (little-endian) integer, and then parse the individual bit fields from the integer using bitwise operators and bit masks.

**Comment by ismell** [comment]
For what I'm proposing, the endianness doesn't really matter. It's really about determining if you have multiple enum values by comparing the type (which defines the endianness) with a bit shift operator.

```Java
EnumSet<MyFlags> flags = EnumSet.noneOf(MyFlags.class);
long field = read_data_into_native_endianness(...);

if (field & (1 << 0) != 0)
  flags.add(MyFlags.BIT_0);

if (field & (1 << 1) != 0)
  flags.add(MyFlags.BIT_1);

if (field & (1 << 2) != 0)
  flags.add(MyFlags.BIT_2);

return flags;
```
Hardware registers are typically defined as reading u1, u2<le/be>, u4<le/be>, u8<le/be> and then using a bit-shift and `bitwise AND` to see if a bit is set.

**Comment by ismell** [comment]
Just throwing this out there:
https://patchwork.kernel.org/patch/10897001/
https://patchwork.kernel.org/patch/10897011/

These two patches were for printing out the SDHCI registers in the linux kernel. In reality the 32-bit registers are a mix of enums/values located in different parts of the register. Each of these enums/values is defined using a bit width, and a bit offset. The endieness only matters when reading the register so you can convert it to the host endianness. All the parsing is then done using endianness agnostic operators.

I guess I'm really saying the same thing as: https://github.com/kaitai-io/kaitai_struct/issues/155#issuecomment-331409271
We need a way to define bit-fields within an integer.

```yaml
flags:
  myflags:
    0: bit_0
    1: bit_1
    2: bit_2
    3: bit_3

seq:
  - id: reg
    type: u4
    fields:
      - id: flags
        width: 4
        offset: 0
        flag: myflags
      - id: size
        width: 5
        offset: 4
```

```C
uint32_t reg = read_data_into_native_endianness(...);
uint8_t flags = reg & (0xF << 0);
uint8_t size = reg & (0x1F << 4);
```

**Comment by dgelessus** [comment]
> For what I'm proposing, the endianness doesn't really matter. It's really about determining if you have multiple enum values by comparing the type (which defines the endianness) with a bit shift operator.

You can already do this in Kaitai Struct, using value instances:
```yaml
types:
  flags:
    seq:
      - id: raw
        type: u4
    instances:
      bit_0:
        value: (raw & (1 << 0)) != 0
      bit_1:
        value: (raw & (1 << 1)) != 0
      bit_2:
        value: (raw & (1 << 2)) != 0
      # ...
```

Of course this still produces a regular structure in the generated code, and not an `EnumSet` or `enum.Flag` or your language's equivalent.

> Hardware registers are typically defined as reading u1, u2<le/be>, u4<le/be>, u8<le/be> and then using a bit-shift and `bitwise AND` to see if a bit is set.

It depends - for example the Intel Software Developer's Manual (i. e. Intel's specification of the x86 architecture) describes structures with bit fields visually like this:

![grafik](https://user-images.githubusercontent.com/6641959/60359111-59cb6b80-99d8-11e9-8670-9c375d83757f.png)

This specifies the order in which the structure is laid out in memory, without saying anything about how one would access the individual bit fields. The bit numbers at the top suggest that you would read it as two little-endian 32-bit integers and do the rest using bit masks, but it's also quite easy to see how you could read the structure byte-wise.

> Each of these enums/values is defined using a bit width, and a bit offset. The endieness only matters when reading the register so you can convert it to the host endianness. All the parsing is then done using endianness agnostic operators.

The links currently give me a 502 Bad Gateway error, so I can't read the actual code right now. I'd be interested if this way of reading the bit fields (first reading the integer, then extracting flags from it) is actually part of the hardware specification, or if it's just the way that it's been implemented in the kernel code.

> I guess I'm really saying the same thing as: https://github.com/kaitai-io/kaitai_struct/issues/155#issuecomment-331409271

The linked comment makes an incorrect assumption. It says:

> Often, _C bit fields_ are used to describe small values. Like this:
> 
> ```
> struct x {
>   int16_t a : 12;
>   int16_t b : 4;
> };
> ```
> 
> The order of the bits is clearly defined, for both big and little endian.

This is false - the order of the bits in `struct x` is *not* clearly defined, in fact the C standard says that bit order in bit fields is implementation-defined ([see here](https://en.cppreference.com/w/c/language/bit_field#Notes)).

**Comment by ismell** [comment]
@dgelessus thanks for that example and explanation. I retract my last statement then :)  Apparently I should have read the [Users Guide](https://doc.kaitai.io/user_guide.html) instead of the [KSY Reference](https://doc.kaitai.io/ksy_reference.html).

**Comment by jaroslaw-wieczorek** [comment]
I try to split the 'object_type' field into two separate b8-bit fields with the use of instances. Unfortunately, due to the fact that I use the 'enum' type, I cannot use the 'size' attribute in the 'object_type' field.
 
```yaml 
seq:
  - id: app_objects
    type: application_objects
    repeat: eos

application_objects:
  seq:
    - id: object_type
       type: b16
       enum: object_type_name
       
      - id: objects_instances
        type: objects_instances_type
        
    instances:
      obj_code: 
        pos: object_type
        type: b8
      var_code: 
        pos: obj
        type: b8


enums:
   object_type_name:
       0x0100: 'name_a'
       0x0111: 'name_b'
       0x0302: 'name_c'

types:
  objects_instances_type:
    id: data_point
    type:
      switch-on: _parent.object_type.to_i
      cases:
        0x0100: type_a
        0x0111: type_b
        0x0302: type_c
```
