### ISSUE TITLE
Can I not use _index in a switch-on?

### ISSUE THREAD

**Issue by trejkaz** [kaitai-io/kaitai_struct#598]
I'm trying to implement NRBF.

Full code here: https://github.com/trejkaz/nrbf.ksy/blob/master/nbrf.ksy

Sample around the problem:

```yaml
  # 2.3.1.2 MemberTypeInfo
  member_type_info:
    seq:
      - id: binary_type_enums
        type: u1
        enum: binary_type_enumeration
        repeat: expr
        repeat-expr: _parent.class_info.member_count
      - id: additional_infos
        type:
          switch-on: binary_type_enums[_index]
          cases:
            'binary_type_enumeration::primitive': member_type_info_additional_info_primitive
            'binary_type_enumeration::string': member_type_info_additional_info_empty
            'binary_type_enumeration::object': member_type_info_additional_info_empty
            'binary_type_enumeration::system_class': member_type_info_additional_info_system_class
            'binary_type_enumeration::class': member_type_info_additional_info_class
            'binary_type_enumeration::object_array': member_type_info_additional_info_empty
            'binary_type_enumeration::string_array': member_type_info_additional_info_empty
            'binary_type_enumeration::primitive_array': member_type_info_additional_info_primitive
        repeat: expr
        repeat-expr: _parent.class_info.member_count
  member_type_info_additional_info_empty:
    seq: []
  member_type_info_additional_info_primitive:
    seq:
      - id: primitive_type
        type: u1
        enum: primitive_type_enumeration
  member_type_info_additional_info_system_class:
    seq:
      - id: class_name
        type: length_prefixed_string
  member_type_info_additional_info_class:
    seq:
      - id: class_type_info
        type: class_type_info
```

If I put in `0` instead of `_index` it works, so is it just not possible to use the index inside a `switch-on` expression?

**Comment by GreyCat** [comment]
That's an interesting scenario — in general, I don't see why it shouldn't work.

I've tested it for Ruby and it seems to work. What do you observe, and (1) which version of ksc you're using? (2) what language are you targeting?

**Comment by trejkaz** [comment]
I'm using the IDE currently deployed at ide.kaitai.io, so JavaScript I guess.

If it works for Ruby, then I guess one possibility is that there's a newer version which works than what's deployed there, and the other possibility is that only JS is busted?

**Comment by GreyCat** [comment]
I'll check with web IDE, thanks!
Meanwhile, you can also try a slightly newer IDE at https://ide.kaitai.io/devel/

**Comment by trejkaz** [comment]
Source data.

[Test.nrbf.zip](https://github.com/kaitai-io/kaitai_struct/files/3354273/Test.nrbf.zip)

I couldn't get it working either on live or on devel web IDE, but I found another way to structure it which might make more sense anyway.

```yaml
  member_type_info:
    seq:
      - id: binary_type_enums
        type: u1
        enum: binary_type_enumeration
        repeat: expr
        repeat-expr: _parent.class_info.member_count
      - id: additional_infos
        type: member_type_info_additional_info(_index)
        repeat: expr
        repeat-expr: _parent.class_info.member_count
  member_type_info_additional_info:
    params:
      - id: i
        type: u1
    seq:
      - id: primitive_type
        type: u1
        enum: primitive_type_enumeration
        if: |
          _parent.binary_type_enums[i] == binary_type_enumeration::primitive ||
          _parent.binary_type_enums[i] == binary_type_enumeration::primitive_array
      - id: class_name
        type: length_prefixed_string
        if: _parent.binary_type_enums[i] == binary_type_enumeration::system_class
      - id: class_type_info
        type: class_type_info
        if: _parent.binary_type_enums[i] == binary_type_enumeration::class
```
