### ISSUE TITLE
generated java contains switch statement with long type

### ISSUE THREAD

**Issue by karlpeterhugo** [kaitai-io/kaitai_struct#599]
for a ksy like this

```
    seq:
      - id: id
        type: u4
      - id: data
        type:
          switch-on: id
          cases:
            0x80000000: a
```
the kaitai-struct-compiler 0.8 generated Java code switches using a 64 long type

```
public long id() { return id; }
..
            switch (id()) {
```

which results in

```
error: incompatible types: possible lossy conversion from long to int
            switch (id()) {
```
