### ISSUE TITLE
Cannot process value of instance

### ISSUE THREAD

**Issue by ghost** [kaitai-io/kaitai_struct#60]
I need to process data twice so I wrote that:
```yaml
  enc_header:
    seq:
      - id: unk_1
        type: u4
      - id: unk_2
        type: u4
      - id: body_offset
        type: u4
      - id: body_dec_size
        type: u4
      - id: body_enc_size
        type: u4
    instances:
      enc_body:
        io: _root._io
        pos: 
            _root.header.enc_headers_offset 
            + _root.header.enc_headers_total_size
            + body_offset
        size: body_enc_size
        process: xor([
            ...
        ])

      dec_body:
        value: enc_body
        process: zlib
```

`enc_body` is xored successfully but `dec_body` only takes that processed value and do nothing with it. As I saw in compiled code, `process` of `dec_body` was ignored:
```perl
sub dec_body {
    my ($self) = @_;
    return $self->{dec_body} if ($self->{dec_body});
    $self->{dec_body} = $self->enc_body();
    return $self->{dec_body};
}
```

I've also tried to specify size of `enc_body`:
```yaml
dec_body:
  value: enc_body
  size: body_enc_size
  process: zlib
```

Is it possible to process value of another instance?

**Comment by GreyCat** [comment]
Value instances actually don't support lots of stuff — probably error checks need to be added [here](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/shared/src/main/scala/io/kaitai/struct/format/InstanceSpec.scala#L21). So far only `enum` and `if` are supported for value instances, and, honestly, I don't think that adding `process` support would be a good idea. `process` requires a byte array to work on (and it is actually a part of data type definition), and there's no way to ensure what we're working on byte array during initial YAML parsing.

When I designed `process`, I thought that supporting multi-step processing is a bad idea: it complicates lots of things, but it's rarely used and it's not really critical to support it literally. One can always do:

```yaml
seq:
  - id: body
    size: body1_size
    process: xor(...)
    type: body2
types:
  body2:
    seq:
      - id: body
        size-eos: true
        process: zlib
        type: body3 # or no type if you just want unXORed + unzipped byte array
```

And thus you'll get what you want by invoking `foo.body.body`.
