### ISSUE TITLE
Access to index of "repeat-expr"

### ISSUE THREAD

**Issue by ghost** [kaitai-io/kaitai_struct#61]
Is there a way to use current index value in `repeat-expr` loop? What I mean:
```yaml
row:
  seq:
    - id: column
      size: _root.column_headers[i].size
      repeat: expr
      repeat-expr: _root.header.column_headers_num
```

It's a simple definition of a database row. One need to read each column for the row, but `column_headers[i].size` is different for each column and can't be hardcoded so one have to obtain these sizes at runtime. But `i` is not valid identifier (unknown for an expression parser, as I understand) so is there a workaround? If no, it would be great to implement it, at least I'm facing this problem not for the first time.
