### ISSUE TITLE
Question: is this correct?

### ISSUE THREAD

**Issue by DCxDemo** [kaitai-io/kaitai_struct#610]
imagine we have this byte stream:
`03 00 00 00 01 00 01 00 FF FF 02 00 01 00 FF FF 02 00 FF FF CC CC`
`03 00 00 00 | (01 00 [01 00 - FF FF] ) (02 00 [01 00 - FF FF] [02 00 - FF FF CC CC]`

this definition fails in web-ide, am i doing something wrong here? is there any specific way to nest types?

error:
`Parse error: undefined
Call stack: undefined RangeError: Offset is outside the bounds of the DataView`

```
meta:
  id: example
  endian: le

seq:
  - id: num
    type: u4
  - id: objects
    type: object
    repeat: expr
    repeat-expr: num

types:

  object:
    seq:
      - id: num
        type: u2
      - id: subobjects
        type: subobject
        repeat: expr
        repeat-expr: num
        
  subobject:
    seq:
      - id: num2
        type: u2
      - id: entry
        type: u2
        repeat: expr
        repeat-expr: num2
```
