### ISSUE TITLE
switch-on: when the selector value is determined after the data

### ISSUE THREAD

**Issue by wyfinger** [kaitai-io/kaitai_struct#611]
When selector variable for switch-on: determinate before data we see this:
![1](https://user-images.githubusercontent.com/431985/62747887-bcb12780-ba99-11e9-99b7-d4e70bf0b978.png)

zamerValues is a struct of zamer_pq type.

but if selector variable determinate before data we see this:
![2](https://user-images.githubusercontent.com/431985/62747966-26313600-ba9a-11e9-9c0d-0d9967a25d6f.png)

zamerValues is a byte array.

How can I determine the switch-on type correctly when the selector  variable is located after the data itself?

**Comment by wyfinger** [comment]
My test data:
[nagr_new.zip](https://github.com/kaitai-io/kaitai_struct/files/3484318/nagr_new.zip)

My test ksy:
```
meta:
  id: nagr
  file-extension: nagr
  endian: le
seq:
  - id: count
    type: u4
  - id: zamer_chanks
    type: zamer
    repeat: eos
types:
  zamer:
    seq:
      - id: zamer_values
        type:
          switch-on: zamer_type
          cases:
            0x01: zamer_pq
            0x02: zamer_ifu
            0x03: zamer_rx
            0x04: zamer_zf
        size: 28
      - id: zamer_type
        type: u4
      - id: zamer_no
        type: str
        size: 16
        encoding: ascii
        
  zamer_pq:
    seq:
      - id: field1
        type: f4
      - id: field2
        type: f4
      - id: field3
        type: f4
      - id: field4
        type: f4
      - id: field5
        type: f4  
      - id: field6
        type: f4
      - id: field7
        type: f4
  zamer_ifu:
    seq:
      - id: field1
        type: f4
      - id: field2
        type: f4
      - id: field3
        type: f4
      - id: field4
        type: f4
      - id: field5
        type: f4  
      - id: field6
        type: f4
      - id: field7
        type: f4      
  zamer_rx:
    seq:
      - id: field1
        type: f4
      - id: field2
        type: f4
      - id: field3
        type: f4
      - id: field4
        type: f4
      - id: field5
        type: f4  
      - id: field6
        type: f4
      - id: field7
        type: f4
  zamer_zf:
    seq:
      - id: field1
        type: f4
      - id: field2
        type: f4
      - id: field3
        type: f4
      - id: field4
        type: f4
      - id: field5
        type: f4  
      - id: field6
        type: f4
      - id: field7
        type: f4
```

**Comment by KOLANICH** [comment]
1. It'd be really nice to have a feature of selecting type of constant size fields after their parsing. The proposed way is to move them into an own substream.

2. The workaround is using instances. Something like
```yaml
 seq:
  - id: measurement_raw
    size: 28
    type: placeholder
  - id: measurement_type
    type: u4
  - id: measurement_no
    type: str
    size: 16
    encoding: ascii
instances:
  measurement:
    pos: 0
    io: measurement_raw._io
    type:
      switch-on: zamer_type
      cases:
        0x01: zamer_pq
        0x02: zamer_ifu
        0x03: zamer_rx
        0x04: zamer_zf
  types:
    placeholder:
      seq:
        - id: placeholder
          size: _io.size
```

3. Please never post source code as screenshots. Yaml syn5ax highlighting is supported by GitHub.

4. `замер` in English is `measurement`. Source code in translit is cancer.
