### ISSUE TITLE
Accessing _index from a higher level

### ISSUE THREAD

**Issue by larsks** [kaitai-io/kaitai_struct#628]
In the data I'm parsing, I have a list of channels, and a list of names.  In the top-level `instances` section of my `.ksy` file I have:

```
  channels:
    pos: 0x1700
    type: channel
    repeat: expr
    repeat-expr: 1000
  channel_names:
    pos: 0x5800
    type: str
    encoding: ascii
    terminator: 0xff
    size: 8
    repeat: expr
    repeat-expr: 1000
```

When reading in the data, I would like each element in `channels` to have a `name` attribute that maps to the corresponding name in the `channel_names` array. I tried this:

```
  channel_fields:
    seq:
      - id: rx_freq
        type: u4
    instances:
      name:
        value: _root.channel_names[_index]
```

But this fails. In the generated Python code, we see:

```
    @property
    def channels(self):
        if hasattr(self, '_m_channels'):
            return self._m_channels if hasattr(self, '_m_channels') else None

        _pos = self._io.pos()
        self._io.seek(5888)
        self._m_channels = [None] * (1000)
        for i in range(1000):
            self._m_channels[i] = self._root.Channel(self._io, self, self._root)

        self._io.seek(_pos)
        return self._m_channels if hasattr(self, '_m_channels') else None
```

The value of `i` is never exposed outside of the loop. There's no way to access it from the subtype.

**Comment by dgelessus** [comment]
I think this is intentional. `_index` is supposed to be a local variable that you can only access in the definition of the `repeat`ed field. The `channel` type doesn't have access to it, because the type itseld has no connection to the `repeat`ed field - it's a generic definition that can be used anywhere, not just from inside a `repeat`. Also, if the type had access to a surrounding `repeat`'s `_index`, it would lead to ambiguity - if you have multiple nested `repeat`s, how do you differentiate between the outer and inner `_index`?

There is a solution though: you can add an integer parameter to your type and explicitly pass the `_index` as an argument to the type. Then you can access the `_index` inside the type (but using the name of the parameter, not actually `_index`).

```yaml
 channels:
    pos: 0x1700
    type: channel(_index)
    repeat: expr
    repeat-expr: 1000
# ...
types:
  channel:
    params:
      - id: number
        type: u2
    seq:
      - id: rx_freq
        type: u4
    instances:
      name:
        value: _parent.channel_names[number]
```

This is how I solved a similar problem in my spec for the Unix `pack` format (in the `unix_pack::tree::level` type): https://github.com/dgelessus/kaitai_struct_formats/blob/unix_pack/archive/unix_pack.ksy#L88
