### ISSUE TITLE
Hexadecimal values not supported on LHS of case statements

### ISSUE THREAD

**Issue by larsks** [kaitai-io/kaitai_struct#629]
I started with the following in my `.ksy` file:

```
types:
  channel:
    seq:
      - id: rx_freq_raw
        type: u4
      - id: data
        type:
          switch-on: rx_freq_raw
          cases:
            0xff: empty_channel
            _: channel_fields
```

...but it failed, because the `0xff` case never matched and it would always use the default case. It works if instead of `0xff` I write:

```
            4294967295: empty_channel
```

I'm glad it works, but it's much less readable, and it's surprising because hexadecimal values are supported elsewhere.
