### ISSUE TITLE
Inconsistent behavior of list-of-ints vs list-of-floats

### ISSUE THREAD

**Issue by larsks** [kaitai-io/kaitai_struct#632]
I just ran into the following odd behavior.  If I specify a literal value as a list of integers, like this:

```
types:
  tables:
    instances:
      example_lookup:
        value: >-
          [10, 20, 30, 40, 50]
```

Then the generated Python code is a byte string:

```
self._m_example_lookup_2 = b"\x0A\x14\x1E\x28\x32"
```

And if I try the following, it fails with `(main): /types/example/instances/value_decoded_2/value: unable to apply operation [] to CalcBytesType`:

```
types:
  tables:
    instances:
      example_lookup:
        value: >-
          [10, 20, 30, 40, 50]
  example:
    seq:
      - id: value_raw
        type: u1
    instances:
      value_decoded:
        value: _root.tables.example_lookup[value_raw]
```

But if I put a single float into that `example_lookup` table, like this:

```
types:
  tables:
    instances:
      example_lookup:
        value: >-
          [10.0, 20, 30, 40, 50]
  example:
    seq:
      - id: value_raw
        type: u1
    instances:
      value_decoded:
        value: _root.tables.example_lookup[value_raw]
```

...it works as expected, and the generated Python code looks like this:

```
self._m_example_lookup_1 = [10.0, 20, 30, 40, 50]
```

What's up with that?
