### ISSUE TITLE
switch on string and return integer

### ISSUE THREAD

**Issue by Ralle** [kaitai-io/kaitai_struct#636]
I am making a parser for the WTG file format from Warcraft 3.
WTG requires that you look up a string from the file elsewhere to determine the number of structs that come after it. I went down a bad path trying to use `process` to determine this number, but that did not work for me. It is way too focused on processing bytes and returning bytes. Anyway, it wouldn't give me a u4 as the number of items.
So I made a script that generates a .ksy file of the entire index. Here is the short version of my generated file, it is in fact over 1000 lines, but the rest is just case entries:
```
meta:
  id: function_info

seq:
  - id: name
    type: strz
    encoding: UTF-8

instances:
  argument_count:
    value:
      switch-on: name
      cases:
        'DoNothing': 0
        'CommentString': 1
        'CustomScriptCode': 1
        'TriggerSleepAction': 1
```

I am getting this error:
`/instances/argument_count/value: expected string, got Map(switch-on -> name, cases -> Map(QuestItemSetCompletedBJ -> 2, SaveLocationHandleBJ -> 4, MultiboardClear -> 1, ......`

What am I doing wrong? Or is it a bug?

**Comment by KOLANICH** [comment]
Not yet implemented.  #627

**Comment by Ralle** [comment]
So if I am to be constrained to what is implemented, would I be returning a string? In that case I can use .to_i() on it in the places I use it.
Or is switch simply not implemented for instances?

**Comment by Ralle** [comment]
Is there any way I can implement this with today's version of Kaitai? I tried making a ternary (of 1000 if statements) and got a Java stack overflow.

I was thinking of switching over the function name and returning an enum of num_args_0-15 but then I would lose the function name. What can I do today?

**Comment by GreyCat** [comment]
> So if I am to be constrained to what is implemented, would I be returning a string? In that case I can use .to_i() on it in the places I use it.
> Or is switch simply not implemented for instances?

As of now, "switch" is only implemented in 2 places, these are:

1. Type switching — i.e. within a `type`, "returning" type reference.
2. Switching over expression to determine default endianness

Implementing switch for instances if possible, but the reason I'm very hestitating about all these features is because we want to keep language as declarative and as domain-specific as possible. Your example, though, makes a very good point, so I'd like to learn more about it.

You're telling me that there is a number of structures that will follow this, and the 

```yaml
seq:
  - id: name
    type: strz
    encoding: UTF-8
  - id: structs
    type:
      switch-on: name
      cases:
        '"DoNothing"': structures(0)
        '"CommentString"': structures(1)
        '"CustomScriptCode"': structures(1)
        # ...
types:
  structures:
    param:
      - id: num_args
        type: u4
    seq:
      - id: args
        type: structure
        repeat: expr
        repeat-expr: num_args
```

Would that work, or you need something completely different?

> After a lot of tinkering I found a work-around:

That's a very creative solution, definitely worth the praise ;)
