### ISSUE TITLE
switch-on result usage

### ISSUE THREAD

**Issue by DCxDemo** [kaitai-io/kaitai_struct#639]
Consider these declarations:

```
vec2u1:
  seq:
    - id: x
      type: u1
    - id: y
      type: u1

vec2u2:
  seq:
    - id: x
      type: u2
    - id: y
      type: u2
```

```
- id: position
  type:
    switch-on: _root.version
    cases:
      'version_id::ver1': vec4u2
      'version_id::ver2': vec4u1
```

Basically I have 2 vector types stored as 1 and 2 bytes, depending on file version.

So it works perfectly in terms of parsing, but the resulting type of "position" here is KaitaiStruct due to the type switching. Given this, how do I exactly use this in code? Do I have to track version myself and add tons of switches to cast manually, or is there a better solution? Talking about C#.

int x = (ex.Version == Example.VersionId.Ver1 ? ((Example.Vec4u2)ex.position).X : ((Example.Vec4u1)ex.position).X);
int y = (ex.Version == Example.VersionId.Ver1 ? ((Example.Vec4u2)ex.position).Y : ((Example.Vec4u1)ex.position).Y);

**Comment by GreyCat** [comment]
Given that what you want is coercion of "x" and "y" in one "common denominator" type, which coercion must happen somewhere. One thing that can ease that is the fact that switch types itself do the coercion. You can do it like that:

```yaml
vec2:
  seq:
    - id: x
      type:
        switch-on: _root.version
        cases:
          'version_id::ver1': u2
          'version_id::ver2': u1
    - id: y
      type:
        switch-on: _root.version
        cases:
          'version_id::ver1': u2
          'version_id::ver2': u1
```

```yaml
- id: position
  type: vec2
```

This way both `x` and `y` will be coerced to CalcIntType automatically, given that no alternatives exist there.

**Comment by DCxDemo** [comment]
i see, so i have to create third context specific struct. i was wondering if i can reuse existing structs for this task, cause i have to keep those two, since they are used in other places, version-independent.

**Comment by GreyCat** [comment]
If you need to reuse existing structures, and prefer having a switch over version in `position`, then `position` becomes of generic KaitaiStruct type, so you'll need to follow the procedure you've shown with ternary expression + cast. You can do that in C#, as you've shown, or in KS:

```yaml
instances:
  x:
    value: |
      _root.version == version_id::ver1 ? position.as<vec2u2>.x : position.as<vec2u1>.x
```
