### ISSUE TITLE
Compiler error messages: invalid type

### ISSUE THREAD

**Issue by v-p-b** [kaitai-io/kaitai_struct#64]
I was playing with Avatao's Kaitai challenges and ran into this weird feature/bug:

After my first attempts I wrongfully thought that I should reference user defined types by their "compiled" names: instead of `my_field_type` I wrote `myFieldType` throughout my definition like this:

```yaml
seq:
  - id: test_id
    type: myFieldType
types:
  my_field_type: 
    seq:
      - id: sub
        type: subType
  sub_type:
    seq:
      - id: length
        type: u1
```

The strange thing was that this actually *worked* as long as I didn't try to reference a subtype (e.g. `if: test_id.sub.length`) which resulted in a compilation error.

So at its root this was certainly a user error, but I feel like the compiler should at least warn when the user specifies an invalid identifier as a type name.
