### ISSUE TITLE
Unexpected alignment when using boolean `b1`

### ISSUE THREAD

**Issue by StefanD986** [kaitai-io/kaitai_struct#642]
I discovered some unexpected result when trying to parse data that has booleans. Not sure whether it **is** a bug, but it feels like one, so putting it up here for discussion. 

# Steps to reproduce:
Given the attached grammar (see below)
1. Parse the following data: `bytearray([0x69, 0x01, 0x01, 0x5F, 0x00])` (see gist at the end for a python test fixture)

## Expected behaviour
Parsing the data should produce an object structure that essentially contains the following data
```python
[
    {'tag': 105, 'multi_byte_len_flag': False, 'length': 1, 'body': True},
    {'tag': 95, 'multi_byte_len_flag': False, 'length': 0, 'body': None}
]
```

## Actual behaviour
Parsing the data throws the folloowing error: `EOFError: requested 2 bytes, but got only 0 bytes`

# Further notes
Upon inspection of the generated code it appears as if there might be a alignment instruction missing after reading the body data of elements with `tag==105` 

https://gist.github.com/StefanD986/e8d7ca9814a070d7bba74044a7d28ae7#file-tlv_debugging-py-L45

I am following the kaitai documentation, that suggests to use the 1 bit `b1` type for booleans. However I also argue that only evaluating the lowest bit to decide whether the value is `True` or `False` is not enough, since many languages interprete anyting non-zero as *truthy*.

# Attachments

```yaml
meta:
  id: tlv_debugging
  file-extension: hex
  endian: le
  encoding: ascii
seq:
  - id: file_hdr0
    type: header_obj
    repeat: until
    repeat-until: _.length == 0
types:
  header_obj:
    seq:
      - id: tag
        type: u1
      - id: multi_byte_len_flag
        type: b1
      - id: length
        type: b7
      - id: body
        size: length
        type:
          switch-on: tag
          cases:
            95:  tb
            105: b1
    types:
      tb: 
        seq:
          - id: no_value
            size: 0

```

Minmal example code can also be found here: https://gist.github.com/StefanD986/e8d7ca9814a070d7bba74044a7d28ae7

**Comment by generalmimon** [comment]
> I am following the kaitai documentation, that suggests to use the 1 bit `b1` type for booleans. However I also argue that only evaluating the lowest bit to decide whether the value is `True` or `False` is not enough, since many languages interprete anyting non-zero as _truthy_.

Kaitai Struct documentation doesn't suggest using `b1` for every field that should be interpreted as boolean. It just says that if you declare a field of type `b1`, its value won't be either 0 or 1, but booleans `True` or `False`. This is because probably the most common use case for `b1` is parsing flag bitfields. That is, for example some byte which numerical value is not important, but each of its 8 bits has its own meaning. These are usually some switches which turn certain features or settings on or off. The Kaitai Struct automatically converts the numerical value of the bit to boolean, because it's convenient in this case.

But you are describing another problem, you want to read a byte and interpret it as true/false **based on its numerical value** (I suppose "0 => `false`, everything else => `true`" is what you want). This should be achieved by declaring a `u1` (or `s1`) field and using `(field != 0)` everywhere you want to use its value.

And to the bug you describe: I realized that it might be very hard to resolve whether to insert alignment instruction or not. There are so many cases that need to be solved separately, such as primitive `b1` followed by `u1` hidden in the sequence of a user type, `b1` hidden in a user type followed by primitive `u1`, `b1` hidden in a user type followed by `u1` in a user type too, etc. Not even counting the number of possibilities when combining user types with own substream/without it, with `switch` or without it, with `repeat` or without, conditional fields with `if` etc. I think all the hard work isn't worth it, especially when the problem has relatively simple workaround:

```yaml
meta:
  id: bits_bytes_user_switch_aligned
seq:
  - id: problematic_field
    type:
      switch-on: 42
      cases:
        42: b1
        _: u1
    # want to always align to byte here? no problem!
  - type: b0
    # there will be the desired align_to_byte() call
  - size: 0
```

And I also think that even if we got all that work done, it may be very confusing for the programmer if the compiler decided to align to byte somewhere where it wasn't supposed to. That would be much worse than the current situation, because there isn't a way to revert the alignment that has been already done without altering the generated code.

Personally I would leave it as is, but the documentation should probably mention this issue.
