### ISSUE TITLE
Reference enums in external file?

### ISSUE THREAD

**Issue by rexxowski** [kaitai-io/kaitai_struct#643]
Hi guys,
I'd like to reference an enum (*rowing_messages::position* in this case)  from external file. For external types it seems it's enough to add "rowing::" prefix, but for enums it doesn't seem to work. Is there any way?

base file (test.ksy)
```
meta:
  id: test
  imports:
    - rowing
  endian: be
  
seq:
  - id: system_id
    type: u1
  - id: data
    type:
      switch-on: system_id
      cases:
        rowing_messages::position: rowing::rowing_position_message
```

the "external" file (rowing.ksy):
```
meta:
  id: rowing
  endian: be
  
enums:
  rowing_messages:
    0x10: position
    0x12: meter_per_stroke
  
types:
  rowing_position_message:
    seq:
      - id: id
        type: u1
      - id: timestamp
        type: u4
```

**Comment by GreyCat** [comment]
@rexxowski, there are multiple issues with this code. First of all, this is a type mismatch:

```yaml
  - id: system_id
    type: u1
  - id: data
    type:
      switch-on: system_id
      cases:
        rowing_messages::position: rowing::rowing_position_message
```

Your `system_id` is an integer, and you're trying to compare it to a enum. To do that, you either need to:

* add `enum: 'rowing::rowing_messages'` to your `system_id`, and compare it as enum => this should work, but likely will require relatively modern compiler (i.e. not v0.8); this is the problem solved in #275 and #293.
* add `.to_i` to enums referenced in comparison, i.e.

  ```
  - id: data
    type:
      switch-on: system_id
      cases:
        'rowing::rowing_messages::position.to_i': rowing::rowing_position_message
  ```

  .. but (1) you'll still need full name specification, i.e. with outer type `rowing::` prepended too, (2) this will be impacted by #552, which is still pending resolution.
