### ISSUE TITLE
utf-8?

### ISSUE THREAD

**Issue by ogamespec** [kaitai-io/kaitai_struct#649]
Can't find utf-8 in Format Gallery:

http://formats.kaitai.io/

**Comment by generalmimon** [comment]
[UTF-8](https://en.m.wikipedia.org/wiki/UTF-8) is a character encoding, not a binary format for representing structured data. You can parse a UTF-8 string from a binary stream by compiling a .ksy file with the following:
```yaml
meta:
  id: utf8_str
seq:
  - id: name
    type: str
    size: 24
    encoding: UTF-8
```

You might want to look into [the user guide](http://doc.kaitai.io/user_guide.html).
