### ISSUE TITLE
Can Kaitai DSL describe an exception to be thrown on unexpected input?

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [kaitai-io/kaitai_struct#650]
Hi,

I've recently came across Kaitai and I'm evaluating it so that I could get rid of manual parsing. My custom binary format is extremely simple:

```yml
meta:
  id: crypto_container_parser
  endian: le
seq:
  - id: magic
    type: magic
  - id: meta
    type: meta
  - id: reverse_magic
    type: reverse_magic
types:
  magic:
    seq:
      - id: magic
        contents: 'CRPT'
  reverse_magic:
    seq:
      - id: magic
        contents: 'TPRC'
  meta:
    seq:
      - id: algorithm
        type: algorithm
      - id: key
        type: key
      - id: parameters
        type: parameters
  algorithm:
    seq:
      - id: self
        type: none_or_byte_array_1
  key:
    seq:
      - id: self
        type: none_or_byte_array_2
  parameters:
    seq:
      - id: self
        type: none_or_byte_array_2
  none_or_byte_array_1:
    seq:
      - id: tag
        type: u1
        enum: type_tag
      - id: optional
        type:
          switch-on: tag
          cases:
            'type_tag::none': none
            'type_tag::byte_array_1': byte_array_1
  none_or_byte_array_2:
    seq:
      - id: tag
        type: u1
        enum: type_tag
      - id: optional
        type:
          switch-on: tag
          cases:
            'type_tag::none': none
            'type_tag::byte_array_2': byte_array_2
  none:
    seq: []
  byte_array_1:
    seq:
      - id: length
        type: u1
      - id: elements
        size: length
  byte_array_2:
    seq:
      - id: length
        type: u2le
      - id: elements
        size: length
enums:
  type_tag:
    0: none
    1: byte_array_1
    2: byte_array_2
```

Byte arrays above require simple type tags `0x00` for null values, `0x01` for 1-byte-length arrays, and `0x02` for 2-byte-length arrays.  In short, this grammar can process such data:

```
'C' 'R' 'P' 'T'
'\x01' '\x03' 'f' 'o' 'o'
'\x00'
'T' 'P' 'R' 'C'
```

Now suppose the type tag is broken for whatever reason and indicates a type that is not registered in the `type_tag` enum above.

```
'C' 'R' 'P' 'T'
'\xDD' '\x03' 'f' 'o' 'o'
'\x00'
'T' 'P' 'R' 'C'
```

Let's say, the actual type tag value is `0xDD` (and it doesn't map any type). Trying to parse such data the following exception is thrown:

```
java.lang.NullPointerException
	at CryptoContainerParser$NoneOrByteArray1._read(CryptoContainerParser.java:166)
	...
```

which points to:

```java
this.tag = CryptoContainerParser.TypeTag.byId(this._io.readU1());
switch (tag()) {
```

The NPE encounters in the switch expression caused by ```public static TypeTag byId(long id) { return byId.get(id); }``` that returns `null` for the unrecognized type tag `0xDD`. If I'm not mistaken at understanding Scala code, currently the compiler does not provide any way of throwing an "unrecognized" exception in `JavaCompiler.scala`. My question is: is there a way to tell the generated code to throw a custom exception on encountering illegal type tags? I would assume that I could add a new case for `_` to the `switch-on` clauses above, but I didn't find anything in the documentation telling how to throw an exception to hide the obscure `NullPointerException`.
