### ISSUE TITLE
Parse the beginning of the stream differently based on a future value

### ISSUE THREAD

**Issue by dummys** [kaitai-io/kaitai_struct#656]
Hi,

Let me explain, for example I have a payload that start with 2 bytes identical, then the following is different based on the 11th byte. if its' 0x11 then the bytes means something else. What is the best way to achieve that ? I tried with if but its not well working. Just a note: the size of the bytes before the 11th bytes is always the same, it's just the meaning of the byte that is different and the size on the internal structure.

**Comment by generalmimon** [comment]
This is a typical usage of [parse instances](http://doc.kaitai.io/user_guide.html#_instances_data_beyond_the_sequence). Based on what you wrote, I would do it like this:
```yaml
seq:
  - id: magic
    contents: [0xf7, 0x9d]
  - id: payload
    size-eos: true # stretch to the end of stream
    type:
      switch-on: payload_id
      cases:
        0x24: foo
        0x99: bar
      # ...
instances:
  payload_id:
    pos: 11
    type: u1

**Comment by dummys** [comment]
ok nice and it is possible that payload_id is an enum ?

**Comment by dummys** [comment]
I would do it like this for example:

```
seq:
  - id: magic
    contents: [0xf7, 0x9d]
  - id: header_type
    size: 8
    type:
      switch-on: header_type
      cases:
        'myenum::case1': foo
        'myenum::case2': bar
      # ...
instances:
  header_type:
    pos: 11
    type: myenum
types:
  foo:
    seq:
    - id: foo1
      size: 8
  bar:
    seq:
    - id: bar1
      size: 8
enums:
  myenum:
    0x1: blabla
    0x2: blabla
```

**Comment by dummys** [comment]
edit I make it works but not exactly as how I want see:

```
eq:
  - id: dunno
    type: u2
  - id: header
    size: 8
    type: header
  - id: cmd
    type: u1
    enum: myenum
  - id: payload
    type: 
      switch-on: cmd
      cases:
        'myenum::blabla1': a1
        'myenum::blabla1': a2

instances:
  header_t:
    pos: 2
    io: header._io
    type:
      switch-on: cmd
      cases:
        'myenum::blabla1': h1
        'myenum::blabla2: h2

types:
  header:
    seq:
    - id: header
      size: 8
  a1:
    seq:
    - id: foo1
      size: 8
  a2:
    seq:
    - id: bar1
      size: 8
types:
  h1:
    seq:
    - id: hh1
      size: 8
  h2:
    seq:
    - id: hh2
      size: 8

enums:
  myenum:
    0x1: blabla1
    0x2: blabla2
```
The wanted result is when I do: 

```  
a = myclass.from_bytes(xxx)
a.header.hh1 should have a value
```
But in reality what it does is:

```
a.header.header
```
And I can't access the hh1, when I access the header.header, I get the 8 bytes not parsed.

**Comment by generalmimon** [comment]
The spec in your previous comment is nearly correct. The first issue is in this field, as the compiler pointed out by the compiler:

```yaml
instances:
  header_type:
    pos: 11
    enum: myenum
```

What the compiler wanted to say is that it simply doesn't know how long is this field. It listed out usual properties to denote that: `size, size-eos or terminator`, but in that case, you rather want to add `type: u1`. This will imply 1-byte size and the unsigned byte value will be resolved in the enum. 

The second problem you will encounter is that you cannot use the same name for name across `seq` and `instances`, because the generated API for them is typically the same. I recommend renaming the 2nd `seq` field from  `header_type` to just `header`.
