### ISSUE TITLE
Signed version of vlq_base128?

### ISSUE THREAD

**Issue by pedronavf** [kaitai-io/kaitai_struct#659]
I'm trying to add support for signed integer values to vlq_base128_le but I'm not sure how to do it. 

Signed values are the same as unsigned but the last byte has a sign in bit 6. The pseudocode according to wikipedia is:

```c
result = 0;
shift = 0;

/* the size in bits of the result variable, e.g., 64 if result's type is int64_t */
size = number of bits in signed integer;

do {
  byte = next byte in input;
  result |= (low order 7 bits of byte << shift);
  shift += 7;
} while(high order bit of byte != 0);

/* sign bit of byte is second high order bit (0x40) */
if ((shift <size) && (sign bit of byte is set))
  /* sign extend */
  result |= (~0 << shift);
```
The current vlq_base128 implementation takes care of the first `do...while` but I'm not sure how to add the `if`block to the `value` instance's expression, especially since it's the last byte. I can add an `is_negative` instance that tells me if the last byte has a sign:

```yaml
instances:
  len:
    value: groups.size
  value:
    value: >-
      groups[0].value
      + (len >= 2 ? (groups[1].value << 7) : 0)
      + (len >= 3 ? (groups[2].value << 14) : 0)
      + (len >= 4 ? (groups[3].value << 21) : 0)
      + (len >= 5 ? (groups[4].value << 28) : 0)
      + (len >= 6 ? (groups[5].value << 35) : 0)
      + (len >= 7 ? (groups[6].value << 42) : 0)
      + (len >= 8 ? (groups[7].value << 49) : 0)
    doc: Resulting value as normal integer
  is_negative:
    value: groups[len-1].value & 0b0100_0000 != 0
```

But I don't know what to do with the information and how can I change the `value` instance to modify its last bite or how to add another statement to the `value` expression.
