### ISSUE TITLE
New built-in type: opcode

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#66]
An ```opcode``` is just a byte of machine code of any architecture intended to run directly by underlying hardware. It is implementation-defined how to treat it. Virtual machines' opcodes are not covered by this and should be treated separately. We need this type in order to support disassemblers and decompiler's APIs as targets.

**Comment by GreyCat** [comment]
Opcodes are just sequences of bytes. Why would you need a special built-in data type for them? I've already done several opcode disassemblers in current paradigm without any major problems.

**Comment by KOLANICH** [comment]
Because we need to distinguish between data bytes (which shouldn't be marked as code because they are not and the code will be garbage if they are disassembled) and code bytes which should be passed to a disassembler.

For example if we are reverse-engineering some binary of known format. What does any binary have? It has entry points. And we want a decompiler to be called automatically on the code referenced by entry points. In #67 I propose a "ptr" attribute for integers to mark them as pointers to automatically parse referenced data. So if we created a pointer to opcode this means that a disassembler should mark the code on that offset as code and disassemble it.

**Comment by GreyCat** [comment]
General pattern to disassemble opcodes is something along the lines of:

```yaml
seq:
  - id: opcodes
    type: opcode
    repeat: eos
# Simplest case, 1 header byte defines instruction
enums:
  code:
    0x02: add
    0x03: sub
    0x08: jmp
types:
  opcode:
    seq:
      - id: code
        type: u1
        enum: code
      - id: args
        type:
          switch-on: code
          cases:
            add: two_addresses
            sub: two_addresses
            jmp: one_address
  one_address:
    seq:
      - id: addr
        type: u4
  two_addresses:
    seq:
      - id: addr1
        type: u4
      - id: addr2
        type: u4
```
