### ISSUE TITLE
Support marking an integer as a pointer/offset

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#67]
I propose the following syntax:
```yaml
 - id: entry_point
        type:
          switch-on: bits
          cases:
            'bits::b32': u4
            'bits::b64': u8
           ptr: opcode
```
```ptr``` attribute is used to declare that the integer member should be used as a pointer/offset. The value of this attribute is the name of a type of a member the pointer refers. The implementation should parse a member by a pointer. The base address should be specified with the ```ptrbase``` attribute either in ```meta``` or in the same member. The default base is 0. If anyone needs other addressing modes he must specify them explicitly using instances.

There may be better syntaxes for this, for example making ptr a dictionary instead of a string.

**Comment by GreyCat** [comment]
I'm sorry, I don't quite understand the proposal.

> The value of this attribute is the name of a type of a member the pointer refers.

What is "type of a member the pointer refers"? You mean that we should go by that offset in a file/stream, and start parsing something using a type `opcode`? What's wrong with current syntax for that, something like that?

```yaml
seq:
 - id: entry_point
   type:
     switch-on: bits
     cases:
       'bits::b32': u4
       'bits::b64': u8
instances:
  entry_point_opcode:
    pos: entry_point
    type: opcode
```
