### ISSUE TITLE
JavaCompiler generates incorrect code in some switch-on cases in debug mode

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#670]
Following `ksy` produces uncompilable java code in debug mode due that fact, that `switch-on` branches has different types:
```yaml
meta:
  id: bug
seq:
  - id: type
    type: u1
  - id: value
    size-eos: true
    type:
      switch-on: type
      cases:
        0: inner
types:
  inner:
    seq:
      - id: data
        size-eos: true
```
Piece of generated code:
```java
private Object value;
...
switch (type()) {
case 0: {
    this._raw_value = this._io.readBytesFull();
    KaitaiStream _io__raw_value = new ByteBufferKaitaiStream(_raw_value);
    this.value = new Inner(_io__raw_value, this, _root);
    this.value._read();//<<<<<<<<<<<<<<<< BUG: value has type Object
    break;
}
default: {
    this.value = this._io.readBytesFull();
    break;
}
```
