### ISSUE TITLE
Non-standard extra keys in .ksy

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#68]
Let's look at an example first, currently I am using this structure:

```yaml
  vm_prot_flag:
    seq:
      - id: value
        type: u4
    instances:
      read:    { value: (value & 0x01) != 0 }
      write:   { value: (value & 0x02) != 0 }
      execute: { value: (value & 0x04) != 0 }
```

I'd like to extend this structure with "hints" for the IDE, for example how to display the structure.

I'd like to add the following extension point:

```yaml
    seq: ...
    instances: ...
    extensions:
      webide:
        representation: "read={read}, write={write}, execute={execute}"
```

Of course these extension points won't be standardized, but it least enables us to keep every required information in the same file and it's not just for the WebIDE but for other custom tools which may or may not be known to us.

Later if we feel that any of these extension points is worth standardization then we can do it later (and automatically convert existing .ksy files in the repo or ask the author to do it manually).

Also in this concrete case (textual representation / summary of an object) there are limitless possibilities how the user would like to see the data, so the question remains: is it worth to put this information into ksy even if it won't be satisfactory for everybody?

I think the answer is **YES.**

My reasoning is the following:

1. not all .ksy are public. From our current experience I think ppl mostly use Kaitai for private purposes (and they don't upload .ksy to formats repo), so their .ksys are private too, this means they can distribute the extension data freely in the .ksy without disturbing other users and this way they at least won't have to put it in a separate file.

2. even if a .ksy is public, the more structured information is available the better probably. At least in this concrete case I think a default representation will help at least 80% of ppl while it won't suffice only for a few of them. But even who wants to use an other representation will get a default template which is easier to modify than writing a new one from scratch.

**Comment by GreyCat** [comment]
Sorry for somewhat late reply, I've been thinking of this proposal in background, and here's my thoughts:

* In general, lack of standards is evil. We all know that it eventually leads to various incompatible forks, i.e. "ksy written for product X" vs "ksy written for product Y", etc, etc. It kind of kills the purpose of doing the standard in the first place.
* Again, in general, I'm not a big fan of adding any "presentation" markup, i.e. colors for visualization, comments-only-for-visualization, formatting-fields-as-hex-or-oct-only-for-vis, etc, etc. In general, I believe that these things can be done by machine algorithms in a more effective way than doing it by hand.

However:

* On the other hand, it is impractical to restrain innovation by a long process of peer review, thinking things over, etc, etc, especially if we're talking about stuff bringing some "wow" factor, such as Web IDE.
* In fact, there is a great example of what's going on with our somewhat similar "bigger brother" — HTML + CSS. Browser-specific tags, properties, etc, etc, bring the chaos, but in fact they're the necessary evil to make progress (proof of concepts, etc, etc) possible.
* So, it's kind of stupid to fight this progress ;)

So, I'm inclined to say that **yes**, we would want some support for non-standard markup inside ksy. The only thing I want to state really clearly that it must *not* be viewed as "extension point", but rather some fancy stuff for "proprietary", "experimental" API.

Thus I want to propose a slightly different syntax, borrowing it from CSS. Let's just allow keys prefixed with `-` anywhere, and compiler would just totally ignore them (something like `-webkit-opacity`, `-moz-opacity` properties in CSS). I.e. you can add your keys as:

```yaml
    seq: ...
    instances: ...
    -webide:
      representation: "read={read}, write={write}, execute={execute}"
```

or even just:

```yaml
    -webide-representation: "read={read}, write={write}, execute={execute}"
```

if you feel like doing so. We'll kind of reserve "vendor prefix" (`-webide`) for web IDE-specific data and thus it won't clash with anybody else. Also, it's much more flexible, as you can use the same technique to add extra markup to any elements, for example, attributes:

```yaml
seq:
  - id: foo
    type: u4
    -webide-format: hex
    -webide-color: #7C3030
    -webide-visibility: hidden
```
