### ISSUE TITLE
Templated user defined type name

### ISSUE THREAD

**Issue by LmpOSX** [kaitai-io/kaitai_struct#681]
Hi,

  I would be interesting to have some kind of templated, or parametrized, type name. Some kind of:

`- id: some_field`
` type: templated_type(param_1, param_2)`

then I have a templated_type.ksy, something like this:

`imports:`
`  - some_type_<selector>`

`params:`
`  - id: version`
`     type: str`
`  - id: other_param`
`    type: u4`

`seq:`
` - id: a_field`
`.   type: a_type`
` - id: final_field`
`    type: some_type_<selector>(a_field.some_data)`

Then we could have a bunch of some_type_*.ksy files which could do:

`  some_type_one:`
`    params:`
`      - id: some_param`
`      .....`

`  some_type_two:`
`    params:`
`     - id: some_param`
`     ....`

A switch is what I'm using today, but it requires modifying templated_type.ksy for ever new selector of some_type, on imports and case select. The procol I'm working, have lot of versions as selectors, for diferent categories which is also a possible selector.

**Comment by KOLANICH** [comment]
1. please read https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
2. We have a proposal for templates: #135 , why not to just create a template and pass there the already imported type?

```yaml
meta:
  imports: 
    - some_type_one
    - some_type_two
seq:
  - id: a
    type: "templ<some_type_one>"
  - id: b
    type: "templ<some_type_two>"
```

>The protocol I'm working, have lot of versions as selectors, for diferent categories which is also a possible selector.

You may want to merge different versions of the same type into a single type where fields presence, types or sizes are selected depending on version if these version share some parts between them.

**Comment by GreyCat** [comment]
@LmpOSX It's not very clear what problem you're trying to solve from this example, and it's not very clear what a "selector" is, why it is in `<>` brackets and what behavior you expect from it.

Passing types as parameters is indeed something that boils down to templates/generics, and, as @KOLANICH pointed out, if that's something you're ok with, I suggest to merge this into #135 and share your design proposals there?

**Comment by LmpOSX** [comment]
I've read #135 and agree to merge it. But I don't know how to do it.

The selector, is a kind of parameter (I called it selector, because it selects a type), or a form to modify the behavior of a called type (outer-type), in a form similar of a switch-case with the difference that it is used to "form" a (variable) type name (inner-type) within the outer type. In this way, you don't need a switch, and avoid the need to modify the outer type for every new "selector". 

The protocol I'm working is Eurocontrol Asterix format. It is based on the definitions of messages formats for different applications. Those formats are called categories. For example, for radars there is a category 1 definition, for multilateration, there is a category 20, for ADSB there is a category 21, for meteorological cat 8. Also you have different versions, an older radar could implement v1.19 and a new one v1.20. There is no clue of the version inside the message, you have to know it previously (your application configurations should include it). Parsing a different version would throw an eos exception in almost every case.

The differences between categories are only the kind of information transmitted which is defined in a catalog of items, so every category defines a different catalog and a different version of a category has a different catalog with minor modifications. The order of transmission of those items in a message are defined in a User Application Profile. Then in the transmitted message exist a kind of bitmap that signals the presence or absence of an item.

Even though you could define an entire category in one ksy in a way similar to #48, my objective is to have all common procedures and mechanics defined in common ksy and types, in a way you could use the part you need, and leave the definitions of new categories or category versions as a minimum, that is, you only define the catalog and the UAP (and perhaps some special logic inside the category file). This will give the chance anyone could come with new categories at minimum effort, and have all testing and debugging independently of categories or catalogs.

Below is a simplified version of files as I resolved it currently. This code won't compile because a deleted al typecasting necessary in the actual code.

I already defined all the Asterix procedures and mechanics, and I'am now just defining new categories.

Below is code example.
Please, note that the "selectors" are passed in sequence, similar to a parameter, it could be a parameter too, but I imagined it be part of the called type name because no logic is involved just type name selection.

File **catalog_001_v1.20.ksy**
```YAML
params:
  - id: item_ref_num
    type: s2

seq:
  - id: item
    type:
      switch-on: item_ref_num
      cases:
        10:  fixed(true,2)
        20:  extended(true,1,1)
        30:  extended(true,1,1)
        40:  fixed(true,4)
        42:  fixed(true,4)
```
File **catalog_002_v2.00.ksy**
```YAML
params:
  - id: item_ref_num
    type: s2

seq:
  - id: item
    type:
      switch-on: item_ref_num
      cases:
        0:   fixed(true,1)
        10:  fixed(true,2)
        20:  fixed(true,1)
        30:  fixed(true,3)
        41:  fixed(true,2)
        50:  extended(true,1,1)
```

File **category_001v1.20.ksy**
```YAML
    imports:
            - field_spec
            - catalog_001_v1.20

    seq:
        - id: fspec
          type: field_spec # a bit map of included fields of the uap_list

        - id: data
          type: uap_type(fspec, [40,20,30,10,42])
          
    types:
      uap_type:
        params:
          - id: fspec
            type: field_spec
          - id: uap_list

        seq:
          - id: items
            type:
              switch-on: fspec.octects[_index/7].bits[_index % 7]
              cases:
                true: catalog_001(uap_list[ _index ])
            repeat: expr
            repeat-expr: loop_range #the minor of fspec.octects.size*7 and uap_list.size
```
  
File **category_002v2.00.ksy**
```YAML
    imports:
            - field_spec
            - catalog_002
    seq:
        - id: fspec
          type: field_spec # a bit map of included fields of the uap_list
        - id: data
          type: uap_type(fspec, [00,50,30,10,41,20])
          
    types:
      uap_type:
        params:
          - id: fspec
            type: field_spec
          - id: uap_list
        seq:
          - id: items
            type:
              switch-on: fspec.octects[_index/7].bits[_index % 7]
              cases:
                true: catalog_002(uap_list[ _index ])
            repeat: expr
            repeat-expr: loop_range #the minor of fspec.octects.size*7 and uap_list.size
```

As you could see, uap_type is defined in both cat1 and cat2 definitions. And only possibility is some sort of switch, but even this is difficult to implement because there already is a switch to reference the corresponding catalog file.

What I imagine is the following:

We define a **uap_type.ksy**. Using #135 similar definition of template, one could have.
```YAML
template:
  - cat
  - ver

imports:
  catalog_<cat>_<ver>

params:
  - id: fspec
    type: field_spec
  - id: uap_list
  
seq:
  - id: items
    type:
      switch-on: fspec.octects[_index/7].bits[_index % 7]
      cases:
        true: catalog_<cat>_<ver>(uap_list[ _index ])
    repeat: expr
    repeat-expr: loop_range #the minor of fspec.octects.size*7 and uap_list.size
```
Then a category definition changes to just the category information:

File **category_001v1.20..ksy**
```YAML
    imports:
            - field_spec
    seq:
        - id: fspec
          type: field_spec # a bit map of included fields of the uap_list
        - id: data
          type: uap_type<"001","v1.20">(fspec, [40,20,30,10,42])
```

Note that the selected types inside uap_type.ksy, could be imported or not. In my example they are, but you could have them defined in uap_type.ksy. Again it doesn't make much sense in my work but for other examples could be.

You could also, avoid passing a selector for example, you could have:

**uap_type<1:"001">**, or **uap_type<2:"v1.20">**. I imagine the selectors are always strings, but being numbers could be interesting, I could certainly have a benefit if they are. The name of the imported/called type inside uap_type (the inner-type) have no impositions of formats. The user have to know what the definition is so the outer-type finds it, otherwise it will fail at runtime.

A more powerful approach would be a selector is in a parameter or field or instance in calling type, so you could have:

uap_type<1:**instance_name**> or uap_type<1:"001",2:**field_name**>

Finally, another option is all catalog files define the type name always as catalog, and the only difference is in name. This is true in my case. So UAP would be:

```YAML
template:
  - cat
  - ver

imports:
  catalog_<cat>_<ver>

params:
  - id: fspec
    type: field_spec
  - id: uap_list
  
seq:
  - id: items
    type:
      switch-on: fspec.octects[_index/7].bits[_index % 7]
      cases:
        true: catalog(uap_list[ _index ])
    repeat: expr
    repeat-expr: loop_range #the minor of fspec.octects.size*7 and uap_list.size
```
