### ISSUE TITLE
Allow to use enums in parameters

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#682]
In such schema `enum` key in parameter description silently ignored
```yaml
meta:
  id: are
  endian: be
params:
  - id: game
    type: u1
    enum: game_type
enums:
  game_type:
    5: pst
seq:
  # ...
  - id: projectile_traps_cnt
    type: u4
    if: _root.game == game_type::pst
```
Web IDE raises error:
> Parse error: undefined
Call stack: undefined io.kaitai.struct.precompile.ErrorInInput: are: /seq/0/if: can't compare Int1Type(false) and EnumType(List(game_type),CalcIntType)
