### ISSUE TITLE
`bytes` cannot be passed as a param

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#686]
Reviewing https://github.com/kaitai-io/kaitai_struct_formats/pull/258/files#diff-3c137cff8c8fae3998a5eaf9dfc69448R69 by @LmpOSX I have noticed a workaround:

```yaml
params:
    - id: f_fmt
    type: str
....
instances:
  fmts:
    value: f_fmt.as<u1[]>
```

It turned out that bytes cannot be passed as a param:

```yaml
meta:
  id: a
  endian: le
seq:
  - id: a
    size: 2
types:
  b:
    params:
      - id: a
instances:
  c:
    pos: 0
    type: b(a)
```

```Call stack: undefined io.kaitai.struct.format.YAMLParseException: /instances/c/type: can't pass argument #0 of type BytesLimitType(IntNum(2),None,false,None,None) into parameter `a` of type CalcBytesType```
