### ISSUE TITLE
can't pass argument #1 of type ArrayTypeInStream(CalcIntType)

### ISSUE THREAD

**Issue by LmpOSX** [kaitai-io/kaitai_struct#687]
When I try to pass this array [-1,300,20] as parameter I got error: can't pass argument #1 of type ArrayTypeInStream(CalcIntType) into parameter `uap_list` of type CalcBytesType
so I have to cast it as str, then back to s2[] in an instance.

```YAML
called_type([-1,300,20].as<s2[]>.as<str>)

param:
  -id: p1
    type: str

instances:
  p1_list:
    value: p1.as<s2[]>
```
