### ISSUE TITLE
Missing checks in enum value instance

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#694]
When creating a value instance with `enum`, the compiler doesn't check its `value` in any way, it doesn't check if the prop exists:

```yaml
meta:
  id: inst_value_enum_nonexistent_prop
instances:
  should_fail:
    value: does_not_exist
    enum: fruit
enums:
  fruit:
    1: apple
    2: banana
```

This will normally pass (in the devel Web IDE) and the compiler generates this (for Java):

```java
this.shouldFail = Fruit.byId(doesNotExist());
```

It's interesting that if I modify the `value` to an expression (to `value: does_not_exist + 0`), it will correctly run a precompile check and throw

```
io.kaitai.struct.precompile.FieldNotFoundError: unable to access 'does_not_exist' in inst_value_enum_nonexistent_prop context
```

So it will be probably enough to run the the precompile checks even if the value is a plain `Ast.identifier`.

**Comment by GreyCat** [comment]
Good catch, thanks!

**Comment by Mingun** [comment]
This is fixed currently. In devel IDE:
```yaml
meta:
  id: issue694
instances:
  value:
    value: unknown
```
```
(main): /instances/value/value:
	error: unable to access 'unknown' in issue694 context
```
