### ISSUE TITLE
Enums: a method to add documentation and original IDs

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#70]
Currently we are not restricting enum names to lower_case format, like in this issue https://github.com/kaitai-io/kaitai_struct_formats/pull/11.

I found that most of the time enums are declared as uppercase constants in many specifications and they can contain "type" prefixes (`MH_`, `CSMAGIC_`, `CSSLOT_`, etc in the referenced case) but these prefixes should be dropped and name of enum should be converted the lowercase because they are look better to compiled into `enum CsMagic { Requirement, CodeDirectory, ... }` instead of `enum CsMagic { CsmagicRequirement, CsmagicCodedirectory, ... }`.

But then the original enum name changes in the ksy too much that it becomes hard to Google it afterwards.

So maybe it would be good if we could add a meta tag to the enum values too which can contain the original enum name (also we could add description field). Currently these can be done via comments in an unstructured manner.

**Comment by GreyCat** [comment]
Actually, it might be a good idea to allow 2 syntaxes for enums: "brief" one, as we have now (i.e. number -> string map, and that's all):

```yaml
enums:
  animals:
    1: dog
    2: cat
```

and "verbose" one, that will map number into map, i.e. something like

```yaml
enums:
  animals:
    1:
      id: dog
      doc: A member of genus Canis.
      original-name: MH_DOG
    2:
      id: cat
      doc: Small, typically furry, carnivorous mammal.
      original-name: MH_FELINE
```

At the very least, there is potential for `doc` field there (to generate docstrings for individual constant values), plus, as you've mentioned, something like `original-name` might be a good idea.
