### ISSUE TITLE
Calculated instance from array

### ISSUE THREAD

**Issue by Jakeler** [kaitai-io/kaitai_struct#700]
Hi, in the protocol for my application are some elements with variable quantity:
```yaml
seq:
  ...
  - id: temp_count
    type: u1
  - id: temp_values
    type: u2
    repeat: expr
    repeat-expr: temp_count
```
This produces of course an array in `temp_values`. Then i would like to apply a calculation on every element of the array and get a new array, so i tried it simply like this:
```yaml
instances:
  temp_celsius:
    value: temp_values * 0.1 - 273.1
    doc: Temperature of NTCs
```
But it fails to compile with:
```
(main): /instances/temp_celsius/value: can't apply operator Mult to ArrayType(IntMultiType(false,Width2,Some(BigEndian))) and CalcFloatType 
```
I know single values can be accessed with `temp_values[i]`, but how to do it with all elements?

**Comment by generalmimon** [comment]
Storing raw values and the respective calculated values in Celsius looks like a common programming antipattern. It's essentially the same as e.g. storing 2D points in a plane in 2 integer arrays, one array storing X coordinates and the second for Y coordinates. That's much harder to maintain than having a single array a new type `Point` storing both coordinates, because you have to make extra effort to keep the arrays in sync. And you're separating closely related data that don't have any meaning on their own, and this will haunt you throughout the whole program.

The same applies for the case you're solving, it's more convenient and also makes more sense to create a new type `temp`, which will look like this:

```yaml
types:
  temp:
    seq:
      - id: value_raw
        types: u2
    instances:
      value_celsius:
        value: value_raw * 0.1 - 273.1
```
