### ISSUE TITLE
Proposal: introduce boolean pseudo-type `bool` similar to that of `str` for strings

### ISSUE THREAD

**Issue by mewmew** [kaitai-io/kaitai_struct#704]
From: https://github.com/kaitai-io/kaitai_struct/issues/642#issuecomment-589289806

As a new and very excited user of Kaitai Struct, I jumped straight in, and read enough of the docs to be dangerous :) As such, I interpreted `b1` as meaning *boolean*.

Well, that was until I used the Kaitai Struct IDE on a sample input and realized `b1` reads *one bit* of the stream, not one byte. To a new user, this was confusion at first since `u1`, `s1` both read 1 byte. However, it becomes clear once you start to think of the `b` prefix in terms of number of bits in a bit stream.

As *boolean* is a rather common field type of various binary formats, it would seem useful to users of Kaitai Struct if a `bool` pseudo-type was defined, similar to how `str` is treated for strings.

I propose the introduction of `bool` as a pseudo-type for *boolean* values and furthermore propose that the `size` field may be used in combination with the `bool` type to specify the size (in number of bytes) of the boolean field.

Previously, a user would write `u4` for 32-bit booleans and `u1` for 8-bit booleans (both of which are common in C code). The single bit boolean `b1` is common in bitstream formats (e.g. FLAC), but byte-sized and dword-sized boolean values are also quite common.

So, to sum up, as a new user of Kaitai Struct, this is about the only issue I ran into. Everything else has been a breeze and especially since I started to use the Kaitai Struct IDE, writing format specifications became quite a fun an exhilarating experience.

Keep up the awesome work!

And happy reversing!

Cheers,
Robin

P.S. I've attached below a few example uses of the proposed *boolean* pseudo-type `bool`.

```yaml
      - id: discovered
        type: bool # bool
        size: 1 # each element of the array is 8-bits
        repeat: expr
        repeat-expr: 40 * 40 # [40][40]bool; per element, 0 => false, otherwise => true

      - id: automap_enabled
        type: bool # bool (8-bit); 0 => false, otherwise => true
        size: 1

      - id: inactive
        type: bool # bool (32-bit); 0 => false, otherwise => true
        size: 4
```
