### ISSUE TITLE
use "process" outside of top level "seq"

### ISSUE THREAD

**Issue by Hedzin** [kaitai-io/kaitai_struct#706]
Not sure if it is a bug or feature, but looks like **process** may be used only in top level "seq" block.
details below:

I have to use **process: ror(1)** to decode old game .pak file.
in this case all file is encoded except last 4 bytes 
my initial ksy was looked like:
```
meta:
  id: autothief_pak
  file-extension: pak
  application: CarJacker game
  endian: le
instances:
  toc_count:
    pos: _io.size - 4
    type: s4
  toc:
    pos: _io.size - 4 + toc_count * 144
    type: toc_record
    repeat: expr
    repeat-expr: -toc_count
types:
  toc_record:
    seq:
      - id: name
        type: strz
        encoding: UTF-8
        size: 128
      - id: ofs_body
        type: u4
      - id: len_body
        type: u4
      - id: unk1
        type: u4
      - id: unk2
        type: u4
    instances:
      file_content:
        pos: ofs_body
        size: len_body
```
and i tried to insert **process: ror(1)** in next places, but all attempts were unsuccessful:
1) inside top level instanses:
![image](https://user-images.githubusercontent.com/10382757/75116720-3696b000-567c-11ea-8329-6608f94e1164.png)

file was accepted by ksv but i got error while opened second level object 
![image](https://user-images.githubusercontent.com/10382757/75116672-dc95ea80-567b-11ea-949c-f249a742a3e0.png)

2) inside types 
![image](https://user-images.githubusercontent.com/10382757/75116739-7362a700-567c-11ea-832f-ece70e61a14c.png)

file was rejected by ksv during processing
![image](https://user-images.githubusercontent.com/10382757/75116748-97be8380-567c-11ea-9a05-34a951260028.png)

So after I checked all examples in format folder of  kaitai-struct-compiler, i found that in all examples the **process** is used in high level seq only.
So i rewrited my ksy into next form:

```
meta:
  id: autothief_pak
  file-extension: pak
  application: CarJacker game
  endian: le
seq:
  - id: body
    size: _io.size-4
    process: ror(1)
    type: pak_body
  - id: toc_count
    type: s4
types:
  pak_body:
    instances:
      toc:
        pos: _io.size + _root.toc_count * 144
        type: toc_record
        repeat: expr
        repeat-expr: -_root.toc_count
  toc_record:
    seq:
      - id: name
        type: strz
        encoding: UTF-8
        size: 128
      - id: ofs_body
        type: u4
      - id: len_body
        type: u4
      - id: unk1
        type: u4
      - id: unk2
        type: u4
    instances:
      file_content:
        pos: ofs_body
        size: len_body
```

And it works as expected but ksy file itself has become much less simple and beautiful as
I had to add unnessesary seq objects on top level to apply **processing**.

So the  question is:
Was i miss somethig or it's really impossible to add processing into the blocks i mentioned above?
