### ISSUE TITLE
Cannot use enum constant in math expression

### ISSUE THREAD

**Issue by smx-smx** [kaitai-io/kaitai_struct#713]
Define an enum

```
enums:
  my_enum:
    10: bar
```

Then try to use `my_enum::bar` as part of the `pos` item of a substream, e.g

```
instances:
  foo:
    pos: some_field - my_enum::bar
    size: 50
```

Results in
```
Call stack: undefined io.kaitai.struct.precompile.TypeMismatchError: can't do IntMultiType(false,Width4,Some(LittleEndian)) Sub EnumType(List(my_enum),CalcIntType)
```

which disappears if i use the constant directly instead of the enum
