### ISSUE TITLE
Conditional valid check

### ISSUE THREAD

**Issue by jocelynke** [kaitai-io/kaitai_struct#716]
Hi,

Thanks for your awesome work on Kaitai. I was wondering the possibility to conditionally check the validity of a field based on an other field. Let's say :
```yaml
seq:
  - id: kind
    type: u4
    enum: item_kind
  - id: size
    type: u4
    valid : ????
enums:
  item_kind:
    0: kind1
    10: kind2
    20: kind3
```
How can I check the validity of size of according to kind ? What I would like is to express : "if kind == kind1 then size == 12; if kind == kind2 then size = 6; else no check".

Right now I am using TLV so size has a different type for each kind, but I think this is a bit overkill.

Thank you for your help !

**Comment by generalmimon** [comment]
@jocelynke This is already proposed in the issue https://github.com/kaitai-io/kaitai_struct/issues/435#issue-323332353 as `valid/expr` key. It's not yet implemented, but when it is, you'll be able to use any expression in it that evaluates to `true` or `false` involving any properties you want to use (substituting `_` with an actual attribute value, i.e. the attribute to which the `valid` key applies). The particular case you're dealing with could look like this:

```yaml
seq:
  - id: kind
    type: u4
    enum: item_kind
  - id: size
    type: u4
    valid:
      expr: |
        kind == item_kind::kind1
          ? _ == 12
          : kind == item_kind::kind2
            ? _ == 6
            : true
enums:
  item_kind:
    0: kind1
    10: kind2
    20: kind3
```

But as mentioned, this currently doesn't work because it's not yet implemented. I'll try to make it work this week, but I don't promise anything.

**Comment by jocelynke** [comment]
Ok great ! No rush, that was a proposal !

**Comment by generalmimon** [comment]
@jocelynke
Actually, I can think of an alternative solution, which is already available in the current compiler. You can use any expressions in `valid/eq` too, so this works as well:

```yaml
seq:
  - id: kind
    type: u4
    enum: item_kind
  - id: size
    type: u4
    valid:
      eq: |
        kind == item_kind::kind1
          ? 12
          : kind == item_kind::kind2
            ? 6
            : size
enums:
  item_kind:
    0: kind1
    10: kind2
    20: kind3
```

It uses a slight hack though ("no check" is done by asserting `size == size`), but it works! If you prefer, you can omit the `eq` key and put the expression directly to the `valid` key.
