### ISSUE TITLE
Repeat seemingly not creating substream

### ISSUE THREAD

**Issue by brumik** [kaitai-io/kaitai_struct#722]
From the documentation: “Any repetition (and this includes repeat: eos) uses current object’s IO stream. Substreams are created individually for every object inside the loop.”
(https://doc.kaitai.io/user_guide.html#_repeating_until_total_size_reaches_limit)

Then I could use the relative positioning described here: (https://doc.kaitai.io/user_guide.html#_relative_positioning).

However, no matter how I tried it did not work as expected.
```yaml
# block.ksy (which is in a substream)
- id: txns
  type: tx
  repeat: expr
  repeat-expr: txn_count.number

# where the tx is imported form the tx.ksy:
instances:
  has_flag:
    pos: 4
    type: u2
```
(https://gitlab.nesad.fit.vutbr.cz/Brumik/bitcoin_protocol_ksy/blob/master/ksy/block.ksy#L12)
(https://gitlab.nesad.fit.vutbr.cz/Brumik/bitcoin_protocol_ksy/blob/master/ksy/tx.ksy#L33)

By the documentation the `has_flag` should be relative to the `tx` substream which is created in the repetition, however, it is relative to the `block` substream.

As nowhere else to turn: Is it possible that the implementation has an error in it?

I tested by using the WebIDE.

**Comment by generalmimon** [comment]
> By the documentation the `has_flag` should be relative to the `tx` substream which is created in the repetition, however, it is relative to the `block` substream.

Of course, `size` creates substream just on the field where you define it, it **doesn't** create a substream on every repeated field that is contained in this substream unless this field has its own `size` key.

A substream in terms of Kaitai Struct is a sequence of bytes with fixed byte size that has to be known at the time of its creation. It isn't possible to cross the boundaries of the stream, this will always fail with an End-Of-Stream error _(unfortunately it's common to call it End-Of-File error, but that's misleading because the end of stream does not necessarily mean the end of file)_. The top-level stream is the one representing the data of the whole binary file loaded into the parser.

Fields defined in `seq` map of a user-defined type always operate with the current IO stream, as well as parse `instances` (if they don't have `io` key). Parse `instances` have also the `pos` key, which specifies the offset relative to the beginning of the current stream. The value of the current IO stream depends on the usage of the given type. There are two options:

1. the user-defined type is used without the `size` or `size-eos` key ⇒ it continues to use the existing stream:
```yaml
seq:
#                ------- offset 0
  - id: rubbish
    type: u4
#                ------- offset 4
  - id: stream
    type: my_type # no `size` here
my_type:
  seq:
#                ------- offset 4
    - id: foo
      size: 7
#                ------- offset 11
    - id: number
      type: u2
#                ------- offset 13
```

2. type usage contains `size` or `size-eos` key ⇒ creates a new substream starting on the current position in the stream (or the offset specified in `pos` key in case of parse `instances`):

```yaml
seq:
#                ------- offset 0
  - id: rubbish
    type: u4
#                ------- offset 4
  - id: stream
    type: my_type # contained in a substream from byte 4 inclusive to byte 20 exclusive
    size: 16
my_type:
  seq: # has own substream
#                ------- offset 0
    - id: foo
      size: 7
#                ------- offset 7
    - id: number
      type: u2
#                ------- offset 9
```

And how this works for fields using repetition: if the repeated field has `size` key, the `size` is applied to **each element individually** and NOT for the whole array. That's what the documentation is trying to say with the sentence "Substreams are created individually for every object inside the loop.", but that applies **only if the `size`** key is present. Simply put, writing this:

```yaml
seq:
  - id: items
    size: 2
    type: item
    repeat: expr
    repeat-expr: 3
```

... is essentially doing this:

```yaml
seq:
  - id: items[0]
    size: 2
    type: item
  - id: items[1]
    size: 2
    type: item
  - id: items[2]
    size: 2
    type: item
```

But keep in mind that the individual items in a repetition won't be wrapped in their own substreams by themselves without the `size` key as you imply. If the `size` is missing, the elements will just continue to use the existing IO stream.
