### ISSUE TITLE
nested/imported types don't support parameters (:: syntax ignores parameters)

### ISSUE THREAD

**Issue by fudgepop01** [kaitai-io/kaitai_struct#724]
Consider the following two files:

```yaml
# common_types.ksy
meta:
  id: common
  endian: be
types:
  my_type:
    params:
      - id: my_param
        type: s2
    seq:
      - id: param_thing
        type: s4
        repeat: expr
        repeat-expr: my_param
```

```yaml
# main.ksy
meta:
  id: test
  endian: be
  imports:
    - common_types
seq:
  - id: thing
    type: common::my_type(2) # will throw an error when compiled
```

As the comment suggests, common::my_type(2) will throw an error when attempting to compile. 

in the case that `my_type` *does* have its param *and* the type referenced in `main.ksy` was just `common::my_type`, it will be treated as an opaque type and compile (as it... should(?)).

if `my_type` didn't have a param and `common::my_type(2)` was just `common::my_type` it will find `my_type` in the other file and compile properly.

---

I assume that when the compiler encounters `::` in a type it will attempt to do something like this:
```
if (referenced type exists) {
  use that type
} else if (type is a valid opaque type name) {
  treat it as an opaque type
} else {
  give up and throw an error
}
```

if this is the case, this could theoretically be fixed by adding a third condition after the others fail that checks to see if () exists at the end of the current "level" of nested identifiers

**Comment by GreyCat** [comment]
Can I ask you to go ahead and add this to the [tests](https://github.com/kaitai-io/kaitai_struct_tests) repo as a test format in `formats/` and KST spec in `spec/ks`?

I wonder if we can even reproduce it within one file: it's not necessary to bring imports, `nested::type` syntax should work within one file just fine.

**Comment by fudgepop01** [comment]
One of the shortest ways to reproduce it in one file is like this:

```yaml
meta:
  id: test
  endian: be
seq:
  - id: my_amazing_seq_block
    type: test::my_type(2)
types:
  my_type:
    params:
      - id: repeat_count
        type: s4
    seq:
      - id: repeated_thing
        type: s4
        repeat: expr
        repeat-expr: repeat_count
```

and yep! I'll add it to `formats/` and `spec/ks`, no prob
