### ISSUE TITLE
Support type key for Calculated ("value") instances

### ISSUE THREAD

**Issue by lvntbkdmr** [kaitai-io/kaitai_struct#725]
When I define a ksy structure in this format;
```
  data_type:
    seq:
      - id: data
        type: s4
    instances:
      data_instance:
        value: data / 65536
```
It generates data_instance also in **int32** type for cpp_stl, but what i need is a float type which originally multiplied by some scale factor (65536 in this case) to strecth between 32-bit signed range. 
When I try to define `type` along with `value` key, it gives me error.

Is it possible for you to add type defining capability for calculated instances ?

Thanks in advance.
