### ISSUE TITLE
Kaitai Struct - How to reference object variable from imported ksy file as size

### ISSUE THREAD

**Issue by ElizabethCapararo** [kaitai-io/kaitai_struct#734]
I have an external ksy file specifically designed to hold an "object" in ksy, it holds something called `coffee`, where `coffee` has attributes `identifier`, `length_in_bytes` and `flavor`.

I am importing `coffee` into my main ksy file and wish to use the value `length_in_bytes` as the `size` attribute for another "object" read in through `seq`.

The code below will explain more succinctly what is happening:

> testfile.ksy

    meta:

      id: testfile

      imports:

         - drinks

      title: testfile

      # additional information here defining file-extension, endian and encoding

      # additional information here defining doc

      

    seq:

      - id: drinksset

        type: drinks

        repeat: expr

        repeat-expr: 2

    

    types:

      drinks:

        seq:

          - id: drinks_listings

            type: coffee

            size: coffee.length_in_bytes

> drinks.ksy

    meta:

       id: coffee

       title: coffee

       # additional information here defining file-extension encoding & endian

       # additional information here defining doc

    

    types:

        coffee:

          seq: 

            - id: identifier

              type: u4

            - id: length_in_bytes

              type: u4

            - id: flavor

              type: u4

          

My issue is with the line: 

    size: coffee.length_in_bytes

 - I know this, because removing this line allows the ksy file to successfully read from the test data file. 

 - When I have the types information for coffee inside `testfile.ksy`, there is **no issue**, it is only when the `coffee` type is imported in a separate file that is has issues. 

 - I am able to read other attributes I may define in `coffee.ksy` without issue, for instance declaring a custom data-type called `u4test` with `type: u4` and referencing that instead of `u4` for `flavor` works fine.

I believe it may be a Kaitai typing issue, and have tried the following:

 - `size: coffee::length_in_bytes`

 - `size: coffee.as<coffee>.length_in_bytes`

 - `size: coffee.as<u4>.length_in_bytes`

 - `size: _parent.coffee.as<coffee>.length_in_bytes`

 - `size: _parent.coffee.as<u4>.length_in_bytes`

But nothing has worked.

Refer [Kaitai.io](http://kaitai.io/)

Thankyou, insight is appreciated.

**Comment by generalmimon** [comment]
There is no single problem here, it seems to me that there are several misunderstandings how types and imports works in KS.

1. The naming you use is confusing and misleading. The imported file from `testfile.ksy` is called **`drinks.ksy`**, the type it contains is named `coffee` (which contains another type called `coffee`), and `drinks` is yet another type defined in `testfile.ksy`:

```yaml
# testfile.ksy
meta:
  id: testfile # (top-level type)
types:
  drinks: # testfile::drinks
    # ...
```

```yaml
# drinks.ksy
meta:
  id: coffee # (top-level type)
types:
  coffee: # coffee::coffee
    # ...
```

The name of the top-level type is identified by `meta/id` key, the subtypes are declared in `types` map. Every KSY has just one top-level type, whereas there can be an unlimited number of subtypes and every subtype can have nested types as well. See https://doc.kaitai.io/user_guide.html#_substructures_subtypes.

Note that `meta/imports` specifies just the name of the file you want to import without the `.ksy` extension, it has nothing to do with the actual type names that are contained in these files. But I always recommend to keep the top-level type name and the .ksy file name the same, because it doesn't bring useless confusion.

2. When you try to compile the KSY format specifications, you get this error:

```yaml
/types/drinks/seq/0/size: unable to access 'coffee' in testfile::drinks context
```

This is because there indeed isn't any field `coffee` to refer to. The only thing named `coffee` is a user-defined type, but you can never use user types in expressions. You can just use initialized fields in `seq` and `instances`. I don't know what language you're familiar with, but it's similar as accessing properties and methods (not static) of the class, without creating an instance from it.

And no matter how hard I try, I can't guess what you intend by this line:

```yaml
size: coffee.length_in_bytes
```

Why do you need to use `size` in the first place? If you use `size` in conjunction with user-defined `type`, it creates a substream with the byte size declared in `size`. You can read about substreams in [User Guide: 5. Streams and substreams](https://doc.kaitai.io/user_guide.html#_streams_and_substreams).

So the code you posted implies that you want to reserve the size for the `coffee` structure in advance. However, according to that the size is `coffee.length_in_bytes` and the type is `coffee`, it looks like that you want to read the `length_in_bytes` from some previously fetched field of type `coffee`, but I don't understand from which one (probably from the just parsed `drinks_listings`? - then you use self-referencing `size` on it) and what you expect from `size: coffee.length_in_bytes` to do then.

> * When I have the types information for coffee inside `testfile.ksy`, there is **no issue**, it is only when the `coffee` type is imported in a separate file that is has issues.

I doubt that, importing a file is functionally equivalent to inlining the imported top-level type to `types` map of the primary spec. You must've done something differently.

Can you give some more context? What you're trying to do? Which format are you describing? Why do you need to use imports?

**Comment by ElizabethCapararo** [comment]
Thankyou for your response generalmimon, you have given me a lot to consider.

In answer to your questions:

**1. Why do you need to use imports?**
I need to use imports as this is a much larger project than that I have generically outlined above, the `drinks.ksy` is not only referenced in `testfile.ksy` but a number of others as well. It is as a result of this, that I don't want to have to manually copy in the contents of `drinks.ksy` into each file referencing it's types, so wish to use imports instead.

2. What do you mean by `size: coffee.length_in_bytes`?
For this one, I apologise, it is clear that when I attempted to make my question generic, that I forgot to add something. Please see the revised version of `testfile.ksy` which references an instantiated variable of type coffee, rather than the type itself.

If you are able to assist me in this instance from the updated information, it would be much appreciated!

```

meta:
  id: testfile
  imports:
    - drinks
  title: testfile
  # additional information here defining file-extension, endian and encoding
  # additional information here defining doc
seq:
  - id: drinksset
    type: drinks
    repeat: expr
    repeat-expr: 2
types:
  drinks:
    seq:
     - id: coffee_item
       type: coffee
       size: 10
      - id: drinks_listings
        type: drink_item
        size: coffee_item.length_in_bytes
     - id: drink_item
       type: u4
       doc: generic item used to hold a drink

**Comment by generalmimon** [comment]
@ElizabethCapararo I can already see the problem - as I already said, the structure of the `drinks.ksy` looks like this:

```yaml
# drinks.ksy
meta:
  id: coffee # `type: coffee`
types:
  coffee: # `type: coffee::coffee`
    # identifier, length_in_bytes, flavor
```

I've written the examples how you would use these types in the `testfile.ksy`. As you can see, to access the type `coffee` with fields `identifier`, `length_in_bytes` and `flavor`, you would have to write `type: coffee::coffee`.

I wrote that every import is functionally equivalent to and can be replaced with copy-pasting the imported top-level type to `types` map of the KSY (well, you only have to use the imported top-level type identifier from `meta/id` as the key, under which you put the whole type). In your case, it would mean that `testfile.ksy` looking like this does exactly the same as the structure `testfile.ksy` ⟵ `drinks.ksy` you describe:

```yaml
# testfile.ksy (with inlined `drinks.ksy`)
meta:
  id: testfile
  imports:
    - drinks
  title: testfile
  # ...
seq:
  - id: drinksset
    type: drinks
    repeat: expr
    repeat-expr: 2
types:
  drinks:
    seq:
      - id: coffee_item
        type: coffee # should be `type: coffee::coffee`
        size: 10
      - id: drinks_listings
        type: drink_item
        size: coffee_item.length_in_bytes
      - id: drink_item
        type: u4
        doc: generic item used to hold a drink
  coffee: # <---------+
    meta: #           |
      # id: coffee  --+
      title: coffee
      # ...
    types:
      coffee:
        seq: 
          - id: identifier
            type: u4
          - id: length_in_bytes
            type: u4
          - id: flavor
            type: u4
```

So one solution of the problem is to use `type: coffee::coffee`, and the other is to rewrite the `drinks.ksy` like this:

```yaml
# drinks.ksy
meta:
  id: coffee
  title: coffee
  # additional information here defining file-extension encoding & endian
  # additional information here defining doc
seq: 
  - id: identifier
    type: u4
  - id: length_in_bytes
    type: u4
  - id: flavor
    type: u4
```

Note that the top-level type from the imported drinks.ksy is also a type, so you can just define `seq` at the top level (and it will belong to the top-level type `coffee`). That way, after importing the `drinks.ksy` from your `testfile.ksy`, you can just use `type: coffee` and it will work as you expect.

I recommend reading the section about imports in [the User Guide](https://doc.kaitai.io/user_guide.html#_importing_types_from_other_files) and try to understand the example, it uses the same approach.

**Comment by LmpOSX** [comment]
From response above, referecing a subtype using :: works as expected if type and its corresponding subtype are on the same ksy file as the calling (parent) type.

However, if the referenced subtype is defined on an imported ksy file (imported type), then two missing parts exists at least in python generated code.

First, no import clause for the python module defining the imported type (Class) and subtype (subclass) is included on top-level calling python module and,
Second, no python module name prefixing is added to the called type::subtype constructor.

Thank you!.

Below is an example:

```yaml

meta:
  id: type1
  endian: be
  imports:
      - type3

seq:
  - id: one
    type: u1

  - id: two
    type: type2::subtype2

  - id: three
    type: type3::subtype3

types:

  type2:

    types:
      subtype2:
        seq:
          - id: field2
            type: u1
```

Generated python code

```python

from pkg_resources import parse_version
import kaitaistruct
from kaitaistruct import KaitaiStruct, KaitaiStream, BytesIO

###################
# missing -> import type3
###################

if parse_version(kaitaistruct.__version__) < parse_version('0.9'):
    raise Exception("Incompatible Kaitai Struct Python API: 0.9 or later is required, but you have %s" % (kaitaistruct.__version__))

class Type1(KaitaiStruct):
    def __init__(self, _io, _parent=None, _root=None):
        self._io = _io
        self._parent = _parent
        self._root = _root if _root else self
        self._read()

    def _read(self):
        self.one = self._io.read_u1()
        self.two = Type1.Type2.Subtype2(self._io, self, self._root)
        self.three = Type3.Subtype3(self._io, self, self._root)
        ## should be -> self.three = type3.Type3.Subtype3(self._io, self, self._root)

    class Type2(KaitaiStruct):
        def __init__(self, _io, _parent=None, _root=None):
            self._io = _io
            self._parent = _parent
            self._root = _root if _root else self
            self._read()

        def _read(self):
            pass

        class Subtype2(KaitaiStruct):
            def __init__(self, _io, _parent=None, _root=None):
                self._io = _io
                self._parent = _parent
                self._root = _root if _root else self
                self._read()

            def _read(self):
                self.field2 = self._io.read_u1()
```
