### ISSUE TITLE
Question: Mention type under switch

### ISSUE THREAD

**Issue by NN---** [kaitai-io/kaitai_struct#735]
For instance I have something like this:

I want to parse nextfield only if version has type v1 and its value is '1'.

```yaml
seq:
  - id: version
    type: obj
  - id: nextfield
    type: string
    # Error version.body is not usable here: Types are not compatible
    if version.hdr.tag == header_type::v1 and version.body == 1

types:
  obj:
    seq:
    - id: hdr
      type: header_type
    - id: body
      size: hdr.len.value
      type:
        switch-on: hdr.tag
        cases:
          header_type::v1: int
          header_type::v2: string

  header_type:
    seq:
    - id: tag
      type: u1
    - id: len
      type: u1

enums:
   header_type:
     v1: 1
     v2: 2
```

**Comment by generalmimon** [comment]
@NN--- 
You can use [type casting](https://doc.kaitai.io/user_guide.html#typecast):

```yaml
seq:
  - id: version
    type: obj
  - id: nextfield
    type: string
    # Error version.body is not usable here: Types are not compatible
    if version.hdr.tag == header_type::v1 and version.body.as<int>.{ATTRIBUTE} == 1
```

But please keep in mind that regardless of how your `int` struct type looks like, you can never compare it to an integer directly (until we have [inlining](https://github.com/kaitai-io/kaitai_struct/issues/88), then you would be able to use the struct just like an integer), so please fill the concrete attribute of the `int` type (I marked it with the `{ATTRIBUTE}` placeholder).
