### ISSUE TITLE
ReferenceError: i is not defined when using _index and .to_i 

### ISSUE THREAD

**Issue by TACIXAT** [kaitai-io/kaitai_struct#737]
I might just be doing something wrong, but here is a minimal repro. I am working on another file format and I do not see a great way to work around this. 

```yaml
meta:
  id: repro
  file-extension: repro
  encoding: utf-8
seq:
  - id: header
    type: header
  - id: data
    type: data
    repeat: expr
    repeat-expr: header.ndata.to_i
types:
  header:
    seq:
      - id: ndata
        type: str
        size: 1
      - id: b
        type: str
        size: 1
        repeat: expr
        repeat-expr: 3
  data:
    seq:
      - id: d
        type: str
        size: _parent.header.b[_index].to_i
```

Target file is just `3543555554444333`, trying to parse like `3`, `5`, `4`, `3`, `55555`, `4444`, `333`. When using `_parent.header.b[_index].to_i` I get an error that says `i is not defined`. 

```
Parse error: undefined
Call stack: undefined ReferenceError: i is not defined
```

I am thinking this is a possible collision between `_index` getting translated to `i` and maybe stomping `i` in `to_i`? Or I am just doing something wrong :)

Thanks!

**Comment by TACIXAT** [comment]
Ah, I have solved it by passing in `_index` as a param.

```
meta:
  id: repro
  file-extension: repro
  encoding: utf-8
seq:
  - id: header
    type: header
  - id: data
    type: data(_index)
    repeat: expr
    repeat-expr: header.ndata.to_i
types:
  header:
    seq:
      - id: ndata
        type: str
        size: 1
      - id: b
        type: str
        size: 1
        repeat: expr
        repeat-expr: 3
  data:
    params:
      - id: idx
        type: u1
    seq:
      - id: d
        type: str
        size: _parent.header.b[idx].to_i
```
