### ISSUE TITLE
DNS UPDATE

### ISSUE THREAD

**Issue by NN---** [kaitai-io/kaitai_struct#741]
According to RFC:
https://tools.ietf.org/html/rfc2136
```
   Opcode  A four bit field that specifies the kind of request in this
           message.  This value is set by the originator of a request
           and copied into the response.  The Opcode value that
           identifies an UPDATE message is five (5).
```

When certain bits in opcode are 5 the whole structure afterwards is totally different.

How this is declared in Kaitai ?
https://github.com/kaitai-io/kaitai_struct_formats/blob/master/network/dns_packet.ksy

**Comment by GreyCat** [comment]
Looks like generally it should handled by something like a switching type:

```yaml
# ...
  - id: flags
    type: packet_flags
  - id: body
    type:
      switch-on: flags.opcode
      cases:
        0: normal_body
        1: normal_body
        2: normal_body
        5: update_body
```
