### ISSUE TITLE
Why u1 has differnet behavior than b8

### ISSUE THREAD

**Issue by alloncm** [kaitai-io/kaitai_struct#743]
Any particular reason this code is expecting at least 3 bytes?
``` yaml
meta:
  id: kaitai
  endian: be
seq:
  - id: flag
    type: b1
  - id: small_num1
    type: b7
    if: flag == false
  - id: small_num2
    type: u1
    if: flag == false
  - id: big_num
    type: b15
    if: flag == true
```
and this code expecting at least 2 bytes?
``` yaml
meta:
  id: kaitai
  endian: be
seq:
  - id: flag
    type: b1
  - id: small_num1
    type: b7
    if: flag == false
  - id: small_num2
    type: b8
    if: flag == false
  - id: big_num
    type: b15
    if: flag == true
```

My desired behavior is the second one (and I think the first one isn't very intuitive (at least for me))

**Comment by generalmimon** [comment]
@alloncm Please never post code examples as screenshots, wrap the KSY snippets in the ["fence code blocks"](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting) with `yaml` language identifier if you're inserting KSY language:  (` ```yaml ` + newline + {your code} + newline + ` ``` `)

**Comment by alloncm** [comment]
@generalmimon Really sorry.
fixed it

**Comment by generalmimon** [comment]
@alloncm Yeah, it's a bug in the compiler. The reason why this happens is that if the compiler encounters a bit-sized integer (`bX`) before a byte-aligned one (= any other type in KS), it inserts an `alignToByte` call, which aligns the current stream position to the nearest higher byte boundary (it's mentioned in the [User Guide](https://doc.kaitai.io/user_guide.html#_bit_sized_integers)). That's necessary in order to keep the internal state of `KaitaiStream` consistent, if it hadn't been inserted, then the third field (`b7`) in sequence `b4` - `u1` - `b7` would give incorrect results, because the internal "bit stream position" still remains in the byte with the `b4` (slightly simplified, but it's enough for idea).

However, the compiler currently ignores any `if` conditions and repetitions on the attributes when performing the "unaligned-aligned" check, and it treats all subtypes and  fields with [type-switching](https://doc.kaitai.io/user_guide.html#tlv) as byte aligned. But don't worry, I've already figured out the solution, and hopefully it won't take long to implement it. The idea is actually quite simple: anytime the compiler is unsure if a byte-aligned type in reads may be preceded with a bit-sized integers somehow, it inserts the `alignToByte()` call, but only just before the reading (i.e. on the previous line). So when with a structure `b3` - `if(T) { u1 }` - `b2`, it will do `a = readBitsInt(3); if (T) { alignToByte(); b = readU1(); } c = readBitsInt(2)`. Or when this type-switching with repetition is performed:

```yaml
seq:
  - id: a
    type:
      switch-on: _index
      cases:
        0: b2
        1: u1
    repeat: expr
    repeat-expr: 2
```

it will compile to this:

```js
this.a = [];
for (var i = 0; i < 2; i++) {
  switch (i) {
  case 0:
    this.a[i] = this._io.readBitsIntBe(2);
    break;
  case 1:
    this.alignToByte();
    this.a[i] = this._io.readU1();
    break;
  }
}
```

This way, if the detection algorithm will be solid, we can be sure that the alignment will be always present when it should be, and it won't be invoked anywhere where it shouldn't be.
