### ISSUE TITLE
More than one layer of process

### ISSUE THREAD

**Issue by alloncm** [kaitai-io/kaitai_struct#745]
Hi lets say I have 10 bytes and I want to run a custom `process` on them that outputs 9 bytes and than depends on the first byte value run one of two other `process`es on the remaining 8 bytes (and then maybe another process but I think you got the idea).
something like this:
I hope this kaitai psuedo code is clear enough
``` yaml
meta:
  id: kaitai
  endian: be
seq:
  - id: p
    size: 10
    process: my_processor1
  - id: p1
    type: process2(p)
    if: p[0] == 0
  - id: p2
    type: process3(p)
    if: p[0] == 1

types:
  process2:
    params:
      - id: payload
        size: 8
    seq:
      - id: p
        contents: payload
        process: my_processor2
      - id: data
        type: data(p)
  process3:
    params:
      - id: payload
        size: 8
    seq:
      - id: p
        contents: payload
        process: my_processor3
      - id: data
        type: data(p)
  data:
    params:
      - id: payload
        size: 4
    seq:
      - id: a
        type: u2
        value: (payload[0]<<8)+payload[1]
      - id: b
        type: u2
        value: (payload[2]<<8)+payload[3]
```
Is that possible to achieve only using kaitai?
And another question how to cast byte array to integers? (and if possible bit sized integers?)

**Comment by generalmimon** [comment]
Yes, it's possible:

```yaml
meta:
  id: multi_process
seq:
  - id: payload_process1
    type: process1
    size: 10
    process: my_processor1
types:
  process1:
    seq:
      - id: first
        type: u1
      - id: data_process2
        size: 8
        type: data
        process: my_processor2
        if: first == 0
      - id: data_process3
        size: 8
        type: data
        process: my_processor3
        if: first == 1
  data:
    seq:
      - id: a
        type: u2be
      - id: b
        type: u2be
```

This is IMHO the shortest way how to do it. Note that we cannot merge `data_process2` and `data_process3` into a single attribute, because they use different processing routines (and `switch-on` in `process` is not implemented: https://github.com/kaitai-io/kaitai_struct/issues/374).
