### ISSUE TITLE
Web IDE shows error when using instances with type named 'object'

### ISSUE THREAD

**Issue by VladimirMakeev** [kaitai-io/kaitai_struct#748]
On this grammar:
```
meta:
  id: tmp

types:
  currency:
    seq:
      - id: amount_str
        type: str
        encoding: ASCII
        size: 4
    instances:
      amount:
        value: amount_str.to_i

  object:
    seq:
      - id: dummy
        type: u1
```
Web IDE shows an error:
```
Parse error: undefined
Call stack: undefined TypeError: Object is undefined
```
This happens only when using instances and one of the types has name `object`.
If I rename `object` or remove instances, the error disappears.
I've searched issues and documentation for reserved keywords and didn't find any mentions.
