### ISSUE TITLE
Question: Is is possible to pass bits array that is not byte aligned to a process or type? 

### ISSUE THREAD

**Issue by alloncm** [kaitai-io/kaitai_struct#749]
I have this piece of code.
As you can see Im parsing the first bit and than call a processor with 4 bytes and then storing the bit I already parsed in order to parse correctly the remaining 31 bits.
Is there a way to pass only the remaining 31 bits? 

```yaml
meta:
  id: kai
  endian: be
seq:
  - id: payload_process
    type: process1
    size: 4
    process: my_processor
types:
  process1:
    instances:
      first:
        type: b1
      data_process:
        pos: 0
        size: 4
        type: data
        process: my_processor
  data:
    seq:
      - id: f
        type: b1
      - id: a
        type: b15
      - id: b
        type: b16
```
thanks in advance
