### ISSUE TITLE
Can't use _index in subtypes?

### ISSUE THREAD

**Issue by Jack-Rickwood** [kaitai-io/kaitai_struct#751]
I think for some reason it doesn't like you using _index in subtypes. Here is my file:
```yaml
seq:
  - id: header
    type: header
  - id: table_1
    type: table_type_1
    
types:
  header:
    seq:
      - id: magic
        contents: [0x10, 0x00, 0x00, 0x00]
  
  table_type_1:
    seq:
      - id: table_header
        type: table_header
      - id: table_body
        type: table_body
        size: 4 + ((table_header.table_header_length - 0x04) * 2)
    types:
      table_header:
        seq:
          - id: table_header_length
            type: u2
          - id: table_end_offset
            type: u2
          - id: table_start_offset
            type: u2
          - id: table_offsets
            type: u2
            repeat: expr
            repeat-expr: (table_header_length - 0x06) / 0x02
      table_body:
        seq:
          - id: header_end
            type: u4
        instances:
          table_data_start:
            pos: _parent.table_header.table_start_offset
            size: 0x04
          table_data:
            pos: _parent.table_header.table_offsets[_index]
            size: 0x04
            repeat: expr
            repeat-expr: (_parent.table_header.table_header_length - 0x06) / 0x02
```
The problem im having is that the 4th last line, pos: _parent.table_header.table_offsets[_index]
doesn't seem to work. I have confirmed that it's the _index thats not working, because if i replace it with a 0 it works fine. I came across this issue: https://github.com/kaitai-io/kaitai_struct/issues/598 which seems to be the same as mine, and it is also in a subtype, so i think that's what the issue is

**Comment by generalmimon** [comment]
@Jack-Rickwood There is nothing wrong with using subtypes, it's just that you expect `pos` in the **repeated** instance to apply to each item individually, but it actually specifies where to start sequentially parsing the whole array. You should read my new [**section about keys in repetition**](https://github.com/kaitai-io/kaitai_struct_doc/blob/7539936a217af8b5f44383da182c0e072db31d67/user_guide.adoc#keys-repeated) in the User Guide (not yet published, because nobody reviewed it so far) and tell me if you understand it and whether it is helpful or not.

**Comment by Jack-Rickwood** [comment]
@generalmimon I think i get it, thanks! Do you mind if i ask one more question? I'm still very beginner at this stuff. I have a table that contains relative offsets compared to where they are in the file. So, what  i have done is i have this:
```
- id: child_tables
        type: child_table(table_body.table_data[_index] - table_header.table_end_offset + table_header.table_offsets[0] + _index * 0x04)
        size-eos: true
        repeat: expr
        repeat-expr: (table_header.table_end_offset - table_header.table_offsets[0] - 0x04) / 0x04
```
Which calculates how many bytes from where it is now in the file, to where the relative offset was read and passes it to child_tables. And then in the child table type i have 
```
child_table:
    params:
      - id: table_offset
        type: u4
    instances:
        table:
           pos: table_offset
           type: table_type_2
           if: table_offset <= 0x224
```
But like before it does one after another, so the first offset works perfectly, but the second is after the end of the file, and i don't know what to do here. If i put size-eos: true in the child table part instead, it calculates it from the start of the file, instead of the end of the table.

**Comment by generalmimon** [comment]
@Jack-Rickwood Does type `child_table` parse anything sequentially from the stream? In your snippet, you left `seq` out, that means that every `child_table` has zero size and thus all `child_table`s start at the exact same offset. Then the part "_table that contains relative offsets compared to **where they are** in the file_" doesn't make much sense to me, because all `child_table`s _are_ at the same offset.

In any case, I'm sure that wrapping the `child_table` in a substream won't help you. While it ensures that the `pos` in it is relative to the `child_table` offset, you are imprisoned in the substream and so you can't read bytes outside it (that would raise an **E**nd-**O**f-**S**tream error). But I understand that you want to refer to positions outside the `child_table`.

The solution is to save the start offset of the `child_table` structure to a value instance (i.e. invoke a value instance with `value: _io.pos` at the beginning of `child_table/seq`) and add it to the `pos` value you want to make relative to the `child_table` struct. Like this:

```yaml
child_table:
  params:
    - id: table_offset
      type: u4
  seq:
    - id: save_this_ofs
      size: 0
      if: this_ofs < 0 # this can be any expression, as long as the type is boolean and it involves `this_ofs` invocation
  instances:
    this_ofs:
      value: _io.pos
    table:
      pos: this_ofs + table_offset # (!)
      type: table_type_2
      if: table_offset <= 0x224
```

It works because instances in KS are lazy and memoized, so they will be evaluated just once after the first invocation and further calls of the same instance instantly yield the memoized value.

It uses a slight hack with the `if: this_ofs < 0`. The only purpose of this weird condition is to invoke the `this_ofs` to memoize the current stream position. It could be achieved using another property as well (e.g. `size: this_ofs - this_ofs`), but using `if` seems to me to be the best (if it evaluates to `false`, the parsing of the attribute won't happen, so it won't have any extra performance cost).
