### ISSUE TITLE
Unexpected behavior with "not" statement

### ISSUE THREAD

**Issue by kadhaus** [kaitai-io/kaitai_struct#756]
I have a sequence with boolean parameter `note_0` and instance, that should appear only if that parameter is `true`:
```yaml
...
seq:
  - id: note_0
    type: b1

instance:
  some_instance:
    value: 42
    if: note_1
...
```
But it parsed incorrectly. The last line parsed like `not e_1` and causes error
```
unable to access 'e_0' in ... context
```
Fix it, please)
