### ISSUE TITLE
Parsing custom types to u4

### ISSUE THREAD

**Issue by ElizabethCapararo** [kaitai-io/kaitai_struct#757]
Hi, I'm looking for assistance with an issue I've been having regarding parsing custom types defined in Kaitai to basic Kaitai types such as u4 and u8.

Here is an example of what I'm working with, it has been made generic for this question:

`enums:
  generic_enum:
    0: generic1
    1: generic2
    2: generic3`

`types:
  custom_type:
    seq:
      - id: custom_type_size
        type: u4
     - id: custom_type_value
       type: u4
  main_type:
    seq: 
      - id: main_type_value
        value: custom_type
        enum: generic_enum`

What I'm trying to achieve is, if main_type -> main_type_value -> custom_type -> custom_type_value == 0,1,2 then the enum value will be display instead.

What I believe I'm confused about is parsing custom_type -> custom_type_value which is held within main_type -> main_type_value into a u4 so that is can be detected by the enum statement.

Any help would be appreciated, thanks!

**Comment by generalmimon** [comment]
Have you tried it? What's the problem? Does it print any error message?

**Comment by dgelessus** [comment]
As far as I know, there's no way to directly convert a non-integer field to an enum. As a workaround, you can add an extra `value` instance that extracts the underlying integer from the structure field, and convert that `value` instance to an `enum`. For example:

```yaml
types:
  custom_type:
    # ...
  main_type:
    seq: 
      - id: main_type_value
        type: custom_type
    instances:
      main_type_value_as_enum:
        value: main_type_value.custom_type_value
        enum: generic_enum
```

> What I'm trying to achieve is, if main_type -> main_type_value -> custom_type -> custom_type_value == 0,1,2 then the enum value will be display instead.

Do you mean that you want to treat the field as an enum only if its value is valid for the enum (0, 1, 2) and as a regular structure/integer otherwise? There's no built-in support for this in Kaitai Struct - you can't use `switch-on` here (because `enum` is separate from `type`). I think it would be easier to implement this by separating the enum conversion from the field (like in the example above) and then adding an `if` condition to the `value` instance that does the enum conversion. Something like:

```yaml
types:
  custom_type:
    # ...
  main_type:
    seq: 
      - id: main_type_value
        type: custom_type
    instances:
      main_type_value_as_enum:
        value: main_type_value.custom_type_value
        enum: generic_enum
        if: main_type_value.custom_type_value >= 0 and main_type_value.custom_type_value <= 2
```

That way you always have the unparsed value available via `main_type_value.custom_type_value`, and if the value is valid for the enum, you can also access it as an enum value via `main_type_value_as_enum`. This solution is also more usable from statically typed languages like Java, because this way every field has a known concrete type, instead of a generic type that needs to be checked at runtime.

Relevant: #518 suggests adding a built-in operator/method for checking if a value is valid for a certain enum. If implemented, that could be used to simplify the `if: main_type_value.custom_type_value >= 0 and main_type_value.custom_type_value <= 2` condition.
