### ISSUE TITLE
C# Nullable support

### ISSUE THREAD

**Issue by NN---** [kaitai-io/kaitai_struct#758]
For instance given:

```yaml
- id: body
  type:
    switch-on: x
    cases:
      a: typea
```

It generates a property `Body`:

```cs
private KaitaiStruct _body;
public KaitaiStruct Body { get { return _body; } }
```

If `x` is not `a` then Body will be null.
It can be easily declared as nullable;

```cs
private KaitaiStruct? _body;
public KaitaiStruct? Body { get { return _body; } }
```
