### ISSUE TITLE
Use of a parameter for contents value

### ISSUE THREAD

**Issue by edrthomas** [kaitai-io/kaitai_struct#764]
Hi, I can't figure out a way to pass a parameter to the the contents element of a custom type.

The situation is as follows:

```yaml
seq:
  - id: foo
    type: foo_type
  
  - id: bar
    type: bar_type

  foo_type:
    seq:
      - id: name
        contents: foo
  
  bar_type:
    seq:
      - id: name
        contents: bar
```

Since the number of types like foo_type and bar_type grows quickly, I would like to compress this declaration to something like:

```yaml
seq:
  - id: foo
    type: any_type('foo')
  
  - id: bar
    type: any_type('bar')

  any_type:
   params:
     - id: expected_name
       type: ???

    seq:
      - id: name
        contents: ?expected_name?
 
```

In my attempts, the value of contents is treated as a string and not recognized as the parameter of any_type. The type to use in the parameter declaration is also unclear to me.

Is there any way to achieve this?

Thanks !

**Comment by generalmimon** [comment]
Hi @edrthomas.

> In my attempts, the value of contents is treated as a string and not recognized as the parameter of any_type.

That's right. The key `contents` doesn't support expression language, you can specify only literal UTF-8 strings or byte arrays here (see [User Guide](https://doc.kaitai.io/user_guide.html#_checking_for_magic_signatures)). Note that an attribute having `contents` must not have `type`, because `contents` only denotes a sequence of bytes that must be present in the stream. So the type is already given, it's always a byte array. (Even if you specify the UTF-8 string, it is translated to a byte array at compile time, check the generated code.)

You'll want to use a `valid` key described in https://github.com/kaitai-io/kaitai_struct/issues/435#issue-323332353 instead. It can be used with any `type` and you can specify arbitrary KS expressions here. In your situation, you can choose if you want to compare against a byte array or a string.

1. using byte arrays

```yaml
seq:
  - id: foo
    type: any_type([0x66, 0x6f, 0x6f])

  - id: bar
    type: any_type([0x62, 0x61, 0x72])

types:
  any_type:
    params:
      - id: expected_name
        type: bytes # you can omit this line, because no `type` already means a byte array in KS

    seq:
      - id: name
        size: expected_name.length
        valid:
          eq: expected_name
```

2. using strings

```yaml
seq:
  - id: foo
    type: any_type('foo')

  - id: bar
    type: any_type('bar')

types:
  any_type:
    params:
      - id: expected_name
        type: str

    seq:
      - id: name
        size: 3
        type: str
        encoding: ascii
        valid:
          eq: expected_name
```

Note that string literals (`'foo'`) get magically transformed into a byte array **only** inside the key `contents`, everywhere else it means just a string (type `str` in KS language).

**Comment by edrthomas** [comment]
Hi @generalmimon,

Thanks for the clear answer ! 

'valid' seems very interesting for my usage of Kaitai so I wanted to try it out and installed ksc from the unstable https://dl.bintray.com/kaitai-io/debian_unstable.

```cmd
$ ksc --version
kaitai-struct-compiler 0.9-SNAPSHOT522603588
```

But I am getting this:
```
$ ksc -t python ../23090-2-omaf/initialisation_segment.ksy
/types/box_type/seq/1/valid: unknown key found, expected: consume, doc, doc-ref, encoding, eos-error, id, if, include, pad-right, repeat, size, size-eos, terminator, type
```

The ksy contains:
```yml
types:
  box_type:
    params:
      - id: expected_name
        type: str

    seq:
      - id: size
        type: u4

      - id: type
        size: 4
        type: str
        encoding: ascii
        valid:
          eq: expected_name
````
Could it be that the snapshot on https://dl.bintray.com/kaitai-io/debian_unstable is not up-to-date enough?
