### ISSUE TITLE
null termination where the null terminator is a int32

### ISSUE THREAD

**Issue by kurtsansom** [kaitai-io/kaitai_struct#766]
when I use `terminator=0` It stops on the first byte that is 0 but I don't want it to stop until it gets to an int32 (`s4`)  that is zero.
 I am having a hard time figuring out how to do that.

The following seems to work, but then this needs to get converted to a string?
```yaml
      - id: str_things
        type: s4
        # encoding: UTF-8
        # terminator: 0
        repeat: until
        repeat-until: _ == 0
```

additionally  I want to read in a list of variable names.

given by
```yaml
      - id: number_vars
        type: s4
```
where `number_vars` is the number of variable names I want to parse where each variable name has length n_chars+1, as each variable names is terminated with a 0 int32 value.

**Comment by kurtsansom** [comment]
This parses, but again it's only giving `s4` arrays of int32 values and includes the the terminating values

```
seq:
  - id: header_sequence
    type: header
types:
  string_array:
    seq:
      - id: str_things
        type: s4
        # encoding: UTF-8
        # terminator: 0
        repeat: until
        repeat-until: _ == 0
  header:
    seq:
      - id: header_str
        type: str
        encoding: UTF-8
        size: 8
      - id: byte_order
        type: s4
      - id: filetype
        type: s4
      - id: title
        type: string_array
      - id: number_vars
        type: s4
      - id: var_names
        type: string_array
        repeat: expr
        repeat-expr: number_vars
```

**Comment by generalmimon** [comment]
> each variable names is terminated with a 0 int32 value.

OK, but does it mean that the termination `00 00 00 00` byte sequence can occur only at a offset that is a multiply by four (0, 4, 8, 12, ...) or can it occur at any offset? If so, feel free to use the `str_things` you defined like that:

```yaml
      - id: str_things
        type: s4
        repeat: until
        repeat-until: _ == 0
```

..., but if the 4 zero bytes are supposed to terminate the string regardless of where they are, you can't use it. For example, the `str_things` you defined would work on a hex dump 1.

```
00 01 02 03 04 05 06 07 08 09 0a 0b      offset in hex
66 6f 6f 20 62 61 72 20 00 00 00 00      hex dump
f  o  o  ⎵  b  a  r  ⎵  .  .  .  .       ASCII representation
└── s4  ──┘ └── s4  ──┘ └── s4  ──┘
```

but not on a hex dump 2.

```
00 01 02 03 04 05 06 07 08 09 0a 0b      offset in hex
66 6f 6f 62 61 72 00 00 00 00            hex dump
f  o  o  b  a  r  .  .  .  .             ASCII representation
└── s4  ──┘ └── s4  ──┘ └── s4  ──┘
```

As you can see, if the format you're describing can look like the hex dump 2., determining the size of the name by reading consecutive `s4` integers won't work and it will likely result in malformed data.

@kurtsansom Are you sure that we're talking about the hex dump 1. situation and nothing else?
