### ISSUE TITLE
Magic string emitted as binary

### ISSUE THREAD

**Issue by matburnham** [kaitai-io/kaitai_struct#768]
I can defined a fixed-length ASCII string using:

```
seq:
  - id: callsign
    type: str
    size: 5
    encoding: ascii
```

![image](https://user-images.githubusercontent.com/1058493/86522710-0943e500-be5a-11ea-8156-c41e5dc57d0d.png)

I also see from https://doc.kaitai.io/user_guide.html#_checking_for_magic_signatures that I can check for a magic string using:

```
seq:
  - id: callsign
    contents: K5USL
```

![image](https://user-images.githubusercontent.com/1058493/86522719-2d9fc180-be5a-11ea-9a8a-82bf3dbdaa41.png)

However, the latter emits a binary not the string which is not ideal.

I get an error if I try to do:

```
seq:
  - id: callsign
    type: str
    size: 5
    encoding: ascii
    contents: K5USL
```

![image](https://user-images.githubusercontent.com/1058493/86522736-6475d780-be5a-11ea-91fb-370537ec469c.png)

Can I match a magic string, **_and_** emit it as a string?

**Comment by generalmimon** [comment]
I think that a good ans

**Comment by generalmimon** [comment]
@matburnham I think this comment https://github.com/kaitai-io/kaitai_struct/issues/764#issuecomment-650427200 can serve as a good answer to your question.

**Comment by matburnham** [comment]
Excellent. Thanks. I ended up with this:

```
seq:
  - id: callsign
    type: str
    size: 5
    encoding: ascii
    valid:
      eq: '"K5USL"'
```

That works fine in https://ide.kaitai.io/devel/ but I now need to wait for the target project to support a newer kaitai version supporting the `valid` syntax. It also explains why I couldn't find any relevant documentation.
