### ISSUE TITLE
to_i unsigned only

### ISSUE THREAD

**Issue by matburnham** [kaitai-io/kaitai_struct#769]
I'm decoding an ASCII-encoded hex string: `200FF1C151E0A1808F5`. I understand from #666 that this isn't supported directly so I've bodged it:

```yaml
  hex_uint:
    seq:
      - id: as_str
        size: 2
        type: str
        encoding: ASCII
    instances:
     as_int:
        value: as_str.to_i(16)
```

This works well enough for unsigned integers. However, `to_i` appears to only support unsigned values, so I have to faff like this::

```yaml
  hex_int:
    seq:
      - id: as_str
        size: 2
        type: str
        encoding: ASCII
    instances:
     as_int:
        value: 'as_str.to_i(16) < 128 ? as_str.to_i(16) : -((as_str.to_i(16) - 1) ^ 0xFF)'

```

Is there a better way to do this, a signed variant of `to_i`?
