### ISSUE TITLE
[Question] - Parse optionally available bytes based on the value in the IO stream

### ISSUE THREAD

**Issue by vrpcse** [kaitai-io/kaitai_struct#772]
Hi,
I have following stream to parse.
```
x, x11, x, x21, y,  y11, y, y21
At least one x, y blocks are mandatory and y blocks will follow after all x blocks.
```

My .ksy to parse this is

```
seq:
    - id: data
      type: block
      repeat: eos

type:
  block:
    - id: block_type
      type: u1
    - id: block_data
      type: u1
```

So i get data as a list of x, y blocks.
I would like to get x blocks separately in a list and y blocks in a separate list.

I tried to use repeat, switch-on. but i couldn't achieve the expectation as my check variable (block_type) is inside the stream.
Any support or guidance is very much appreiciated.
