### ISSUE TITLE
Support for Binary-coded decimal (BCD)?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct#78]
I have a format which uses [BCD](https://en.wikipedia.org/wiki/Binary-coded_decimal) to represent some serial number, like in the following example where all bytes are provided as HEX values:

> [44h, A8h, 34h, 44h, 33h, 22h, 11h]

The serial number I need is `11223344`. I would like to have it either as string or int, but currently I can only read the int without the knowledge that it's BCD encoded and therefore get a wrong value. To not confuse people, I describe the serial as raw `byte[]` currently.

Am I missing something or is it currently not possible to get a BCD encoded int/string? If I'm not missing something, how about an approach based on "process"?

I currently think of two operation modes, one converting to an array of ASCII bytes, so that one can use `str`-functions afterwards, and one converting to raw binary decimals, so one can use `u8`. Something like `bcd_to_string` and `bcd_to_decimal`.

One problem would still be that in case of `bcd_to_string` and using the `str` type I would get the wrong order of the serial, because read order is `44332211`. So `bcd_to_string` would need to honour the current encoding of the KSY and reverse the bytes itself? Reading as `u8` would honour the encoding implicitly as well. But that implies always creating left-to-right text read-order. Is that acceptable or would one need to pass an arg to `bcd_to_str` to specify read-order?

Any thoughts?

**Comment by GreyCat** [comment]
Right now, there's no native support for any BCD. One can implement it as a user type, calculating its value with an expression, but that's probably not very performance-wise.

There are many versions of BCD (one-byte-per-digit, one-nibble-per-digit, with different endianness, digit order, additional sign specifications, etc). I guess if we'd want to support any of them, we should specify which version(s) exactly do we support and address them accordingly.

Implementing stuff with `process` would require some relatively large changes. So far, `process` was supposed to be used only on byte arrays, and outputs only byte arrays. If you want to do stuff like `bcd_to_string` and `bcd_to_decimal`, we'll need to change type derivation engine to be aware of different output data types.

Basically, I see the following alternatives:

### Do nothing, keep doing various BCD stuff as user types

Pros:

* simple
* we can probably add some widespread BCD implementations into our formats repository and reuse them
* we can have two value methods: one that transforms BCD into integer, and one that transforms it into string → somewhat effective

Cons:

* not the best performance (no native reading support ever, etc)
* not native type (i.e. you can't just do `foo`, you'll have to invoke it as `foo.decimal_value` or `foo.str_value`, etc)

### Implement native BCD type(s)

I.e. introduce something like `type: bcd8be` and treat them as integers.

Pros:

* native implementation possible (i.e. native libraries & processor instructions)
* easy to use - i.e. just `foo` and you're guaranteed to get an integer

Cons:

* need to do a full list of possible BCD schemes and implement them all in all possible runtimes / languages
* it would be always one target type (probably integer), i.e. you can't do efficient conversion of BCD -> string without intermediate integer in this approach

### Implement as `process`

Pros:

* somewhat easy to implement (i.e. you reuse existing int and string parsing facilities)
* possible to do multiple BCD schemes, possible to support multiple target types (i.e. both string + int)

Cons:

* still need to do full list of possible BCD schemes and implement them all in all possible runtimes / languages
* would need more hacks in type derivation (that's not terribly hard to do, but I'm not sure if we'd want to break a "byte array in, byte array out" contract).
* somewhat complicated to use — you need to do both `process` + implement a supporting user type + access via `foo.value`.

**Comment by tschoening** [comment]
> Do nothing, keep doing various BCD stuff as user types

Do you have an example of how that would work, so I would have a string in the end like in my example above? I couldn't think of a way to reverse order of the bytes and such.

**Comment by GreyCat** [comment]
I might disappoint you, but here's what I have in mind, really nothing fancy, basically everything unrolled manually. This example does 8-digit, 4-byte packed BCD (one decimal digit per 4-bit nibble):

```yaml
types:
  bcd8:
    seq:
      - id: b1
        type: u1
      - id: b2
        type: u1
      - id: b3
        type: u1
      - id: b4
        type: u1
    instances:
      digit1:
        value: b4 & 0xf
      digit2:
        value: (b4 & 0xf0) >> 4
      digit3:
        value: b3 & 0xf
      digit4:
        value: (b3 & 0xf0) >> 4
      digit5:
        value: b2 & 0xf
      digit6:
        value: (b2 & 0xf0) >> 4
      digit7:
        value: b1 & 0xf
      digit8:
        value: (b1 & 0xf0) >> 4
      as_int:
        value: >
          digit1 +
          digit2 * 10 +
          digit3 * 100 +
          digit4 * 1000 +
          digit5 * 10000 +
          digit6 * 100000 +
          digit7 * 1000000 +
          digit8 * 10000000
```

Applying this `bcd8` type to 4 bytes `12 34 56 78` would give `foo.as_int` as 12345678 (decimal). This is very verbose implementation, of course, one can inline all `digit1`..`digit8` value instances into `as_int`. 

Implementing `as_str` might be a little trickier: the simplest way would be probably just doing `as_int.to_s` (but `to_s` is currently not implemented, though it should be), or we can go hard core and implement some "get character by its ASCII / Unicode integer code", and do something like

```
chr(digit8 + 0x30) + chr(digit7 + 0x30) + chr(digit6 + 0x30) + ...
```

or

```
digit8.to_s + digit7.to_s + digit6.to_s + ...
```

**Comment by tschoening** [comment]
> I might disappoint you[...]

Not really, your example even reminded me that some of my serials follow a naming scheme, in which e.g. the first digit is the production year of the corresponding device. Using a user-type I get all what I need in one place: A substream for raw data (like with process), numeric integers if needed, a string preserving leading zeros and optionally even the "production year". I like that.

To get my string representation, I implemented `to_s` for `IntType`, as per your recommendation. I need this for each digit to easily keep leading zeros. The test for `to_s` can be used as an example for this discussion as well. Hope you will merge both...

Should this be closed or left open for a general discussion? I can live with user-types and `to_s` for now and would re-open as needed.

**Comment by GreyCat** [comment]
You're the one who has a real-life hands-on with the BCDs, not me ;) So, if you say that it's a good match for BCD, then I totally trust you :)

`to_s` implementation would be absolutely welcome, of course :)

Let's commit some ready-made BCD implementations to [format repo](https://github.com/kaitai-io/kaitai_struct_formats) then? I can make 1-2-4 byte versions × be/le versions × half-byte/full-byte versions => should be 3*2*2 = 12 files. Basically, the only thing we need to decided on then is how to name them?

**Comment by tschoening** [comment]
I wouldn't rush things, your example from above e.g. didn't produce the order of values I needed. The individual digits needed to be switched.

      digit1:
        value: (b4 & 0xF0) >> 4
      digit2:
        value: (b4 & 0x0F)

Maybe it's better to first collect some tests with correct implementations? People needing examples can find this issue and can have a look at and add their own tests.

> serialization/bcd_WIDTH_packed|unpacked_be|le
> serialization/bcd_be|le_packed|unpacked_WIDTH[_byte]

I think I would prefer the latter, creates better groups.

**Comment by GreyCat** [comment]
> I wouldn't rush things, your example from above e.g. didn't produce the order of values I needed. The individual digits needed to be switched.

Hmm, that makes it up to two more varieties of BCD? Switched vs unswitched nibbles?

> Maybe it's better to first collect some tests with correct implementations?

I guess it would help tremendously to investigate current usage of BCDs in real-life formats. You have one, I'll try to look up for more formats that use BCD. For example, Intel's FPU format (FBLD instruction), etc.

By the way, I came up with slightly more concise and less "manually unrolled" ksy:

```yaml
seq:
  - id: digits
    type: b4
    repeat: expr
    repeat-expr: 8
instances:
  as_int:
    value: >
      digits[7] +
      digits[6] * 10 +
      digits[5] * 100 +
      digits[4] * 1000 +
      digits[3] * 10000 +
      digits[2] * 100000 +
      digits[1] * 1000000 +
      digits[0] * 10000000
```

The bonus point of this is that it's easy to switch half-byte / full-byte versions (just change `b4` to `u1`) and it's easy to adjust numbers of digits (`repeat-expr` + adjust clauses in `as_int`).

**Comment by tschoening** [comment]
> Hmm, that makes it up to two more varieties of BCD? Switched vs unswitched nibbles?

Yes.

> By the way, I came up with slightly more concise and less "manually unrolled" ksy:

Good example for the usefulness of bit fields, but your first approach has a big pro as well: One can easily decide which digit is logically the "first" one, depending on the encoding used. In my example this is the high nibble of the last byte (packed and switched), so using your `repeat` I get the following:

    seq:
      - id:           digits
        type:         b4
        repeat:       expr
        repeat-expr:  8

    # fmt_oms_dll_header_reading_serial:
    instances:
      as_int:
        value:  digits[1] *        1 +
                digits[0] *       10 +
                digits[3] *      100 +
                digits[2] *     1000 +
                digits[5] *    10000 +
                digits[4] *   100000 +
                digits[7] *  1000000 +
                digits[6] * 10000000
      as_str:
        value:  digits[6].to_s + digits[7].to_s + digits[4].to_s + digits[5].to_s + digits[2].to_s + digits[3].to_s + digits[0].to_s + digits[1].to_s

Looks a bit harder to understand to me, but as often, guess it's a matter of taste. Good to have both approaches documented here. :-)

Might even be an idea to let the bit fields implementation take care of the switch/unswitched thing automatically? This way one would get normally increasingly indexes in the array at least. But that would really be the cherry on top of the fancy cake.

**Comment by GreyCat** [comment]
Well, to be frank, I guess we're on the verge on getting to parametric types. Doing so many combinations would be absurd. Something like that (of course, syntax is just as example).

```
meta:
  id: bcd
params:
  - id: num_bytes
    type: u4
  - id: is_half_byte
    type: bool
seq:
  - id: digits
    type:
      switch-on: is_half_byte
      cases:
        true: b4
        false: u1
    repeat: expr
    repeat-expr: is_half_byte ? (num_bytes * 2) : num_bytes
```

To use this type, one needs to call it with parameters, i.e. something like that:

```
- id: imei
  type: bcd(8, true)
- id: some_bcd_number
  type: bcd(6, false)
```
