### ISSUE TITLE
switch-on support for enum

### ISSUE THREAD

**Issue by smarek** [kaitai-io/kaitai_struct#781]
service protocols has strict type-subtype validation, that would be great to be validated by parser/compiler

specially if values do not match, parsing would fail on enum value not found when parsing instead of later manual programmer checks

example
```yml
meta:
  id: protocol
enums:
  general_types:
    0xA0: standard
    0xB0: emergency
  standard_subtypes:
    0x01: standard_a
    0x02: standard_b
  emergency_subtypes:
    0x10: emerg_a
    0x12: emerg_b
    0x13: emerg_c
seq:
  - id: type
    enum: general_types
    type: u1
  - id: subtype
    type: u1
    enum:
      switch-on: type
      cases:
        general_types::standard: standard_subtypes
        general_types::emergency: emergency_subtypes
```

This also expects the process to be strict when matching values, which depends on resolving #778
