### ISSUE TITLE
`include: true/consume: true` errously consume one more byte from stream

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#783]
Consider following ksy:
```yaml
meta:
  id: terminator
seq:
  - id: value
    terminator: 4
    #consume: false
    include: true
  - id: next
    type: u1
```
If you test it on samples/sample1.zip in web-IDE (both devel and stable), `next` will point to byte at index 5 instead of 4.
For reference, start of file:
|Index     | 0| 1| 2| 3| 4| 5|
|----------|--|--|--|--|--|--|
|Byte (hex)|50|4b|03|04|14|00|

`terminator` always match byte at index 3 (0x04).

I prepare table, summarizing behaviour of different `include/consume` settings. Each cell contains:
- number of readed bytes
- number of bytes in `value`
- byte index (0-based) of `next` field

|include:       => |none/false|true |
|------------------|----------|-----|
|consume: none/true|4/3/4     |5/4/5|
|consume: false    |3/3/3     |4/4/4|

`include` should only affect whether `next` points to byte 4 (if none/`false`) or byte 3 (if `true`).

`consume` should affect only whether value will have 3 (if `false`) or 4 (if none/`true`) bytes.
