### ISSUE TITLE
NPE if field in expression language context is null

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#784]
Consider following KSY:
```yaml
meta:
  id: null_bugs
  endian:
    switch-on: null
    cases:
      null: be # technically key 'null' is expression. That is really useful?
params:
  - id: null
    type: bool
seq:
  - type:
      switch-on: null
      cases:
        null: u1 # technically key 'null' is expression. That is really useful?
```
First, as you can see in web-IDE, having `null` as value for `switch-on` and `params.id` key causes NPE in compiler. If you replace `null` with `'null'` (ie. turn it into string), NPE is gone, but compiler generates incorrect code (at least for JS) -- reserved word `null` used as parameter name. So, currently @dgelessus assumption (from #773) is wrong:

> The compiler doesn't allow `null`/`false`/`true` as parameter names (either as YAML `null`/booleans or as strings), so the schema should disallow that too.

Currently that is allowed (you can check in web-IDE that JS-code will be generated). And should compiler also discard something like:
```yaml
...
  endian:
    switch-on: null + 1
    cases:
      null + 1: be
```
In that case `null` is parsed as identifier in expression.

My 5 cents: that's all should be allowed, but each target should rename invalid identifiers into something valid in target language.

Another question is that is really necessary treat `cases` keys as expressions? For example, such KSY currently is valid:
```yaml
meta:
  endian:
    switch-on: 1
    cases:
      0 + 1: be
```
but I don't see any benefits from such flexibility.

**Comment by generalmimon** [comment]
@Mingun Please note that there is no thing like `null` in the KS expression language currently, see https://github.com/kaitai-io/kaitai_struct/issues/616#issuecomment-531809092. `null` inside the expression should be treated now like every other identifier, and have no special meaning.

AFAIK the only place where it has special meaning currently is the [KST spec](https://doc.kaitai.io/kst.html) used to help with creating the unit test specs for all languages, but it can only be used as a special verbatim "enum value" of the `expected` key, see [`BaseGenerator.scala:50`](https://github.com/kaitai-io/kaitai_struct_tests/blob/2b5bd04ce950691760d503506a1ea7eae5f31ddb/translator/src/main/scala/io/kaitai/struct/testtranslator/specgenerators/BaseGenerator.scala#L50) from the KST translator. But note that KS compiler doesn't know about it at all.

> but each target should rename invalid identifiers into something valid in target language

> but compiler generates incorrect code (at least for JS) -- reserved word `null` used as parameter name

Please continue the discussion on the topic of identifiers colliding with the reserved words/keywords in the target languages in https://github.com/kaitai-io/kaitai_struct/issues/90.

> Another question is that is really necessary treat `cases` keys as expressions?

I have no doubt about that, expressions in `cases` are commonly used across various existing specs for enum values, for example.

```yaml
- id: opcode
  type: u1
- id: body
  type:
    switch-on: opcode
    cases:
      'opcode_enum::float.to_i': f4
```

> I don't see any benefits from such flexibility.

I don't see any benefits from restricting some features of the KS expression language specifically for the `cases`, what would be the point? It would just make the expression translator inside the KS compiler more complex. And moreover, the fact that you don't see the benefit of using summation `+` inside the type switching `cases` doesn't mean that someone else wouldn't consider it a great solution to their situation.

> First, as you can see in web-IDE, having `null` as value for `switch-on` and `params.id` key causes NPE in compiler.

I don't know exactly what happens in the Scala JS generated code (currently it's quite hard to debug it, because our infrastructure doesn't pack the generated JS source map into the npm package along with the code, so you see just the pretty much unreadable JS bundle with 102k lines), but the KSC gives quite a clear message when run on JVM:

```
$ ksc -t java switch_on_null.ksy
/meta/switch-on: expected string, got null
```

Declaring `switch-on: null` is the same as `switch-on: ` (without any value) in terms of the YAML syntax, and hence it should definitely cause a compile error.

**Comment by Mingun** [comment]
> I have no doubt about that, expressions in cases are commonly used across various existing specs for enum values, for example.

Well, it makes sense, although in this case I would use
```yaml
- id: opcode
  type: u1
  enum: opcode_enum
- id: body
  type:
    switch-on: opcode
    cases:
      'opcode_enum::float': f4
```
or
```yaml
- id: opcode
  type: u1
- id: body
  type:
    switch-on: opcode.as<opcode_enum>
    cases:
      'opcode_enum::float': f4
```

> It would just make the expression translator inside the KS compiler more complex.

Complexity would not be affected if you simply do not use expression translator for `cases` keys. It was a question of why to use a translator in this place at all. Now I see why, however, IMHO, the SKY spec will be clearer if they are not used in this place.

**Comment by generalmimon** [comment]
> Well, it makes sense, although in this case I would use

Note that `'opcode_enum::float'` is actually also an expression, although it doesn't look like it. The same expression can be used in value instances as well, for example. To avoid using the [`Expressions`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/eb420a617ae91a803659dfc29c8a8b54516b7b70/shared/src/main/scala/io/kaitai/struct/exprlang/Expressions.scala) parser, you would need to somehow extract the section handling the [enum values](https://github.com/kaitai-io/kaitai_struct_compiler/blob/eb420a617ae91a803659dfc29c8a8b54516b7b70/shared/src/main/scala/io/kaitai/struct/exprlang/Expressions.scala#L165-L177), which would probably mean to create a new "expression parser fork" `SwitchCaseExpressions`, which is exactly what we're trying to avoid. Moreover, you would likely have to add an extra `SwitchCaseExpressionTranslator` and somehow wire it to the existing language-specific translation methods like [`doEnumByLabel`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/eb420a617ae91a803659dfc29c8a8b54516b7b70/shared/src/main/scala/io/kaitai/struct/translators/JavaTranslator.scala#L58).

And if a enum value in the "limited expression syntax" for `cases` looks like `'opcode_enum::float': ...`, how would you declare a case with a string `"opcode_enum::float"` having 18 characters? You still have no other option than the infamous double quoting, because otherwise you won't be able to distinguish between these cases:

```yaml
  type:
    switch-on: my_string
    cases:
      '"opcode_enum::float"': f4
```

And what if you want to match a string using escapes? Well, to be fair, you could enforce taking advantage of the YAML escapes and accept already decoded characters, but you would have to teach users that they need to use the reverse order of quotes than usual - double quotes `"` as the outer fencing for YAML and single quotes `'` as the inner fencing to be recognized by the ``SwitchCaseExpressions`` parser as string. A slight difference, but very important. This would work:

```yaml
  type:
    switch-on: my_string
    cases:
      "'\ud835\udd42\ud835\udd52\ud835\udd5a\ud835\udd65\ud835\udd52\ud835\udd5a \ud835\udd4a\ud835\udd65\ud835\udd63\ud835\udd66\ud835\udd54\ud835\udd65'": f4
```

Or alternatively escaping the double quotes, but looks weird:

```yaml
  type:
    switch-on: my_string
    cases:
      "\"\ud835\udd42\ud835\udd4a\"": f4
```

However, this would not work (and I imagine the issues from confused users with label "bug found" and description "escape sequences don't work in string literals in `cases`"):

```yaml
  type:
    switch-on: my_string
    cases:
      '"\u..."': f4
```

And yet another type to support in the case expressions: byte array literals. The example can be seen in the User Guide: [7.9. Calculated default endianness](https://doc.kaitai.io/user_guide.html#calc-endian). YAML will no longer help you here, because you can't use arrays as keys. The `SwitchCaseExpressions` parser would need to support at least hexadecimal numbers (`0x4d`) and decimal numbers of course. Binary and octal number notation could be more appropriate in some cases though, so it would be nice to support them as well.

---

Do you still think it would be better "not to use the expression translator for `cases` keys"?
