### ISSUE TITLE
User type resolution broken when using paths

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#786]
Following KSY failed to compile in web-IDE:
```yaml
meta:
  id: type_resolution_bugs
  #endian: be
seq:
  - id: field
    type: ::u2
types:
  u2:
    seq:
      - size: 10
```
with
```
Parse error: undefined
Call stack: undefined io.kaitai.struct.format.YAMLParseException: /seq/0: unable to find type '::u2', searching from type_resolution_bugs
```
Error doesn't change even if use more regular name, such as `u22`

-----
This KSY incorrectly uses top `nested2` type instead of `outer::nested::nested2`:
```yaml
meta:
  id: type_resolution_bugs
  endian: be
seq:
  - id: field
    type: outer
types:
  nested2:
    seq:
      - id: y
        size: 2
  outer:
    seq:
      - id: f
        size: 10
        type: nested::nested2
    types:
      nested:
        seq:
          - id: n
            size: 9
        types:
          nested2:
            seq:
              - id: x
                size: 8
```
----
According to the [KSY schema](https://github.com/kaitai-io/ksy_schema/blob/master/ksy_schema.json) both usages must be valid.

**Comment by generalmimon** [comment]
@Mingun Well, thanks for the reports. The first example is apparently trying to use "absolute path" to the type, but I'm not pretty sure they're fully implemented right now. I've seen some clues in the compiler suggesting that the original intent was to support them, but I don't think the actions went far. We don't have relevant tests in our [test suite](https://github.com/kaitai-io/kaitai_struct_tests), so it's totally possible that they're simply not working right now. I would consider this feature as not yet implemented. It would be nice if you could create a new feature request on it, if you want it to be implemented.

As for the second spec, this is an instance of bug https://github.com/kaitai-io/kaitai_struct_webide/issues/105 I reported 5 months ago. This bug is happening exclusively in the Web IDE, the spec is otherwise perfectly valid, and works normally outside the Web IDE.

**Comment by Mingun** [comment]
Probably the second example is fixed now, but bug in compiler still exist. Compiler incorrectly resolves type paths. The problem is because each element of a path resolved independently without restrictions, here:
https://github.com/kaitai-io/kaitai_struct_compiler/blob/c23ec2ca88d84042edba76f70c1f003d062b7585/shared/src/main/scala/io/kaitai/struct/ClassTypeProvider.scala#L119-L130

The all path elements except the first should not continue to looking to the parent type that is above the previous name in the path. Currently this KSY resolves non-existing path:
```yaml
meta:
  id: root
types:
  child_1:
    seq:
        # 1) `one` resolved to child_11
        # 2) `two` resolved to child_12
      - type: one::two # resolved to child_12
    types:
      one: {} # child_11
      two:    # child_12
        types:
          one: {} # child_121
          two: {} # child_122
  child_2:
    types:
      one: {} # child_21
      two: {} # child_22
```
