### ISSUE TITLE
Consistently handling user types and built-in sized types

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#788]
I found, that `size` and `size-eos` keys won't work with built-in types with known size (`u1`, etc.):
```yaml
- id: field
  type: u4 # and other sized built-ins
  # Compile-time error
  # io.kaitai.struct.format.YAMLParseException: /seq/0/size: unknown key found, expected: consume, doc, doc-ref, eos-error, id, if, include, repeat, terminator, type, valid
  # size: 10
  # Compile-time error
  # size-eos: true
```
At the same time you can specify `terminator` key, but it seams it has no meaning for that case:
```yaml
- id: field
  # result: 0x504b0304
  type: u4be # and other sized built-ins
  # on input [50 4b 03 04]
  terminator: 3
```

I think, it will more consistent, if size-related keys will be independent from types. Each kaitai stream must have 4 properties:
- start offset
- consumed size
- availible size for sub-streams. That size is different from "consumed size" when terminator and/or pad-right is used. Technically more convenient to store as an end offset
- local current offset -- used as base for `pos` keys

At start root stream have:
- start offset = 0
- local current offset = start offset
- consumed size = undefined
- end offset = start offset + data size

Parsing will run as follows (`current_offset` -- global offset in parsed data):
1. Create new sub-stream of specified size
    - `start_offset = current_offset`
    - `end_offset = parent_stream.end_offset`
    - `local_current_offset = parent_stream.local_current_offset`
    - `consumed_size = undefined`
    - if `size` specified, `consumed_size = <size>, end_offset = start_offset + <size>, local_current_offset = 0`
    - if `size-eos: true` specified, `local_current_offset = 0`
2. If `terminator` specified, find first `terminator` in sub-stream, and limit stream availible size
    - `local_current_offset = 0`
    - if terminator NOT found
      - if `eos-error: true` raise error, stop
      - if `consumed_size` is not defined, `consumed_size = end_offset - start_offset`
    - if terminator found
      - `end_offset = <position of terminator>`
      - if `include: true` specified, `end_offset = end_offset + 1`
      - if `consumed_size` is not defined
        - `consumed_size = <position of terminator> - start_offset`
        - if `consume: true` specified, `consumed_size = consumed_size + 1`
3. If terminator NOT found and `pad-right` specified, find first `pad-right` in sub-stream, and limit stream availible size
    - if padding byte(s) found, `end_offset = <position of start padding>`
4. Read specified type, using `[start_offset, end_offset)` slice as source of data
    - if type is built-in type, call corresponding built-in function
      - fixed sized types read only necessary part of buffer, other is unused
      - variable sized types (`str`, `strz` and `bytes`) use entire buffer as result
    - if type is user type, recursively repeat this algorithm for all fields of user type
    - if type is opaque type, call read function of opaque type
5. If `consumed_size` is not defined, set `consumed_size = <readed size>`
6. `current_offset = start_offset + consumed_size`

That algorithm also fixes #783

**Comment by Mingun** [comment]
Allowing size to built-in sized types also more naturally handle such situations:
```yaml
meta:
  id: size_problems
  endian: be
  encoding: utf-8
seq:
  - id: field
    size: 5
    type:
      switch-on: 2
      cases:
        1: u4
        2: str
```
Depending on `switch-on` result `size` member is taken into account or not. I think that is not good. `size` should define size of _field_, not the size of _type_.

**Comment by webbnh** [comment]
In the example posted in your follow-up reply above, your two cases are a five-character string and a four-byte integer presumably with a padding byte:  it would be best to handle them as separate, explicit "types", rather than trying to claim that the _field_ is five-bytes thereby creating a new problem in which we try to figure out how to extract an integer from an over-sized field (i.e., how is KSC supposed to know which four of the five bytes to use for the integer (the answer might change with endianness...) and what is it supposed to do with the extra byte?).

My instinct here is that the `size` attribute is implicit when applied to a field with a built-in type.  I don't see any reason why one shouldn't be allowed to specify it explicitly (other than product implementation, documentation, and support costs....), but, if one _does_ specify it, it **must** match, and so your example of a `size: 5` field containing a `u4` should result in an error.

**Comment by Mingun** [comment]
This is just a minimal example showing the problem, assume that it will look like this:
```yaml
meta:
  id: size_problems
  endian: be
  encoding: utf-8
seq:
  - id: field
    size: 5
    type:
      switch-on: 2
      cases:
        1: U4
        2: str
types:
  U4:
    seq:
      - id: field
        size: 4
```
Now it no longer raises these questions, because everything works as described in the documentation, right?
