### ISSUE TITLE
ASCII-encoded Integers

### ISSUE THREAD

**Issue by jqk1032** [kaitai-io/kaitai_struct#79]
I am wondering if there is any way to read in ASCII text and convert it to a numeric type? In other words, I'd like to be able to do something like read in a 3-byte ASCII string and parse it as a u4. So far I can't find a way to do this.

**Comment by koczkatamas** [comment]
Sadly there is no way currently to convert text to number.

The best you can do is something like this, but this is only works for 4-digit numbers separated by spaces (ex. `1234 9876<space>`):

```yaml
meta:
  id: ascii_integer
  file-extension: ascii_integer
seq:
  - id: value
    type: number
    repeat: eos
types:
  number:
    seq:
      - id: digits
        type: u1
        repeat: until
        repeat-until: _ == 0x20
    -webide-representation: "{value:dec}"
    instances:
      value:
        value: >
          ((((digits[0] - 0x30)
          * 10 + (digits[1] - 0x30))
          * 10 + (digits[2] - 0x30))
          * 10 + (digits[3] - 0x30))
        -webide-parse-mode: eager
```

We can make it variable-length too, but it gets ugly fast:

Input: `1234 987 56 0<space><space>`

```yaml
meta:
  id: ascii_integer
  file-extension: ascii_integer
seq:
  - id: value
    type: number
    repeat: eos
types:
  number:
    seq:
      - id: digits
        type: u1
        repeat: until
        repeat-until: _ == 0x20
    -webide-representation: "{value:dec}"
    instances:
      value:
        value: >
          (
            (
              (
                (digits[0] == 0x20 ? 0 : digits[0] - 0x30)
                * (digits[0] == 0x20 or digits[1] == 0x20 ? 1 : 10) + (digits[0] == 0x20 or digits[1] == 0x20 ? 0 : digits[1] - 0x30)
              ) 
              * (digits[0] == 0x20 or digits[1] == 0x20 or digits[2] == 0x20 ? 1 : 10) + (digits[0] == 0x20 or digits[1] == 0x20 or digits[2] == 0x20 ? 0 : digits[2] - 0x30)
            ) 
            * (digits[0] == 0x20 or digits[1] == 0x20 or digits[2] == 0x20 or digits[3] == 0x20 ? 1 : 10) + (digits[0] == 0x20 or digits[1] == 0x20 or digits[2] == 0x20 or digits[3] == 0x20 ? 0 : digits[3] - 0x30)
          )
        -webide-parse-mode: eager
```

**Comment by GreyCat** [comment]
Actually, strings have `to_i` method:

```yaml
meta:
  id: test_digits
seq:
  - id: num_as_str
    size: 3       # <= feel free to specify other size here
    type: str     # <= or use strz to read the string until some terminator
    encoding: ASCII
instances:
  num_as_int:
    value: num_as_str.to_i
```

Also, you can parse hex strings using `.to_i(16)`, octal strings using `.to_i(8)`, etc.
