### ISSUE TITLE
Can't use field-local only `encoding` with switch-on types

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#790]
```yaml
meta:
  id: encoding_bugs
seq:
  - id: field
    type:
      switch-on: 1
      cases:
        1: strz
    encoding: utf-8
```
issues the following error without `encoding`:
```
/seq/0/cases/1: string type, but no encoding found
```
...and following with `encoding`:
```
/seq/0/encoding: unknown key found, expected: consume, contents, doc, doc-ref, eos-error, id, if, include, pad-right, parent, process, repeat, size, size-eos, terminator, type, valid
```
The only way to avoid error is to specify encoding in `meta`.

Also note, that path in first error slightly incorrect; should be `/seq/0/type/cases/1`

**Comment by webbnh** [comment]
This actually sort of makes sense:  I can imagine a situation where the `switch-on` could be used to switch among strings with different encodings -- thus, similar to the `size` in #788, the `encoding` attribute needs to be applied to the _type_, not the _field_.

This can be resolved by using user-types in the `switch-on` and applying the encodings there.

**Comment by Mingun** [comment]
Of course it can and should, if you faced with situation like you described. But this does not mean that my example should not work. In any case, if you use user types, `encoding` will not applied to it.

**Comment by webbnh** [comment]
I think the problem is that, absent a `switch-on` attribute, the `type` attribute accepts a number of sub-attributes (whose applications are reasonably well understood), while, when the `switch-on` attribute is present, the "type" is no longer unique, and so the applications of the sub-attributes in many cases no longer make good sense.

To resolve this, the problematic sub-attributes need to be moved inside the individual `cases`.  As we agree, this is easily achieved by using user-types in the `cases`, but that seems unnecessarily cumbersome when the cases are built-in types.  Thus, it would be handy if syntax like the following were available:
```
meta:
  id: encoding_bugs
seq:
  - id: field
    type:
      switch-on: 1
      cases:
        1:
          strz
          encoding: utf-8
```
But, I don't know how practical that is.

(@Mingun, looking at your example, I think the second error message is correct; I think that you intended to indent the `encoding` line one level further -- as it is, it's an attribute of `seq/0`, not `seq/0/type`, which _is_ nonsensical -- what happens when you correct he indentation?)
