### ISSUE TITLE
Compiler should throw error if `pad-right` or `terminator` do not fit into byte

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#791]
`terminator` and `pad-right` specify single bytes, but compiler allows any integer value,which do not fit into byte.

Fox example, that KSY successfully compiles in web-IDE (both stable and devel):
```yaml
meta:
  id: non_bytes
seq:
  - id: field
    pad-right: 0x200
    terminator: 0x300
    size: 1
```
