### ISSUE TITLE
Implement literals prefixes

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#80]
It will be very useful to have [C++14 literals prefixes](http://en.cppreference.com/w/cpp/language/integer_literal) (in fact Verilog have been having some of them for long time before C++), especially ```0b``` one.

**Comment by koczkatamas** [comment]
They are already implemented.

This
```yaml
meta:
  id: test
instances:
  binary:  { value: '0b100' }
  hex:     { value: '0x10' }
  decimal: { value: '42' }
  octal:   { value: '0111' }
```
generates the following output
```json
{
  "binary": 4,
  "hex": 16,
  "decimal": 42,
  "octal": 73
}
```
