### ISSUE TITLE
I need to parse data differently depend on flag in the middle of struct.

### ISSUE THREAD

**Issue by kalash-** [kaitai-io/kaitai_struct#811]
```yaml
directory_rec:
    seq:
      - id: file_name
        size: 11
        type: str
        encoding: ASCII
      - id: attribute
        type: u1
      - id: file_size
        type: u4
```
Depending on `attribute` I need to parse data differently. 
Best guess so far is create instance with different struct and use `pos 0` with substream. But I cannot specify the size because I read data with `repeat: until`.

Any suggestion how I could achieve this?

**Comment by KOLANICH** [comment]
`type`, `swithch-on`, `cases`.

**Comment by kalash-** [comment]
Hmm, i don't really get how I could do this. Main concern that I need to change data types and members size before and after `swithch-on` statement.

**Comment by kalash-** [comment]
Something like this
```yaml
directory_rec:
    seq:
      - id: file_name
        type:
          switch-on: attribute
          cases:
            1: str
            2: header_struc
      - id: attribute
        type: u1
      - id: file_size
        type:
          switch-on: attribute
          cases:
            1: str
            2: several_parameters_struct
```

**Comment by webbnh** [comment]
If you were doing this manually, like with a hex editor, how would you know which byte holds `attribute`?

**Comment by kalash-** [comment]
The position of attribute is fixed.

**Comment by Mingun** [comment]
May be this can help?
```yaml
directory_rec:
  seq:
    - id: file_name
      type:
        switch-on: attribute
        cases:
          1: str
          2: header_struc
    - type: u1
    - id: file_size
      type:
        switch-on: attribute
        cases:
          1: str
          2: several_parameters_struct
  instances:
    attribute:
      pos: <choose>
      type: u1
```

**Comment by kalash-** [comment]
As I understand to use this approach I should use substream and declare size of `directory_rec` where I use it. But if         `size: 64` and `repeat: until` declared fir same struct, instance calculations fails with "Call stack: undefined KaitaiEOFError: requested 64 bytes, but only 0 bytes available".

**Comment by kalash-** [comment]
Maybe somehow I can use relative positioning without substream?

**Comment by generalmimon** [comment]
@kalash-:
> But if `size: 64` and `repeat: until` declared for same struct, instance calculations fails with "Call stack: undefined KaitaiEOFError: requested 64 bytes, but only 0 bytes available".

I don't understand what you mean by this. Maybe there is some flaw in how you use the `repeat: until`. Here's a simplified example that works (tested in the [devel Web IDE](https://ide.kaitai.io/devel/)):

```yaml
meta:
  id: repeat_until_substream
  endian: le
  encoding: ascii
seq:
  - id: items
    size: 5
    type: item
    repeat: until
    repeat-until: _.type == -1
types:
  item:
    # must be contained in substream `size: 5`
    seq:
      - id: data
        size: 4
        type:
          switch-on: type
          cases:
            1: str
            2: f4
      - type: s1
    instances:
      type:
        pos: 4
        type: s1
```

Tested on this hex dump:

```
Offset(h) 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f

00000000  64 61 74 61 01 54 f8 2d 40 02 00 00 00 00 ff     data.Tø-@.....ÿ 
```

This is the result:

![repeat-until-substream](https://user-images.githubusercontent.com/47499687/94338331-af366400-fff1-11ea-98b8-2fc83747d45a.gif)

Can you describe what's different in your situation?

**Comment by Mingun** [comment]
@generalmimon, some off-topic question. How do you load custom binary file into web-IDE? I can't find that ability in the interface

**Comment by generalmimon** [comment]
> How do you load custom binary file into web-IDE? I can't find that ability in the interface

You can click the middle button in the bottom left corner (which opens the _Open..._ dialog)

![image](https://user-images.githubusercontent.com/47499687/94339950-3ee20f80-fffe-11ea-823e-f9ddbec51452.png)

or just drag & drop the custom binary file anywhere in the Web IDE window, as shown [on _kaitai_struct_webide_ GitHub wiki page](https://github.com/kaitai-io/kaitai_struct_webide/wiki/Features#drag--drop-files-directly-into-editor).

**Comment by kalash-** [comment]
@generalmimon You are right. I was inattentive. Thank you all guys for useful advises.

**Comment by webbnh** [comment]
@kalash- , I don't see a need to use an instance at all (and then you don't need to worry about whether you're using substreams or not):  KS supports lazy evaluation, and, because your `attribute` is at a fixed offset, it can access it during the parse to determine how to parse your other fields, even the field which precedes it:

```
meta:
  id: repeat_without_substream
  endian: le
  encoding: ascii
seq:
  - id: alignment
    type: u2
  - id: entry
    type: directory_rec
    repeat: eos
types:
  directory_rec:
    seq:
      - id: file_name
        size: 11
        type:
          switch-on: attribute
          cases:
            1: str
            2: header_struc
      - id: attribute
        type: u1
      - id: file_size
        size: 4
        type:
          switch-on: attribute
          cases:
            1: str
            2: several_parameters_struct
            
  header_struc:
    seq:
      - id: fld1
        type: u4
      - id: fld2
        type: u2
      
  several_parameters_struct:
    seq:
      - id: fld1
        type: u4
```
(I added the `alignment` field, because the same data I was chewing on didn't have an even number of 16-byte chunks in it -- presumably you will have different requirements.)
