### ISSUE TITLE
How to use switch-on for multiple fields?

### ISSUE THREAD

**Issue by hg-zt** [kaitai-io/kaitai_struct#829]
Is it possible to write my schema like this?

```yaml
#...
seq:
  - id: header
    type: my_header_type
  - id: body
    type:
      switch-on: '[header.field1, header.field2]'
      cases:
        '[0x00, 0x00]': payload_type_a
        '[0x02, 0x03]': payload_type_b
        # ...
```

I guess if these fields are guaranteed to be small numeric values, I could use a composed value by `field1 * 256 + field2` and use calculated results for `cases`. But it is not very readable so I want a more decent solution.
