### ISSUE TITLE
Variable-sized integers

### ISSUE THREAD

**Issue by JohnnyJayJay** [kaitai-io/kaitai_struct#833]
Is it somehow possible to define variable sized integers? 

I.e., I want something like this:

```yaml
seq: 
  - id: num_size
    type: u1
  - id: number
    type: u[num_size] 
``` 
So I essentially want this to read a variable number of bytes and create an integer from that.

**Comment by vrpcse** [comment]
Either you can read them as bytes if they are not possessing any uniqueness or you can read them as a custom data type.

**Comment by JohnnyJayJay** [comment]
> Either you can read them as bytes if they are not possessing any uniqueness or you can read them as a custom data type.

I know that, I suppose my question is rather "can I do that without having to transform a byte array to an integer manually later on"

**Comment by vrpcse** [comment]
In my opinion, it depends on the usecase that the array may not be a 1 byte member array everytime. So I feel, it falls under custom processing to handle the bytes accordingly.

**Comment by dgelessus** [comment]
You can't directly specify an integer type with a variable size. If there's only a small number of sizes that can occur in your data, you can use a `switch-on` as a workaround:

```yaml
seq: 
  - id: num_size
    type: u1
  - id: number
    type:
      switch-on: num_size
      cases:
        1: u1
        2: u2
        4: u4
        8: u8
```

If you need to support non-standard integer sizes like 3 or 5 bytes, you can also use bit-sized integers (e. g. `b24` would be a 3-byte unsigned integer). In that case you have to be careful that you set `bit-endian` correctly in your spec's `meta` - by default `bit-endian` is always `be`, even if you have already set `endian: le`!

If the integer can be larger than 8 bytes, there's no way to read it natively using Kaitai Struct. In that case you probably have to read it as a byte array (or array of larger integers if it's more convenient) and construct the integer value in your code.
