### ISSUE TITLE
Cannot use _index inside "pos" key

### ISSUE THREAD

**Issue by whiteh0le** [kaitai-io/kaitai_struct#834]
# Problem:
Let's say you encounter the following file format:
```yaml
meta:
  id: table_tb
  file-extension: tb
  endian: le
seq:
  - id: count
    type: u4
  - id: table_info
    type: table_info
    repeat: expr
    repeat-expr: count
instances:
  data:
    pos: table_info[_index].offset
    size: table_info[_index].size
    repeat: expr
    repeat-expr: count
types:
  table_info:
    seq:
      - id: offset
        type: u4
      - id: size
        type: u4
```
The format consist of a number of offsets and sizes that point to data, if we want to parse the data, we must use instances, the problem is, Kaitai doesn't allow the use of `_index` inside the `pos` key as it will throw us the following error message:
> Parse error: undefined
> Call stack: undefined TypeError: this.tableInfo[i] is undefined

The parse error occurs due to the Kaitai Struct Compiler generating the following code:
```javascript
[...]
Object.defineProperty(TableTb.prototype, 'data', {
  get: function() {
    if (this._m_data !== undefined)
      return this._m_data;
    var _pos = this._io.pos;
    this._io.seek(this.tableInfo[i].offset);
    this._m_data = new Array(this.count);
    for (var i = 0; i < this.count; i++) {
      this._m_data[i] = this._io.readBytes(this.tableInfo[i].size);
    }
    this._io.seek(_pos);
    return this._m_data;
  }
}
[...]
```
As you can see, the `this._io.seek` function is not inside the `for` loop and so, the `i` variable is not visible.
One could argue that you can just replace the `_index` variable inside `pos` by `0` and let the size do the rest:
```yaml
[...]
instances:
  data:
    pos: table_info[0].offset
    size: table_info[_index].size
    repeat: expr
    repeat-expr: count
[...]
````
But **this would only work if the data offset of an element is equal to the offset of the element before it + its size** which is not true for our file format.

# Possible Solution:
The solution would be to place the `this._io.seek` call inside the `for` **only when `pos` has the _index variable inside it** like so:
```javascript
[...]
for (var i = 0; i < this.count; i++) {
  this._io.seek(this.tableInfo[i].offset);
  this._m_data[i] = this._io.readBytes(this.tableInfo[i].size);
}
[...]
```
PD: I created this example file format to demonstrate the bug, I didn't use a real file format because it would be more complicated to point out the problem, but just to let you know, I've encountered this problem while reversing real file formats numerous times.

**Comment by Mingun** [comment]
I think that your case can be trivially solved if you move `data` instance inside the `table_info` type and remove `repeat` key in it.

Making meaning of `pos` depending on the expression content is a bad idea: how, for example, you should process such definition:
```yaml
params:
- id: flag
  type: b1
instances:
  data:
    pos: flag ? _index : 42
```

All instance positions should be counted from the beginning of enclosed type (for top-level instances enclosed type is implicitly named as `meta/id` value). Right now that isn't true, because `pos` relative to the parsed stream which isn't the same -- not all types has it's own stream, only them which have an explicitly defined `size`.
