### ISSUE TITLE
sizeof and lea operations

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#84]
It'd be nice to have ```sizeof``` operators for getting amount of space occupied by some set of structures and ```lea``` for getting offset of properties to have relative addressing modes.
The specification is:
```lea()``` returns an offset of the struct making the scope
```lea(property_name)``` returns an offset of the property which name is passed
```sizeof()``` returns a size of the struct making the scope
```sizeof(property_name)```  returns a size of the property which name is passed
```sizeof(property_name1, property_name2)```  is equivalent to
```lea(property_name2) - lea(property_name1) + sizeof(property_name2)``` and ```lea(property_name2) >= lea(property_name1)``` must satisfy
The example is

```yaml
seq:
 - id: str
   type: strz
   encoding: ASCII
 - id: revision
   type: u1
 - id: len
    type: u1
 - id: struct_offset0
   type: u2
 - id: struct_offset1
    type: u2
 - id: data
   size: len - sizeof(str, struct_offset1)  #equivalently len - sizeof(str) -sizeof(revision) - sizeof(len) -sizeof(struct_offset0) - sizeof(struct_offset1)
instances:
  str0:
    type: superstruct
    pos: lea(data)+struct_offset0
  str1:
    type: superstruct
    pos: lea(data)+struct_offset1
```
It creates a struct of size ```len``` with variable-length string in the beginning. Then it places a 2 ```superstruct```s in ```data``` relative to beginning of ```data```. Variable-length string is taken as an example of a case where sizes and offsets are not defined on compile time.

**Comment by KOLANICH** [comment]
@GreyCat

**Comment by KOLANICH** [comment]
@GreyCat

**Comment by KOLANICH** [comment]
@greycat, when can I expect this landed?

**Comment by koczkatamas** [comment]
Could you show the file format? I think this can be worked around by splitting the type into two different subtypes.

**Comment by KOLANICH** [comment]
Of course it can, but it will be ugly.

[Here](https://bitmessage.org/wiki/Protocol_specification#Encrypted_payload) the spec for payload. It is a separate type, which size is defined by the field size it is placed in. It can be placed into different types, so I dislike to use the hacks like ```_parent.payload_len```. In python source the size is also [calculated from the len of payload buffer](https://github.com/Bitmessage/PyBitmessage/blob/b304872b6824bdca60c4679c052277291d4001c0/src/pyelliptic/ecc.py#L472) .

**Comment by GreyCat** [comment]
There are many different proposals here, so let's break it into some parts. First of all, `sizeof`. I totally agree that we need some functionality akin to C-like `sizeof`, but there are some important differences in KS vs traditional C-like implementation:

* Not every structure and/or data type in KS would have a definite fixed size, unlike C
* In C, there are actually two different kinds of `sizeof` operator: doing stuff like `sizeof some_var` vs `sizeof char`. First kind takes value expression as argument, second one takes types (actually, type expressions) as argument. Your proposal rotates around the first kind, and even enhances it more, but, actually, in KS, even that could result in some undefined behavior, i.e. when asking for stuff like `sizeof(1)`, `sizeof(some_member + 1)`, `sizeof(some_member * 2.0)`, `sizeof(x)` where `x` is `type: b26`, `sizeof(true)`, etc.
* We don't have global functions, and I don't really like the idea of introducing them. Actually, even languages like C implement `sizeof` as a special operator due to its duality and special compile-time definition.

So, I can propose that we'd start from the basic `sizeof`. I can see that we could implement 2 basic forms:

* using type name (dynamic type size, non-user type => error)
* using expression (calculated expression type, boolean type, non-fixed type size, IO stream type => error)

Given that we support addressing in both bytes and bits, probably we'd need two implementations of these, like `bitsize` and `bytesize`.

I have an relatively easy syntax proposal for "using expression": do something like `some_stuff_here._size` and `some_stuff_here._bits` — akin to existing `size` and proposed `bits` (see #112) YAML keys.

I have no idea right now on how to implement type-based sizeof operator, except for introducing yet another keyword, which is probably doable, but definitely not very pretty...

**Comment by KOLANICH** [comment]
Do we really need type-based syntax? I mean if the field of the type is never used, we don't need its size, if it is used, we can use expression-based syntax.

**Comment by GreyCat** [comment]
> Do we really need type-based syntax? I mean if the field of the type is never used, we don't need its size, if it is used, we can use expression-based syntax.

Well, yes and no. Sometimes it's just very inconvenient to go through all that `_parent._parent.blah.blah.blah` stuff to name a particular element to take size of. Sometimes (and that's yet another question to decide), you want the size of basic structure by itself, and your only application of a structure is array, i.e.:

```yaml
seq:
  - id: things
    type: thing
    repeat: eos
```

`things._size` would probably return size of whole array, but you want the size of one individual element.
