### ISSUE TITLE
Question: Instruct kaitai to read the stream but not to store byte array

### ISSUE THREAD

**Issue by kmrsh** [kaitai-io/kaitai_struct#867]
We have a situation where large number of records (hence the large size too) come inside single file , we only need to process two types of events and we need to ignore other types. We can simply provide unsupported kaitai struct with  the `size` but it still store those byte array in the memory. This is huge in our case, is there a way to tell kaitai struct that it needs to advance the stream based on the `size` given but not to store those bytes in instance variable

ex: let's say way have the following 2 event and one we don't care

~~~yaml
  t_event_A_body:
    params:
      - id: body_length
        type: u2
    seq:
      - id: data                      # We need this data so 'data' property should have the byte array of size 'body_length'
        size: body_length         

  t_event_B_body:
    params:
      - id: body_length
        type: u2
    seq:
      - id: data                       # We need this data so 'data' property should have the byte array of size 'body_length'
        size: body_length          

  t_event_unsupported_body:
    params:
      - id: body_length
        type: u2
    seq:
      - id: data
        size: body_length         # Now here we don't care about this data and we need 'data' to be empty to save memory but stream should advance to next event record using the size ('body_length') provided, so that it correctly parse the subsequent events
~~~

**Comment by KOLANICH** [comment]
I guess it can be done with `pos` instances (`pos` instances have memory copied into an own buffer before parsing only if `size` is present), but it is ma dirty, hacky and incorrect solution.

```yaml
meta:
  id: format
seq:
  - type: t_event
    repeat: eos

types:
  t_event:
    seq:
      - id: type
        type: u1
      - id: body_length
        type: u2
      - id: body
        type:
          switch-on: type
          ...
        if: is_supported
      instances:
        is_supported:
          value: type != type::unsupported
        next:
          pos: _io.pos + body_length
          type: format
          if: !is_supported
```

So for the last item in the seq you would have to check if it `is_supported`, and if it is not, descend into `next`.

BTW, what is your format?
