### ISSUE TITLE
Does graphviz support opaque types?

### ISSUE THREAD

**Issue by pi-guy-in-the-sky** [kaitai-io/kaitai_struct#882]
Currently when trying to use `ksc` to build to graphviz, when there are opaque types in the `.ksy` file, the compiler throws this error:

```
CastToType(Attribute(Name(identifier(length)),identifier(val)),typeId(false,ArrayBuffer(u4),false)) (of class io.kaitai.struct.exprlang.Ast$expr$CastToType)
```

The relevant code in the `.ksy` file is:

```
types:
  columns:
    seq:
      - id: length
        type: vint # vint is an opaque type with a val() method that returns a "long long"
      - id: array
        type: column
        repeat: expr
        repeat-expr: length.val.as<u4>
```

Would it be possible to support adding a simple text field to represent an opaque type in graphviz? The visual documentation would be extremely helpful.
