### ISSUE TITLE
Permit non-lazy instances

### ISSUE THREAD

**Issue by joeyoravec** [kaitai-io/kaitai_struct#886]
User guide section [4.12 Instances](https://doc.kaitai.io/user_guide.html#_instances_data_beyond_the_sequence) states:

> Another very important difference between the seq attribute and the instances attribute is that instances are lazy __by default__. What does that mean? Unless someone would call that body getter method programmatically, no actual parsing of body would be done.

"By default" could be restated "always" because there is currently no syntax to make instances non-lazy. @generalmimon proposed a workaround to add a `size 0` to the seq like:

```
  - size: 0
    if: "my_first_instance == [].as<bytes>"
```
or
```
  - size: 0
    if: 'my_first_instance != my_first_instance
```

forcing the instance to be evaluated. But it could be more elegant if the KSY syntax supported something like:
```
instances:
  my_first_instance:
    lazy: false
    pos: 0
    size: 8
    type: my_custom_type
 ```

that would force parsing this instance. The rationale is not performance -- in case `my_custom_type` is utilized like a callback, and has a side-effect to invoke a API when this field is parsed, then the caller would want this instance parsed non-lazy.

**Comment by Mingun** [comment]
Problem with that proposal in that when instance should be parsed?

**Comment by joeyoravec** [comment]
> Problem with that proposal in that when instance should be parsed?

Not sure! So far it's just an idea for an enhancement. 😎  Today the instances are resolved lazy, and the caller would force resolution after constructing the object:
```
kaitai::kstream ks(&is);
example_t obj(&ks);

// walk the object structure, access instances to resolve anything that was parsed
x = obj.my_first_instance();
```

@generalmimon 's suggestion generated code that resolved the instance inside the code that reads the seq:
```
void example_t::val_t::_read() {
    m_val = m__io->read_bytes(8);
    n__unnamed1 = true;
    if (my_first_instance() != my_first_instance()) {
        n__unnamed1 = false;
        m__unnamed1 = m__io->read_bytes(0);
    }
}
```

This works fine for my problem but I suspect this would fall apart if the instance references other dependencies.

For a general solution that avoids any chain-of-dependencies it might make more sense to build a list and defer resolution of any non-lazy instances until the end of the `example_t` constructor after the entire seq has been parsed.

**Comment by joeyoravec** [comment]
Also confirmed -- neither method works properly with opaque parametric types. I started with the test case described in kaitai-io/kaitai_struct#888 then added the workaround to test what happens with this "really tough" scenario:

### Case 1

```
meta:
  id: example
  endian: le
  ks-opaque-types: true

seq:
  - id: rec
    size: 8
    repeat: eos
  - size: 0
    if: 'my_opaque_parametric_instance != my_opaque_parametric_instance'

instances:
  my_param_1:
    type: u1
  my_param_2:
    type: u1
  my_opaque_parametric_instance:
    type: my_opaque_parametric_type(my_param_1, my_param_2)
```

returns:

```
$ ksc ../ksy/testcase.ksy -t cpp_stl
example: /seq/1/if: can't compare CalcUserType(List(my_opaque_parametric_type),None,ArrayBuffer(Name(identifier(my_param_1)), Name(identifier(my_param_2)))) and CalcUserType(List(my_opaque_parametric_type),None,ArrayBuffer(Name(identifier(my_param_1)), Name(identifier(my_param_2))))
```

### Case 2

```
meta:
  id: example
  endian: le
  ks-opaque-types: true

seq:
  - id: rec
    size: 8
    repeat: eos
  - size: 0
    if: 'my_opaque_parametric_instance == [].as<bytes>'

instances:
  my_param_1:
    type: u1
  my_param_2:
    type: u1
  my_opaque_parametric_instance:
    type: my_opaque_parametric_type(my_param_1, my_param_2)
```

returns:

```
$ ksc ../ksy/testcase.ksy -t cpp_stl
example: /seq/1/if: can't compare CalcUserType(List(my_opaque_parametric_type),None,ArrayBuffer(Name(identifier(my_param_1)), Name(identifier(my_param_2)))) and CalcBytesType
```

**Comment by joeyoravec** [comment]
I circled back to this and discovered a more-direct workaround for my original problem:
```
seq:
- id: val
  size: 8
- size: 0
  type: my_custom_type(my_first_instance)
instances:
  my_first_instance:
    pos: 0
    size: 8
    process: my_process_routine
```
this approach splits 1) the instance for feeding pos/size through a custom processing routine and 2) the size=0 sequence element to construct an opaque-type. By feeding the instance as a parameter it forces the instance to evaluate.
