### ISSUE TITLE
ksc rejects typecast to opaque type

### ISSUE THREAD

**Issue by joeyoravec** [kaitai-io/kaitai_struct#887]
User's guide section [7.8 Typecasting](https://doc.kaitai.io/user_guide.html#typecast) demonstrates typecast to a type defined in the ksy. But when I tried casting to an opaque type:
```
meta:
  id: example
  endian: le
  ks-opaque-types: true

seq:
  - id: rec
    size: 8
    type: my_first_instance
    repeat: eos

instances:
  my_first_instance:
      pos: 0
      size: 10
  my_casted_instance:
      value: my_first_instance.as<my_opaque_type>
```
ksc fails with:
```
$ ksc testcase.ksy -t cpp_stl
(main): /instances/my_casted_instance/value: unable to find type 'my_opaque_type', searching from example
```
I was expecting this to work somewhat similarly to any other opaque type and generate a constructor for `my_casted_instance` that contains typecasting to the opaque type.
