### ISSUE TITLE
ksc fails to include header for opaque parametric type

### ISSUE THREAD

**Issue by joeyoravec** [kaitai-io/kaitai_struct#888]
For this testcase:
```
meta:
  id: example
  endian: le
  ks-opaque-types: true

seq:
  - id: rec
    size: 8
    repeat: eos

types:
  my_opaque_parametric_type:
    params:
      - id: param1
        type: u1
      - id: param2
        type: u1

instances:
  my_param_1:
    type: u1
  my_param_2:
    type: u1
  my_opaque_parametric_instance:
    type: my_opaque_parametric_type(my_param_1, my_param_2)
```
running:
```
$ ksc ../ksy/testcase.ksy -t cpp_stl
```
generates the constructor for `my_opaque_parametric_type` no problem, but the top portion of the `example.cpp` looks like:
```
// This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

#include "example.h"

example_t::example_t(kaitai::kstream* p__io, kaitai::kstruct* p__parent, example_t* p__root) : kaitai::kstruct(p__io) {
```
notice that it's missing an `#include "my_opaque_parametric_type.h"` that you'd expect to see for a KSY that contains an opaque type

**Comment by joeyoravec** [comment]
sorry for the noise -- that test case is __not__ opaque. The type is defined in the file so `ksc` is not supposed to generate code that includes a header as-if it were opaque.

**Comment by joeyoravec** [comment]
Confirmed, after correcting the test case to _actually_ be opaque:
```
meta:
  id: example
  endian: le
  ks-opaque-types: true

seq:
  - id: rec
    size: 8
    repeat: eos
  - size: 0
    if: 'my_opaque_parametric_instance'

instances:
  my_param_1:
    type: u1
  my_param_2:
    type: u1
  my_opaque_parametric_instance:
    type: my_opaque_parametric_type(my_param_1, my_param_2)
```
no problem, ksc generated a proper:
```
my_opaque_parametric_type_t* example_t::my_opaque_parametric_instance() {
    if (f_my_opaque_parametric_instance)
        return m_my_opaque_parametric_instance;
    m_my_opaque_parametric_instance = new my_opaque_parametric_type_t(my_param_1(), my_param_2(), m__io);
    f_my_opaque_parametric_instance = true;
    return m_my_opaque_parametric_instance;
}
```
and the expected `#include` at the top of the file. This functions as-expected.
