### ISSUE TITLE
value instance with typecast?

### ISSUE THREAD

**Issue by joeyoravec** [kaitai-io/kaitai_struct#890]
I tried to follow the example in [7.8 Typecasting](https://doc.kaitai.io/user_guide.html#typecast) to interpret a byte array:
```
meta:
  id: example
  endian: le

seq:
  - id: rec
    size: 8

types:
  my_byte_array_as_u1_type:
    seq:
      - id: val
        type: u1

instances:
  my_instance:
    value: rec.as<my_byte_array_as_u1_type>.val
```
this is not the `ksc` succeeds but the c++ compile fails with:
```
example.cpp: In member function ‘uint8_t example_t::my_instance()’:
example.cpp:55:78: error: invalid static_cast from type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to type ‘example_t::my_byte_array_as_u1_type_t*’
   55 | y_instance = static_cast<example_t::my_byte_array_as_u1_type_t*>(rec())->val();
      |                                                                       ^
```
did I do something wrong? The goal is similar to #887 except in this case I was trying to interpret a byte array using a defined type containing only [6.1 Basic Data Types](https://doc.kaitai.io/user_guide.html#_basic_data_types) instead of an opaque type.
