### ISSUE TITLE
Python: Enums in "switch-on" with extra math aren't supported

### ISSUE THREAD

**Issue by andrey-yantsen** [kaitai-io/kaitai_struct#891]
In my ksy I have a sequence like this:
```yaml
- id: message_type
  type: b4
  enum: message_type
- id: is_update_request
  type: b1
- id: is_from_server
  type: b1
- id: params
  type:
    switch-on: "message_type.as<u1> + (is_from_server.as<u1> << 4) + (is_update_request.as<u1> << 5)"
    cases:
      32: ping_device
```

And below is the generated code for this switch:
```python
_on = ((self.message_type + (self.is_from_server << 4)) + (self.is_update_request << 5))
```

I had to change `self.message_type` to `self.message_type.value` to get this working. The same applies to instances too.
