### ISSUE TITLE
Javascript compile breaks on id-less contents key

### ISSUE THREAD

**Issue by Swiftb0y** [kaitai-io/kaitai_struct#909]
Trying to compile this in either the web ide or ksc results in an exception:
```yaml
meta:
  id: demo_contents_bug

seq:
  - contents: [0, 0, 0, 0]
```

WebIDE:
> Parse error: undefined
Call stack: undefined io.kaitai.struct.precompile.FieldNotFoundError: unable to access 'unnamed_0' in demo_contents_bug context

KSC:
> unable to access 'unnamed_0' in demo_contents_bug context

Compiling to other languages seems fine, at least graphviz and rust which I used for narrowing this issue down.
