### ISSUE TITLE
Loss of information at bit level when using if

### ISSUE THREAD

**Issue by digitalTrilunaire** [kaitai-io/kaitai_struct#913]
I notice painfully that we can get a loss of information after declaring a bit field: if an expected structure is not parsed after this bitfield (due to an if), kaitai seems to realign parsing at byte level instead of bit level:

```yaml
seq:
  - id: header
    type: header
    size: 6 # size here is just to ensure that we get 6 bytes
types:
  header:
    seq:
       - id: version
         type: b2
# AOS PART
      - id: aos_sc_id
        if: version == 1
        type: b8
     - id: aos_vc_id
        if: version == 1
        type: b6
     - id: aos_header
        if: version == 1
        type: u4be
# TRANSFER PART
      - id: transfer_sc_id
        if: version == 0
        type: b10
     - id: transfer_vc_id
        if: version == 0
        type: b3
     - id: ocf_flag
        if: version == 0
        type: b1
     - id: transfer_header
        if: version == 0
        type: u4be
```
If I try to parse a frame with version = 0b00, kaitai say that there is one byte missing. It works when version == 1. If I invert the transfer and AOS part (starting from the two comments), the parsing works if version == 0 but not if version ==1 (same error, 1 byte missing). I can not use "switch-on" feature because the enum does not work with bits (at least it works but it silently convert bit in byte leading to info lost), thus I have no choice to use if.
