### ISSUE TITLE
c++ 'switch-on' generating uninitialized code that leads to segfault

### ISSUE THREAD

**Issue by rhd** [kaitai-io/kaitai_struct#919]
Hi! Thanks for the great tool. I have been experimenting with it lately and I so far I really like it. Writing binary parsers is not fun anymore.

Ok, now on to the problem...

##### The yaml

```yaml
meta:
  id: j29
  endian: be
  bit-endian: be
seq:
  - id: packets
    type: packet
    repeat: eos
    if: false

types:
  packet:
    seq:
      - id: header
        type: generic_header
        size: sizeof<generic_header>
      - id: packet_type
        type:
          switch-on: header.type
          cases:
            'packet_type::signal_data': signal_data
            'packet_type::context_packet': context_data

  generic_header:
    seq:
      - id: type
        type: b4
        enum: packet_type
        valid: 
          any-of:
            - packet_type::signal_data
            - packet_type::context_packet
      - type: b28
```

##### Generates this data in the header file:

```cpp
private:
    std::vector<packet_t*>* m_packets;
    bool n_packets;
```

##### And this constructor:

```
j29_t::packet_t::packet_t(kaitai::kstream* p__io, j29_t* p__parent, j29_t* p__root) : kaitai::kstruct(p__io) {
    m__parent = p__parent;
    m__root = p__root;
    m_header = 0;
    m__io__raw_header = 0;

    try {
        _read();
    } catch(...) {
        _clean_up();
        throw;
    }
}
```

Notice that `m_packets` and `n_packets` are not initialized? This can lead to the following cleanup code actually deleting a packet that was never actually created. This happens because the validation fails.

##### CPP file

```cpp
void j29_t::packet_t::_clean_up() {
<snip>
    if (!n_packet_type) {
        if (m_packet_type) {
            delete m_packet_type; m_packet_type = 0;
        }
    }
}
```

If I set `m_packet_type = NULL` in the constructor, all is well. But really, all private variables need to be initialized in the constructor to be safe.

Are there any current workarounds?

Thanks!

**Comment by generalmimon** [comment]
Thanks for the report!

> Notice that `m_packets` and `n_packets` are not initialized? This can lead to the following cleanup code actually deleting a packet that was never actually created.

You're right, I can see it - `n_packet_type` is "initialized" in the `_read` right before the switch:

```cpp
void j29_t::packet_t::_read() {
    m__raw_header = m__io->read_bytes(4);
    m__io__raw_header = new kaitai::kstream(m__raw_header);
    m_header = new generic_header_t(m__io__raw_header, this, m__root);
    n_packet_type = true;
    switch (header()->type()) {
    case j29_t::PACKET_TYPE_SIGNAL_DATA: {
        n_packet_type = false;
        m_packet_type = new signal_data_t(m__io, this, m__root);
        break;
    }
```

... but that's too late, because any read above it may have failed - then it has an uninitialized value and subsequently the `_clean_up()` method is called, which reads it.

> If I set `m_packet_type = NULL` in the constructor, all is well. But really, all private variables need to be initialized in the constructor to be safe.

Yep, they definitely need to - I thought we've done it as a part of https://github.com/kaitai-io/kaitai_struct/issues/244, but apparently not.

Failing to initialize the pointer to `0` has to do something with the type switch.

> Are there any current workarounds?

If your codebase allows that, tell `kaitai-struct-compiler` to produce code for the C++11 target by passing the option `--cpp-standard 11`. C++98-compatible code is generated by default, because it used to be the only option available before 0.9 and we didn't want to potentially break people's builds because of upgrading to the new version of the compiler (this was probably a bad idea and we should've changed the default, because a lot of people now use the "worse" version when they would likely be OK with C++11, but that's how it is - we may change it in the next version).

**Comment by rhd** [comment]
@generalmimon Thanks for the response! I've just tried the cpp 11 option but it fails to compile with both clang 10 and gcc 9.

```
kaitai_test.p/j29.cpp:430:9: error: no matching conversion for static_cast from 'std::unique_ptr<kaitai::kstruct>' to 'std::unique_ptr<signal_data_t>'
        static_cast<std::unique_ptr<signal_data_t>>(m_packet_type)->_read();
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:211:2: note: candidate constructor template not viable: no known conversion from 'std::unique_ptr<kaitai::kstruct>' to 'std::unique_ptr<j29_t::signal_data_t, std::default_delete<j29_t::signal_data_t> >::pointer' (aka 'j29_t::signal_data_t *') for 1st argument
        unique_ptr(pointer __p) noexcept
        ^
```

The generated code looks like:

```cpp
    switch (header()->type()) {
    case vita49_t::PACKET_TYPE_SIGNAL_DATA: {
        n_packet_type = false;
        m_packet_type = std::unique_ptr<signal_data_t>(new signal_data_t(m__io, this, m__root));
        static_cast<std::unique_ptr<signal_data_t>>(m_packet_type)->_read();
        break;
    }
    case vita49_t::PACKET_TYPE_CONTEXT_PACKET: {
        n_packet_type = false;
        m_packet_type = std::unique_ptr<context_data_t>(new context_data_t(m__io, this, m__root));
        static_cast<std::unique_ptr<context_data_t>>(m_packet_type)->_read();
        break;
    }
```

Have you seen this before?

**Comment by generalmimon** [comment]
> Have you seen this before?

Yeah, I've just checked that we already have a test [`debug_switch_user.ksy`](https://github.com/kaitai-io/kaitai_struct_tests/blob/fd46e606f09e668891ecf43aac3e6c74cf3b0180/formats/debug_switch_user.ksy) with the same pattern in the generated code (see [`debug_switch_user.cpp:17`](https://github.com/kaitai-io/ci_targets/blob/89220c43d95f79268d5f6bf4dea70f1f558d1164/compiled/cpp_stl_11/debug_switch_user.cpp#L17):

```cpp
        static_cast<std::unique_ptr<one_t>>(m_data)->_read();
```

https://app.travis-ci.com/github/kaitai-io/ci_targets/jobs/548026361#L1127:

```
home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/debug_switch_user.cpp:17:9: error: no matching conversion for static_cast from 'std::unique_ptr<kaitai::kstruct>' to 'std::unique_ptr<one_t>'
        static_cast<std::unique_ptr<one_t>>(m_data)->_read();
```

This only happens when you compile in the `--no-auto-read` mode, so the workaround would be not to use it and leave the automatic `_read()` call in the constructor (if that's acceptable for you).

**Comment by rhd** [comment]
> This only happens when you compile in the `--no-auto-read` mode, so the workaround would be not to use it and leave the automatic _read() call in the constructor (if that's acceptable for you).

You're right - it works without `--no-auto-read`! Thank you! Since I'm using the `if: false` trick that I saw from a different issue, I didn't mean to leave in the `--no-auto-read` flag. So, this workaround is perfect for me. 👍

**Comment by debugger-zhang** [comment]
m_xxx pointer should be initialized to 0 by default.
For example, the following schema:
```
meta:
  id: test
  endian: be

seq:
  - id: type
    type: u4
  - id: data
    size: 10
    type:
      switch-on: type
      cases:
        1: foo
        2: bar

types:
  foo:
    seq: []
  bar:
    seq: []
```

will generate the following _read function:
```c++
void test_t::_read() {
    m_type = m__io->read_u4be();
    n_data = true;
    switch (type()) {
    case 1: {
        n_data = false;
        m__raw_data = m__io->read_bytes(10);
        m__io__raw_data = new kaitai::kstream(m__raw_data);
        m_data = new foo_t(m__io__raw_data, this, m__root);
        break;
    }
    case 2: {
        n_data = false;
        m__raw_data = m__io->read_bytes(10);
        m__io__raw_data = new kaitai::kstream(m__raw_data);
        m_data = new bar_t(m__io__raw_data, this, m__root);
        break;
    }
    default: {
        m__raw_data = m__io->read_bytes(10);
        break;
    }
    }
}
```

When type is not 1, n_data is set to true but m_data is still an uninitialized pointer. If m_data is initialized to 0 it is safe to get a foo_t pointer via `dynamic_cast<test_t::foo_t*>(obj->data()))` (which will return a null pointer if the data is not foo). If the type of data is bar, dynamic_cast will correctly return a null pointer; If data is neither foo nor bar currently dynamic_cast will operate on an uninitialized pointer which will segfault.
