### ISSUE TITLE
Type resolution wrongly consider enums as user types

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#921]
The following KSY should produce compilation error but it doesn't
```yaml
meta:
  id: type_resolution_bug
seq:
  - id: enumeration
    type: type_resolution_bug::enum
enums:
  enum:
    0: e0
    1: e1
```
The `enum` is not a type -- it is an `enum` and you cannot use it in the `type` key

_(You'll get an error in WebIDE, but it arises at the parse time, not at compile time. If you wrap `seq` into a nested type, WebIDE will silence_
> Parse error: undefined
> Call stack: undefined TypeError: TypeResolutionBug.Enum is not a constructor

_)_
