### ISSUE TITLE
Java: invalid generation of switch with expressions in `case` clause

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#922]
The following KSY generates invalid Java code:
```yaml
meta:
  id: java_switch_bug
seq:
  - id: a
    type: u1
  - id: if
    type:
      switch-on: 0
      cases:
        a: u1
        _: u8be
```
Generator always uses `switch` statement for the `switch-on` expression which is incorrect in case of non-constant `cases`. Unlike JavaScript Java only supports constant `case` labels (only `int` before Java 7, `int` and `String` from Java 7).
```java
class Test {
  final int a = 0;
  final long b = 0L;
  int c = 0;

  final String d = "0";
  String e = "0";

  void test() {
    switch (...) {
      case 0:      // OK
      case a:      // OK
      case this.a: // error: constant expression required
      case b:      // error: incompatible types: possible lossy conversion from long to int
      case c:      // error: constant expression required

      case "0":    // OK from Java 7
      case d:      // OK from Java 7
      case this.d: // error: constant expression required
      case e:      // error: constant expression required
    }
  }
}
```
