### ISSUE TITLE
Development version of WebIDE allow usage of unknown fields in expressions

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#924]
https://ide.kaitai.io/devel/ (and thus the [current master](https://github.com/kaitai-io/kaitai_struct_webide/commit/a8f6f9c022761a06a3860f728ff68af63f04b483) for WebIDE) does not report an error for unknown fields:
```yaml
meta:
  id: unknown_attribute_bug
seq:
  - id: value
    size: unknown
```
compiled succesfully
