### ISSUE TITLE
Development version of WebIDE does not check types in expressions

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#925]
https://ide.kaitai.io/devel/ (and thus the [current master](https://github.com/kaitai-io/kaitai_struct_webide/commit/a8f6f9c022761a06a3860f728ff68af63f04b483) for WebIDE) does not report an error when expected type of expression does not match the expression type:
```yaml
meta:
  id: uncompatible_types_bug
  encoding: utf-8
seq:
  - id: before
    type: strz
  - id: value
    size: before
```
compiled succesfully
