### ISSUE TITLE
Compiler does not check field dependencies in expressions

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#926]
You can write an expression that will refer to fields parsed after the field which you try to parse:
```yaml
meta:
  id: dependencies_bug
seq:
  - id: value
    size: after
  - id: after
    type: u1
```
compiled successfully in both development and released WebIDE.

This check could be more tricky because compiler should also detect indirect dependencies and prohibit them:
```yaml
meta:
  id: indirect_dependencies_bug
params:
  - id: direct_size
    type: bool
seq:
  - id: value
    size: instance
  - id: after
    type: u1
instances:
  instance:
    value: 'direct_size ? 2 : after'
```

At the same time, I would like this to be allowed:
```yaml
meta:
  id: indirect_dependencies_allowed
params:
  - id: direct_size
    type: bool
seq:
  - id: value
    size: 'direct_size ? instance : 3'
  - id: after
    type: u1
instances:
  instance:
    value: 'direct_size ? 2 : after'
```
