### ISSUE TITLE
`_sizeof` special property does not properly handle conditional fields

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#927]
The following KSY successfully compiles although `_sizeof` expression depends on the presence of the `value` field which is dependent on the `_sizeof` result.
```yaml
meta:
  id: sizeof_bug
seq:
  - id: value
    size: 2
    if: _sizeof == 1
    # or this:
    # if: _root._sizeof == 1
```
(_`_sizeof` calculated as 2_)
Compiler should detect this situation and raise an error.
