### ISSUE TITLE
Compiler does not check types in `endian.switch-on`

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#929]
The following KSY compiled successfully ([in stable WebIDE](https://ide.kaitai.io/))
```yaml
meta:
  id: endian_switch_on_bug
  endian:
    switch-on: param
    cases:
      0: be
      _: le
params:
  - id: param
    type: bool
seq:
  - id: size
    type: u2
```
Some targets actually throw an internal compiler error on this and do not generate anything. For example, Java target:
```console
$ ./ksc-java/kaitai-struct-compiler-0.9/bin/kaitai-struct-compiler.bat --target java test.ksy
None.get
```
