### ISSUE TITLE
Compiler allow unknown fields in `endian.cases.<case>` property

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#930]
The following KSY compiled successfully and generate code that accesses non existent field `unknown`:
```yaml
meta:
  id: endian_switch_on_bug
  encoding: utf-8
  endian:
    switch-on: 0
    cases:
      unknown: be
      _: le
```
