### ISSUE TITLE
Using a range of values for `cases`

### ISSUE THREAD

**Issue by demberto** [kaitai-io/kaitai_struct#936]
```yaml
event:
  seq:
    - id: id
      type: u1
    - id: length
      type: vlq_base128_le
      if: id >= 192
    - id: data
      size:
        switch-on: id
          cases:
            1-63: 1
            64-127: 2
            128-191: 4
            192-255: length
```

1-63 for example, represents all numbers from 1 to 63. If not switch-cases, how can I do it with a simple if-else? The docs don't mention this use case, I am sure its pretty common.

**Comment by Mingun** [comment]
> If not switch-cases, how can I do it with a simple if-else? 

Something like that:
```yaml
seq:
  - id: id
    type: u1
  - id: length
    type: vlq_base128_le
    if: id >= 192
  - id: data
    size: 'id < 192 ? (id < 128 ? (id < 64 ? 1 : 2) : 4) : length'
```
