### ISSUE TITLE
Bit-sized integers allow strange syntax

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#939]
This definitions is valid and it seems they should be forbidden:
```yaml
seq:
  - id: zeroes
    type: b00000008 # == b8
  - id: zero
    type: b0 # should be forbidden
```
