### ISSUE TITLE
"imports" not imported in generated code

### ISSUE THREAD

**Issue by Mimickal** [kaitai-io/kaitai_struct#946]
Given two `ksy` files where one imports a type from another, the generated code does not have the corresponding imports. I need to add them to the generated files manually.

These are my `ksy` files
```yaml
shared.ksy
---
meta:
  id: shared
types:
  thing:
    seq:
      - id: field1
        type: u1
```
```yaml
example.ksy
---
meta:
  id: example
  endian: le
  imports:
    - shared
seq:
  - id: field1
    type: shared::thing
```
I compile using this command: `ksc --target python example.ksy`

The output Python (omitting `shared.py`)
```python
# This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

from pkg_resources import parse_version
import kaitaistruct
from kaitaistruct import KaitaiStruct, KaitaiStream, BytesIO
# Missing this: from shared import Shared


if parse_version(kaitaistruct.__version__) < parse_version('0.9'):
    raise Exception("Incompatible Kaitai Struct Python API: 0.9 or later is required, but you have %s" % (kaitaistruct.__version__))

class Example(KaitaiStruct):
    def __init__(self, _io, _parent=None, _root=None):
        self._io = _io
        self._parent = _parent
        self._root = _root if _root else self
        self._read()

    def _read(self):
        # Shared is not imported!
        self.field1 = Shared.Thing(self._io, self, self._root)
```
I see this on compiler release 0.9 and development build https://github.com/kaitai-io/kaitai_struct_compiler/tree/e8542816277c0f78a17afcd4eed756337df9cd70

Shouldn't the Python have `from shared import Shared` at the top? I've tried several other languages and they all appear to be missing these imports. Is this the expected behavior?
