### ISSUE TITLE
[Question] Switch between constants

### ISSUE THREAD

**Issue by TimSchimansky** [kaitai-io/kaitai_struct#962]
Hi,
tldr: I am searching for a method to switch between 64 constant values to use for multiplication in an instance value expression.

I have the data of a laserscanner (Hesai Pandar 64). The scanner spits out a UDP package with header, body and tail. The body consists of 1164 bytes and is dividable into 6 blocks. Each blocks contains one 2 bit integer for the azimuth (horizontal angle) value and 3 bytes (2 for distance, 1 for reflectance) for each of the 64 laser beams.

The readout of this works fine and maybe the goal to archieve this with kaitai is overambitious... I have a calibration file for the Pandar64, where every of the 64 channels gets an elevation angle (as well as an azimuth offset; same thing but i only need to describe one thing).  My goal is to convert the polar coordinates (azimuth/elevation) into cartesian coordinates (x/y/z). Therefore i need kind of a lookup table for the values (i have tried it with enums but ran into the problem of not accepting numbervalues as values). Is this even feesable.

In the following example i dont even try to calculate anything:

```
[...]
  
seq:
    - id: header
      type: header
    - id: blocks
      type: block
      repeat: expr
      repeat-expr: header.n_blocks
    - id: tail
      type: tail
    
types:
    
    [...]
	
    block:
        seq:
            - id: azimuth_raw
              type: u2
              doc: divide by 100 degrees
            - id: channel
              type: channel(_index)
              repeat: expr
              repeat-expr: _parent.header.n_lasers
        instances:
            azimuth_deg:
                value: azimuth_raw.as<f8> / 100
              
    [...]

    channel:
        params:
            - id: i
              type: u1
        seq:
            - id: distance_value_raw
              type: u2
              doc: Multiplication with distance_unit needed
            - id: reflectance_value
              type: u1
              doc: Reflectance on a scale of 0 to 255
        instances:
            distance_value:
                value: distance_value_raw * _parent._parent.header.distance_unit
				
			# THIS IS THE PROBLEM #####################
            elevation:
                value: i
                enum: elevations

enums:
    elevations:
        1: 14.803
        2: 10.953
        3: 7.98
      
		[...]
	  
        61: -13.053
        62: -14.009
        63: -18.968
        64: -24.976
```
