### ISSUE TITLE
Graphviz generator crashes on `sizeof<>` expressions

### ISSUE THREAD

**Issue by jtbandes** [kaitai-io/kaitai_struct#966]
The following definition crashes the graphviz generator:

```yaml
meta:
  id: asdf
  file-extension: asdf

seq:
  - id: x
    size: sizeof<xx>
    
types:
  xx:
    seq:
      - id: a
        type: u1
```

I believe the problem is that [this `match`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/0acfa60452a10b770a2c2e746f3de057f8ab76d9/shared/src/main/scala/io/kaitai/struct/GraphvizClassCompiler.scala#L282) doesn't handle sizeofs.

This is preventing `log/mcap.ksy` from having a svg generated at https://formats.kaitai.io/mcap/
