### ISSUE TITLE
string content as parameter

### ISSUE THREAD

**Issue by schiebel** [kaitai-io/kaitai_struct#968]
Hello, this could be user error... I am trying to follow the documentation, but I cannot get parameters to work for string content. I have a lot of data blocks like:
```
      - id: name_len
        type: u4
      - id: name
        contents: ["TableRecord"]
```
so I would like to be able to use parameters like:
```
label:
    params:
      - id: value
         type: str
    seq:
      - id: name_len
         type: u4
      - id: name
         contents: value
```
I tried `label( ["TableRecord"] )`, `label( "TableRecord" )` and `label( [0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64] )`, I put the square brackets in the parameterized struct, I tried removing the type from `value` but nothing seems to work.

Is it possible to parameterize string content? Thanks in advance for any help...
