### ISSUE TITLE
`to_s` should be available for all the struct types with `to-string` implemented

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#980]

**Comment by Mingun** [comment]
Just allow to call `to_s` on custom types is not possible, because `<kaitai-object>.to_s` means access to `to_s` field/instance of an object. Some other syntax is required to calling `to_s`, probably a special operator for that?

**Comment by EmperorArthur** [comment]
@Mingun What do you mean by access to field/instance of an object?

There can obviously be parsing order limitations, but those exist today.  Heck, for everything I'd like to do just allowing `to-string` f-strings to implicitly call to_s on types would work.

Simple example which would make debugging what the parser is doing so much easier:
```yaml
fixed_point_angle:
  to_string: f"<fixed_point_angle degrees={degrees}>"
  seq:
  - id: raw
    type: s2
  instances:
    degrees:
      value: raw * 180.0 / 0x8000
polar_coordinate:
  to_string: f"<polar_coordinate distance={distance} angles=[{xy_ang}, {xz_angle}] >"
  seq:
  - id: distance
    type: f4
  - id: xy_angle
    type: fixed_point_angle
  - id: xz_angle
    type: fixed_point_angle
```

**Comment by Mingun** [comment]
This is valid KSY:
```yaml
seq:
  - id: to_s
    type: u1
instances:
  # to_s:
  #   value: 42
  use_to_s:
    value: to_s
```
Your example is not what is requested in that issue, because it don't contain _explicit_ `to_s` calls. I agree that it should work, that should be posible without any limitations. What is requested here is
```yaml
to-string: "my cool type"
seq: []
instances:
  use_to_s:
    value: to_s # returns "my cool type"
```
