### ISSUE TITLE
Bit sized integers and custom value types

### ISSUE THREAD

**Issue by benpnz** [kaitai-io/kaitai_struct#982]
Hi,

I am currently defining ksy file with the intention of parsing a data structure that uses bit sized integers combined with custom value types that are also bit sized. For example, I have the following combinations:

```ksy
      - id: psant0
        type: b1
      - id: vsabus
        type: ubusvolt12
      - id: psant1
        type: b1
      - id: psgyr1
        type: b1
  ubusvolt12:
    seq:
      - id: raw
        type: b12
    instances:
      value:
        value: raw * 0.001619779146
```

What I have found is that it seems the parser will align the custom value types (in this example vsabus) on the next byte rather than on the second bit which would be my intention. Is this the expected behavior? I am assuming the parser does not look in to the custom values so assumes they are not bit sized integers.

Thanks for any help or tips to handle this situation.

**Comment by generalmimon** [comment]
> Is this the expected behavior?

See https://gitter.im/kaitai_struct/Lobby?at=628eb63309eea00adeb191b0 for explanation and workaround.

There are a dozen issues (some open, some closed) reporting this, but I haven't even decided yet which should be the main one so that I can close the others as duplicates.

**Comment by benpnz** [comment]
Sorry I did have a look for duplicate issues but obviously missed these others. Thanks @generalmimon for the write-up and I will close this issue.

**Comment by benpnz** [comment]
For future reference for myself and others here is the change that resolved the issue:

```
      - id: psant0
        type: binary1
      - id: vsabus
        type: ubusvolt12
      - id: psant1
        type: b1
      - id: psgyr1
        type: b1
      - id: psuhf0
        type: b1
  binary1:
    seq:
      - id: raw
        type: b1
    instances:
      value:
        value: raw
  ubusvolt12:
    seq:
      - id: raw
        type: b12
    instances:
      value:
        value: raw * 0.001619779146
```
