### ISSUE TITLE
Reference the current structure in its instance

### ISSUE THREAD

**Issue by agatti** [kaitai-io/kaitai_struct#989]
Hello,

I am writing a KSY for a filesystem parser, and I am stuck on one minor detail, which I am not sure is my fault or a limitation of Kaitai.  While structure parsing works just fine, I am trying to let Kaitai fill in parent-child relationships between entries since it already knows which element has which children at parse time.  I cannot find a way to let Kaitai perform that association.

The (stripped down and merged) KSY file is as follows:

```yaml
meta:
  id: fs_file
  endian: le

params:
  - id: logical_offset
    type: u4
  - id: io
    type: io

seq:
  - id: len_data
    type: u4
  - id: offset
    type: u4
  - id: is_directory
    type: u1
  - id: name
    type: strz
    encoding: ASCII

instances:
  data:
    pos: offset - logical_offset
    size: len_data
    io: io
    if: is_directory == 0
  children:
    pos: offset - logical_offset
    type: fs_directory(logical_offset, io)
    io: io
    if: is_directory == 1

# The following types are in a different file; they reference each other.

types:

  fs_directory:
    params:
      - id: logical_offset
        type: u4
      - id: io
        type: io

    seq:
      - id: len_payload
        type: u4
      - id: payload
        type: fs_directory_entries(logical_offset, io)
        size: len_payload

  fs_directory_entries:
    params:
      - id: logical_offset
        type: u4
      - id: io
        type: io

    seq:
      - id: children
        type: fs_file(logical_offset, io)
        repeat: eos
```

Once things are parsed, all `_parent` fields are set to `null`, so parent-children relationships must be explicitly filled in.  From my limited experience with Kaitai, the only way I make this work would be to be able to reference the currently parsed structure, pass that in the various structure constructors and expose it as an instance value.  For that, I haven't found anything useful as I only found references to `_`, which is a placeholder for the current field, not for the current structure instance.  Section 7.7.1 of the documentation mentions `this` as if it were a keyword, but the compiler does not accept it and raises a syntax error.

This is not blocking, as I can always write some code that rebuilds the tree structure at a later stage, but I wonder if this is possible within Kaitai?
