### ISSUE TITLE
Support of offload certain specs to native implementations

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#991]
Initally pitched in https://github.com/kaitai-io/kaitai_struct_formats/pull/210#issuecomment-562963340

It would be nice to have ability to offload certain things to native more efficient implementations.

1. Interfaces proposal is implemented https://github.com/kaitai-io/kaitai_struct/issues/314
2. inlining & discarding is implemented and becomes a part of an interface
3. an additional metadata property `offload` is implemented to mark a type as natively-offloaded and specify how exactly offloading is done

```yaml
meta:
  offload:
    name: name of a lib
    namespace: namespace of a lib
    factory: factory function name
```

Factory function returns either KS object implementing a certain interface or a primitive type, if `inlining` to it is used.

4. certain specs within standard library get this property
5. offloads are implemented as native pieces of code, separate libraries, for each target
