### ISSUE TITLE
howto: switch based on the value of another field

### ISSUE THREAD

**Issue by stanleygambarin** [kaitai-io/kaitai_struct#995]
i can not seem to find a way to implement this using existing facilities... 

types:
  type_id:
    seq:
      - id: name_id
        type: u4
      - id: name
        type: strz
        encoding: UTF-8

  type_select:
    seq:
      - id: set_id
        type: u4
      - id: body
        type: 
           switch-on: ??? 
             cases:
                'FOO': foo_struct
                'BAR': bar_struct

So, the first type defines mapping between some number and name, e.g. FOO=>23, BAR=44.  The second type will define different substructures based on a 'set_id' number. I need a way to express this (including adding additional code)...something like:

- record_mapping(name_id, name) when processing type_id
- get_mapping_name(set_id) as input to switch-on when processing type_select.

thanks for help in advance.

**Comment by pfroud** [comment]
I think this is how you do it:

```yaml
meta:
  id: issue_995
  file-extension: issue_995
  endian: le
seq: []
types:
  type_id:
    seq:
      - id: name_id
        type: u4
      - id: name
        type: strz
        encoding: UTF-8
  type_select:
    seq:
      - id: set_id
        type: type_id
      - id: body
        type: 
           switch-on: set_id.name
           cases:
              '"FOO"': foo_struct
              '"BAR"': bar_struct
  foo_struct:
    seq: []
  bar_struct:
    seq: []
```


I found the syntax here to do string matching here: https://github.com/kaitai-io/kaitai_struct/issues/636#issuecomment-544240353
