### ISSUE TITLE
Can't compare BitsType1(BigBitEndian) and Int1Type(true)

### ISSUE THREAD

**Issue by bersbersbers** [kaitai-io/kaitai_struct#997]
Related: https://github.com/kaitai-io/kaitai_struct/issues/118

```yml
meta:
  id: switch_b1
seq:
  - id: bit1
    type: b1
  - id: next
    type:
      switch-on: bit1
      cases:
        0: b1
        1: b1
```
> switch_b1: /seq/1/type/cases/IntNum(0):
	error: can't compare BitsType1(BigBitEndian) and Int1Type(true)

**Comment by bersbersbers** [comment]
This works:
```yml
meta:
  id: switch_b1
seq:
  - id: bit1
    type: b1
  - id: next
    type:
      switch-on: bit1
      cases:
        false: b1
        true: b1
```
